/*
Copyright (c) 2014-2019 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

#pragma once

// Values are tested on 3.3.5a client
// Values without comments didn't return anything
enum SpellCastResult : uint8_t
{
    SPELL_FAILED_SUCCESS                        = 0x00,
    SPELL_FAILED_AFFECTING_COMBAT               = 0x01, // You are in combat
    SPELL_FAILED_ALREADY_AT_FULL_HEALTH         = 0x02, // You are already at full Health
    SPELL_FAILED_ALREADY_AT_FULL_MANA           = 0x03, // You are already at full Mana
    SPELL_FAILED_ALREADY_AT_FULL_POWER          = 0x04, // You are already at full Rage (tested on warrior)
    SPELL_FAILED_ALREADY_BEING_TAMED            = 0x05, // That creature is already being tamed
    SPELL_FAILED_ALREADY_HAVE_CHARM             = 0x06, // You already control a charmed creature
    SPELL_FAILED_ALREADY_HAVE_SUMMON            = 0x07, // You already control a summoned creature
    SPELL_FAILED_ALREADY_OPEN                   = 0x08, // Already open
    SPELL_FAILED_AURA_BOUNCED                   = 0x09, // A more powerful spell is already active
    SPELL_FAILED_AUTOTRACK_INTERRUPTED          = 0x0A,
    SPELL_FAILED_BAD_IMPLICIT_TARGETS           = 0x0B, // You have no target
    SPELL_FAILED_BAD_TARGETS                    = 0x0C, // Invalid target
    SPELL_FAILED_CANT_BE_CHARMED                = 0x0D, // Target can't be charmed
    SPELL_FAILED_CANT_BE_DISENCHANTED           = 0x0E, // Item cannot be disenchanted
    SPELL_FAILED_CANT_BE_DISENCHANTED_SKILL     = 0x0F, // Your enchanting skill is not high enough to disenchant that
    SPELL_FAILED_CANT_BE_MILLED                 = 0x10, // You cannot mill that
    SPELL_FAILED_CANT_BE_PROSPECTED             = 0x11, // There are no gems in this
    SPELL_FAILED_CANT_CAST_ON_TAPPED            = 0x12, // Target is tapped
    SPELL_FAILED_CANT_DUEL_WHILE_INVISIBLE      = 0x13, // You can't start a duel while invisible
    SPELL_FAILED_CANT_DUEL_WHILE_STEALTHED      = 0x14, // You can't start a duel while stealthed
    SPELL_FAILED_CANT_STEALTH                   = 0x15, // You are too close to enemies
    SPELL_FAILED_CASTER_AURASTATE               = 0x16, // You can't do that yet
    SPELL_FAILED_CASTER_DEAD                    = 0x17, // You are dead
    SPELL_FAILED_CHARMED                        = 0x18, // Can't do that while charmed
    SPELL_FAILED_CHEST_IN_USE                   = 0x19, // That is already being used
    SPELL_FAILED_CONFUSED                       = 0x1A, // Can't do that while confused
    SPELL_FAILED_DONT_REPORT                    = 0x1B,
    SPELL_FAILED_EQUIPPED_ITEM                  = 0x1C, // Must have the proper item equipped
    SPELL_FAILED_EQUIPPED_ITEM_CLASS            = 0x1D, // Must have a %s equipped
    SPELL_FAILED_EQUIPPED_ITEM_CLASS_MAINHAND   = 0x1E, // Must have a %s equipped in the main hand
    SPELL_FAILED_EQUIPPED_ITEM_CLASS_OFFHAND    = 0x1F, // Must have a %s equipped in the offhand
    SPELL_FAILED_ERROR                          = 0x20, // Internal error
    SPELL_FAILED_FIZZLE                         = 0x21, // Fizzled
    SPELL_FAILED_FLEEING                        = 0x22, // Can't do that while fleeing
    SPELL_FAILED_FOOD_LOWLEVEL                  = 0x23, // That food's level is not high enough for your pet
    SPELL_FAILED_HIGHLEVEL                      = 0x24, // Target is too high level
    SPELL_FAILED_HUNGER_SATIATED                = 0x25,
    SPELL_FAILED_IMMUNE                         = 0x26, // Immune
    SPELL_FAILED_INCORRECT_AREA                 = 0x27, // You are in the wrong zone
    SPELL_FAILED_INTERRUPTED                    = 0x28, // Interrupted
    SPELL_FAILED_INTERRUPTED_COMBAT             = 0x29, // Interrupted
    SPELL_FAILED_ITEM_ALREADY_ENCHANTED         = 0x2A, // Item is already enchanted
    SPELL_FAILED_ITEM_GONE                      = 0x2B, // Item is gone
    SPELL_FAILED_ITEM_NOT_FOUND                 = 0x2C, // Tried to enchant an item that didn't exist
    SPELL_FAILED_ITEM_NOT_READY                 = 0x2D, // Item is not ready yet
    SPELL_FAILED_LEVEL_REQUIREMENT              = 0x2E, // You are not high enough level
    SPELL_FAILED_LINE_OF_SIGHT                  = 0x2F, // Target not in line of sight
    SPELL_FAILED_LOWLEVEL                       = 0x30, // Target is too low level
    SPELL_FAILED_LOW_CASTLEVEL                  = 0x31, // Skill not high enough
    SPELL_FAILED_MAINHAND_EMPTY                 = 0x32, // Your weapon hand is empty
    SPELL_FAILED_MOVING                         = 0x33, // Can't do that while moving
    SPELL_FAILED_NEED_AMMO                      = 0x34, // Ammo needs to be in the paper doll ammo slot before it can be fired
    SPELL_FAILED_NEED_AMMO_POUCH                = 0x35, // Requires: %s
    SPELL_FAILED_NEED_EXOTIC_AMMO               = 0x36, // Requires exotic ammo: %s
    SPELL_FAILED_NEED_MORE_ITEMS                = 0x37, // Requires %d %s
    SPELL_FAILED_NOPATH                         = 0x38, // No path available
    SPELL_FAILED_NOT_BEHIND                     = 0x39, // You must be behind your target
    SPELL_FAILED_NOT_FISHABLE                   = 0x3A, // Your cast didn't land in fishable water
    SPELL_FAILED_NOT_FLYING                     = 0x3B, // You are flying
    SPELL_FAILED_NOT_HERE                       = 0x3C, // You can't use that here
    SPELL_FAILED_NOT_INFRONT                    = 0x3D, // You must be in front of your target
    SPELL_FAILED_NOT_IN_CONTROL                 = 0x3E, // You are not in control of your actions
    SPELL_FAILED_NOT_KNOWN                      = 0x3F, // Spell not learned
    SPELL_FAILED_NOT_MOUNTED                    = 0x40, // You are mounted
    SPELL_FAILED_NOT_ON_TAXI                    = 0x41, // You are in flight
    SPELL_FAILED_NOT_ON_TRANSPORT               = 0x42, // You are on a transport
    SPELL_FAILED_NOT_READY                      = 0x43, // Spell is not ready yet
    SPELL_FAILED_NOT_SHAPESHIFT                 = 0x44, // You are in shapeshift form
    SPELL_FAILED_NOT_STANDING                   = 0x45, // You must be standing to do that
    SPELL_FAILED_NOT_TRADEABLE                  = 0x46, // You can only use this on an object you own
    SPELL_FAILED_NOT_TRADING                    = 0x47, // Tried to enchant a trade item, but not trading
    SPELL_FAILED_NOT_UNSHEATHED                 = 0x48, // You have to be unsheathed to do that! (with yellow color)
    SPELL_FAILED_NOT_WHILE_GHOST                = 0x49, // Can't cast as ghost
    SPELL_FAILED_NOT_WHILE_LOOTING              = 0x4A, // You are busy looting
    SPELL_FAILED_NO_AMMO                        = 0x4B, // Out of ammo
    SPELL_FAILED_NO_CHARGES_REMAIN              = 0x4C, // No charges remain
    SPELL_FAILED_NO_CHAMPION                    = 0x4D, // You haven't selected a champion
    SPELL_FAILED_NO_COMBO_POINTS                = 0x4E, // That ability requires combo points
    SPELL_FAILED_NO_DUELING                     = 0x4F, // Dueling isn't allowed here
    SPELL_FAILED_NO_ENDURANCE                   = 0x50, // Not enough endurance
    SPELL_FAILED_NO_FISH                        = 0x51, // There aren't any fish here
    SPELL_FAILED_NO_ITEMS_WHILE_SHAPESHIFTED    = 0x52, // Can't use items while shapeshifted
    SPELL_FAILED_NO_MOUNTS_ALLOWED              = 0x53, // You can't mount here
    SPELL_FAILED_NO_PET                         = 0x54, // You do not have a pet
    SPELL_FAILED_NO_POWER                       = 0x55, // Not enough mana (tested on warrior)
    SPELL_FAILED_NOTHING_TO_DISPEL              = 0x56, // Nothing to dispel
    SPELL_FAILED_NOTHING_TO_STEAL               = 0x57, // Nothing to steal
    SPELL_FAILED_ONLY_ABOVEWATER                = 0x58, // Cannot use while swimming
    SPELL_FAILED_ONLY_DAYTIME                   = 0x59, // Can only use during the day
    SPELL_FAILED_ONLY_INDOORS                   = 0x5A, // Can only use indoors
    SPELL_FAILED_ONLY_MOUNTED                   = 0x5B, // Can only use while mounted
    SPELL_FAILED_ONLY_NIGHTTIME                 = 0x5C, // Can only use during the night
    SPELL_FAILED_ONLY_OUTDOORS                  = 0x5D, // Can only use outside
    SPELL_FAILED_ONLY_SHAPESHIFT                = 0x5E, // Must be in %s
    SPELL_FAILED_ONLY_STEALTHED                 = 0x5F, // You must be in stealth mode
    SPELL_FAILED_ONLY_UNDERWATER                = 0x60, // Can only use while swimming
    SPELL_FAILED_OUT_OF_RANGE                   = 0x61, // Out of range
    SPELL_FAILED_PACIFIED                       = 0x62, // Can't use that ability while pacified
    SPELL_FAILED_POSSESSED                      = 0x63, // You are possessed
    SPELL_FAILED_REAGENTS                       = 0x64, // Missing reagent: %s
    SPELL_FAILED_REQUIRES_AREA                  = 0x65, // You need to be in %s
    SPELL_FAILED_REQUIRES_SPELL_FOCUS           = 0x66, // Requires %s
    SPELL_FAILED_ROOTED                         = 0x67, // You are unable to move
    SPELL_FAILED_SILENCED                       = 0x68, // Can't do that while silenced
    SPELL_FAILED_SPELL_IN_PROGRESS              = 0x69, // Another action is in progress
    SPELL_FAILED_SPELL_LEARNED                  = 0x6A, // You have already learned the spell
    SPELL_FAILED_SPELL_UNAVAILABLE              = 0x6B, // The spell is not available to you
    SPELL_FAILED_STUNNED                        = 0x6C, // Can't do that while stunned
    SPELL_FAILED_TARGETS_DEAD                   = 0x6D, // Your target is dead
    SPELL_FAILED_TARGET_AFFECTING_COMBAT        = 0x6E, // Target is in combat
    SPELL_FAILED_TARGET_AURASTATE               = 0x6F, // You can't do that yet
    SPELL_FAILED_TARGET_DUELING                 = 0x70, // Target is currently dueling
    SPELL_FAILED_TARGET_ENEMY                   = 0x71, // Target is hostile
    SPELL_FAILED_TARGET_ENRAGED                 = 0x72, // Target is too enraged to be charmed
    SPELL_FAILED_TARGET_FRIENDLY                = 0x73, // Target is friendly
    SPELL_FAILED_TARGET_IN_COMBAT               = 0x74, // The target can't be in combat
    SPELL_FAILED_TARGET_IS_PLAYER               = 0x75, // Can't target players
    SPELL_FAILED_TARGET_IS_PLAYER_CONTROLLED    = 0x76, // Can't target player controlled units
    SPELL_FAILED_TARGET_NOT_DEAD                = 0x77, // Target is alive
    SPELL_FAILED_TARGET_NOT_IN_PARTY            = 0x78, // Target is not in your party
    SPELL_FAILED_TARGET_NOT_LOOTED              = 0x79, // Creature must be looted first
    SPELL_FAILED_TARGET_NOT_PLAYER              = 0x7A, // Target is not a player
    SPELL_FAILED_TARGET_NO_POCKETS              = 0x7B, // No pockets to pick
    SPELL_FAILED_TARGET_NO_WEAPONS              = 0x7C, // Target has no weapons equipped
    SPELL_FAILED_TARGET_NO_RANGED_WEAPONS       = 0x7D, // Target has no ranged weapons equipped
    SPELL_FAILED_TARGET_UNSKINNABLE             = 0x7E, // Creature is not skinnable
    SPELL_FAILED_THIRST_SATIATED                = 0x7F,
    SPELL_FAILED_TOO_CLOSE                      = 0x80, // Target too close
    SPELL_FAILED_TOO_MANY_OF_ITEM               = 0x81, // You have too many of that item already
    SPELL_FAILED_TOTEM_CATEGORY                 = 0x82, // Requires %s
    SPELL_FAILED_TOTEMS                         = 0x83, // Requires %s
    SPELL_FAILED_TRY_AGAIN                      = 0x84, // Failed attempt
    SPELL_FAILED_UNIT_NOT_BEHIND                = 0x85, // Target needs to be behind you
    SPELL_FAILED_UNIT_NOT_INFRONT               = 0x86, // Target needs to be in front of you
    SPELL_FAILED_WRONG_PET_FOOD                 = 0x87, // Your pet doesn't like that food
    SPELL_FAILED_NOT_WHILE_FATIGUED             = 0x88, // Can't cast while fatigued
    SPELL_FAILED_TARGET_NOT_IN_INSTANCE         = 0x89, // Target must be in this instance
    SPELL_FAILED_NOT_WHILE_TRADING              = 0x8A, // Can't cast while trading
    SPELL_FAILED_TARGET_NOT_IN_RAID             = 0x8B, // Target is not in your party or raid group
    SPELL_FAILED_TARGET_FREEFORALL              = 0x8C, // Target is currently in free-for-all PvP combat
    SPELL_FAILED_NO_EDIBLE_CORPSES              = 0x8D, // There are no nearby corpses to eat
    SPELL_FAILED_ONLY_BATTLEGROUNDS             = 0x8E, // Can only use in battlegrounds
    SPELL_FAILED_TARGET_NOT_GHOST               = 0x8F, // Target is not a ghost
    SPELL_FAILED_TRANSFORM_UNUSABLE             = 0x90, // You can't use the new item
    SPELL_FAILED_WRONG_WEATHER                  = 0x91, // The weather isn't right for that
    SPELL_FAILED_DAMAGE_IMMUNE                  = 0x92, // You can't do that while you are immune
    SPELL_FAILED_PREVENTED_BY_MECHANIC          = 0x93, // Can't do that while %s
    SPELL_FAILED_PLAY_TIME                      = 0x94, // Maximum play time exceeded
    SPELL_FAILED_REPUTATION                     = 0x95, // Your reputation isn't high enough
    SPELL_FAILED_MIN_SKILL                      = 0x96, // Your skill is not high enough. Requires %s(%d).
    SPELL_FAILED_NOT_IN_ARENA                   = 0x97, // You can't do that in an arena
    SPELL_FAILED_NOT_ON_SHAPESHIFT              = 0x98, // Cannot be cast on shapeshifted target
    SPELL_FAILED_NOT_ON_STEALTHED               = 0x99, // Spell cannot be cast on stealthed target
    SPELL_FAILED_NOT_ON_DAMAGE_IMMUNE           = 0x9A, // Spell cannot be cast on a damage immune target
    SPELL_FAILED_NOT_ON_MOUNTED                 = 0x9B, // Spell cannot be cast on a mounted unit
    SPELL_FAILED_TOO_SHALLOW                    = 0x9C, // Water too shallow
    SPELL_FAILED_TARGET_NOT_IN_SANCTUARY        = 0x9D, // Target is not in a sanctuary
    SPELL_FAILED_TARGET_IS_TRIVIAL              = 0x9E, // Can't target trivial
    SPELL_FAILED_BM_OR_INVISGOD                 = 0x9F, // The spell cannot be cast on beastmaster or invis god targets
    SPELL_FAILED_EXPERT_RIDING_REQUIREMENT      = 0xA0, // Requires expert riding skill
    SPELL_FAILED_ARTISAN_RIDING_REQUIREMENT     = 0xA1, // Requires artisan riding skill
    SPELL_FAILED_NOT_IDLE                       = 0xA2, // Can't use while Idle
    SPELL_FAILED_NOT_INACTIVE                   = 0xA3, // Can't use while Inactive
    SPELL_FAILED_PARTIAL_PLAYTIME               = 0xA4, // You can not do this. You have more than 3 hours of online time
    SPELL_FAILED_NO_PLAYTIME                    = 0xA5, // You can not do this. You have more than 5 hours of online time
    SPELL_FAILED_NOT_IN_BATTLEGROUND            = 0xA6, // You can't do that in a battleground
    SPELL_FAILED_NOT_IN_RAID_INSTANCE           = 0xA7, // You can't do that in a raid instance
    SPELL_FAILED_ONLY_IN_ARENA                  = 0xA8, // You can only do that in an arena
    SPELL_FAILED_TARGET_LOCKED_TO_RAID_INSTANCE = 0xA9, // Target is locked to another raid instance
    SPELL_FAILED_ON_USE_ENCHANT                 = 0xAA, // That item already has an activated ability
    SPELL_FAILED_NOT_ON_GROUND                  = 0xAB, // Cannot use on the ground
    SPELL_FAILED_CUSTOM_ERROR                   = 0xAC,
    SPELL_FAILED_CANT_DO_THAT_RIGHT_NOW         = 0xAD, // You can't do that right now
    SPELL_FAILED_TOO_MANY_SOCKETS               = 0xAE, // That item has too many sockets
    SPELL_FAILED_INVALID_GLYPH                  = 0xAF, // That glyph cannot be inscribed there
    SPELL_FAILED_UNIQUE_GLYPH                   = 0xB0, // That glyph is already inscribed in your spellbook
    SPELL_FAILED_GLYPH_SOCKET_LOCKED            = 0xB1, // You cannot inscribe a glyph there yet
    SPELL_FAILED_NO_VALID_TARGETS               = 0xB2, // No valid targets
    SPELL_FAILED_ITEM_AT_MAX_CHARGES            = 0xB3, // Item already has the maximum number of charges
    SPELL_FAILED_NOT_IN_BARBERSHOP              = 0xB4, // You can't do that while in the barber shop
    SPELL_FAILED_FISHING_TOO_LOW                = 0xB5, // Requires fishing %d
    SPELL_FAILED_ITEM_ENCHANT_TRADE_WINDOW      = 0xB6, // Item cannot be enchanted in trade
    SPELL_FAILED_SUMMON_PENDING                 = 0xB7, // A summon is already pending
    SPELL_FAILED_MAX_SOCKETS                    = 0xB8, // That item cannot receive additional sockets
    SPELL_FAILED_PET_CAN_RENAME                 = 0xB9, // You can already rename your pet
    SPELL_FAILED_TARGET_CANNOT_BE_RESURRECTED   = 0xBA, // Target cannot be resurrected
    SPELL_FAILED_UNKNOWN                        = 0xBB  // Unknown reason
};

#define SPELL_CANCAST_OK SPELL_FAILED_SUCCESS

// Extra error messages
enum SpellExtraError
{
    SPELL_EXTRA_ERROR_NONE = 0,     // none
    SPELL_EXTRA_ERROR_UNK1 = 1,
    SPELL_EXTRA_ERROR_UNK2 = 2,
    SPELL_EXTRA_ERROR_UNK3 = 3,
    SPELL_EXTRA_ERROR_UNK4 = 4,
    SPELL_EXTRA_ERROR_UNK5 = 5,
    SPELL_EXTRA_ERROR_UNK6 = 6,
    SPELL_EXTRA_ERROR_UNK7 = 7,
    SPELL_EXTRA_ERROR_UNK8 = 8,
    SPELL_EXTRA_ERROR_UNK9 = 9,
    SPELL_EXTRA_ERROR_UNK10 = 10,
    SPELL_EXTRA_ERROR_UNK11 = 11,
    SPELL_EXTRA_ERROR_UNK12 = 12,
    SPELL_EXTRA_ERROR_UNK13 = 13,
    SPELL_EXTRA_ERROR_UNK14 = 14,
    SPELL_EXTRA_ERROR_UNK15 = 15,
    SPELL_EXTRA_ERROR_UNK16 = 16,
    SPELL_EXTRA_ERROR_UNK17 = 17,
    SPELL_EXTRA_ERROR_UNK18 = 18,
    SPELL_EXTRA_ERROR_UNK19 = 19,
    SPELL_EXTRA_ERROR_UNK20 = 20,
    SPELL_EXTRA_ERROR_UNK21 = 21,
    SPELL_EXTRA_ERROR_UNK22 = 22,
    SPELL_EXTRA_ERROR_UNK23 = 23,
    SPELL_EXTRA_ERROR_UNK24 = 24,
    SPELL_EXTRA_ERROR_UNK25 = 25,
    SPELL_EXTRA_ERROR_UNK26 = 26,
    SPELL_EXTRA_ERROR_UNK27 = 27,
    SPELL_EXTRA_ERROR_UNK28 = 28,
    SPELL_EXTRA_ERROR_UNK29 = 29,
    SPELL_EXTRA_ERROR_UNK30 = 30,
    SPELL_EXTRA_ERROR_UNK31 = 31,
    SPELL_EXTRA_ERROR_UNK32 = 32,
    SPELL_EXTRA_ERROR_UNK33 = 33,
    SPELL_EXTRA_ERROR_UNK34 = 34,
    SPELL_EXTRA_ERROR_UNK35 = 35,
    SPELL_EXTRA_ERROR_UNK36 = 36,
    SPELL_EXTRA_ERROR_UNK37 = 37,
    SPELL_EXTRA_ERROR_UNK38 = 38,
    SPELL_EXTRA_ERROR_UNK39 = 39,
    SPELL_EXTRA_ERROR_UNK40 = 40,
    SPELL_EXTRA_ERROR_UNK41 = 41,
    SPELL_EXTRA_ERROR_UNK42 = 42,
    SPELL_EXTRA_ERROR_UNK43 = 43,
    SPELL_EXTRA_ERROR_UNK44 = 44,
    SPELL_EXTRA_ERROR_UNK45 = 45,
    SPELL_EXTRA_ERROR_UNK46 = 46,
    SPELL_EXTRA_ERROR_UNK47 = 47,
    SPELL_EXTRA_ERROR_UNK48 = 48,
    SPELL_EXTRA_ERROR_UNK49 = 49,
    SPELL_EXTRA_ERROR_UNK50 = 50,
    SPELL_EXTRA_ERROR_UNK51 = 51,
    SPELL_EXTRA_ERROR_UNK52 = 52,
    SPELL_EXTRA_ERROR_UNK53 = 53,
    SPELL_EXTRA_ERROR_UNK54 = 54,
    SPELL_EXTRA_ERROR_UNK55 = 55,
    SPELL_EXTRA_ERROR_UNK56 = 56,
    SPELL_EXTRA_ERROR_UNK57 = 57,
    SPELL_EXTRA_ERROR_UNK58 = 58,
    SPELL_EXTRA_ERROR_UNK59 = 59,
    SPELL_EXTRA_ERROR_UNK60 = 60,
    SPELL_EXTRA_ERROR_UNK61 = 61,
    SPELL_EXTRA_ERROR_UNK62 = 62,
    SPELL_EXTRA_ERROR_UNK63 = 63,
    SPELL_EXTRA_ERROR_UNK64 = 64,
    SPELL_EXTRA_ERROR_GM_ONLY = 65,     // Only GMs may use that. Your account has been reported for investigation.
    SPELL_EXTRA_ERROR_UNK66 = 66,
    SPELL_EXTRA_ERROR_UNK67 = 67,
    SPELL_EXTRA_ERROR_UNK68 = 68,
    SPELL_EXTRA_ERROR_UNK69 = 69,
    SPELL_EXTRA_ERROR_UNK70 = 70,
    SPELL_EXTRA_ERROR_UNK71 = 71,
    SPELL_EXTRA_ERROR_UNK72 = 72,
    SPELL_EXTRA_ERROR_UNK73 = 73,
    SPELL_EXTRA_ERROR_UNK74 = 74,
    SPELL_EXTRA_ERROR_UNK75 = 75,
    SPELL_EXTRA_ERROR_UNK76 = 76,
    SPELL_EXTRA_ERROR_UNK77 = 77,
    SPELL_EXTRA_ERROR_UNK78 = 78,
    SPELL_EXTRA_ERROR_UNK79 = 79,
    SPELL_EXTRA_ERROR_UNK80 = 80,
    SPELL_EXTRA_ERROR_UNK81 = 81,
    SPELL_EXTRA_ERROR_UNK82 = 82,
    SPELL_EXTRA_ERROR_MUST_HAVE_FIRE_TOTEM  = 83,       // You must have a Fire Totem active.
    SPELL_EXTRA_ERROR_UNK84 = 84,
    SPELL_EXTRA_ERROR_UNK85 = 85,
    SPELL_EXTRA_ERROR_UNK86 = 86,
    SPELL_EXTRA_ERROR_UNK87 = 87,
    SPELL_EXTRA_ERROR_UNK88 = 88,
    SPELL_EXTRA_ERROR_UNK89 = 89,
    SPELL_EXTRA_ERROR_UNK90 = 90,
    SPELL_EXTRA_ERROR_UNK91 = 91,
    SPELL_EXTRA_ERROR_UNK92 = 92,
    SPELL_EXTRA_ERROR_UNK93 = 93,
    SPELL_EXTRA_ERROR_UNK94 = 94,
    SPELL_EXTRA_ERROR_UNK95 = 95,
    SPELL_EXTRA_ERROR_UNK96 = 96,
    SPELL_EXTRA_ERROR_UNK97 = 97,
    SPELL_EXTRA_ERROR_UNK98 = 98,
    SPELL_EXTRA_ERROR_UNK99 = 99
};

enum PetTameFailure
{
    PETTAME_INVALIDCREATURE                                      = 1,
    PETTAME_TOOMANY                                              = 2,
    PETTAME_CREATUREALREADYOWNED                                 = 3,
    PETTAME_NOTTAMEABLE                                          = 4,
    PETTAME_ANOTHERSUMMONACTIVE                                  = 5,
    PETTAME_UNITSCANTTAME                                        = 6,
    PETTAME_NOPETAVAILABLE                                       = 7,
    PETTAME_INTERNALERROR                                        = 8,
    PETTAME_TOOHIGHLEVEL                                         = 9,
    PETTAME_DEAD                                                 = 10,
    PETTAME_NOTDEAD                                              = 11,
    PETTAME_CANTCONTROLEXOTIC                                    = 12,
    PETTAME_UNKNOWNERROR                                         = 13
};

enum MountFailure
{
    ERR_MOUNT_NOTMOUNTABLE                                       = 0,
    ERR_MOUNT_TOOFARAWAY                                         = 1,
    ERR_MOUNT_ALREADYMOUNTED                                     = 2,
    ERR_MOUNT_INVALIDMOUNTEE                                     = 3,
    ERR_MOUNT_NOTYOURPET                                         = 4,
    ERR_MOUNT_OTHER                                              = 5,
    ERR_MOUNT_LOOTING                                            = 6,
    ERR_MOUNT_RACECANTMOUNT                                      = 7,
    ERR_MOUNT_SHAPESHIFTED                                       = 8,
    ERR_MOUNT_FORCEDDISMOUNT                                     = 9
};

enum DismountFailure
{
    ERR_DISMOUNT_NOPET                                           = 0,
    ERR_DISMOUNT_NOTMOUNTED                                      = 1,
    ERR_DISMOUNT_NOTYOURPET                                      = 2
};
