--
-- DELETE wrong spawns
--
DELETE FROM `creature_spawns` WHERE `entry` = 27559;
DELETE FROM `creature_spawns` WHERE `entry` = 19222;

--
-- Update creature_spawns Wrathgarte phase
--
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127853;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127854;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127855;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127856;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127858;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127859;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127860;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127861;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127862;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127863;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127864;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127865;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127866;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127867;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127868;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127869;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127870;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127871;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127872;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127873;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127874;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127875;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127876;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127877;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127878;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127879;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127880;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127881;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127882;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127883;
UPDATE `creature_spawns` SET `phase` = 2 WHERE `id` = 127884;

--
-- DELETE wrong gameobject_spawns
--
DELETE FROM `gameobject_spawns` WHERE `entry` = 191861;

--
-- Update gameobject_spawns Wrathgarte phase
--
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 49424;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51767;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51768;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51769;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51770;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51771;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51772;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51773;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51774;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51777;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51781;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51783;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51785;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51787;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51789;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51791;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51792;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51793;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51794;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51795;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51796;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51797;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51798;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51799;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51800;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51801;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51809;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51810;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51811;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51812;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51813;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51815;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51816;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51818;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51820;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51822;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51824;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51826;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51828;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51830;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51832;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51834;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51835;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51836;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51837;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51838;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51839;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51840;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51841;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51842;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51843;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51844;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51845;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51846;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51847;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51848;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51849;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51850;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51851;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51852;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51853;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51854;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51856;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51857;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51859;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51860;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51862;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51864;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51866;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51867;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51868;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51869;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51870;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51871;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51874;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51876;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51877;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51879;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51881;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51883;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51884;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51886;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51889;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51892;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51895;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51896;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51897;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51898;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51899;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51900;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51901;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51908;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51910;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51911;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51912;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51913;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51914;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51915;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51916;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51920;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51921;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51922;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51924;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51925;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51928;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51930;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51932;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51934;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51936;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51938;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51940;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51941;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51943;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51945;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51946;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51948;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51950;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51952;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51973;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51974;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51975;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51989;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51990;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51991;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51992;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51993;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51995;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51996;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51997;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 51999;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52001;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52003;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52004;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52005;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52006;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52007;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52008;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52009;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52010;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52011;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52012;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52013;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52014;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52015;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52016;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52017;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52018;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52019;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52020;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52021;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52022;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52023;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52025;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52027;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52029;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52030;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52031;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52032;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52033;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52034;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52036;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52037;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52039;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52040;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52041;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52042;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52043;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52045;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52048;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52050;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52052;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52054;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52055;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52056;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52057;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52058;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52059;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52060;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52061;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 52062;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 56132;
UPDATE `gameobject_spawns` SET `phase` = 2 WHERE `id` = 56575;

--
-- Update world_db_version
--

UPDATE `world_db_version` SET `LastUpdate` = '2015-10-22_05_misc_updates' WHERE `LastUpdate` = '2015-10-22_04_misc_updates';
