--
-- serverside spells
--
DROP TABLE IF EXISTS `spells`;
CREATE TABLE IF NOT EXISTS `spells` (
  `Id` int(11) unsigned NOT NULL DEFAULT '0',
  `Category` int(11) unsigned NOT NULL DEFAULT '0',
  `DispelType` int(11) unsigned NOT NULL DEFAULT '0',
  `MechanicsType` int(11) unsigned NOT NULL DEFAULT '0',
  `Attributes` int(11) unsigned NOT NULL DEFAULT '0',
  `AttributesEx` int(11) unsigned NOT NULL DEFAULT '0',
  `AttributesExB` int(11) unsigned NOT NULL DEFAULT '0',
  `AttributesExC` int(11) unsigned NOT NULL DEFAULT '0',
  `AttributesExD` int(11) unsigned NOT NULL DEFAULT '0',
  `AttributesExE` int(11) unsigned NOT NULL DEFAULT '0',
  `AttributesExF` int(11) unsigned NOT NULL DEFAULT '0',
  `AttributesExG` int(11) unsigned NOT NULL DEFAULT '0',
  `AttributesExH` int(11) unsigned NOT NULL DEFAULT '0',
  `AttributesExI` int(11) unsigned NOT NULL DEFAULT '0',
  `AttributesExJ` int(11) unsigned NOT NULL DEFAULT '0',
  `RequiredShapeShift` int(11) unsigned NOT NULL DEFAULT '0',
  `ShapeshiftExclude` int(11) unsigned NOT NULL DEFAULT '0',
  `Targets` int(11) unsigned NOT NULL DEFAULT '0',
  `TargetCreatureType` int(11) unsigned NOT NULL DEFAULT '0',
  `RequiresSpellFocus` int(11) unsigned NOT NULL DEFAULT '0',
  `FacingCasterFlags` int(11) unsigned NOT NULL DEFAULT '0',
  `CasterAuraState` int(11) unsigned NOT NULL DEFAULT '0',
  `TargetAuraState` int(11) unsigned NOT NULL DEFAULT '0',
  `CasterAuraStateNot` int(11) unsigned NOT NULL DEFAULT '0',
  `TargetAuraStateNot` int(11) unsigned NOT NULL DEFAULT '0',
  `casterAuraSpell` int(11) unsigned NOT NULL DEFAULT '0',
  `targetAuraSpell` int(11) unsigned NOT NULL DEFAULT '0',
  `casterAuraSpellNot` int(11) unsigned NOT NULL DEFAULT '0',
  `targetAuraSpellNot` int(11) unsigned NOT NULL DEFAULT '0',
  `CastingTimeIndex` int(11) unsigned NOT NULL DEFAULT '0',
  `RecoveryTime` int(11) unsigned NOT NULL DEFAULT '0',
  `CategoryRecoveryTime` int(11) unsigned NOT NULL DEFAULT '0',
  `InterruptFlags` int(11) unsigned NOT NULL DEFAULT '0',
  `AuraInterruptFlags` int(11) unsigned NOT NULL DEFAULT '0',
  `ChannelInterruptFlags` int(11) unsigned NOT NULL DEFAULT '0',
  `procFlags` int(11) unsigned NOT NULL DEFAULT '0',
  `procChance` int(11) unsigned NOT NULL DEFAULT '0',
  `procCharges` int(11) unsigned NOT NULL DEFAULT '0',
  `maxLevel` int(11) unsigned NOT NULL DEFAULT '0',
  `baseLevel` int(11) unsigned NOT NULL DEFAULT '0',
  `spellLevel` int(11) unsigned NOT NULL DEFAULT '0',
  `DurationIndex` int(11) unsigned NOT NULL DEFAULT '0',
  `powerType` int(11) NOT NULL DEFAULT '0',
  `manaCost` int(11) unsigned NOT NULL DEFAULT '0',
  `manaCostPerlevel` int(11) unsigned NOT NULL DEFAULT '0',
  `manaPerSecond` int(11) unsigned NOT NULL DEFAULT '0',
  `manaPerSecondPerLevel` int(11) unsigned NOT NULL DEFAULT '0',
  `rangeIndex` int(11) unsigned NOT NULL DEFAULT '0',
  `speed` float NOT NULL DEFAULT '0',
  `modalNextSpell` int(11) unsigned NOT NULL DEFAULT '0',
  `maxstack` int(11) unsigned NOT NULL DEFAULT '0',
  `Totem_0` int(11) unsigned NOT NULL DEFAULT '0',
  `Totem_1` int(11) unsigned NOT NULL DEFAULT '0',
  `Reagent_0` int(11) unsigned NOT NULL DEFAULT '0',
  `Reagent_1` int(11) unsigned NOT NULL DEFAULT '0',
  `Reagent_2` int(11) unsigned NOT NULL DEFAULT '0',
  `Reagent_4` int(11) unsigned NOT NULL DEFAULT '0',
  `Reagent_5` int(11) unsigned NOT NULL DEFAULT '0',
  `Reagent_6` int(11) unsigned NOT NULL DEFAULT '0',
  `Reagent_7` int(11) unsigned NOT NULL DEFAULT '0',
  `Reagent_8` int(11) unsigned NOT NULL DEFAULT '0',
  `ReagentCount_0` int(11) unsigned NOT NULL DEFAULT '0',
  `ReagentCount_1` int(11) unsigned NOT NULL DEFAULT '0',
  `ReagentCount_2` int(11) unsigned NOT NULL DEFAULT '0',
  `ReagentCount_4` int(11) unsigned NOT NULL DEFAULT '0',
  `ReagentCount_5` int(11) unsigned NOT NULL DEFAULT '0',
  `ReagentCount_6` int(11) unsigned NOT NULL DEFAULT '0',
  `ReagentCount_7` int(11) unsigned NOT NULL DEFAULT '0',
  `ReagentCount_8` int(11) unsigned NOT NULL DEFAULT '0',
  `EquippedItemClass` int(11) NOT NULL DEFAULT '0',
  `EquippedItemSubClass` int(11) unsigned NOT NULL DEFAULT '0',
  `RequiredItemFlags` int(11) unsigned NOT NULL DEFAULT '0',
  `Effect_0` int(11) unsigned NOT NULL DEFAULT '0',
  `Effect_1` int(11) unsigned NOT NULL DEFAULT '0',
  `Effect_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectDieSides_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectDieSides_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectDieSides_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectRealPointsPerLevel_0` float NOT NULL DEFAULT '0',
  `EffectRealPointsPerLevel_1` float NOT NULL DEFAULT '0',
  `EffectRealPointsPerLevel_2` float NOT NULL DEFAULT '0',
  `EffectBasePoints_0` int(11) NOT NULL DEFAULT '0',
  `EffectBasePoints_1` int(11) NOT NULL DEFAULT '0',
  `EffectBasePoints_2` int(11) NOT NULL DEFAULT '0',
  `EffectMechanic_0` int(11) NOT NULL DEFAULT '0',
  `EffectMechanic_1` int(11) NOT NULL DEFAULT '0',
  `EffectMechanic_2` int(11) NOT NULL DEFAULT '0',
  `EffectImplicitTargetA_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectImplicitTargetA_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectImplicitTargetA_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectImplicitTargetB_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectImplicitTargetB_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectImplicitTargetB_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectRadiusIndex_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectRadiusIndex_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectRadiusIndex_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectApplyAuraName_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectApplyAuraName_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectApplyAuraName_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectAmplitude_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectAmplitude_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectAmplitude_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectMultipleValue_0` float NOT NULL DEFAULT '0',
  `EffectMultipleValue_1` float NOT NULL DEFAULT '0',
  `EffectMultipleValue_2` float NOT NULL DEFAULT '0',
  `EffectChainTarget_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectChainTarget_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectChainTarget_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectItemType_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectItemType_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectItemType_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectMiscValue_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectMiscValue_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectMiscValue_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectMiscValueB_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectMiscValueB_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectMiscValueB_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectTriggerSpell_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectTriggerSpell_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectTriggerSpell_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectPointsPerComboPoint_0` float NOT NULL DEFAULT '0',
  `EffectPointsPerComboPoint_1` float NOT NULL DEFAULT '0',
  `EffectPointsPerComboPoint_2` float NOT NULL DEFAULT '0',
  `EffectSpellClassMask_0_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMask_0_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMask_0_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMask_1_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMask_1_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMask_1_2` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMask_2_0` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMask_2_1` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMask_2_2` int(11) unsigned NOT NULL DEFAULT '0',
  `SpellVisual` int(11) unsigned NOT NULL DEFAULT '0',
  `field114` int(11) unsigned NOT NULL DEFAULT '0',
  `spellIconID` int(11) unsigned NOT NULL DEFAULT '0',
  `activeIconID` int(11) unsigned NOT NULL DEFAULT '0',
  `spellPriority` int(11) unsigned NOT NULL DEFAULT '0',
  `Name` varchar(150) DEFAULT NULL,
  `Rank` varchar(50) DEFAULT NULL,
  `Description` varchar(800) DEFAULT NULL,
  `BuffDescription` varchar(650) DEFAULT NULL,
  `ManaCostPercentage` int(11) unsigned NOT NULL DEFAULT '0',
  `StartRecoveryCategory` int(11) unsigned NOT NULL DEFAULT '0',
  `StartRecoveryTime` int(11) unsigned NOT NULL DEFAULT '0',
  `MaxTargetLevel` int(11) unsigned NOT NULL DEFAULT '0',
  `SpellFamilyName` int(11) unsigned NOT NULL DEFAULT '0',
  `SpellGroupType_0` int(11) unsigned NOT NULL DEFAULT '0',
  `SpellGroupType_1` int(11) unsigned NOT NULL DEFAULT '0',
  `SpellGroupType_2` int(11) unsigned NOT NULL DEFAULT '0',
  `MaxTargets` int(11) unsigned NOT NULL DEFAULT '0',
  `Spell_Dmg_Type` int(11) unsigned NOT NULL DEFAULT '0',
  `PreventionType` int(11) unsigned NOT NULL DEFAULT '0',
  `StanceBarOrder` int(11) NOT NULL DEFAULT '0',
  `dmg_multiplier_0` float NOT NULL DEFAULT '0',
  `dmg_multiplier_1` float NOT NULL DEFAULT '0',
  `dmg_multiplier_2` float NOT NULL DEFAULT '0',
  `MinFactionID` int(11) unsigned NOT NULL DEFAULT '0',
  `MinReputation` int(11) unsigned NOT NULL DEFAULT '0',
  `RequiredAuraVision` int(11) unsigned NOT NULL DEFAULT '0',
  `TotemCategory_0` int(11) unsigned NOT NULL DEFAULT '0',
  `TotemCategory_1` int(11) unsigned NOT NULL DEFAULT '0',
  `RequiresAreaId` int(11) NOT NULL DEFAULT '0',
  `School` int(11) unsigned NOT NULL DEFAULT '0',
  `RuneCostID` int(11) unsigned NOT NULL DEFAULT '0',
  `SpellMissileID` int(11) unsigned NOT NULL DEFAULT '0',
  `PowerDisplayId` int(11) unsigned NOT NULL DEFAULT '0',
  `EffectBonusMultiplier_0` float NOT NULL DEFAULT '0',
  `EffectBonusMultiplier_1` float NOT NULL DEFAULT '0',
  `EffectBonusMultiplier_2` float NOT NULL DEFAULT '0',
  `SpellDescriptionVariable` int(11) unsigned NOT NULL DEFAULT '0',
  `SpellDifficultyID` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Id` (`Id`),
  KEY `Id_2` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Update world_db_version
--
UPDATE `world_db_version` SET `LastUpdate` = '2016-10-15_01_serverside_spells' WHERE `LastUpdate` = '2016-10-14_01_kezan_quest';