/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

// Generated by the version table generator - do not edit by hand, regenerate instead.

#pragma once

#include <cstdint>

// Version neutral field ids for the WoW data structs. Every id that exists in any client
// version is listed, the per version layout tables decide which ones are present. Each
// enum covers the own fields of its struct, the base struct fields have their own enum.
// Besides the whole members the leaves are listed: union parts and members of array elements.
namespace Version
{
    enum class ObjectField : uint16_t
    {
        Guid,                                        // guid
        GuidLow,                                     // guid.parts.low
        GuidHigh,                                    // guid.parts.high
        Type,                                        // type
        Entry,                                       // entry
        ScaleX,                                      // scale_x
        PaddingObject,                               // padding_object
        Data,                                        // data
        FieldType,                                   // field_type
        FieldTypeType,                               // field_type.parts.type
        FieldTypeGuildId,                            // field_type.parts.guild_id
        DynamicField,                                // dynamic_field
        DynamicFieldDynamicFlags,                    // dynamic_field.dynamic_field_parts.dynamic_flags
        DynamicFieldPathProgress,                    // dynamic_field.dynamic_field_parts.path_progress
        Count
    };

    enum class UnitField : uint16_t
    {
        CharmGuid,                                   // charm_guid
        CharmGuidLow,                                // charm_guid.parts.low
        CharmGuidHigh,                               // charm_guid.parts.high
        SummonGuid,                                  // summon_guid
        SummonGuidLow,                               // summon_guid.parts.low
        SummonGuidHigh,                              // summon_guid.parts.high
        CharmedByGuid,                               // charmed_by_guid
        CharmedByGuidLow,                            // charmed_by_guid.parts.low
        CharmedByGuidHigh,                           // charmed_by_guid.parts.high
        SummonedByGuid,                              // summoned_by_guid
        SummonedByGuidLow,                           // summoned_by_guid.parts.low
        SummonedByGuidHigh,                          // summoned_by_guid.parts.high
        CreatedByGuid,                               // created_by_guid
        CreatedByGuidLow,                            // created_by_guid.parts.low
        CreatedByGuidHigh,                           // created_by_guid.parts.high
        TargetGuid,                                  // target_guid
        TargetGuidLow,                               // target_guid.parts.low
        TargetGuidHigh,                              // target_guid.parts.high
        PersuadedGuid,                               // persuaded_guid
        PersuadedGuidLow,                            // persuaded_guid.parts.low
        PersuadedGuidHigh,                           // persuaded_guid.parts.high
        ChannelObjectGuid,                           // channel_object_guid
        ChannelObjectGuidLow,                        // channel_object_guid.parts.low
        ChannelObjectGuidHigh,                       // channel_object_guid.parts.high
        Health,                                      // health
        Power1,                                      // power_1
        Power2,                                      // power_2
        Power3,                                      // power_3
        Power4,                                      // power_4
        Power5,                                      // power_5
        MaxHealth,                                   // max_health
        MaxPower1,                                   // max_power_1
        MaxPower2,                                   // max_power_2
        MaxPower3,                                   // max_power_3
        MaxPower4,                                   // max_power_4
        MaxPower5,                                   // max_power_5
        Level,                                       // level
        FactionTemplate,                             // faction_template
        FieldBytes0,                                 // field_bytes_0
        FieldBytes0Race,                             // field_bytes_0.s.race
        FieldBytes0UnitClass,                        // field_bytes_0.s.unit_class
        FieldBytes0Gender,                           // field_bytes_0.s.gender
        FieldBytes0PowerType,                        // field_bytes_0.s.power_type
        VirtualItemSlotDisplay,                      // virtual_item_slot_display[]
        VirtualItemInfo,                             // virtual_item_info[]
        VirtualItemInfoItemClass,                    // virtual_item_info.fields.item_class[]
        VirtualItemInfoItemSubclass,                 // virtual_item_info.fields.item_subclass[]
        VirtualItemInfoUnk0,                         // virtual_item_info.fields.unk0[]
        VirtualItemInfoMaterial,                     // virtual_item_info.fields.material[]
        VirtualItemInfoInventoryType,                // virtual_item_info.fields.inventory_type[]
        VirtualItemInfoSheath,                       // virtual_item_info.fields.sheath[]
        UnitFlags,                                   // unit_flags
        Aura,                                        // aura[]
        AuraFlags,                                   // aura_flags[]
        AuraLevels,                                  // aura_levels[]
        AuraApplications,                            // aura_applications[]
        AuraState,                                   // aura_state
        BaseAttackTime,                              // base_attack_time[]
        BoundingRadius,                              // bounding_radius
        CombatReach,                                 // combat_reach
        DisplayId,                                   // display_id
        NativeDisplayId,                             // native_display_id
        MountDisplayId,                              // mount_display_id
        MinimumDamage,                               // minimum_damage
        MaximumDamage,                               // maximum_damage
        MinimumOffhandDamage,                        // minimum_offhand_damage
        MaximumOffhandDamage,                        // maximum_offhand_damage
        FieldBytes1,                                 // field_bytes_1
        FieldBytes1StandState,                       // field_bytes_1.s.stand_state
        FieldBytes1PetLoyalty,                       // field_bytes_1.s.pet_loyalty
        FieldBytes1ShapeShiftForm,                   // field_bytes_1.s.shape_shift_form
        FieldBytes1StandStateFlag,                   // field_bytes_1.s.stand_state_flag
        PetNumber,                                   // pet_number
        PetNameTimestamp,                            // pet_name_timestamp
        PetExperience,                               // pet_experience
        PetNextLevelExperience,                      // pet_next_level_experience
        DynamicFlags,                                // dynamic_flags
        ChannelSpell,                                // channel_spell
        ModCastSpeed,                                // mod_cast_speed
        CreatedBySpellId,                            // created_by_spell_id
        NpcFlags,                                    // npc_flags
        NpcEmoteState,                               // npc_emote_state
        TrainingPoints,                              // training_points
        Stat,                                        // stat[]
        Resistance,                                  // resistance[]
        BaseMana,                                    // base_mana
        BaseHealth,                                  // base_health
        FieldBytes2,                                 // field_bytes_2
        FieldBytes2SheathType,                       // field_bytes_2.s.sheath_type
        FieldBytes2Unk1,                             // field_bytes_2.s.unk1
        FieldBytes2Unk2,                             // field_bytes_2.s.unk2
        FieldBytes2Unk3,                             // field_bytes_2.s.unk3
        AttackPower,                                 // attack_power
        AttackPowerMods,                             // attack_power_mods
        AttackPowerMultiplier,                       // attack_power_multiplier
        RangedAttackPower,                           // ranged_attack_power
        RangedAttackPowerMods,                       // ranged_attack_power_mods
        RangedAttackPowerMultiplier,                 // ranged_attack_power_multiplier
        MinimumRangedDamage,                         // minimum_ranged_damage
        MaximumRangedDamage,                         // maximum_ranged_ddamage
        PowerCostModifier,                           // power_cost_modifier[]
        PowerCostMultiplier,                         // power_cost_multiplier[]
        UnitPadding,                                 // unit_padding
        UnitFlags2,                                  // unit_flags_2
        FieldBytes1AnimationFlag,                    // field_bytes_1.s.animation_flag
        PositiveStat,                                // positive_stat[]
        NegativeStat,                                // negative_stat[]
        ResistanceBuffModPositive,                   // resistance_buff_mod_positive[]
        ResistanceBuffModNegative,                   // resistance_buff_mod_negative[]
        FieldBytes2PositiveAuraLimit,                // field_bytes_2.s.positive_aura_limit
        FieldBytes2PetFlag,                          // field_bytes_2.s.pet_flag
        FieldBytes2ShapeShiftForm,                   // field_bytes_2.s.shape_shift_form
        MaxHealthModifier,                           // max_health_modifier
        CritterGuid,                                 // critter_guid
        CritterGuidLow,                              // critter_guid.parts.low
        CritterGuidHigh,                             // critter_guid.parts.high
        Power6,                                      // power_6
        Power7,                                      // power_7
        MaxPower6,                                   // max_power_6
        MaxPower7,                                   // max_power_7
        PowerRegenFlatModifier,                      // power_regen_flat_modifier[]
        PowerRegenInterruptedFlatModifier,           // power_regen_interrupted_flat_modifier[]
        FieldBytes1PetTalentPoints,                  // field_bytes_1.s.pet_talent_points
        FieldBytes2PvpFlag,                          // field_bytes_2.s.pvp_flag
        HoverHeight,                                 // hover_height
        ModCastHaste,                                // mod_cast_haste
        AttackPowerModPos,                           // attack_power_mod_pos
        AttackPowerModNeg,                           // attack_power_mod_neg
        RangedAttackPowerModsPos,                    // ranged_attack_power_mods_pos
        RangedAttackPowerModsNeg,                    // ranged_attack_power_mods_neg
        MaxItemLevel,                                // max_item_level
        DemonCreatorGuid,                            // demon_creator_guid
        DemonCreatorGuidLow,                         // demon_creator_guid.parts.low
        DemonCreatorGuidHigh,                        // demon_creator_guid.parts.high
        BattlePetCompanionGuid,                      // battle_pet_companion_guid
        BattlePetCompanionGuidLow,                   // battle_pet_companion_guid.parts.low
        BattlePetCompanionGuidHigh,                  // battle_pet_companion_guid.parts.high
        SummonedByHomeRealm,                         // summoned_by_home_realm
        FieldBytes0ClassSpec,                        // field_bytes_0.s.class_spec
        DisplayPower,                                // display_power
        OverrideDisplayPowerId,                      // override_display_power_id
        EffectiveLevel,                              // effective_level
        FieldBytes1Unk1,                             // field_bytes_1.s.unk1
        ModHaste,                                    // mod_haste
        ModRangedHaste,                              // mod_ranged_haste
        ModHasteRegen,                               // mod_haste_regen
        MinItemLevel,                                // min_item_level
        WildBattlePetLevel,                          // wild_battle_pet_level
        BattlePetCompanionNameTimestamp,             // battle_pet_companion_name_timestamp
        InteractSpellId,                             // interact_spell_id
        Count
    };

    enum class PlayerField : uint16_t
    {
        DuelArbiter,                                 // duel_arbiter
        PlayerFlags,                                 // player_flags
        GuildId,                                     // guild_id
        GuildRank,                                   // guild_rank
        PlayerBytes,                                 // player_bytes
        PlayerBytesSkinColor,                        // player_bytes.s.skin_color
        PlayerBytesFace,                             // player_bytes.s.face
        PlayerBytesHairStyle,                        // player_bytes.s.hair_style
        PlayerBytesHornStyle,                        // player_bytes.s.horn_style
        PlayerBytesHairColor,                        // player_bytes.s.hair_color
        PlayerBytesHornColor,                        // player_bytes.s.horn_color
        PlayerBytes2,                                // player_bytes_2
        PlayerBytes2FacialHair,                      // player_bytes_2.s.facial_hair
        PlayerBytes2Piercings,                       // player_bytes_2.s.piercings
        PlayerBytes2Features,                        // player_bytes_2.s.features
        PlayerBytes2Markings,                        // player_bytes_2.s.markings
        PlayerBytes2Hair,                            // player_bytes_2.s.hair
        PlayerBytes2Earrings,                        // player_bytes_2.s.earrings
        PlayerBytes2Tusks,                           // player_bytes_2.s.tusks
        PlayerBytes2HornStyle,                       // player_bytes_2.s.horn_style
        PlayerBytes2Ears,                            // player_bytes_2.s.ears
        PlayerBytes2Unk1,                            // player_bytes_2.s.unk1
        PlayerBytes2BankSlots,                       // player_bytes_2.s.bank_slots
        PlayerBytes2RestState,                       // player_bytes_2.s.rest_state
        PlayerBytes3,                                // player_bytes_3
        PlayerBytes3Gender,                          // player_bytes_3.s.gender
        PlayerBytes3DrunkValue,                      // player_bytes_3.s.drunk_value
        PlayerBytes3PvpCityProtectorRank,            // player_bytes_3.s.pvp_city_protector_rank
        PlayerBytes3PvpRank,                         // player_bytes_3.s.pvp_rank
        DuelTeam,                                    // duel_team
        GuildTimestamp,                              // guild_timestamp
        Quests,                                      // quests[]
        QuestsQuestId,                               // quests.quest_id[]
        QuestsRequiredCountState,                    // quests.required_count_state[]
        QuestsExpireTime,                            // quests.expire_time[]
        VisibleItems,                                // visible_items[]
        VisibleItemsCreator,                         // visible_items.creator[]
        VisibleItemsEntry,                           // visible_items.entry[]
        VisibleItemsProperties,                      // visible_items.properties[]
        VisibleItemsPadding,                         // visible_items.padding[]
        InventorySlot,                               // inventory_slot[]
        PackSlot,                                    // pack_slot[]
        BankSlot,                                    // bank_slot[]
        BankBagSlot,                                 // bank_bag_slot[]
        VendorBuyBackSlot,                           // vendor_buy_back_slot[]
        KeyRingSlot,                                 // key_ring_slot[]
        FarsightGuid,                                // farsight_guid
        FieldComboTarget,                            // field_combo_target
        Xp,                                          // xp
        NextLevelXp,                                 // next_level_xp
        SkillInfo,                                   // skill_info[]
        SkillInfoId,                                 // skill_info.id[]
        SkillInfoStep,                               // skill_info.step[]
        SkillInfoCurrentValue,                       // skill_info.current_value[]
        SkillInfoMaxValue,                           // skill_info.max_value[]
        SkillInfoBonusTemporary,                     // skill_info.bonus_temporary[]
        SkillInfoBonusPermanent,                     // skill_info.bonus_permanent[]
        CharacterPoints1,                            // character_points_1
        CharacterPoints2,                            // character_points_2
        TrackCreatures,                              // track_creatures
        TrackResources,                              // track_resources
        BlockPct,                                    // block_pct
        DodgePct,                                    // dodge_pct
        ParryPct,                                    // parry_pct
        CritPct,                                     // crit_pct
        RangedCritPct,                               // ranged_crit_pct
        ExploredZones,                               // explored_zones[]
        RestStateXp,                                 // rest_state_xp
        FieldCoinage,                                // field_coinage
        PosStat,                                     // pos_stat[]
        NegStat,                                     // neg_stat[]
        ResistanceBuffModPositive,                   // resistance_buff_mod_positive[]
        ResistanceBuffModNegative,                   // resistance_buff_mod_negative[]
        FieldModDamageDonePositive,                  // field_mod_damage_done_positive[]
        FieldModDamageDoneNegative,                  // field_mod_damage_done_negative[]
        FieldModDamageDonePct,                       // field_mod_damage_done_pct[]
        PlayerFieldBytes,                            // player_field_bytes
        PlayerFieldBytesMiscFlags,                   // player_field_bytes.s.misc_flags
        PlayerFieldBytesComboPoints,                 // player_field_bytes.s.combo_points
        PlayerFieldBytesEnabledActionBars,           // player_field_bytes.s.enabled_action_bars
        PlayerFieldBytesMaxPvpRank,                  // player_field_bytes.s.max_pvp_rank
        AmmoId,                                      // ammo_id
        SelfResurrectionSpell,                       // self_resurrection_spell
        FieldPvpMedals,                              // field_pvp_medals
        FieldBuyBackPrice,                           // field_buy_back_price[]
        FieldBuyBackTimestamp,                       // field_buy_back_timestamp[]
        FieldSessionKills,                           // field_session_kills
        FieldYesterdayKills,                         // field_yesterday_kills
        FieldLastWeekKills,                          // field_last_week_kills
        FieldThisWeekKills,                          // field_this_week_kills
        FieldThisWeekContribution,                   // field_this_week_contribution
        FieldLifetimeHonorableKills,                 // field_lifetime_honorable_kills
        FieldLifetimeDishonorableKills,              // field_lifetime_dishonorable_kills
        FieldYersterdayContribution,                 // field_yersterday_contribution
        FieldLastWeekContribution,                   // field_last_week_contribution
        FieldLastWeekRank,                           // field_last_week_rank
        PlayerFieldBytes2,                           // player_field_bytes_2
        PlayerFieldBytes2Unk0,                       // player_field_bytes_2.s.unk0
        PlayerFieldBytes2AuraVision,                 // player_field_bytes_2.s.aura_vision
        PlayerFieldBytes2Unk2,                       // player_field_bytes_2.s.unk2
        PlayerFieldBytes2Unk3,                       // player_field_bytes_2.s.unk3
        FieldWatchedFactionIdx,                      // field_watched_faction_idx
        FieldCombatRating,                           // field_combat_rating[]
        PlayerBytes3ArenaFaction,                    // player_bytes_3.s.arena_faction
        QuestsState,                                 // quests.state[]
        QuestsRequiredMobOrGo,                       // quests.required_mob_or_go[]
        ChosenTitle,                                 // chosen_title
        PlayerPadding0,                              // player_padding_0
        VanityPetSlot,                               // vanity_pet_slot[]
        FieldKnownTitles,                            // field_known_titles[]
        Expertise,                                   // expertise
        OffhandExpertise,                            // offhand_expertise
        OffhandCritPct,                              // offhand_crit_pct
        SpellCritPct,                                // spell_crit_pct[]
        ShieldBlock,                                 // shield_block
        FieldModHealingDone,                         // field_mod_healing_done
        FieldModTargetResistance,                    // field_mod_target_resistance
        FieldModTargetPhysicalResistance,            // field_mod_target_physical_resistance
        PlayerFieldBytesRafLevel,                    // player_field_bytes.s.raf_level
        FieldKills,                                  // field_kills
        FieldKillsKillsToday,                        // field_kills.kills_field_parts.kills_today
        FieldKillsKillsYesterday,                    // field_kills.kills_field_parts.kills_yesterday
        FieldContributionToday,                      // field_contribution_today
        FieldContributionYesterday,                  // field_contribution_yesterday
        FieldArenaTeamInfo,                          // field_arena_team_info[]
        FieldArenaTeamInfoTeamId,                    // field_arena_team_info.team_id[]
        FieldArenaTeamInfoMemberRank,                // field_arena_team_info.member_rank[]
        FieldArenaTeamInfoGamesWeek,                 // field_arena_team_info.games_week[]
        FieldArenaTeamInfoGamesSeason,               // field_arena_team_info.games_season[]
        FieldArenaTeamInfoWinsSeason,                // field_arena_team_info.wins_season[]
        FieldArenaTeamInfoPersonalRating,            // field_arena_team_info.personal_rating[]
        FieldHonorCurrency,                          // field_honor_currency
        FieldArenaCurrency,                          // field_arena_currency
        FieldModManaRegen,                           // field_mod_mana_regen
        FieldModManaRegenInterrupt,                  // field_mod_mana_regen_interrupt
        FieldMaxLevel,                               // field_max_level
        FieldDailyQuests,                            // field_daily_quests[]
        VisibleItemsEnchantment,                     // visible_items.enchantment[]
        VisibleItemsEnchantmentPermEnchantment,      // visible_items.enchantment.enchantment_field_parts.perm_enchantment[]
        VisibleItemsEnchantmentTempEnchantment,      // visible_items.enchantment.enchantment_field_parts.temp_enchantment[]
        Inebriation,                                 // inebriation
        CurrencytokenSlot,                           // currencytoken_slot[]
        FieldKnownCurrencies,                        // field_known_currencies
        ShieldBlockCritPct,                          // shield_block_crit_pct
        FieldModHealingPct,                          // field_mod_healing_pct
        FieldModHealingDonePct,                      // field_mod_healing_done_pct
        PlayerFieldBytes2OverrideSpellId,            // player_field_bytes_2.s.override_spell_id
        PlayerFieldBytes2IgnorePowerRegenPredictionMask, // player_field_bytes_2.s.ignore_power_regen_prediction_mask
        FieldArenaTeamInfoType,                      // field_arena_team_info.type[]
        RuneRegen,                                   // rune_regen[]
        NoReagentCost,                               // no_reagent_cost[]
        FieldGlyphSlots,                             // field_glyph_slots[]
        FieldGlyphs,                                 // field_glyphs[]
        GlyphsEnabled,                               // glyphs_enabled
        PetSpellPower,                               // pet_spell_power
        GuildDeleteDate,                             // guild_delete_date
        GuildLevel,                                  // guild_level
        FieldSkillInfo,                              // field_skill_info
        FieldSkillInfoSkillLine,                     // field_skill_info.skill_info_parts.skill_line[]
        FieldSkillInfoSkillStep,                     // field_skill_info.skill_info_parts.skill_step[]
        FieldSkillInfoSkillRank,                     // field_skill_info.skill_info_parts.skill_rank[]
        FieldSkillInfoSkillMaxRank,                  // field_skill_info.skill_info_parts.skill_max_rank[]
        FieldSkillInfoSkillMod,                      // field_skill_info.skill_info_parts.skill_mod[]
        FieldSkillInfoSkillTalent,                   // field_skill_info.skill_info_parts.skill_talent[]
        Mastery,                                     // mastery
        WeaponDmgMultiplier,                         // weapon_dmg_multiplier[]
        ModSpellPowerPct,                            // mod_spell_power_pct
        OverrideSpellPowerByApPct,                   // override_spell_power_by_ap_pct
        BattlegroundRating,                          // battleground_rating
        Researching,                                 // researching[]
        ResearchSite,                                // research_site[]
        ProfessionSkillLine,                         // profession_skill_line[]
        UiHitMod,                                    // ui_hit_mod
        UiHitSpellMod,                               // ui_hit_spell_mod
        UiHomeRealmTimeOffset,                       // ui_home_realm_time_offset
        ModHaste,                                    // mod_haste
        ModRangedHaste,                              // mod_ranged_haste
        ModPetHaste,                                 // mod_pet_haste
        ModHasteRegen,                               // mod_haste_regen
        VirtualPlayerRealm,                          // virtual_player_realm
        CurrentSpecId,                               // current_spec_id
        TaxiMountAnimKitId,                          // taxi_mount_anim_kit_id
        CurrentBattlePetBreedQuality,                // current_battle_pet_breed_quality
        FieldSkillInfoSkillId,                       // field_skill_info.skill_id[]
        FieldSkillInfoSkillStartingRank,             // field_skill_info.skill_info_parts.skill_starting_rank[]
        MaxTalentTiers,                              // max_talent_tiers
        RangedExpertise,                             // ranged_expertise
        CombatRatingExpertise,                       // combat_rating_expertise
        PvpPowerDamage,                              // pvp_power_damage
        PvpPowerHealing,                             // pvp_power_healing
        FieldModPeriodicHealingDonePct,              // field_mod_periodic_healing_done_pct
        ModResiliencePct,                            // mod_resilience_pct
        OverrideApBySpellPowerPct,                   // override_ap_by_spell_power_pct
        FieldArenaTeamInfoUnk,                       // field_arena_team_info.unk[]
        SummonedBattlePetGuid,                       // summoned_battle_pet_guid
        OverrideSpellId,                             // override_spell_id
        LfgBonusFactionId,                           // lfg_bonus_faction_id
        LootSpecId,                                  // loot_spec_id
        OverrideZonePvpType,                         // override_zone_pvp_type
        ItemLevelDelta,                              // item_level_delta
        Count
    };

    enum class ItemField : uint16_t
    {
        OwnerGuid,                                   // owner_guid
        OwnerGuidLow,                                // owner_guid.parts.low
        OwnerGuidHigh,                               // owner_guid.parts.high
        ContainerGuid,                               // container_guid
        ContainerGuidLow,                            // container_guid.parts.low
        ContainerGuidHigh,                           // container_guid.parts.high
        CreatorGuid,                                 // creator_guid
        CreatorGuidLow,                              // creator_guid.parts.low
        CreatorGuidHigh,                             // creator_guid.parts.high
        GiftCreatorGuid,                             // gift_creator_guid
        GiftCreatorGuidLow,                          // gift_creator_guid.parts.low
        GiftCreatorGuidHigh,                         // gift_creator_guid.parts.high
        StackCount,                                  // stack_count
        Duration,                                    // duration
        SpellCharges,                                // spell_charges[]
        Flags,                                       // flags
        Enchantment,                                 // enchantment[]
        EnchantmentId,                               // enchantment.id[]
        EnchantmentDuration,                         // enchantment.duration[]
        EnchantmentCharges,                          // enchantment.charges[]
        PropertySeed,                                // property_seed
        RandomPropertiesId,                          // random_properties_id
        ItemTextId,                                  // item_text_id
        Durability,                                  // durability
        MaxDurability,                               // max_durability
        CreatePlayedTime,                            // create_played_time
        ItemPadding0,                                // item_padding_0
        ModifierMask,                                // modifier_mask
        Count
    };

    enum class ContainerField : uint16_t
    {
        SlotCount,                                   // slot_count
        PaddingContainer,                            // padding_container
        ItemSlot,                                    // item_slot[]
        ItemSlotLow,                                 // item_slot.parts.low[]
        ItemSlotHigh,                                // item_slot.parts.high[]
        ContainerPadding0,                           // container_padding_0
        Count
    };

    enum class GameObjectField : uint16_t
    {
        ObjectFieldCreatedBy,                        // object_field_created_by
        ObjectFieldCreatedByLow,                     // object_field_created_by.parts.low
        ObjectFieldCreatedByHigh,                    // object_field_created_by.parts.high
        DisplayId,                                   // display_id
        Flags,                                       // flags
        Rotation,                                    // rotation[]
        State,                                       // state
        X,                                           // x
        Y,                                           // y
        Z,                                           // z
        O,                                           // o
        Dynamic,                                     // dynamic
        FactionTemplate,                             // faction_template
        Type,                                        // type
        Level,                                       // level
        ArtKit,                                      // art_kit
        AnimationProgress,                           // animation_progress
        GameobjectPadding,                           // gameobject_padding
        DynamicDynFlag,                              // dynamic.dynamic_field_parts.dyn_flag
        DynamicPathProgress,                         // dynamic.dynamic_field_parts.path_progress
        Bytes1,                                      // bytes_1
        Bytes1State,                                 // bytes_1.bytes_1_gameobject.state
        Bytes1Type,                                  // bytes_1.bytes_1_gameobject.type
        Bytes1ArtKit,                                // bytes_1.bytes_1_gameobject.art_kit
        Bytes1AnimationProgress,                     // bytes_1.bytes_1_gameobject.animation_progress
        Bytes1Unk,                                   // bytes_1.bytes_1_gameobject.unk
        Bytes1Health,                                // bytes_1.bytes_1_gameobject.health
        Bytes2,                                      // bytes_2
        Bytes2Transparency,                          // bytes_2.bytes_2_gameobject.transparency
        Bytes2ArtKit,                                // bytes_2.bytes_2_gameobject.art_kit
        Bytes2Unk2,                                  // bytes_2.bytes_2_gameobject.unk2
        Bytes2AnimationProgress,                     // bytes_2.bytes_2_gameobject.animation_progress
        Count
    };

    enum class DynamicObjectField : uint16_t
    {
        CasterGuid,                                  // caster_guid
        DynamicobjectBytes,                          // dynamicobject_bytes
        DynamicobjectBytesType,                      // dynamicobject_bytes.s.type
        DynamicobjectBytesUnk1,                      // dynamicobject_bytes.s.unk1
        DynamicobjectBytesUnk2,                      // dynamicobject_bytes.s.unk2
        DynamicobjectBytesUnk3,                      // dynamicobject_bytes.s.unk3
        SpellId,                                     // spell_id
        Radius,                                      // radius
        X,                                           // x
        Y,                                           // y
        Z,                                           // z
        O,                                           // o
        Padding,                                     // padding
        CastTime,                                    // cast_time
        DynamicobjectBytesRaw,                       // dynamicobject_bytes.raw
        Count
    };

    enum class CorpseField : uint16_t
    {
        OwnerGuid,                                   // owner_guid
        PartyGuid,                                   // party_guid
        O,                                           // o
        X,                                           // x
        Y,                                           // y
        Z,                                           // z
        DisplayId,                                   // display_id
        Item,                                        // item[]
        CorpseBytes1,                                // corpse_bytes_1
        CorpseBytes1Unk1,                            // corpse_bytes_1.s.unk1
        CorpseBytes1Race,                            // corpse_bytes_1.s.race
        CorpseBytes1Gender,                          // corpse_bytes_1.s.gender
        CorpseBytes1SkinColor,                       // corpse_bytes_1.s.skin_color
        CorpseBytes2,                                // corpse_bytes_2
        CorpseBytes2Face,                            // corpse_bytes_2.s.face
        CorpseBytes2HairStyle,                       // corpse_bytes_2.s.hair_style
        CorpseBytes2HairColor,                       // corpse_bytes_2.s.hair_color
        CorpseBytes2FacialHair,                      // corpse_bytes_2.s.facial_hair
        Guild,                                       // guild
        CorpseFlags,                                 // corpse_flags
        DynamicFlags,                                // dynamic_flags
        CorpsePadding,                               // corpse_padding
        Count
    };

    enum class AreaTriggerField : uint16_t
    {
        SpellId,                                     // spell_id
        SpellVisualId,                               // spell_visual_id
        Duration,                                    // duration
        PosX,                                        // pos_x
        PosY,                                        // pos_y
        PosZ,                                        // pos_z
        CasterGuid,                                  // caster_guid
        CasterGuidLow,                               // caster_guid.parts.low
        CasterGuidHigh,                              // caster_guid.parts.high
        Scale,                                       // scale
        Count
    };
}
