/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

// Generated by the version table generator - do not edit by hand, regenerate instead.

#pragma once

#include <cstdint>

// Version neutral field ids for the WoW data structs. Every id that exists in any client
// version is listed, the per version layout tables decide which ones are present. Each
// enum covers the own fields of its struct, the base struct fields have their own enum.
namespace Version
{
    enum class ObjectField : uint16_t
    {
        Guid,                                    // guid
        Type,                                    // type
        Entry,                                   // entry
        ScaleX,                                  // scale_x
        PaddingObject,                           // padding_object
        Data,                                    // data
        FieldType,                               // field_type
        DynamicField,                            // dynamic_field
        Count
    };

    enum class UnitField : uint16_t
    {
        CharmGuid,                               // charm_guid
        SummonGuid,                              // summon_guid
        CharmedByGuid,                           // charmed_by_guid
        SummonedByGuid,                          // summoned_by_guid
        CreatedByGuid,                           // created_by_guid
        TargetGuid,                              // target_guid
        PersuadedGuid,                           // persuaded_guid
        ChannelObjectGuid,                       // channel_object_guid
        Health,                                  // health
        Power1,                                  // power_1
        Power2,                                  // power_2
        Power3,                                  // power_3
        Power4,                                  // power_4
        Power5,                                  // power_5
        MaxHealth,                               // max_health
        MaxPower1,                               // max_power_1
        MaxPower2,                               // max_power_2
        MaxPower3,                               // max_power_3
        MaxPower4,                               // max_power_4
        MaxPower5,                               // max_power_5
        Level,                                   // level
        FactionTemplate,                         // faction_template
        FieldBytes0,                             // field_bytes_0
        VirtualItemSlotDisplay,                  // virtual_item_slot_display
        VirtualItemInfo,                         // virtual_item_info
        UnitFlags,                               // unit_flags
        Aura,                                    // aura
        AuraFlags,                               // aura_flags
        AuraLevels,                              // aura_levels
        AuraApplications,                        // aura_applications
        AuraState,                               // aura_state
        BaseAttackTime,                          // base_attack_time
        BoundingRadius,                          // bounding_radius
        CombatReach,                             // combat_reach
        DisplayId,                               // display_id
        NativeDisplayId,                         // native_display_id
        MountDisplayId,                          // mount_display_id
        MinimumDamage,                           // minimum_damage
        MaximumDamage,                           // maximum_damage
        MinimumOffhandDamage,                    // minimum_offhand_damage
        MaximumOffhandDamage,                    // maximum_offhand_damage
        FieldBytes1,                             // field_bytes_1
        PetNumber,                               // pet_number
        PetNameTimestamp,                        // pet_name_timestamp
        PetExperience,                           // pet_experience
        PetNextLevelExperience,                  // pet_next_level_experience
        DynamicFlags,                            // dynamic_flags
        ChannelSpell,                            // channel_spell
        ModCastSpeed,                            // mod_cast_speed
        CreatedBySpellId,                        // created_by_spell_id
        NpcFlags,                                // npc_flags
        NpcEmoteState,                           // npc_emote_state
        TrainingPoints,                          // training_points
        Stat,                                    // stat
        Resistance,                              // resistance
        BaseMana,                                // base_mana
        BaseHealth,                              // base_health
        FieldBytes2,                             // field_bytes_2
        AttackPower,                             // attack_power
        AttackPowerMods,                         // attack_power_mods
        AttackPowerMultiplier,                   // attack_power_multiplier
        RangedAttackPower,                       // ranged_attack_power
        RangedAttackPowerMods,                   // ranged_attack_power_mods
        RangedAttackPowerMultiplier,             // ranged_attack_power_multiplier
        MinimumRangedDamage,                     // minimum_ranged_damage
        MaximumRangedDamage,                     // maximum_ranged_ddamage
        PowerCostModifier,                       // power_cost_modifier
        PowerCostMultiplier,                     // power_cost_multiplier
        UnitPadding,                             // unit_padding
        UnitFlags2,                              // unit_flags_2
        PositiveStat,                            // positive_stat
        NegativeStat,                            // negative_stat
        ResistanceBuffModPositive,               // resistance_buff_mod_positive
        ResistanceBuffModNegative,               // resistance_buff_mod_negative
        MaxHealthModifier,                       // max_health_modifier
        CritterGuid,                             // critter_guid
        Power6,                                  // power_6
        Power7,                                  // power_7
        MaxPower6,                               // max_power_6
        MaxPower7,                               // max_power_7
        PowerRegenFlatModifier,                  // power_regen_flat_modifier
        PowerRegenInterruptedFlatModifier,       // power_regen_interrupted_flat_modifier
        HoverHeight,                             // hover_height
        ModCastHaste,                            // mod_cast_haste
        AttackPowerModPos,                       // attack_power_mod_pos
        AttackPowerModNeg,                       // attack_power_mod_neg
        RangedAttackPowerModsPos,                // ranged_attack_power_mods_pos
        RangedAttackPowerModsNeg,                // ranged_attack_power_mods_neg
        MaxItemLevel,                            // max_item_level
        DemonCreatorGuid,                        // demon_creator_guid
        BattlePetCompanionGuid,                  // battle_pet_companion_guid
        SummonedByHomeRealm,                     // summoned_by_home_realm
        DisplayPower,                            // display_power
        OverrideDisplayPowerId,                  // override_display_power_id
        EffectiveLevel,                          // effective_level
        ModHaste,                                // mod_haste
        ModRangedHaste,                          // mod_ranged_haste
        ModHasteRegen,                           // mod_haste_regen
        MinItemLevel,                            // min_item_level
        WildBattlePetLevel,                      // wild_battle_pet_level
        BattlePetCompanionNameTimestamp,         // battle_pet_companion_name_timestamp
        InteractSpellId,                         // interact_spell_id
        Count
    };

    enum class PlayerField : uint16_t
    {
        DuelArbiter,                             // duel_arbiter
        PlayerFlags,                             // player_flags
        GuildId,                                 // guild_id
        GuildRank,                               // guild_rank
        PlayerBytes,                             // player_bytes
        PlayerBytes2,                            // player_bytes_2
        PlayerBytes3,                            // player_bytes_3
        DuelTeam,                                // duel_team
        GuildTimestamp,                          // guild_timestamp
        Quests,                                  // quests
        VisibleItems,                            // visible_items
        InventorySlot,                           // inventory_slot
        PackSlot,                                // pack_slot
        BankSlot,                                // bank_slot
        BankBagSlot,                             // bank_bag_slot
        VendorBuyBackSlot,                       // vendor_buy_back_slot
        KeyRingSlot,                             // key_ring_slot
        FarsightGuid,                            // farsight_guid
        FieldComboTarget,                        // field_combo_target
        Xp,                                      // xp
        NextLevelXp,                             // next_level_xp
        SkillInfo,                               // skill_info
        CharacterPoints1,                        // character_points_1
        CharacterPoints2,                        // character_points_2
        TrackCreatures,                          // track_creatures
        TrackResources,                          // track_resources
        BlockPct,                                // block_pct
        DodgePct,                                // dodge_pct
        ParryPct,                                // parry_pct
        CritPct,                                 // crit_pct
        RangedCritPct,                           // ranged_crit_pct
        ExploredZones,                           // explored_zones
        RestStateXp,                             // rest_state_xp
        FieldCoinage,                            // field_coinage
        PosStat,                                 // pos_stat
        NegStat,                                 // neg_stat
        ResistanceBuffModPositive,               // resistance_buff_mod_positive
        ResistanceBuffModNegative,               // resistance_buff_mod_negative
        FieldModDamageDonePositive,              // field_mod_damage_done_positive
        FieldModDamageDoneNegative,              // field_mod_damage_done_negative
        FieldModDamageDonePct,                   // field_mod_damage_done_pct
        PlayerFieldBytes,                        // player_field_bytes
        AmmoId,                                  // ammo_id
        SelfResurrectionSpell,                   // self_resurrection_spell
        FieldPvpMedals,                          // field_pvp_medals
        FieldBuyBackPrice,                       // field_buy_back_price
        FieldBuyBackTimestamp,                   // field_buy_back_timestamp
        FieldSessionKills,                       // field_session_kills
        FieldYesterdayKills,                     // field_yesterday_kills
        FieldLastWeekKills,                      // field_last_week_kills
        FieldThisWeekKills,                      // field_this_week_kills
        FieldThisWeekContribution,               // field_this_week_contribution
        FieldLifetimeHonorableKills,             // field_lifetime_honorable_kills
        FieldLifetimeDishonorableKills,          // field_lifetime_dishonorable_kills
        FieldYersterdayContribution,             // field_yersterday_contribution
        FieldLastWeekContribution,               // field_last_week_contribution
        FieldLastWeekRank,                       // field_last_week_rank
        PlayerFieldBytes2,                       // player_field_bytes_2
        FieldWatchedFactionIdx,                  // field_watched_faction_idx
        FieldCombatRating,                       // field_combat_rating
        ChosenTitle,                             // chosen_title
        PlayerPadding0,                          // player_padding_0
        VanityPetSlot,                           // vanity_pet_slot
        FieldKnownTitles,                        // field_known_titles
        Expertise,                               // expertise
        OffhandExpertise,                        // offhand_expertise
        OffhandCritPct,                          // offhand_crit_pct
        SpellCritPct,                            // spell_crit_pct
        ShieldBlock,                             // shield_block
        FieldModHealingDone,                     // field_mod_healing_done
        FieldModTargetResistance,                // field_mod_target_resistance
        FieldModTargetPhysicalResistance,        // field_mod_target_physical_resistance
        FieldKills,                              // field_kills
        FieldContributionToday,                  // field_contribution_today
        FieldContributionYesterday,              // field_contribution_yesterday
        FieldArenaTeamInfo,                      // field_arena_team_info
        FieldHonorCurrency,                      // field_honor_currency
        FieldArenaCurrency,                      // field_arena_currency
        FieldModManaRegen,                       // field_mod_mana_regen
        FieldModManaRegenInterrupt,              // field_mod_mana_regen_interrupt
        FieldMaxLevel,                           // field_max_level
        FieldDailyQuests,                        // field_daily_quests
        Inebriation,                             // inebriation
        CurrencytokenSlot,                       // currencytoken_slot
        FieldKnownCurrencies,                    // field_known_currencies
        ShieldBlockCritPct,                      // shield_block_crit_pct
        FieldModHealingPct,                      // field_mod_healing_pct
        FieldModHealingDonePct,                  // field_mod_healing_done_pct
        RuneRegen,                               // rune_regen
        NoReagentCost,                           // no_reagent_cost
        FieldGlyphSlots,                         // field_glyph_slots
        FieldGlyphs,                             // field_glyphs
        GlyphsEnabled,                           // glyphs_enabled
        PetSpellPower,                           // pet_spell_power
        GuildDeleteDate,                         // guild_delete_date
        GuildLevel,                              // guild_level
        FieldSkillInfo,                          // field_skill_info
        Mastery,                                 // mastery
        WeaponDmgMultiplier,                     // weapon_dmg_multiplier
        ModSpellPowerPct,                        // mod_spell_power_pct
        OverrideSpellPowerByApPct,               // override_spell_power_by_ap_pct
        BattlegroundRating,                      // battleground_rating
        Researching,                             // researching
        ResearchSite,                            // research_site
        ProfessionSkillLine,                     // profession_skill_line
        UiHitMod,                                // ui_hit_mod
        UiHitSpellMod,                           // ui_hit_spell_mod
        UiHomeRealmTimeOffset,                   // ui_home_realm_time_offset
        ModHaste,                                // mod_haste
        ModRangedHaste,                          // mod_ranged_haste
        ModPetHaste,                             // mod_pet_haste
        ModHasteRegen,                           // mod_haste_regen
        VirtualPlayerRealm,                      // virtual_player_realm
        CurrentSpecId,                           // current_spec_id
        TaxiMountAnimKitId,                      // taxi_mount_anim_kit_id
        CurrentBattlePetBreedQuality,            // current_battle_pet_breed_quality
        MaxTalentTiers,                          // max_talent_tiers
        RangedExpertise,                         // ranged_expertise
        CombatRatingExpertise,                   // combat_rating_expertise
        PvpPowerDamage,                          // pvp_power_damage
        PvpPowerHealing,                         // pvp_power_healing
        FieldModPeriodicHealingDonePct,          // field_mod_periodic_healing_done_pct
        ModResiliencePct,                        // mod_resilience_pct
        OverrideApBySpellPowerPct,               // override_ap_by_spell_power_pct
        SummonedBattlePetGuid,                   // summoned_battle_pet_guid
        OverrideSpellId,                         // override_spell_id
        LfgBonusFactionId,                       // lfg_bonus_faction_id
        LootSpecId,                              // loot_spec_id
        OverrideZonePvpType,                     // override_zone_pvp_type
        ItemLevelDelta,                          // item_level_delta
        Count
    };

    enum class ItemField : uint16_t
    {
        OwnerGuid,                               // owner_guid
        ContainerGuid,                           // container_guid
        CreatorGuid,                             // creator_guid
        GiftCreatorGuid,                         // gift_creator_guid
        StackCount,                              // stack_count
        Duration,                                // duration
        SpellCharges,                            // spell_charges
        Flags,                                   // flags
        Enchantment,                             // enchantment
        PropertySeed,                            // property_seed
        RandomPropertiesId,                      // random_properties_id
        ItemTextId,                              // item_text_id
        Durability,                              // durability
        MaxDurability,                           // max_durability
        CreatePlayedTime,                        // create_played_time
        ItemPadding0,                            // item_padding_0
        ModifierMask,                            // modifier_mask
        Count
    };

    enum class ContainerField : uint16_t
    {
        SlotCount,                               // slot_count
        PaddingContainer,                        // padding_container
        ItemSlot,                                // item_slot
        ContainerPadding0,                       // container_padding_0
        Count
    };

    enum class GameObjectField : uint16_t
    {
        ObjectFieldCreatedBy,                    // object_field_created_by
        DisplayId,                               // display_id
        Flags,                                   // flags
        Rotation,                                // rotation
        State,                                   // state
        X,                                       // x
        Y,                                       // y
        Z,                                       // z
        O,                                       // o
        Dynamic,                                 // dynamic
        FactionTemplate,                         // faction_template
        Type,                                    // type
        Level,                                   // level
        ArtKit,                                  // art_kit
        AnimationProgress,                       // animation_progress
        GameobjectPadding,                       // gameobject_padding
        Bytes1,                                  // bytes_1
        Bytes2,                                  // bytes_2
        Count
    };

    enum class DynamicObjectField : uint16_t
    {
        CasterGuid,                              // caster_guid
        DynamicobjectBytes,                      // dynamicobject_bytes
        SpellId,                                 // spell_id
        Radius,                                  // radius
        X,                                       // x
        Y,                                       // y
        Z,                                       // z
        O,                                       // o
        Padding,                                 // padding
        CastTime,                                // cast_time
        Count
    };

    enum class CorpseField : uint16_t
    {
        OwnerGuid,                               // owner_guid
        PartyGuid,                               // party_guid
        O,                                       // o
        X,                                       // x
        Y,                                       // y
        Z,                                       // z
        DisplayId,                               // display_id
        Item,                                    // item
        CorpseBytes1,                            // corpse_bytes_1
        CorpseBytes2,                            // corpse_bytes_2
        Guild,                                   // guild
        CorpseFlags,                             // corpse_flags
        DynamicFlags,                            // dynamic_flags
        CorpsePadding,                           // corpse_padding
        Count
    };

    enum class AreaTriggerField : uint16_t
    {
        SpellId,                                 // spell_id
        SpellVisualId,                           // spell_visual_id
        Duration,                                // duration
        PosX,                                    // pos_x
        PosY,                                    // pos_y
        PosZ,                                    // pos_z
        CasterGuid,                              // caster_guid
        Scale,                                   // scale
        Count
    };
}
