#pragma once

#include "MovementElements.hpp"
#include "Server/Opcodes.hpp"
#include <array>
#include <span>

namespace MoPMovement
{
    constexpr std::array<MovementElement, 71> templatePlayerMove = {
        MovementElement::HasPitch,
        MovementElement::HasGuidByte2,
        MovementElement::ZeroBit,
        MovementElement::ZeroBit,
        MovementElement::HasGuidByte0,
        MovementElement::HasOrientation,
        MovementElement::HasFallData,
        MovementElement::HasCounter,
        MovementElement::HasGuidByte3,
        MovementElement::HasFallDirection,
        MovementElement::HasTransportData,
        MovementElement::HasGuidByte4,
        MovementElement::HasTransportGuidByte5,
        MovementElement::HasTransportGuidByte4,
        MovementElement::HasTransportGuidByte7,
        MovementElement::HasTransportGuidByte2,
        MovementElement::HasTransportGuidByte6,
        MovementElement::HasTransportTime2,
        MovementElement::HasTransportGuidByte3,
        MovementElement::HasTransportGuidByte1,
        MovementElement::HasTransportTime3,
        MovementElement::HasTransportGuidByte0,
        MovementElement::HasSplineElevation,
        MovementElement::HasMovementFlags,
        MovementElement::ZeroBit,
        MovementElement::MovementFlags,
        MovementElement::HasMovementFlags2,
        MovementElement::HasGuidByte7,
        MovementElement::HasGuidByte1,
        MovementElement::HasTimestamp,
        MovementElement::MovementFlags2,
        MovementElement::HasGuidByte5,
        MovementElement::ForcesCount,
        MovementElement::HasGuidByte6,
        MovementElement::PositionY,
        MovementElement::TransportGuidByte7,
        MovementElement::TransportTime2,
        MovementElement::TransportPositionX,
        MovementElement::TransportGuidByte5,
        MovementElement::TransportSeat,
        MovementElement::TransportGuidByte2,
        MovementElement::TransportGuidByte0,
        MovementElement::TransportGuidByte3,
        MovementElement::TransportTime,
        MovementElement::TransportGuidByte4,
        MovementElement::TransportPositionZ,
        MovementElement::TransportGuidByte1,
        MovementElement::TransportPositionY,
        MovementElement::TransportOrientation,
        MovementElement::TransportGuidByte6,
        MovementElement::TransportTime3,
        MovementElement::GuidByte5,
        MovementElement::GuidByte1,
        MovementElement::PositionZ,
        MovementElement::Timestamp,
        MovementElement::Orientation,
        MovementElement::GuidByte3,
        MovementElement::FallSinAngle,
        MovementElement::FallHorizontalSpeed,
        MovementElement::FallCosAngle,
        MovementElement::FallVerticalSpeed,
        MovementElement::FallTime,
        MovementElement::GuidByte0,
        MovementElement::Pitch,
        MovementElement::GuidByte2,
        MovementElement::GuidByte6,
        MovementElement::SplineElevation,
        MovementElement::Counter,
        MovementElement::PositionX,
        MovementElement::GuidByte4,
        MovementElement::GuidByte7
    };

    constexpr std::array<MovementElement, 71> templateHeartbeat = {
        MovementElement::PositionZ,
        MovementElement::PositionX,
        MovementElement::PositionY,
        MovementElement::ForcesCount,
        MovementElement::HasMovementFlags,
        MovementElement::ZeroBit,
        MovementElement::ZeroBit,
        MovementElement::HasGuidByte3,
        MovementElement::HasGuidByte6,
        MovementElement::HasPitch,
        MovementElement::ZeroBit,
        MovementElement::ZeroBit,
        MovementElement::HasGuidByte7,
        MovementElement::HasGuidByte2,
        MovementElement::HasGuidByte4,
        MovementElement::HasMovementFlags2,
        MovementElement::HasOrientation,
        MovementElement::HasTimestamp,
        MovementElement::HasTransportData,
        MovementElement::HasFallData,
        MovementElement::HasGuidByte5,
        MovementElement::HasSplineElevation,
        MovementElement::HasGuidByte1,
        MovementElement::HasGuidByte0,

        // Transport presence bits
        MovementElement::HasTransportGuidByte5,
        MovementElement::HasTransportGuidByte3,
        MovementElement::HasTransportGuidByte6,
        MovementElement::HasTransportGuidByte0,
        MovementElement::HasTransportGuidByte7,
        MovementElement::HasTransportTime3,
        MovementElement::HasTransportGuidByte1,
        MovementElement::HasTransportGuidByte2,
        MovementElement::HasTransportGuidByte4,
        MovementElement::HasTransportTime2,

        // Value blocks dependent on bits
        MovementElement::MovementFlags,
        MovementElement::HasFallDirection,
        MovementElement::MovementFlags2,

        // Guid bytes (Part 1)
        MovementElement::GuidByte2,
        MovementElement::GuidByte3,
        MovementElement::GuidByte6,
        MovementElement::GuidByte1,
        MovementElement::GuidByte4,
        MovementElement::GuidByte7,

        // Forces
        MovementElement::Forces,

        // Guid bytes (Part 2)
        MovementElement::GuidByte5,
        MovementElement::GuidByte0,

        // Fall data values
        MovementElement::FallSinAngle,
        MovementElement::FallCosAngle,
        MovementElement::FallHorizontalSpeed,
        MovementElement::FallVerticalSpeed, // Corresponds to jump_info.velocity
        MovementElement::FallTime,

        // Transport data values
        MovementElement::TransportGuidByte1,
        MovementElement::TransportGuidByte3,
        MovementElement::TransportGuidByte2,
        MovementElement::TransportGuidByte0,
        MovementElement::TransportTime3,
        MovementElement::TransportSeat,
        MovementElement::TransportGuidByte7,
        MovementElement::TransportPositionX,
        MovementElement::TransportGuidByte4,
        MovementElement::TransportTime2,
        MovementElement::TransportPositionY,
        MovementElement::TransportGuidByte6,
        MovementElement::TransportGuidByte5,
        MovementElement::TransportPositionZ,
        MovementElement::TransportTime,
        MovementElement::TransportOrientation,

        // Trailing floats/ints
        MovementElement::Orientation,
        MovementElement::Pitch,
        MovementElement::Timestamp,
        MovementElement::SplineElevation
    };

    constexpr std::array<MovementElement, 72> templateStartForward = {
        MovementElement::PositionZ,
        MovementElement::PositionX,
        MovementElement::PositionY,
        MovementElement::HasMovementFlags2,
        MovementElement::ZeroBit,
        MovementElement::HasCounter,
        MovementElement::ZeroBit,
        MovementElement::HasGuidByte0,
        MovementElement::HasOrientation,
        MovementElement::HasFallData,
        MovementElement::ForcesCount,
        MovementElement::HasGuidByte4,
        MovementElement::HasGuidByte1,
        MovementElement::HasTimestamp,
        MovementElement::HasGuidByte7,
        MovementElement::HasPitch,
        MovementElement::HasTransportData,
        MovementElement::HasGuidByte5,
        MovementElement::HasMovementFlags,
        MovementElement::HasGuidByte3,
        MovementElement::HasSplineElevation,
        MovementElement::HasGuidByte2,
        MovementElement::HasGuidByte6,
        MovementElement::ZeroBit,
        MovementElement::HasTransportGuidByte1,
        MovementElement::HasTransportTime3,
        MovementElement::HasTransportGuidByte3,
        MovementElement::HasTransportGuidByte4,
        MovementElement::HasTransportGuidByte2,
        MovementElement::HasTransportGuidByte5,
        MovementElement::HasTransportGuidByte0,
        MovementElement::HasTransportGuidByte7,
        MovementElement::HasTransportGuidByte6,
        MovementElement::HasTransportTime2,
        MovementElement::HasFallDirection,
        MovementElement::MovementFlags2,
        MovementElement::MovementFlags,
        MovementElement::GuidByte1,
        MovementElement::GuidByte6,
        MovementElement::GuidByte7,
        MovementElement::Forces,
        MovementElement::GuidByte5,
        MovementElement::GuidByte0,
        MovementElement::GuidByte3,
        MovementElement::GuidByte2,
        MovementElement::GuidByte4,
        MovementElement::TransportGuidByte3,
        MovementElement::TransportGuidByte1,
        MovementElement::TransportGuidByte6,
        MovementElement::TransportPositionZ,
        MovementElement::TransportGuidByte4,
        MovementElement::TransportTime3,
        MovementElement::TransportSeat,
        MovementElement::TransportGuidByte7,
        MovementElement::TransportOrientation,
        MovementElement::TransportTime2,
        MovementElement::TransportGuidByte5,
        MovementElement::TransportGuidByte2,
        MovementElement::TransportPositionX,
        MovementElement::TransportGuidByte0,
        MovementElement::TransportPositionY,
        MovementElement::TransportTime,
        MovementElement::FallCosAngle,
        MovementElement::FallSinAngle,
        MovementElement::FallHorizontalSpeed,
        MovementElement::FallTime,
        MovementElement::FallVerticalSpeed,
        MovementElement::Timestamp,
        MovementElement::Pitch,
        MovementElement::SplineElevation,
        MovementElement::Orientation,
        MovementElement::Counter
    };
    constexpr std::array<MovementElement, 72> templateStartBackward = {
        MovementElement::PositionY,
        MovementElement::PositionZ,
        MovementElement::PositionX,
        MovementElement::HasTimestamp,
        MovementElement::HasOrientation,
        MovementElement::HasGuidByte7,
        MovementElement::HasGuidByte2,
        MovementElement::ForcesCount,
        MovementElement::HasFallData,
        MovementElement::ZeroBit,
        MovementElement::HasGuidByte5,
        MovementElement::HasGuidByte3,
        MovementElement::HasGuidByte6,
        MovementElement::HasSplineElevation,
        MovementElement::HasGuidByte4,
        MovementElement::HasTransportData,
        MovementElement::HasGuidByte0,
        MovementElement::HasMovementFlags,
        MovementElement::HasPitch,
        MovementElement::HasCounter,
        MovementElement::HasMovementFlags2,
        MovementElement::ZeroBit,
        MovementElement::HasGuidByte1,
        MovementElement::ZeroBit,
        MovementElement::HasTransportGuidByte1,
        MovementElement::HasTransportTime2,
        MovementElement::HasTransportGuidByte0,
        MovementElement::HasTransportGuidByte7,
        MovementElement::HasTransportTime3,
        MovementElement::HasTransportGuidByte3,
        MovementElement::HasTransportGuidByte5,
        MovementElement::HasTransportGuidByte6,
        MovementElement::HasTransportGuidByte2,
        MovementElement::HasTransportGuidByte4,
        MovementElement::MovementFlags2,
        MovementElement::MovementFlags,
        MovementElement::HasFallDirection,
        MovementElement::Forces,
        MovementElement::GuidByte1,
        MovementElement::GuidByte3,
        MovementElement::GuidByte5,
        MovementElement::GuidByte2,
        MovementElement::GuidByte0,
        MovementElement::GuidByte4,
        MovementElement::GuidByte7,
        MovementElement::GuidByte6,
        MovementElement::Counter,
        MovementElement::TransportTime,
        MovementElement::TransportGuidByte4,
        MovementElement::TransportGuidByte1,
        MovementElement::TransportGuidByte5,
        MovementElement::TransportGuidByte3,
        MovementElement::TransportGuidByte6,
        MovementElement::TransportSeat,
        MovementElement::TransportOrientation,
        MovementElement::TransportPositionX,
        MovementElement::TransportGuidByte0,
        MovementElement::TransportPositionY,
        MovementElement::TransportTime3,
        MovementElement::TransportGuidByte7,
        MovementElement::TransportTime2,
        MovementElement::TransportPositionZ,
        MovementElement::TransportGuidByte2,
        MovementElement::Orientation,
        MovementElement::FallTime,
        MovementElement::FallSinAngle,
        MovementElement::FallCosAngle,
        MovementElement::FallHorizontalSpeed,
        MovementElement::FallVerticalSpeed,
        MovementElement::Pitch,
        MovementElement::Timestamp,
        MovementElement::SplineElevation
    };

    constexpr std::array<MovementElement, 72> templateStop = {
        MovementElement::PositionX,
        MovementElement::PositionY,
        MovementElement::PositionZ,
        MovementElement::HasGuidByte5,
        MovementElement::HasGuidByte2,
        MovementElement::HasFallData,
        MovementElement::HasGuidByte0,
        MovementElement::ZeroBit,
        MovementElement::ZeroBit,
        MovementElement::HasCounter,
        MovementElement::HasGuidByte1,
        MovementElement::ForcesCount,
        MovementElement::HasPitch,
        MovementElement::HasGuidByte3,
        MovementElement::HasGuidByte4,
        MovementElement::HasTransportData,
        MovementElement::ZeroBit,
        MovementElement::HasGuidByte6,
        MovementElement::HasMovementFlags,
        MovementElement::HasTimestamp,
        MovementElement::HasMovementFlags2,
        MovementElement::HasOrientation,
        MovementElement::HasSplineElevation,
        MovementElement::HasGuidByte7,
        MovementElement::HasTransportTime2,
        MovementElement::HasTransportGuidByte7,
        MovementElement::HasTransportGuidByte4,
        MovementElement::HasTransportGuidByte1,
        MovementElement::HasTransportGuidByte0,
        MovementElement::HasTransportGuidByte5,
        MovementElement::HasTransportGuidByte2,
        MovementElement::HasTransportGuidByte3,
        MovementElement::HasTransportTime3,
        MovementElement::HasTransportGuidByte6,
        MovementElement::HasFallDirection,
        MovementElement::MovementFlags2,
        MovementElement::MovementFlags,
        MovementElement::GuidByte0,
        MovementElement::GuidByte3,
        MovementElement::Forces,
        MovementElement::GuidByte6,
        MovementElement::GuidByte1,
        MovementElement::GuidByte4,
        MovementElement::GuidByte2,
        MovementElement::GuidByte5,
        MovementElement::GuidByte7,
        MovementElement::Orientation,
        MovementElement::FallVerticalSpeed,
        MovementElement::FallHorizontalSpeed,
        MovementElement::FallSinAngle,
        MovementElement::FallCosAngle,
        MovementElement::FallTime,
        MovementElement::SplineElevation,
        MovementElement::TransportPositionX,
        MovementElement::TransportTime,
        MovementElement::TransportGuidByte3,
        MovementElement::TransportOrientation,
        MovementElement::TransportPositionY,
        MovementElement::TransportGuidByte2,
        MovementElement::TransportGuidByte6,
        MovementElement::TransportGuidByte7,
        MovementElement::TransportGuidByte1,
        MovementElement::TransportGuidByte4,
        MovementElement::TransportTime3,
        MovementElement::TransportGuidByte0,
        MovementElement::TransportSeat,
        MovementElement::TransportPositionZ,
        MovementElement::TransportGuidByte5,
        MovementElement::TransportTime2,
        MovementElement::Counter,
        MovementElement::Pitch,
        MovementElement::Timestamp
    };

    constexpr std::array<MovementElement, 72> templateJump = {
        MovementElement::PositionY,
        MovementElement::PositionX,
        MovementElement::PositionZ,
        MovementElement::HasGuidByte1,
        MovementElement::HasGuidByte7,
        MovementElement::HasMovementFlags2,
        MovementElement::HasGuidByte5,
        MovementElement::HasSplineElevation,
        MovementElement::HasOrientation,
        MovementElement::HasGuidByte6,
        MovementElement::HasGuidByte4,
        MovementElement::ZeroBit,
        MovementElement::HasTransportData,
        MovementElement::ZeroBit,
        MovementElement::ForcesCount,
        MovementElement::HasPitch,
        MovementElement::HasMovementFlags,
        MovementElement::HasTimestamp,
        MovementElement::HasCounter,
        MovementElement::HasGuidByte3,
        MovementElement::ZeroBit,
        MovementElement::HasFallData,
        MovementElement::HasGuidByte2,
        MovementElement::HasGuidByte0,
        MovementElement::HasTransportGuidByte2,
        MovementElement::HasTransportGuidByte3,
        MovementElement::HasTransportGuidByte1,
        MovementElement::HasTransportGuidByte4,
        MovementElement::HasTransportTime2,
        MovementElement::HasTransportGuidByte5,
        MovementElement::HasTransportGuidByte6,
        MovementElement::HasTransportGuidByte0,
        MovementElement::HasTransportGuidByte7,
        MovementElement::HasTransportTime3,
        MovementElement::MovementFlags,
        MovementElement::MovementFlags2,
        MovementElement::HasFallDirection,
        MovementElement::GuidByte7,
        MovementElement::GuidByte1,
        MovementElement::GuidByte0,
        MovementElement::Forces,
        MovementElement::GuidByte2,
        MovementElement::GuidByte6,
        MovementElement::GuidByte3,
        MovementElement::GuidByte4,
        MovementElement::GuidByte5,
        MovementElement::FallVerticalSpeed,
        MovementElement::FallSinAngle,
        MovementElement::FallCosAngle,
        MovementElement::FallHorizontalSpeed,
        MovementElement::FallTime,
        MovementElement::TransportGuidByte5,
        MovementElement::TransportGuidByte7,
        MovementElement::TransportSeat,
        MovementElement::TransportGuidByte4,
        MovementElement::TransportGuidByte0,
        MovementElement::TransportPositionZ,
        MovementElement::TransportGuidByte6,
        MovementElement::TransportGuidByte2,
        MovementElement::TransportPositionY,
        MovementElement::TransportTime,
        MovementElement::TransportPositionX,
        MovementElement::TransportTime2,
        MovementElement::TransportGuidByte1,
        MovementElement::TransportGuidByte3,
        MovementElement::TransportTime3,
        MovementElement::TransportOrientation,
        MovementElement::SplineElevation,
        MovementElement::Orientation,
        MovementElement::Pitch,
        MovementElement::Counter,
        MovementElement::Timestamp
    };

    // Template for MSG_MOVE_FALL_LAND (72 elements)
    constexpr std::array<MovementElement, 72> templateFallLand = {
        MovementElement::PositionY,
        MovementElement::PositionZ,
        MovementElement::PositionX,
        MovementElement::HasFallData,
        MovementElement::ZeroBit,
        MovementElement::ZeroBit,
        MovementElement::HasTimestamp,
        MovementElement::HasGuidByte7,
        MovementElement::ZeroBit,
        MovementElement::HasSplineElevation,
        MovementElement::HasGuidByte5,
        MovementElement::HasPitch,
        MovementElement::HasMovementFlags2,
        MovementElement::HasGuidByte2,
        MovementElement::HasGuidByte3,
        MovementElement::HasGuidByte0,
        MovementElement::HasOrientation,
        MovementElement::ForcesCount,
        MovementElement::HasMovementFlags,
        MovementElement::HasCounter,
        MovementElement::HasGuidByte1,
        MovementElement::HasTransportData,
        MovementElement::HasGuidByte6,
        MovementElement::HasGuidByte4,
        MovementElement::HasTransportGuidByte0,
        MovementElement::HasTransportTime2,
        MovementElement::HasTransportGuidByte3,
        MovementElement::HasTransportGuidByte5,
        MovementElement::HasTransportGuidByte1,
        MovementElement::HasTransportGuidByte7,
        MovementElement::HasTransportGuidByte4,
        MovementElement::HasTransportGuidByte2,
        MovementElement::HasTransportGuidByte6,
        MovementElement::HasTransportTime3,
        MovementElement::MovementFlags2,
        MovementElement::HasFallDirection,
        MovementElement::MovementFlags,
        MovementElement::GuidByte4,
        MovementElement::GuidByte3,
        MovementElement::GuidByte7,
        MovementElement::GuidByte0,
        MovementElement::GuidByte2,
        MovementElement::GuidByte5,
        MovementElement::GuidByte1,
        MovementElement::GuidByte6,
        MovementElement::Forces,
        MovementElement::FallSinAngle,
        MovementElement::FallHorizontalSpeed,
        MovementElement::FallCosAngle,
        MovementElement::FallTime,
        MovementElement::FallVerticalSpeed,
        MovementElement::TransportGuidByte4,
        MovementElement::TransportPositionY,
        MovementElement::TransportOrientation,
        MovementElement::TransportPositionZ,
        MovementElement::TransportSeat,
        MovementElement::TransportGuidByte3,
        MovementElement::TransportGuidByte6,
        MovementElement::TransportTime2,
        MovementElement::TransportGuidByte2,
        MovementElement::TransportGuidByte1,
        MovementElement::TransportGuidByte5,
        MovementElement::TransportTime3,
        MovementElement::TransportTime,
        MovementElement::TransportPositionX,
        MovementElement::TransportGuidByte7,
        MovementElement::TransportGuidByte0,
        MovementElement::Counter,
        MovementElement::Timestamp,
        MovementElement::SplineElevation,
        MovementElement::Pitch,
        MovementElement::Orientation
    };

    // TODO: Add more templates for other movement opcodes

    inline std::span<const MovementElement> getMovementTemplate(uint32_t internalOpcodeId)
    {
        switch (internalOpcodeId)
        {
        case SMSG_PLAYER_MOVE:
            return templatePlayerMove;
        case MSG_MOVE_HEARTBEAT:
            return templateHeartbeat;
        case MSG_MOVE_START_FORWARD:
            return templateStartForward;
        case MSG_MOVE_START_BACKWARD:
            return templateStartBackward;
        case MSG_MOVE_STOP:
            return templateStop;
        case MSG_MOVE_FALL_LAND:
            return templateFallLand;
        case MSG_MOVE_JUMP:
            return templateJump;
            // TODO: Add more cases for other movement opcodes and their corresponding templates

        default:
            return {};
        }
    }
}