#ifndef _INSTANCE_FORGE_OF_SOULS_H
#define _INSTANCE_FORGE_OF_SOULS_H

enum BronjahmData
{
};

enum DevourerOfSoulsData
{
};

enum CreatureIDs
{
	//Bosses
	CN_BRONJAHM = 36497,
	CN_DEVOURER_OF_SOULS = 36502,
	//Alliance Spawns
	CN_JAINA_PROUDMOORE = 37597,
	CN_ARCHMAGE_ELANDRA = 37774,
	CN_ARCHMAGE_KORELN = 37582,
	//Horde Spawns
	CN_SYLVANAS_WINDRUNNER = 37596,
	CN_DARK_RANGER_KALIRA = 37583,
	CN_DARK_RANGER_LORALEN = 37779

};

#endif  // _INSTANCE_FORGE_OF_SOULS_H