#ifndef _INSTANCE_PIT_OF_SARON_H
#define _INSTANCE_PIT_OF_SARON_H

enum ForgemasterGarfrostData
{
};

enum Ick_KrickData
{
};

enum ScourgelordTyrannusData
{
};

enum CreatureIDs
{
	//Bosses
    CN_FORGEMASTER_GARFROST = 36494,
    CN_ICK = 36476,
	CN_KRICK = 36477,
	CN_SCOURGELORD_TYRANNUS = 36658,
	//Alliance Spawns
	CN_JAINA_PROUDMOORE = 36993,
	CN_ARCHMAGE_ELANDRA = 37774,
	CN_ARCHMAGE_KORELN = 37582,
	//Horde Spawns
	CN_SYLVANAS_WINDRUNNER = 36990,
	CN_DARK_RANGER_KALIRA = 37583,
	CN_DARK_RANGER_LORALEN = 37779
};

#endif  // _INSTANCE_PIT_OF_SARON_H