blank_issues_enabled: true
contact_links:
  - name: 📢 Discord
    url: https://discord.com/invite/CBdgrh7
    about: The official AscEmu Discord.
  - name: 🎫 Forum
    url: https://github.com/AscEmu/AscEmu/discussions
    about: The official AscEmu Discussions.
