blank_issues_enabled: true
contact_links:
  - name: 📢 Discord
    url: https://discord.com/invite/CBdgrh7
    about: The official AscEmu Discord.
  - name: 🎫 Forum
    url: http://board.ascemu.org/
    about: The official AscEmu Board.
