/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

#pragma once

// Grim Batol - four bosses, no gating doors between them. Identities and mechanics verified
// against wowhead.

uint32_t const GrimBatolEncounterCount = 4;

enum GrimBatolData
{
    DATA_GENERAL_UMBRISS      = 0,
    DATA_FORGEMASTER_THRONGUS = 1,
    DATA_DRAHGA_SHADOWBURNER  = 2,
    DATA_ERUDAX               = 3
};

enum GrimBatolCreatures
{
    BOSS_GENERAL_UMBRISS      = 39625,
    BOSS_FORGEMASTER_THRONGUS = 40177,
    BOSS_DRAHGA_SHADOWBURNER  = 40319,
    BOSS_ERUDAX               = 40484,

    NPC_TWILIGHT_BEGUILER     = 40167,

    NPC_TROGG_DWELLER         = 39450,
    NPC_TWILIGHT_ENFORCER     = 39956,
    NPC_TWILIGHT_EARTHSHAPER  = 39890,
    NPC_TWILIGHT_ARMSMASTER   = 41073,
    NPC_AZUREBORNE_GUARDIAN   = 39854,
    NPC_TWILIGHT_STORMBREAKER = 39962,
    NPC_CRIMSONBORNE_GUARDIAN = 39381,
    NPC_AZUREBORNE_SEER       = 39855,
    NPC_ENSLAVED_GRONN_BRUTE  = 40166
};

enum TwilightBeguilerSpells
{
    SPELL_BEGUILER_DECEITFUL_BLAST = 76715,
    SPELL_BEGUILER_CHAINED_MIND    = 76711
};

enum GrimBatolTrashSpells
{
    SPELL_TROGG_DWELLER_CLAW_PUNCTURE         = 76507,

    SPELL_TWILIGHT_ENFORCER_MEAT_GRINDER      = 76411,

    SPELL_EARTHSHAPER_EARTH_SPIKE             = 76603,
    SPELL_EARTHSHAPER_STONE_SKIN              = 76596,
    SPELL_EARTHSHAPER_SUMMON_ROCK_ELEMENTAL   = 74552,

    SPELL_ARMSMASTER_MORTAL_STRIKE            = 76727,
    SPELL_ARMSMASTER_FLURRY_OF_BLOWS          = 76729,

    SPELL_AZUREBORNE_GUARDIAN_CURSE           = 76394,
    SPELL_AZUREBORNE_GUARDIAN_ARCANE_INFUSION = 76378,

    SPELL_STORMBREAKER_WATER_BOLT             = 76720,
    SPELL_STORMBREAKER_WATER_SHELL            = 90522,
    SPELL_STORMBREAKER_SUMMON_WATER_SPIRIT    = 74561,

    SPELL_CRIMSONBORNE_GUARDIAN_CHARGE        = 76404,
    SPELL_CRIMSONBORNE_GUARDIAN_SHOCKWAVE     = 76409,

    SPELL_AZUREBORNE_SEER_TWILIGHT_BOLT       = 76369,
    SPELL_AZUREBORNE_SEER_WARPED_TWILIGHT     = 76370,
    SPELL_AZUREBORNE_SEER_TWISTED_ARCANE      = 76340,

    SPELL_ENSLAVED_GRONN_BRUTE_SMASH          = 76703
};

enum UmbrissSpells
{
    SPELL_UMBRISS_BLEEDING_WOUND = 74846,
    SPELL_UMBRISS_BLITZ          = 74670,
    SPELL_UMBRISS_GROUND_SIEGE   = 74634,
    SPELL_UMBRISS_SUMMON_SKARDYN = 74859,
    SPELL_UMBRISS_FRENZY         = 74853
};

enum ThrongusSpells
{
    SPELL_THRONGUS_MIGHTY_STOMP      = 74984,
    SPELL_THRONGUS_DISORIENTING_ROAR = 74976,
    SPELL_THRONGUS_IMPALING_SLAM     = 75056,
    SPELL_THRONGUS_FLAMING_SHIELD    = 90819
};

enum DrahgaSpells
{
    SPELL_DRAHGA_BURNING_SHADOWBOLT   = 75245,
    SPELL_DRAHGA_INVOCATION_OF_FLAME  = 75218,
    SPELL_DRAHGA_DEVOURING_FLAMES_AOE = 90945
};

enum ErudaxSpells
{
    SPELL_ERUDAX_BINDING_SHADOWS           = 79466,
    SPELL_ERUDAX_SHADOW_GALE               = 75664,
    SPELL_ERUDAX_SUMMON_FACELESS_CORRUPTOR = 75704,
    SPELL_ERUDAX_ENFEEBLING_BLOW_10        = 75789,
    SPELL_ERUDAX_ENFEEBLING_BLOW_25        = 91091
};
