/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

// Generated by the version table generator - do not edit by hand, regenerate instead.

#include "Version/ObjectLayout.hpp"

namespace Version::Tables
{
    static const FieldDesc mopObjectFields[] =
    {
        {    0,   8 },  // Guid
        { kNoField, 0 },  // Type - not in this version
        {   20,   4 },  // Entry
        {   28,   4 },  // ScaleX
        { kNoField, 0 },  // PaddingObject - not in this version
        {    8,   8 },  // Data
        {   16,   4 },  // FieldType
        {   24,   4 },  // DynamicField
    };

    static const FieldDesc mopUnitFields[] =
    {
        {   32,   8 },  // CharmGuid
        {   40,   8 },  // SummonGuid
        {   56,   8 },  // CharmedByGuid
        {   64,   8 },  // SummonedByGuid
        {   72,   8 },  // CreatedByGuid
        {   88,   8 },  // TargetGuid
        { kNoField, 0 },  // PersuadedGuid - not in this version
        {  104,   8 },  // ChannelObjectGuid
        {  132,   4 },  // Health
        {  136,   4 },  // Power1
        {  140,   4 },  // Power2
        {  144,   4 },  // Power3
        {  148,   4 },  // Power4
        {  152,   4 },  // Power5
        {  156,   4 },  // MaxHealth
        {  160,   4 },  // MaxPower1
        {  164,   4 },  // MaxPower2
        {  168,   4 },  // MaxPower3
        {  172,   4 },  // MaxPower4
        {  176,   4 },  // MaxPower5
        {  220,   4 },  // Level
        {  228,   4 },  // FactionTemplate
        {  120,   4 },  // FieldBytes0
        {  232,  12 },  // VirtualItemSlotDisplay
        { kNoField, 0 },  // VirtualItemInfo - not in this version
        {  244,   4 },  // UnitFlags
        { kNoField, 0 },  // Aura - not in this version
        { kNoField, 0 },  // AuraFlags - not in this version
        { kNoField, 0 },  // AuraLevels - not in this version
        { kNoField, 0 },  // AuraApplications - not in this version
        {  252,   4 },  // AuraState
        {  256,  12 },  // BaseAttackTime
        {  268,   4 },  // BoundingRadius
        {  272,   4 },  // CombatReach
        {  276,   4 },  // DisplayId
        {  280,   4 },  // NativeDisplayId
        {  284,   4 },  // MountDisplayId
        {  288,   4 },  // MinimumDamage
        {  292,   4 },  // MaximumDamage
        {  296,   4 },  // MinimumOffhandDamage
        {  300,   4 },  // MaximumOffhandDamage
        {  304,   4 },  // FieldBytes1
        {  308,   4 },  // PetNumber
        {  312,   4 },  // PetNameTimestamp
        {  316,   4 },  // PetExperience
        {  320,   4 },  // PetNextLevelExperience
        { kNoField, 0 },  // DynamicFlags - not in this version
        {  112,   4 },  // ChannelSpell
        {  324,   4 },  // ModCastSpeed
        {  344,   4 },  // CreatedBySpellId
        {  348,   8 },  // NpcFlags
        {  356,   4 },  // NpcEmoteState
        { kNoField, 0 },  // TrainingPoints - not in this version
        {  360,  20 },  // Stat
        {  420,  28 },  // Resistance
        {  504,   4 },  // BaseMana
        {  508,   4 },  // BaseHealth
        {  512,   4 },  // FieldBytes2
        {  516,   4 },  // AttackPower
        { kNoField, 0 },  // AttackPowerMods - not in this version
        {  528,   4 },  // AttackPowerMultiplier
        {  532,   4 },  // RangedAttackPower
        { kNoField, 0 },  // RangedAttackPowerMods - not in this version
        {  544,   4 },  // RangedAttackPowerMultiplier
        {  548,   4 },  // MinimumRangedDamage
        {  552,   4 },  // MaximumRangedDamage
        {  556,  28 },  // PowerCostModifier
        {  584,  28 },  // PowerCostMultiplier
        { kNoField, 0 },  // UnitPadding - not in this version
        {  248,   4 },  // UnitFlags2
        {  380,  20 },  // PositiveStat
        {  400,  20 },  // NegativeStat
        {  448,  28 },  // ResistanceBuffModPositive
        {  476,  28 },  // ResistanceBuffModNegative
        {  612,   4 },  // MaxHealthModifier
        {   48,   8 },  // CritterGuid
        { kNoField, 0 },  // Power6 - not in this version
        { kNoField, 0 },  // Power7 - not in this version
        { kNoField, 0 },  // MaxPower6 - not in this version
        { kNoField, 0 },  // MaxPower7 - not in this version
        {  180,  20 },  // PowerRegenFlatModifier
        {  200,  20 },  // PowerRegenInterruptedFlatModifier
        {  616,   4 },  // HoverHeight
        {  328,   4 },  // ModCastHaste
        {  520,   4 },  // AttackPowerModPos
        {  524,   4 },  // AttackPowerModNeg
        {  536,   4 },  // RangedAttackPowerModsPos
        {  540,   4 },  // RangedAttackPowerModsNeg
        {  624,   4 },  // MaxItemLevel
        {   80,   8 },  // DemonCreatorGuid
        {   96,   8 },  // BattlePetCompanionGuid
        {  116,   4 },  // SummonedByHomeRealm
        {  124,   4 },  // DisplayPower
        {  128,   4 },  // OverrideDisplayPowerId
        {  224,   4 },  // EffectiveLevel
        {  332,   4 },  // ModHaste
        {  336,   4 },  // ModRangedHaste
        {  340,   4 },  // ModHasteRegen
        {  620,   4 },  // MinItemLevel
        {  628,   4 },  // WildBattlePetLevel
        {  632,   4 },  // BattlePetCompanionNameTimestamp
        {  636,   4 },  // InteractSpellId
    };

    static const FieldDesc mopPlayerFields[] =
    {
        {  640,   8 },  // DuelArbiter
        {  648,   4 },  // PlayerFlags
        { kNoField, 0 },  // GuildId - not in this version
        {  652,   4 },  // GuildRank
        {  664,   4 },  // PlayerBytes
        {  668,   4 },  // PlayerBytes2
        {  672,   4 },  // PlayerBytes3
        {  676,   4 },  // DuelTeam
        {  680,   4 },  // GuildTimestamp
        {  684, 3000 },  // Quests
        { 3684, 152 },  // VisibleItems
        { 3860, 184 },  // InventorySlot
        { 4044, 128 },  // PackSlot
        { 4172, 224 },  // BankSlot
        { 4396,  56 },  // BankBagSlot
        { 4452,  96 },  // VendorBuyBackSlot
        { kNoField, 0 },  // KeyRingSlot - not in this version
        { 4548,   8 },  // FarsightGuid
        { kNoField, 0 },  // FieldComboTarget - not in this version
        { 4604,   4 },  // Xp
        { 4608,   4 },  // NextLevelXp
        { kNoField, 0 },  // SkillInfo - not in this version
        { 6404,   4 },  // CharacterPoints1
        { kNoField, 0 },  // CharacterPoints2 - not in this version
        { 6412,   4 },  // TrackCreatures
        { 6416,   4 },  // TrackResources
        { 6436,   4 },  // BlockPct
        { 6440,   4 },  // DodgePct
        { 6444,   4 },  // ParryPct
        { 6448,   4 },  // CritPct
        { 6452,   4 },  // RangedCritPct
        { 6508, 800 },  // ExploredZones
        { 7308,   4 },  // RestStateXp
        { 4596,   8 },  // FieldCoinage
        { kNoField, 0 },  // PosStat - not in this version
        { kNoField, 0 },  // NegStat - not in this version
        { kNoField, 0 },  // ResistanceBuffModPositive - not in this version
        { kNoField, 0 },  // ResistanceBuffModNegative - not in this version
        { 7312,  28 },  // FieldModDamageDonePositive
        { 7340,  28 },  // FieldModDamageDoneNegative
        { 7368,  28 },  // FieldModDamageDonePct
        { 7448,   4 },  // PlayerFieldBytes
        { kNoField, 0 },  // AmmoId - not in this version
        { 7452,   4 },  // SelfResurrectionSpell
        { 7456,   4 },  // FieldPvpMedals
        { 7460,  48 },  // FieldBuyBackPrice
        { 7508,  48 },  // FieldBuyBackTimestamp
        { kNoField, 0 },  // FieldSessionKills - not in this version
        { kNoField, 0 },  // FieldYesterdayKills - not in this version
        { kNoField, 0 },  // FieldLastWeekKills - not in this version
        { kNoField, 0 },  // FieldThisWeekKills - not in this version
        { kNoField, 0 },  // FieldThisWeekContribution - not in this version
        { 7560,   4 },  // FieldLifetimeHonorableKills
        { kNoField, 0 },  // FieldLifetimeDishonorableKills - not in this version
        { kNoField, 0 },  // FieldYersterdayContribution - not in this version
        { kNoField, 0 },  // FieldLastWeekContribution - not in this version
        { kNoField, 0 },  // FieldLastWeekRank - not in this version
        { kNoField, 0 },  // PlayerFieldBytes2 - not in this version
        { 7564,   4 },  // FieldWatchedFactionIdx
        { 7568, 108 },  // FieldCombatRating
        { 3836,   4 },  // ChosenTitle
        { kNoField, 0 },  // PlayerPadding0 - not in this version
        { kNoField, 0 },  // VanityPetSlot - not in this version
        { 4556,  40 },  // FieldKnownTitles
        { 6420,   4 },  // Expertise
        { 6424,   4 },  // OffhandExpertise
        { 6456,   4 },  // OffhandCritPct
        { 6460,  28 },  // SpellCritPct
        { 6488,   4 },  // ShieldBlock
        { 7396,   4 },  // FieldModHealingDone
        { 7440,   4 },  // FieldModTargetResistance
        { 7444,   4 },  // FieldModTargetPhysicalResistance
        { 7556,   4 },  // FieldKills
        { kNoField, 0 },  // FieldContributionToday - not in this version
        { kNoField, 0 },  // FieldContributionYesterday - not in this version
        { 7676,  96 },  // FieldArenaTeamInfo
        { kNoField, 0 },  // FieldHonorCurrency - not in this version
        { kNoField, 0 },  // FieldArenaCurrency - not in this version
        { kNoField, 0 },  // FieldModManaRegen - not in this version
        { kNoField, 0 },  // FieldModManaRegenInterrupt - not in this version
        { 7772,   4 },  // FieldMaxLevel
        { kNoField, 0 },  // FieldDailyQuests - not in this version
        { 3840,   4 },  // Inebriation
        { kNoField, 0 },  // CurrencytokenSlot - not in this version
        { kNoField, 0 },  // FieldKnownCurrencies - not in this version
        { 6492,   4 },  // ShieldBlockCritPct
        { 7400,   4 },  // FieldModHealingPct
        { 7404,   4 },  // FieldModHealingDonePct
        { 7776,  16 },  // RuneRegen
        { 7792,  16 },  // NoReagentCost
        { 7808,  24 },  // FieldGlyphSlots
        { 7832,  24 },  // FieldGlyphs
        { 7856,   4 },  // GlyphsEnabled
        { 7860,   4 },  // PetSpellPower
        {  656,   4 },  // GuildDeleteDate
        {  660,   4 },  // GuildLevel
        { 4612, 1792 },  // FieldSkillInfo
        { 6496,   4 },  // Mastery
        { 7412,  12 },  // WeaponDmgMultiplier
        { 7424,   4 },  // ModSpellPowerPct
        { 7432,   4 },  // OverrideSpellPowerByApPct
        { kNoField, 0 },  // BattlegroundRating - not in this version
        { 7864,  32 },  // Researching
        { kNoField, 0 },  // ResearchSite - not in this version
        { 7896,   8 },  // ProfessionSkillLine
        { 7904,   4 },  // UiHitMod
        { 7908,   4 },  // UiHitSpellMod
        { 7912,   4 },  // UiHomeRealmTimeOffset
        { kNoField, 0 },  // ModHaste - not in this version
        { kNoField, 0 },  // ModRangedHaste - not in this version
        { 7916,   4 },  // ModPetHaste
        { kNoField, 0 },  // ModHasteRegen - not in this version
        { 3844,   4 },  // VirtualPlayerRealm
        { 3848,   4 },  // CurrentSpecId
        { 3852,   4 },  // TaxiMountAnimKitId
        { 3856,   4 },  // CurrentBattlePetBreedQuality
        { 6408,   4 },  // MaxTalentTiers
        { 6428,   4 },  // RangedExpertise
        { 6432,   4 },  // CombatRatingExpertise
        { 6500,   4 },  // PvpPowerDamage
        { 6504,   4 },  // PvpPowerHealing
        { 7408,   4 },  // FieldModPeriodicHealingDonePct
        { 7428,   4 },  // ModResiliencePct
        { 7436,   4 },  // OverrideApBySpellPowerPct
        { 7920,   8 },  // SummonedBattlePetGuid
        { 7928,   4 },  // OverrideSpellId
        { 7932,   4 },  // LfgBonusFactionId
        { 7936,   4 },  // LootSpecId
        { 7940,   4 },  // OverrideZonePvpType
        { 7944,   4 },  // ItemLevelDelta
    };

    static const FieldDesc mopItemFields[] =
    {
        {   32,   8 },  // OwnerGuid
        {   40,   8 },  // ContainerGuid
        {   48,   8 },  // CreatorGuid
        {   56,   8 },  // GiftCreatorGuid
        {   64,   4 },  // StackCount
        {   68,   4 },  // Duration
        {   72,  20 },  // SpellCharges
        {   92,   4 },  // Flags
        {   96, 156 },  // Enchantment
        {  252,   4 },  // PropertySeed
        {  256,   4 },  // RandomPropertiesId
        { kNoField, 0 },  // ItemTextId - not in this version
        {  260,   4 },  // Durability
        {  264,   4 },  // MaxDurability
        {  268,   4 },  // CreatePlayedTime
        { kNoField, 0 },  // ItemPadding0 - not in this version
        {  272,   4 },  // ModifierMask
    };

    static const FieldDesc mopContainerFields[] =
    {
        {  564,   4 },  // SlotCount
        { kNoField, 0 },  // PaddingContainer - not in this version
        {  276, 288 },  // ItemSlot
        { kNoField, 0 },  // ContainerPadding0 - not in this version
    };

    static const FieldDesc mopGameObjectFields[] =
    {
        {   32,   8 },  // ObjectFieldCreatedBy
        {   40,   4 },  // DisplayId
        {   44,   4 },  // Flags
        {   48,  16 },  // Rotation
        { kNoField, 0 },  // State - not in this version
        { kNoField, 0 },  // X - not in this version
        { kNoField, 0 },  // Y - not in this version
        { kNoField, 0 },  // Z - not in this version
        { kNoField, 0 },  // O - not in this version
        { kNoField, 0 },  // Dynamic - not in this version
        {   64,   4 },  // FactionTemplate
        { kNoField, 0 },  // Type - not in this version
        {   68,   4 },  // Level
        { kNoField, 0 },  // ArtKit - not in this version
        { kNoField, 0 },  // AnimationProgress - not in this version
        { kNoField, 0 },  // GameobjectPadding - not in this version
        {   72,   4 },  // Bytes1
        {   76,   4 },  // Bytes2
    };

    static const FieldDesc mopDynamicObjectFields[] =
    {
        {   32,   8 },  // CasterGuid
        {   40,   4 },  // DynamicobjectBytes
        {   44,   4 },  // SpellId
        {   48,   4 },  // Radius
        { kNoField, 0 },  // X - not in this version
        { kNoField, 0 },  // Y - not in this version
        { kNoField, 0 },  // Z - not in this version
        { kNoField, 0 },  // O - not in this version
        { kNoField, 0 },  // Padding - not in this version
        {   52,   4 },  // CastTime
    };

    static const FieldDesc mopCorpseFields[] =
    {
        {   32,   8 },  // OwnerGuid
        {   40,   8 },  // PartyGuid
        { kNoField, 0 },  // O - not in this version
        { kNoField, 0 },  // X - not in this version
        { kNoField, 0 },  // Y - not in this version
        { kNoField, 0 },  // Z - not in this version
        {   48,   4 },  // DisplayId
        {   52,  76 },  // Item
        {  128,   4 },  // CorpseBytes1
        {  132,   4 },  // CorpseBytes2
        { kNoField, 0 },  // Guild - not in this version
        {  136,   4 },  // CorpseFlags
        {  140,   4 },  // DynamicFlags
        { kNoField, 0 },  // CorpsePadding - not in this version
    };

    static const FieldDesc mopAreaTriggerFields[] =
    {
        {   44,   4 },  // SpellId
        {   48,   4 },  // SpellVisualId
        {   40,   4 },  // Duration
        { kNoField, 0 },  // PosX - not in this version
        { kNoField, 0 },  // PosY - not in this version
        { kNoField, 0 },  // PosZ - not in this version
        {   32,   8 },  // CasterGuid
        {   52,   4 },  // Scale
    };

    const ExpansionLayouts mopLayouts
    {
        { mopObjectFields, static_cast<uint16_t>(std::size(mopObjectFields)), 32 },  // object
        { mopUnitFields, static_cast<uint16_t>(std::size(mopUnitFields)), 640 },  // unit
        { mopPlayerFields, static_cast<uint16_t>(std::size(mopPlayerFields)), 7948 },  // player
        { mopItemFields, static_cast<uint16_t>(std::size(mopItemFields)), 276 },  // item
        { mopContainerFields, static_cast<uint16_t>(std::size(mopContainerFields)), 568 },  // container
        { mopGameObjectFields, static_cast<uint16_t>(std::size(mopGameObjectFields)), 80 },  // gameObject
        { mopDynamicObjectFields, static_cast<uint16_t>(std::size(mopDynamicObjectFields)), 56 },  // dynamicObject
        { mopCorpseFields, static_cast<uint16_t>(std::size(mopCorpseFields)), 144 },  // corpse
        { mopAreaTriggerFields, static_cast<uint16_t>(std::size(mopAreaTriggerFields)), 56 },  // areaTrigger
    };
}
