/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

// Generated by the version table generator - do not edit by hand, regenerate instead.

#include "Version/ObjectLayout.hpp"

namespace Version::Tables
{
    static const FieldDesc wotlkObjectFields[] =
    {
        {    0,   8 },  // Guid
        {    8,   4 },  // Type
        {   12,   4 },  // Entry
        {   16,   4 },  // ScaleX
        {   20,   4 },  // PaddingObject
        { kNoField, 0 },  // Data - not in this version
        { kNoField, 0 },  // FieldType - not in this version
        { kNoField, 0 },  // DynamicField - not in this version
    };

    static const FieldDesc wotlkUnitFields[] =
    {
        {   24,   8 },  // CharmGuid
        {   32,   8 },  // SummonGuid
        {   48,   8 },  // CharmedByGuid
        {   56,   8 },  // SummonedByGuid
        {   64,   8 },  // CreatedByGuid
        {   72,   8 },  // TargetGuid
        { kNoField, 0 },  // PersuadedGuid - not in this version
        {   80,   8 },  // ChannelObjectGuid
        {   96,   4 },  // Health
        {  100,   4 },  // Power1
        {  104,   4 },  // Power2
        {  108,   4 },  // Power3
        {  112,   4 },  // Power4
        {  116,   4 },  // Power5
        {  128,   4 },  // MaxHealth
        {  132,   4 },  // MaxPower1
        {  136,   4 },  // MaxPower2
        {  140,   4 },  // MaxPower3
        {  144,   4 },  // MaxPower4
        {  148,   4 },  // MaxPower5
        {  216,   4 },  // Level
        {  220,   4 },  // FactionTemplate
        {   92,   4 },  // FieldBytes0
        {  224,  12 },  // VirtualItemSlotDisplay
        { kNoField, 0 },  // VirtualItemInfo - not in this version
        {  236,   4 },  // UnitFlags
        { kNoField, 0 },  // Aura - not in this version
        { kNoField, 0 },  // AuraFlags - not in this version
        { kNoField, 0 },  // AuraLevels - not in this version
        { kNoField, 0 },  // AuraApplications - not in this version
        {  244,   4 },  // AuraState
        {  248,  12 },  // BaseAttackTime
        {  260,   4 },  // BoundingRadius
        {  264,   4 },  // CombatReach
        {  268,   4 },  // DisplayId
        {  272,   4 },  // NativeDisplayId
        {  276,   4 },  // MountDisplayId
        {  280,   4 },  // MinimumDamage
        {  284,   4 },  // MaximumDamage
        {  288,   4 },  // MinimumOffhandDamage
        {  292,   4 },  // MaximumOffhandDamage
        {  296,   4 },  // FieldBytes1
        {  300,   4 },  // PetNumber
        {  304,   4 },  // PetNameTimestamp
        {  308,   4 },  // PetExperience
        {  312,   4 },  // PetNextLevelExperience
        {  316,   4 },  // DynamicFlags
        {   88,   4 },  // ChannelSpell
        {  320,   4 },  // ModCastSpeed
        {  324,   4 },  // CreatedBySpellId
        {  328,   4 },  // NpcFlags
        {  332,   4 },  // NpcEmoteState
        { kNoField, 0 },  // TrainingPoints - not in this version
        {  336,  20 },  // Stat
        {  396,  28 },  // Resistance
        {  480,   4 },  // BaseMana
        {  484,   4 },  // BaseHealth
        {  488,   4 },  // FieldBytes2
        {  492,   4 },  // AttackPower
        {  496,   4 },  // AttackPowerMods
        {  500,   4 },  // AttackPowerMultiplier
        {  504,   4 },  // RangedAttackPower
        {  508,   4 },  // RangedAttackPowerMods
        {  512,   4 },  // RangedAttackPowerMultiplier
        {  516,   4 },  // MinimumRangedDamage
        {  520,   4 },  // MaximumRangedDamage
        {  524,  28 },  // PowerCostModifier
        {  552,  28 },  // PowerCostMultiplier
        {  588,   4 },  // UnitPadding
        {  240,   4 },  // UnitFlags2
        {  356,  20 },  // PositiveStat
        {  376,  20 },  // NegativeStat
        {  424,  28 },  // ResistanceBuffModPositive
        {  452,  28 },  // ResistanceBuffModNegative
        {  580,   4 },  // MaxHealthModifier
        {   40,   8 },  // CritterGuid
        {  120,   4 },  // Power6
        {  124,   4 },  // Power7
        {  152,   4 },  // MaxPower6
        {  156,   4 },  // MaxPower7
        {  160,  28 },  // PowerRegenFlatModifier
        {  188,  28 },  // PowerRegenInterruptedFlatModifier
        {  584,   4 },  // HoverHeight
        { kNoField, 0 },  // ModCastHaste - not in this version
        { kNoField, 0 },  // AttackPowerModPos - not in this version
        { kNoField, 0 },  // AttackPowerModNeg - not in this version
        { kNoField, 0 },  // RangedAttackPowerModsPos - not in this version
        { kNoField, 0 },  // RangedAttackPowerModsNeg - not in this version
        { kNoField, 0 },  // MaxItemLevel - not in this version
        { kNoField, 0 },  // DemonCreatorGuid - not in this version
        { kNoField, 0 },  // BattlePetCompanionGuid - not in this version
        { kNoField, 0 },  // SummonedByHomeRealm - not in this version
        { kNoField, 0 },  // DisplayPower - not in this version
        { kNoField, 0 },  // OverrideDisplayPowerId - not in this version
        { kNoField, 0 },  // EffectiveLevel - not in this version
        { kNoField, 0 },  // ModHaste - not in this version
        { kNoField, 0 },  // ModRangedHaste - not in this version
        { kNoField, 0 },  // ModHasteRegen - not in this version
        { kNoField, 0 },  // MinItemLevel - not in this version
        { kNoField, 0 },  // WildBattlePetLevel - not in this version
        { kNoField, 0 },  // BattlePetCompanionNameTimestamp - not in this version
        { kNoField, 0 },  // InteractSpellId - not in this version
    };

    static const FieldDesc wotlkPlayerFields[] =
    {
        {  592,   8 },  // DuelArbiter
        {  600,   4 },  // PlayerFlags
        {  604,   4 },  // GuildId
        {  608,   4 },  // GuildRank
        {  612,   4 },  // PlayerBytes
        {  616,   4 },  // PlayerBytes2
        {  620,   4 },  // PlayerBytes3
        {  624,   4 },  // DuelTeam
        {  628,   4 },  // GuildTimestamp
        {  632, 500 },  // Quests
        { 1132, 152 },  // VisibleItems
        { 1296, 184 },  // InventorySlot
        { 1480, 128 },  // PackSlot
        { 1608, 224 },  // BankSlot
        { 1832,  56 },  // BankBagSlot
        { 1888,  96 },  // VendorBuyBackSlot
        { 1984, 256 },  // KeyRingSlot
        { 2496,   8 },  // FarsightGuid
        { kNoField, 0 },  // FieldComboTarget - not in this version
        { 2536,   4 },  // Xp
        { 2540,   4 },  // NextLevelXp
        { 2544, 1536 },  // SkillInfo
        { 4080,   4 },  // CharacterPoints1
        { 4084,   4 },  // CharacterPoints2
        { 4088,   4 },  // TrackCreatures
        { 4092,   4 },  // TrackResources
        { 4096,   4 },  // BlockPct
        { 4100,   4 },  // DodgePct
        { 4104,   4 },  // ParryPct
        { 4116,   4 },  // CritPct
        { 4120,   4 },  // RangedCritPct
        { 4164, 512 },  // ExploredZones
        { 4676,   4 },  // RestStateXp
        { 4680,   4 },  // FieldCoinage
        { kNoField, 0 },  // PosStat - not in this version
        { kNoField, 0 },  // NegStat - not in this version
        { kNoField, 0 },  // ResistanceBuffModPositive - not in this version
        { kNoField, 0 },  // ResistanceBuffModNegative - not in this version
        { 4684,  28 },  // FieldModDamageDonePositive
        { 4712,  28 },  // FieldModDamageDoneNegative
        { 4740,  28 },  // FieldModDamageDonePct
        { 4788,   4 },  // PlayerFieldBytes
        { 4792,   4 },  // AmmoId
        { 4796,   4 },  // SelfResurrectionSpell
        { 4800,   4 },  // FieldPvpMedals
        { 4804,  48 },  // FieldBuyBackPrice
        { 4852,  48 },  // FieldBuyBackTimestamp
        { kNoField, 0 },  // FieldSessionKills - not in this version
        { kNoField, 0 },  // FieldYesterdayKills - not in this version
        { kNoField, 0 },  // FieldLastWeekKills - not in this version
        { kNoField, 0 },  // FieldThisWeekKills - not in this version
        { kNoField, 0 },  // FieldThisWeekContribution - not in this version
        { 4912,   4 },  // FieldLifetimeHonorableKills
        { kNoField, 0 },  // FieldLifetimeDishonorableKills - not in this version
        { kNoField, 0 },  // FieldYersterdayContribution - not in this version
        { kNoField, 0 },  // FieldLastWeekContribution - not in this version
        { kNoField, 0 },  // FieldLastWeekRank - not in this version
        { 4916,   4 },  // PlayerFieldBytes2
        { 4920,   4 },  // FieldWatchedFactionIdx
        { 4924, 100 },  // FieldCombatRating
        { 1284,   4 },  // ChosenTitle
        { 1292,   4 },  // PlayerPadding0
        { kNoField, 0 },  // VanityPetSlot - not in this version
        { 2504,  24 },  // FieldKnownTitles
        { 4108,   4 },  // Expertise
        { 4112,   4 },  // OffhandExpertise
        { 4124,   4 },  // OffhandCritPct
        { 4128,  28 },  // SpellCritPct
        { 4156,   4 },  // ShieldBlock
        { 4768,   4 },  // FieldModHealingDone
        { 4780,   4 },  // FieldModTargetResistance
        { 4784,   4 },  // FieldModTargetPhysicalResistance
        { 4900,   4 },  // FieldKills
        { 4904,   4 },  // FieldContributionToday
        { 4908,   4 },  // FieldContributionYesterday
        { 5024,  84 },  // FieldArenaTeamInfo
        { 5108,   4 },  // FieldHonorCurrency
        { 5112,   4 },  // FieldArenaCurrency
        { kNoField, 0 },  // FieldModManaRegen - not in this version
        { kNoField, 0 },  // FieldModManaRegenInterrupt - not in this version
        { 5116,   4 },  // FieldMaxLevel
        { 5120, 100 },  // FieldDailyQuests
        { 1288,   4 },  // Inebriation
        { 2240, 256 },  // CurrencytokenSlot
        { 2528,   8 },  // FieldKnownCurrencies
        { 4160,   4 },  // ShieldBlockCritPct
        { 4772,   4 },  // FieldModHealingPct
        { 4776,   4 },  // FieldModHealingDonePct
        { 5220,  16 },  // RuneRegen
        { 5236,  12 },  // NoReagentCost
        { 5248,  24 },  // FieldGlyphSlots
        { 5272,  24 },  // FieldGlyphs
        { 5296,   4 },  // GlyphsEnabled
        { 5300,   4 },  // PetSpellPower
        { kNoField, 0 },  // GuildDeleteDate - not in this version
        { kNoField, 0 },  // GuildLevel - not in this version
        { kNoField, 0 },  // FieldSkillInfo - not in this version
        { kNoField, 0 },  // Mastery - not in this version
        { kNoField, 0 },  // WeaponDmgMultiplier - not in this version
        { kNoField, 0 },  // ModSpellPowerPct - not in this version
        { kNoField, 0 },  // OverrideSpellPowerByApPct - not in this version
        { kNoField, 0 },  // BattlegroundRating - not in this version
        { kNoField, 0 },  // Researching - not in this version
        { kNoField, 0 },  // ResearchSite - not in this version
        { kNoField, 0 },  // ProfessionSkillLine - not in this version
        { kNoField, 0 },  // UiHitMod - not in this version
        { kNoField, 0 },  // UiHitSpellMod - not in this version
        { kNoField, 0 },  // UiHomeRealmTimeOffset - not in this version
        { kNoField, 0 },  // ModHaste - not in this version
        { kNoField, 0 },  // ModRangedHaste - not in this version
        { kNoField, 0 },  // ModPetHaste - not in this version
        { kNoField, 0 },  // ModHasteRegen - not in this version
        { kNoField, 0 },  // VirtualPlayerRealm - not in this version
        { kNoField, 0 },  // CurrentSpecId - not in this version
        { kNoField, 0 },  // TaxiMountAnimKitId - not in this version
        { kNoField, 0 },  // CurrentBattlePetBreedQuality - not in this version
        { kNoField, 0 },  // MaxTalentTiers - not in this version
        { kNoField, 0 },  // RangedExpertise - not in this version
        { kNoField, 0 },  // CombatRatingExpertise - not in this version
        { kNoField, 0 },  // PvpPowerDamage - not in this version
        { kNoField, 0 },  // PvpPowerHealing - not in this version
        { kNoField, 0 },  // FieldModPeriodicHealingDonePct - not in this version
        { kNoField, 0 },  // ModResiliencePct - not in this version
        { kNoField, 0 },  // OverrideApBySpellPowerPct - not in this version
        { kNoField, 0 },  // SummonedBattlePetGuid - not in this version
        { kNoField, 0 },  // OverrideSpellId - not in this version
        { kNoField, 0 },  // LfgBonusFactionId - not in this version
        { kNoField, 0 },  // LootSpecId - not in this version
        { kNoField, 0 },  // OverrideZonePvpType - not in this version
        { kNoField, 0 },  // ItemLevelDelta - not in this version
    };

    static const FieldDesc wotlkItemFields[] =
    {
        {   24,   8 },  // OwnerGuid
        {   32,   8 },  // ContainerGuid
        {   40,   8 },  // CreatorGuid
        {   48,   8 },  // GiftCreatorGuid
        {   56,   4 },  // StackCount
        {   60,   4 },  // Duration
        {   64,  20 },  // SpellCharges
        {   84,   4 },  // Flags
        {   88, 144 },  // Enchantment
        {  232,   4 },  // PropertySeed
        {  236,   4 },  // RandomPropertiesId
        { kNoField, 0 },  // ItemTextId - not in this version
        {  240,   4 },  // Durability
        {  244,   4 },  // MaxDurability
        {  248,   4 },  // CreatePlayedTime
        {  252,   4 },  // ItemPadding0
        { kNoField, 0 },  // ModifierMask - not in this version
    };

    static const FieldDesc wotlkContainerFields[] =
    {
        {  256,   4 },  // SlotCount
        {  260,   4 },  // PaddingContainer
        {  264, 288 },  // ItemSlot
        { kNoField, 0 },  // ContainerPadding0 - not in this version
    };

    static const FieldDesc wotlkGameObjectFields[] =
    {
        {   24,   8 },  // ObjectFieldCreatedBy
        {   32,   4 },  // DisplayId
        {   36,   4 },  // Flags
        {   40,  16 },  // Rotation
        { kNoField, 0 },  // State - not in this version
        { kNoField, 0 },  // X - not in this version
        { kNoField, 0 },  // Y - not in this version
        { kNoField, 0 },  // Z - not in this version
        { kNoField, 0 },  // O - not in this version
        {   56,   4 },  // Dynamic
        {   60,   4 },  // FactionTemplate
        { kNoField, 0 },  // Type - not in this version
        {   64,   4 },  // Level
        { kNoField, 0 },  // ArtKit - not in this version
        { kNoField, 0 },  // AnimationProgress - not in this version
        { kNoField, 0 },  // GameobjectPadding - not in this version
        {   68,   4 },  // Bytes1
        { kNoField, 0 },  // Bytes2 - not in this version
    };

    static const FieldDesc wotlkDynamicObjectFields[] =
    {
        {   24,   8 },  // CasterGuid
        {   32,   4 },  // DynamicobjectBytes
        {   36,   4 },  // SpellId
        {   40,   4 },  // Radius
        { kNoField, 0 },  // X - not in this version
        { kNoField, 0 },  // Y - not in this version
        { kNoField, 0 },  // Z - not in this version
        { kNoField, 0 },  // O - not in this version
        { kNoField, 0 },  // Padding - not in this version
        {   44,   4 },  // CastTime
    };

    static const FieldDesc wotlkCorpseFields[] =
    {
        {   24,   8 },  // OwnerGuid
        {   32,   8 },  // PartyGuid
        { kNoField, 0 },  // O - not in this version
        { kNoField, 0 },  // X - not in this version
        { kNoField, 0 },  // Y - not in this version
        { kNoField, 0 },  // Z - not in this version
        {   40,   4 },  // DisplayId
        {   44,  76 },  // Item
        {  120,   4 },  // CorpseBytes1
        {  124,   4 },  // CorpseBytes2
        {  128,   4 },  // Guild
        {  132,   4 },  // CorpseFlags
        {  136,   4 },  // DynamicFlags
        {  140,   4 },  // CorpsePadding
    };

    // WoWAreaTrigger does not exist in this client version
    static const FieldDesc wotlkAreaTriggerFields[] =
    {
        { kNoField, 0 },  // SpellId - not in this version
        { kNoField, 0 },  // SpellVisualId - not in this version
        { kNoField, 0 },  // Duration - not in this version
        { kNoField, 0 },  // PosX - not in this version
        { kNoField, 0 },  // PosY - not in this version
        { kNoField, 0 },  // PosZ - not in this version
        { kNoField, 0 },  // CasterGuid - not in this version
        { kNoField, 0 },  // Scale - not in this version
    };

    const ExpansionLayouts wotlkLayouts
    {
        { wotlkObjectFields, static_cast<uint16_t>(std::size(wotlkObjectFields)), 24 },  // object
        { wotlkUnitFields, static_cast<uint16_t>(std::size(wotlkUnitFields)), 592 },  // unit
        { wotlkPlayerFields, static_cast<uint16_t>(std::size(wotlkPlayerFields)), 5304 },  // player
        { wotlkItemFields, static_cast<uint16_t>(std::size(wotlkItemFields)), 256 },  // item
        { wotlkContainerFields, static_cast<uint16_t>(std::size(wotlkContainerFields)), 552 },  // container
        { wotlkGameObjectFields, static_cast<uint16_t>(std::size(wotlkGameObjectFields)), 72 },  // gameObject
        { wotlkDynamicObjectFields, static_cast<uint16_t>(std::size(wotlkDynamicObjectFields)), 48 },  // dynamicObject
        { wotlkCorpseFields, static_cast<uint16_t>(std::size(wotlkCorpseFields)), 144 },  // corpse
        { wotlkAreaTriggerFields, static_cast<uint16_t>(std::size(wotlkAreaTriggerFields)), 0 },  // areaTrigger
    };
}
