/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

// Generated by the version table generator - do not edit by hand, regenerate instead.

#include "Version/ObjectLayout.hpp"

namespace Version::Tables
{
    static const FieldDesc cataObjectFields[] =
    {
        {    0,   8 },  // Guid
        { kNoField, 0 },  // Type - not in this version
        {   20,   4 },  // Entry
        {   24,   4 },  // ScaleX
        {   28,   4 },  // PaddingObject
        {    8,   8 },  // Data
        {   16,   4 },  // FieldType
        { kNoField, 0 },  // DynamicField - not in this version
    };

    static const FieldDesc cataUnitFields[] =
    {
        {   32,   8 },  // CharmGuid
        {   40,   8 },  // SummonGuid
        {   56,   8 },  // CharmedByGuid
        {   64,   8 },  // SummonedByGuid
        {   72,   8 },  // CreatedByGuid
        {   80,   8 },  // TargetGuid
        { kNoField, 0 },  // PersuadedGuid - not in this version
        {   88,   8 },  // ChannelObjectGuid
        {  104,   4 },  // Health
        {  108,   4 },  // Power1
        {  112,   4 },  // Power2
        {  116,   4 },  // Power3
        {  120,   4 },  // Power4
        {  124,   4 },  // Power5
        {  128,   4 },  // MaxHealth
        {  132,   4 },  // MaxPower1
        {  136,   4 },  // MaxPower2
        {  140,   4 },  // MaxPower3
        {  144,   4 },  // MaxPower4
        {  148,   4 },  // MaxPower5
        {  192,   4 },  // Level
        {  196,   4 },  // FactionTemplate
        {  100,   4 },  // FieldBytes0
        {  200,  12 },  // VirtualItemSlotDisplay
        { kNoField, 0 },  // VirtualItemInfo - not in this version
        {  212,   4 },  // UnitFlags
        { kNoField, 0 },  // Aura - not in this version
        { kNoField, 0 },  // AuraFlags - not in this version
        { kNoField, 0 },  // AuraLevels - not in this version
        { kNoField, 0 },  // AuraApplications - not in this version
        {  220,   4 },  // AuraState
        {  224,  12 },  // BaseAttackTime
        {  236,   4 },  // BoundingRadius
        {  240,   4 },  // CombatReach
        {  244,   4 },  // DisplayId
        {  248,   4 },  // NativeDisplayId
        {  252,   4 },  // MountDisplayId
        {  256,   4 },  // MinimumDamage
        {  260,   4 },  // MaximumDamage
        {  264,   4 },  // MinimumOffhandDamage
        {  268,   4 },  // MaximumOffhandDamage
        {  272,   4 },  // FieldBytes1
        {  276,   4 },  // PetNumber
        {  280,   4 },  // PetNameTimestamp
        {  284,   4 },  // PetExperience
        {  288,   4 },  // PetNextLevelExperience
        {  292,   4 },  // DynamicFlags
        {   96,   4 },  // ChannelSpell
        {  296,   4 },  // ModCastSpeed
        {  304,   4 },  // CreatedBySpellId
        {  308,   4 },  // NpcFlags
        {  312,   4 },  // NpcEmoteState
        { kNoField, 0 },  // TrainingPoints - not in this version
        {  316,  20 },  // Stat
        {  376,  28 },  // Resistance
        {  460,   4 },  // BaseMana
        {  464,   4 },  // BaseHealth
        {  468,   4 },  // FieldBytes2
        {  472,   4 },  // AttackPower
        { kNoField, 0 },  // AttackPowerMods - not in this version
        {  484,   4 },  // AttackPowerMultiplier
        {  488,   4 },  // RangedAttackPower
        { kNoField, 0 },  // RangedAttackPowerMods - not in this version
        {  500,   4 },  // RangedAttackPowerMultiplier
        {  504,   4 },  // MinimumRangedDamage
        {  508,   4 },  // MaximumRangedDamage
        {  512,  28 },  // PowerCostModifier
        {  540,  28 },  // PowerCostMultiplier
        {  580,   4 },  // UnitPadding
        {  216,   4 },  // UnitFlags2
        {  336,  20 },  // PositiveStat
        {  356,  20 },  // NegativeStat
        {  404,  28 },  // ResistanceBuffModPositive
        {  432,  28 },  // ResistanceBuffModNegative
        {  568,   4 },  // MaxHealthModifier
        {   48,   8 },  // CritterGuid
        { kNoField, 0 },  // Power6 - not in this version
        { kNoField, 0 },  // Power7 - not in this version
        { kNoField, 0 },  // MaxPower6 - not in this version
        { kNoField, 0 },  // MaxPower7 - not in this version
        {  152,  20 },  // PowerRegenFlatModifier
        {  172,  20 },  // PowerRegenInterruptedFlatModifier
        {  572,   4 },  // HoverHeight
        {  300,   4 },  // ModCastHaste
        {  476,   4 },  // AttackPowerModPos
        {  480,   4 },  // AttackPowerModNeg
        {  492,   4 },  // RangedAttackPowerModsPos
        {  496,   4 },  // RangedAttackPowerModsNeg
        {  576,   4 },  // MaxItemLevel
        { kNoField, 0 },  // DemonCreatorGuid - not in this version
        { kNoField, 0 },  // BattlePetCompanionGuid - not in this version
        { kNoField, 0 },  // SummonedByHomeRealm - not in this version
        { kNoField, 0 },  // DisplayPower - not in this version
        { kNoField, 0 },  // OverrideDisplayPowerId - not in this version
        { kNoField, 0 },  // EffectiveLevel - not in this version
        { kNoField, 0 },  // ModHaste - not in this version
        { kNoField, 0 },  // ModRangedHaste - not in this version
        { kNoField, 0 },  // ModHasteRegen - not in this version
        { kNoField, 0 },  // MinItemLevel - not in this version
        { kNoField, 0 },  // WildBattlePetLevel - not in this version
        { kNoField, 0 },  // BattlePetCompanionNameTimestamp - not in this version
        { kNoField, 0 },  // InteractSpellId - not in this version
    };

    static const FieldDesc cataPlayerFields[] =
    {
        {  584,   8 },  // DuelArbiter
        {  592,   4 },  // PlayerFlags
        { kNoField, 0 },  // GuildId - not in this version
        {  596,   4 },  // GuildRank
        {  608,   4 },  // PlayerBytes
        {  612,   4 },  // PlayerBytes2
        {  616,   4 },  // PlayerBytes3
        {  620,   4 },  // DuelTeam
        {  624,   4 },  // GuildTimestamp
        {  628, 1000 },  // Quests
        { 1628, 152 },  // VisibleItems
        { 1792, 184 },  // InventorySlot
        { 1976, 128 },  // PackSlot
        { 2104, 224 },  // BankSlot
        { 2328,  56 },  // BankBagSlot
        { 2384,  96 },  // VendorBuyBackSlot
        { kNoField, 0 },  // KeyRingSlot - not in this version
        { 2480,   8 },  // FarsightGuid
        { kNoField, 0 },  // FieldComboTarget - not in this version
        { 2520,   4 },  // Xp
        { 2524,   4 },  // NextLevelXp
        { kNoField, 0 },  // SkillInfo - not in this version
        { 4064,   4 },  // CharacterPoints1
        { kNoField, 0 },  // CharacterPoints2 - not in this version
        { 4068,   4 },  // TrackCreatures
        { 4072,   4 },  // TrackResources
        { 4084,   4 },  // BlockPct
        { 4088,   4 },  // DodgePct
        { 4092,   4 },  // ParryPct
        { 4096,   4 },  // CritPct
        { 4100,   4 },  // RangedCritPct
        { 4148, 624 },  // ExploredZones
        { 4772,   4 },  // RestStateXp
        { 4776,   8 },  // FieldCoinage
        { kNoField, 0 },  // PosStat - not in this version
        { kNoField, 0 },  // NegStat - not in this version
        { kNoField, 0 },  // ResistanceBuffModPositive - not in this version
        { kNoField, 0 },  // ResistanceBuffModNegative - not in this version
        { 4784,  28 },  // FieldModDamageDonePositive
        { 4812,  28 },  // FieldModDamageDoneNegative
        { 4840,  28 },  // FieldModDamageDonePct
        { 4908,   4 },  // PlayerFieldBytes
        { kNoField, 0 },  // AmmoId - not in this version
        { 4912,   4 },  // SelfResurrectionSpell
        { 4916,   4 },  // FieldPvpMedals
        { 4920,  48 },  // FieldBuyBackPrice
        { 4968,  48 },  // FieldBuyBackTimestamp
        { kNoField, 0 },  // FieldSessionKills - not in this version
        { kNoField, 0 },  // FieldYesterdayKills - not in this version
        { kNoField, 0 },  // FieldLastWeekKills - not in this version
        { kNoField, 0 },  // FieldThisWeekKills - not in this version
        { kNoField, 0 },  // FieldThisWeekContribution - not in this version
        { 5020,   4 },  // FieldLifetimeHonorableKills
        { kNoField, 0 },  // FieldLifetimeDishonorableKills - not in this version
        { kNoField, 0 },  // FieldYersterdayContribution - not in this version
        { kNoField, 0 },  // FieldLastWeekContribution - not in this version
        { kNoField, 0 },  // FieldLastWeekRank - not in this version
        { 5024,   4 },  // PlayerFieldBytes2
        { 5028,   4 },  // FieldWatchedFactionIdx
        { 5032, 104 },  // FieldCombatRating
        { 1780,   4 },  // ChosenTitle
        { 1788,   4 },  // PlayerPadding0
        { kNoField, 0 },  // VanityPetSlot - not in this version
        { 2488,  32 },  // FieldKnownTitles
        { 4076,   4 },  // Expertise
        { 4080,   4 },  // OffhandExpertise
        { 4104,   4 },  // OffhandCritPct
        { 4108,  28 },  // SpellCritPct
        { 4136,   4 },  // ShieldBlock
        { 4868,   4 },  // FieldModHealingDone
        { 4900,   4 },  // FieldModTargetResistance
        { 4904,   4 },  // FieldModTargetPhysicalResistance
        { 5016,   4 },  // FieldKills
        { kNoField, 0 },  // FieldContributionToday - not in this version
        { kNoField, 0 },  // FieldContributionYesterday - not in this version
        { 5136,  84 },  // FieldArenaTeamInfo
        { kNoField, 0 },  // FieldHonorCurrency - not in this version
        { kNoField, 0 },  // FieldArenaCurrency - not in this version
        { kNoField, 0 },  // FieldModManaRegen - not in this version
        { kNoField, 0 },  // FieldModManaRegenInterrupt - not in this version
        { 5224,   4 },  // FieldMaxLevel
        { 5228, 100 },  // FieldDailyQuests
        { 1784,   4 },  // Inebriation
        { kNoField, 0 },  // CurrencytokenSlot - not in this version
        { kNoField, 0 },  // FieldKnownCurrencies - not in this version
        { 4140,   4 },  // ShieldBlockCritPct
        { 4872,   4 },  // FieldModHealingPct
        { 4876,   4 },  // FieldModHealingDonePct
        { 5328,  16 },  // RuneRegen
        { 5344,  12 },  // NoReagentCost
        { 5356,  36 },  // FieldGlyphSlots
        { 5392,  36 },  // FieldGlyphs
        { 5428,   4 },  // GlyphsEnabled
        { 5432,   4 },  // PetSpellPower
        {  600,   4 },  // GuildDeleteDate
        {  604,   4 },  // GuildLevel
        { 2528, 1536 },  // FieldSkillInfo
        { 4144,   4 },  // Mastery
        { 4880,  12 },  // WeaponDmgMultiplier
        { 4892,   4 },  // ModSpellPowerPct
        { 4896,   4 },  // OverrideSpellPowerByApPct
        { 5220,   4 },  // BattlegroundRating
        { 5436,  32 },  // Researching
        { 5468,  32 },  // ResearchSite
        { 5500,   8 },  // ProfessionSkillLine
        { 5508,   4 },  // UiHitMod
        { 5512,   4 },  // UiHitSpellMod
        { 5516,   4 },  // UiHomeRealmTimeOffset
        { 5520,   4 },  // ModHaste
        { 5524,   4 },  // ModRangedHaste
        { 5528,   4 },  // ModPetHaste
        { 5532,   4 },  // ModHasteRegen
        { kNoField, 0 },  // VirtualPlayerRealm - not in this version
        { kNoField, 0 },  // CurrentSpecId - not in this version
        { kNoField, 0 },  // TaxiMountAnimKitId - not in this version
        { kNoField, 0 },  // CurrentBattlePetBreedQuality - not in this version
        { kNoField, 0 },  // MaxTalentTiers - not in this version
        { kNoField, 0 },  // RangedExpertise - not in this version
        { kNoField, 0 },  // CombatRatingExpertise - not in this version
        { kNoField, 0 },  // PvpPowerDamage - not in this version
        { kNoField, 0 },  // PvpPowerHealing - not in this version
        { kNoField, 0 },  // FieldModPeriodicHealingDonePct - not in this version
        { kNoField, 0 },  // ModResiliencePct - not in this version
        { kNoField, 0 },  // OverrideApBySpellPowerPct - not in this version
        { kNoField, 0 },  // SummonedBattlePetGuid - not in this version
        { kNoField, 0 },  // OverrideSpellId - not in this version
        { kNoField, 0 },  // LfgBonusFactionId - not in this version
        { kNoField, 0 },  // LootSpecId - not in this version
        { kNoField, 0 },  // OverrideZonePvpType - not in this version
        { kNoField, 0 },  // ItemLevelDelta - not in this version
    };

    static const FieldDesc cataItemFields[] =
    {
        {   32,   8 },  // OwnerGuid
        {   40,   8 },  // ContainerGuid
        {   48,   8 },  // CreatorGuid
        {   56,   8 },  // GiftCreatorGuid
        {   64,   4 },  // StackCount
        {   68,   4 },  // Duration
        {   72,  20 },  // SpellCharges
        {   92,   4 },  // Flags
        {   96, 180 },  // Enchantment
        {  276,   4 },  // PropertySeed
        {  280,   4 },  // RandomPropertiesId
        { kNoField, 0 },  // ItemTextId - not in this version
        {  284,   4 },  // Durability
        {  288,   4 },  // MaxDurability
        {  292,   4 },  // CreatePlayedTime
        { kNoField, 0 },  // ItemPadding0 - not in this version
        { kNoField, 0 },  // ModifierMask - not in this version
    };

    static const FieldDesc cataContainerFields[] =
    {
        {  296,   4 },  // SlotCount
        { kNoField, 0 },  // PaddingContainer - not in this version
        {  304, 288 },  // ItemSlot
        {  300,   4 },  // ContainerPadding0
    };

    static const FieldDesc cataGameObjectFields[] =
    {
        {   32,   8 },  // ObjectFieldCreatedBy
        {   40,   4 },  // DisplayId
        {   44,   4 },  // Flags
        {   48,  16 },  // Rotation
        { kNoField, 0 },  // State - not in this version
        { kNoField, 0 },  // X - not in this version
        { kNoField, 0 },  // Y - not in this version
        { kNoField, 0 },  // Z - not in this version
        { kNoField, 0 },  // O - not in this version
        {   64,   4 },  // Dynamic
        {   68,   4 },  // FactionTemplate
        { kNoField, 0 },  // Type - not in this version
        {   72,   4 },  // Level
        { kNoField, 0 },  // ArtKit - not in this version
        { kNoField, 0 },  // AnimationProgress - not in this version
        { kNoField, 0 },  // GameobjectPadding - not in this version
        {   76,   4 },  // Bytes1
        { kNoField, 0 },  // Bytes2 - not in this version
    };

    static const FieldDesc cataDynamicObjectFields[] =
    {
        {   32,   8 },  // CasterGuid
        {   40,   4 },  // DynamicobjectBytes
        {   44,   4 },  // SpellId
        {   48,   4 },  // Radius
        { kNoField, 0 },  // X - not in this version
        { kNoField, 0 },  // Y - not in this version
        { kNoField, 0 },  // Z - not in this version
        { kNoField, 0 },  // O - not in this version
        { kNoField, 0 },  // Padding - not in this version
        {   52,   4 },  // CastTime
    };

    static const FieldDesc cataCorpseFields[] =
    {
        {   32,   8 },  // OwnerGuid
        {   40,   8 },  // PartyGuid
        { kNoField, 0 },  // O - not in this version
        { kNoField, 0 },  // X - not in this version
        { kNoField, 0 },  // Y - not in this version
        { kNoField, 0 },  // Z - not in this version
        {   48,   4 },  // DisplayId
        {   52,  76 },  // Item
        {  128,   4 },  // CorpseBytes1
        {  132,   4 },  // CorpseBytes2
        { kNoField, 0 },  // Guild - not in this version
        {  136,   4 },  // CorpseFlags
        {  140,   4 },  // DynamicFlags
        { kNoField, 0 },  // CorpsePadding - not in this version
    };

    static const FieldDesc cataAreaTriggerFields[] =
    {
        {   32,   4 },  // SpellId
        {   36,   4 },  // SpellVisualId
        {   40,   4 },  // Duration
        {   44,   4 },  // PosX
        {   48,   4 },  // PosY
        {   52,   4 },  // PosZ
        { kNoField, 0 },  // CasterGuid - not in this version
        { kNoField, 0 },  // Scale - not in this version
    };

    const ExpansionLayouts cataLayouts
    {
        { cataObjectFields, static_cast<uint16_t>(std::size(cataObjectFields)), 32 },  // object
        { cataUnitFields, static_cast<uint16_t>(std::size(cataUnitFields)), 584 },  // unit
        { cataPlayerFields, static_cast<uint16_t>(std::size(cataPlayerFields)), 5536 },  // player
        { cataItemFields, static_cast<uint16_t>(std::size(cataItemFields)), 296 },  // item
        { cataContainerFields, static_cast<uint16_t>(std::size(cataContainerFields)), 592 },  // container
        { cataGameObjectFields, static_cast<uint16_t>(std::size(cataGameObjectFields)), 80 },  // gameObject
        { cataDynamicObjectFields, static_cast<uint16_t>(std::size(cataDynamicObjectFields)), 56 },  // dynamicObject
        { cataCorpseFields, static_cast<uint16_t>(std::size(cataCorpseFields)), 144 },  // corpse
        { cataAreaTriggerFields, static_cast<uint16_t>(std::size(cataAreaTriggerFields)), 56 },  // areaTrigger
    };
}
