/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

// Layout of the object values for WoD clients: byte offset, size, element count and element stride of every field.

#include "Version/ObjectLayout.hpp"

#include <iterator>

namespace Version::Tables
{
    // WoWObject: 11 fields, 48 bytes
    static const FieldEntry<ObjectField> wodObjectFields[] =
    {
        { ObjectField::Guid,                     {    0,   16,   1,    0 } },
        { ObjectField::Data,                     {   16,   16,   1,    0 } },
        { ObjectField::FieldType,                {   32,    4,   1,    0 } },
        { ObjectField::Type,                     {   32,    4,   1,    0 } },
        { ObjectField::FieldTypeType,            {   32,    2,   1,    0 } },
        { ObjectField::FieldTypeGuildId,         {   34,    2,   1,    0 } },
        { ObjectField::Entry,                    {   36,    4,   1,    0 } },
        { ObjectField::DynamicField,             {   40,    4,   1,    0 } },
        { ObjectField::DynamicFieldDynamicFlags, {   40,    2,   1,    0 } },
        { ObjectField::DynamicFieldPathProgress, {   42,    2,   1,    0 } },
        { ObjectField::ScaleX,                   {   44,    4,   1,    0 } },
    };

    // WoWUnit: 102 fields, 848 bytes
    static const FieldEntry<UnitField> wodUnitFields[] =
    {
        { UnitField::CharmGuid,                         {   48,   16,   1,    0 } },
        { UnitField::SummonGuid,                        {   64,   16,   1,    0 } },
        { UnitField::CritterGuid,                       {   80,   16,   1,    0 } },
        { UnitField::CharmedByGuid,                     {   96,   16,   1,    0 } },
        { UnitField::SummonedByGuid,                    {  112,   16,   1,    0 } },
        { UnitField::CreatedByGuid,                     {  128,   16,   1,    0 } },
        { UnitField::DemonCreatorGuid,                  {  144,   16,   1,    0 } },
        { UnitField::TargetGuid,                        {  160,   16,   1,    0 } },
        { UnitField::MaxPower2,                         {  168,    4,   1,    0 } },
        { UnitField::BattlePetCompanionGuid,            {  176,   16,   1,    0 } },
        { UnitField::ChannelObjectGuid,                 {  200,   16,   1,    0 } },
        { UnitField::ChannelSpell,                      {  216,    4,   1,    0 } },
        { UnitField::SummonedByHomeRealm,               {  224,    4,   1,    0 } },
        { UnitField::FieldBytes0,                       {  228,    4,   1,    0 } },
        { UnitField::FieldBytes0Race,                   {  228,    1,   1,    0 } },
        { UnitField::FieldBytes0UnitClass,              {  229,    1,   1,    0 } },
        { UnitField::FieldBytes0ClassSpec,              {  230,    1,   1,    0 } },
        { UnitField::FieldBytes0Gender,                 {  231,    1,   1,    0 } },
        { UnitField::DisplayPower,                      {  232,    4,   1,    0 } },
        { UnitField::OverrideDisplayPowerId,            {  236,    4,   1,    0 } },
        { UnitField::Health,                            {  240,    4,   1,    0 } },
        { UnitField::Power1,                            {  244,    4,   1,    0 } },
        { UnitField::Power2,                            {  248,    4,   1,    0 } },
        { UnitField::Power3,                            {  252,    4,   1,    0 } },
        { UnitField::Power4,                            {  256,    4,   1,    0 } },
        { UnitField::Power5,                            {  260,    4,   1,    0 } },
        { UnitField::Power6,                            {  264,    4,   1,    0 } },
        { UnitField::MaxHealth,                         {  268,    4,   1,    0 } },
        { UnitField::MaxPower1,                         {  272,    4,   1,    0 } },
        { UnitField::MaxPower3,                         {  280,    4,   1,    0 } },
        { UnitField::MaxPower4,                         {  284,    4,   1,    0 } },
        { UnitField::MaxPower5,                         {  288,    4,   1,    0 } },
        { UnitField::MaxPower6,                         {  292,    4,   1,    0 } },
        { UnitField::PowerRegenFlatModifier,            {  296,    4,   6,    4 } },
        { UnitField::PetNumber,                         {  300,    4,   1,    0 } },
        { UnitField::PetNameTimestamp,                  {  304,    4,   1,    0 } },
        { UnitField::PetExperience,                     {  308,    4,   1,    0 } },
        { UnitField::DynamicFlags,                      {  316,    4,   1,    0 } },
        { UnitField::PowerRegenInterruptedFlatModifier, {  320,    4,   6,    4 } },
        { UnitField::Level,                             {  344,    4,   1,    0 } },
        { UnitField::EffectiveLevel,                    {  348,    4,   1,    0 } },
        { UnitField::FactionTemplate,                   {  352,    4,   1,    0 } },
        { UnitField::VirtualItemSlotDisplay,            {  356,    4,   6,    4 } },
        { UnitField::UnitFlags,                         {  380,    4,   1,    0 } },
        { UnitField::UnitFlags2,                        {  384,    4,   1,    0 } },
        { UnitField::AuraState,                         {  392,    4,   1,    0 } },
        { UnitField::BaseAttackTime,                    {  396,    4,   2,    4 } },
        { UnitField::BoundingRadius,                    {  408,    4,   1,    0 } },
        { UnitField::CombatReach,                       {  412,    4,   1,    0 } },
        { UnitField::DisplayId,                         {  416,    4,   1,    0 } },
        { UnitField::NativeDisplayId,                   {  420,    4,   1,    0 } },
        { UnitField::MountDisplayId,                    {  424,    4,   1,    0 } },
        { UnitField::MinimumDamage,                     {  428,    4,   1,    0 } },
        { UnitField::MaximumDamage,                     {  432,    4,   1,    0 } },
        { UnitField::MinimumOffhandDamage,              {  436,    4,   1,    0 } },
        { UnitField::MaximumOffhandDamage,              {  440,    4,   1,    0 } },
        { UnitField::FieldBytes1,                       {  444,    4,   1,    0 } },
        { UnitField::FieldBytes1StandState,             {  444,    1,   1,    0 } },
        { UnitField::FieldBytes1Unk1,                   {  445,    1,   1,    0 } },
        { UnitField::FieldBytes1StandStateFlag,         {  446,    1,   1,    0 } },
        { UnitField::FieldBytes1AnimationFlag,          {  447,    1,   1,    0 } },
        { UnitField::PetNextLevelExperience,            {  460,    4,   1,    0 } },
        { UnitField::ModCastSpeed,                      {  464,    4,   1,    0 } },
        { UnitField::ModCastHaste,                      {  468,    4,   1,    0 } },
        { UnitField::ModHaste,                          {  472,    4,   1,    0 } },
        { UnitField::ModRangedHaste,                    {  476,    4,   1,    0 } },
        { UnitField::ModHasteRegen,                     {  480,    4,   1,    0 } },
        { UnitField::CreatedBySpellId,                  {  484,    4,   1,    0 } },
        { UnitField::NpcFlags,                          {  488,    8,   1,    0 } },
        { UnitField::NpcEmoteState,                     {  496,    4,   1,    0 } },
        { UnitField::Stat,                              {  500,    4,   5,    4 } },
        { UnitField::PositiveStat,                      {  520,    4,   5,    4 } },
        { UnitField::NegativeStat,                      {  540,    4,   5,    4 } },
        { UnitField::Resistance,                        {  560,    4,   7,    4 } },
        { UnitField::ResistanceBuffModPositive,         {  588,    4,   7,    4 } },
        { UnitField::ResistanceBuffModNegative,         {  616,    4,   7,    4 } },
        { UnitField::BaseMana,                          {  648,    4,   1,    0 } },
        { UnitField::BaseHealth,                        {  652,    4,   1,    0 } },
        { UnitField::FieldBytes2,                       {  656,    4,   1,    0 } },
        { UnitField::FieldBytes2SheathType,             {  656,    1,   1,    0 } },
        { UnitField::FieldBytes2PvpFlag,                {  657,    1,   1,    0 } },
        { UnitField::FieldBytes2PetFlag,                {  658,    1,   1,    0 } },
        { UnitField::FieldBytes2ShapeShiftForm,         {  659,    1,   1,    0 } },
        { UnitField::AttackPower,                       {  660,    4,   1,    0 } },
        { UnitField::AttackPowerModPos,                 {  664,    4,   1,    0 } },
        { UnitField::AttackPowerModNeg,                 {  668,    4,   1,    0 } },
        { UnitField::AttackPowerMultiplier,             {  672,    4,   1,    0 } },
        { UnitField::RangedAttackPower,                 {  676,    4,   1,    0 } },
        { UnitField::RangedAttackPowerModsPos,          {  680,    4,   1,    0 } },
        { UnitField::RangedAttackPowerModsNeg,          {  684,    4,   1,    0 } },
        { UnitField::RangedAttackPowerMultiplier,       {  688,    4,   1,    0 } },
        { UnitField::MinimumRangedDamage,               {  692,    4,   1,    0 } },
        { UnitField::MaximumRangedDamage,               {  696,    4,   1,    0 } },
        { UnitField::PowerCostModifier,                 {  700,    4,   7,    4 } },
        { UnitField::PowerCostMultiplier,               {  728,    4,   7,    4 } },
        { UnitField::MaxHealthModifier,                 {  756,    4,   1,    0 } },
        { UnitField::HoverHeight,                       {  760,    4,   1,    0 } },
        { UnitField::MinItemLevel,                      {  768,    4,   1,    0 } },
        { UnitField::MaxItemLevel,                      {  772,    4,   1,    0 } },
        { UnitField::WildBattlePetLevel,                {  776,    4,   1,    0 } },
        { UnitField::BattlePetCompanionNameTimestamp,   {  780,    4,   1,    0 } },
        { UnitField::InteractSpellId,                   {  784,    4,   1,    0 } },
    };

    // WoWPlayer: 136 fields, 14404 bytes
    static const FieldEntry<PlayerField> wodPlayerFields[] =
    {
        { PlayerField::DuelArbiter,                            {  848,   16,   1,    0 } },
        { PlayerField::PlayerFlags,                            {  896,    4,   1,    0 } },
        { PlayerField::GuildRank,                              {  904,    4,   1,    0 } },
        { PlayerField::GuildDeleteDate,                        {  908,    4,   1,    0 } },
        { PlayerField::GuildLevel,                             {  912,    4,   1,    0 } },
        { PlayerField::PlayerBytes,                            {  916,    4,   1,    0 } },
        { PlayerField::PlayerBytesSkinColor,                   {  916,    1,   1,    0 } },
        { PlayerField::PlayerBytesFace,                        {  917,    1,   1,    0 } },
        { PlayerField::PlayerBytesHairStyle,                   {  918,    1,   1,    0 } },
        { PlayerField::PlayerBytesHornStyle,                   {  918,    1,   1,    0 } },
        { PlayerField::PlayerBytesHairColor,                   {  919,    1,   1,    0 } },
        { PlayerField::PlayerBytesHornColor,                   {  919,    1,   1,    0 } },
        { PlayerField::PlayerBytes2,                           {  920,    4,   1,    0 } },
        { PlayerField::PlayerBytes2Earrings,                   {  920,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Ears,                       {  920,    1,   1,    0 } },
        { PlayerField::PlayerBytes2FacialHair,                 {  920,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Features,                   {  920,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Hair,                       {  920,    1,   1,    0 } },
        { PlayerField::PlayerBytes2HornStyle,                  {  920,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Markings,                   {  920,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Piercings,                  {  920,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Tusks,                      {  920,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Unk1,                       {  921,    1,   1,    0 } },
        { PlayerField::PlayerBytes2BankSlots,                  {  922,    1,   1,    0 } },
        { PlayerField::PlayerBytes2RestState,                  {  923,    1,   1,    0 } },
        { PlayerField::PlayerBytes3,                           {  924,    4,   1,    0 } },
        { PlayerField::PlayerBytes3Gender,                     {  924,    1,   1,    0 } },
        { PlayerField::PlayerBytes3DrunkValue,                 {  925,    1,   1,    0 } },
        { PlayerField::PlayerBytes3PvpRank,                    {  926,    1,   1,    0 } },
        { PlayerField::PlayerBytes3ArenaFaction,               {  927,    1,   1,    0 } },
        { PlayerField::DuelTeam,                               {  928,    4,   1,    0 } },
        { PlayerField::GuildTimestamp,                         {  932,    4,   1,    0 } },
        { PlayerField::Quests,                                 {  936,   60,  50,   60 } },
        { PlayerField::QuestsQuestId,                          {  936,    4,  50,   60 } },
        { PlayerField::QuestsState,                            {  940,    4,  50,   60 } },
        { PlayerField::QuestsRequiredMobOrGo,                  {  944,    8,  50,   60 } },
        { PlayerField::QuestsExpireTime,                       {  952,    4,  50,   60 } },
        { PlayerField::VisibleItems,                           { 3936,    8,  19,    8 } },
        { PlayerField::VisibleItemsEntry,                      { 3936,    4,  19,    8 } },
        { PlayerField::VisibleItemsEnchantment,                { 3940,    4,  19,    8 } },
        { PlayerField::VisibleItemsEnchantmentPermEnchantment, { 3940,    2,  19,    8 } },
        { PlayerField::VisibleItemsEnchantmentTempEnchantment, { 3942,    2,  19,    8 } },
        { PlayerField::ChosenTitle,                            { 4088,    4,   1,    0 } },
        { PlayerField::Inebriation,                            { 4092,    4,   1,    0 } },
        { PlayerField::VirtualPlayerRealm,                     { 4096,    4,   1,    0 } },
        { PlayerField::CurrentSpecId,                          { 4100,    4,   1,    0 } },
        { PlayerField::TaxiMountAnimKitId,                     { 4104,    4,   1,    0 } },
        { PlayerField::CurrentBattlePetBreedQuality,           { 4124,    4,   1,    0 } },
        { PlayerField::InventorySlot,                          { 4128,   16,  23,   16 } },
        { PlayerField::PackSlot,                               { 4496,   16,  16,   16 } },
        { PlayerField::BankSlot,                               { 4752,   16,  28,   16 } },
        { PlayerField::BankBagSlot,                            { 5200,   16,   7,   16 } },
        { PlayerField::VendorBuyBackSlot,                      { 5312,   16,  12,   16 } },
        { PlayerField::FarsightGuid,                           { 7072,   16,   1,    0 } },
        { PlayerField::FieldKnownTitles,                       { 7088,    8,   6,    8 } },
        { PlayerField::FieldCoinage,                           { 7136,    8,   1,    0 } },
        { PlayerField::Xp,                                     { 7144,    4,   1,    0 } },
        { PlayerField::NextLevelXp,                            { 7148,    4,   1,    0 } },
        { PlayerField::FieldSkillInfo,                         { 7152, 1792,   1,    0 } },
        { PlayerField::FieldSkillInfoSkillId,                  { 7152,    4, 448,    4 } },
        { PlayerField::FieldSkillInfoSkillLine,                { 7152,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillStep,                { 7408,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillRank,                { 7664,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillStartingRank,        { 7920,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillMaxRank,             { 8176,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillMod,                 { 8432,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillTalent,              { 8688,    4,  64,    4 } },
        { PlayerField::CharacterPoints1,                       { 8944,    4,   1,    0 } },
        { PlayerField::MaxTalentTiers,                         { 8948,    4,   1,    0 } },
        { PlayerField::TrackCreatures,                         { 8952,    4,   1,    0 } },
        { PlayerField::TrackResources,                         { 8956,    4,   1,    0 } },
        { PlayerField::Expertise,                              { 8960,    4,   1,    0 } },
        { PlayerField::OffhandExpertise,                       { 8964,    4,   1,    0 } },
        { PlayerField::RangedExpertise,                        { 8968,    4,   1,    0 } },
        { PlayerField::CombatRatingExpertise,                  { 8972,    4,   1,    0 } },
        { PlayerField::BlockPct,                               { 8976,    4,   1,    0 } },
        { PlayerField::DodgePct,                               { 8980,    4,   1,    0 } },
        { PlayerField::ParryPct,                               { 8984,    4,   1,    0 } },
        { PlayerField::CritPct,                                { 8988,    4,   1,    0 } },
        { PlayerField::RangedCritPct,                          { 8992,    4,   1,    0 } },
        { PlayerField::OffhandCritPct,                         { 8996,    4,   1,    0 } },
        { PlayerField::SpellCritPct,                           { 9000,    4,   7,    4 } },
        { PlayerField::ShieldBlock,                            { 9028,    4,   1,    0 } },
        { PlayerField::ShieldBlockCritPct,                     { 9032,    4,   1,    0 } },
        { PlayerField::Mastery,                                { 9036,    4,   1,    0 } },
        { PlayerField::PvpPowerDamage,                         { 9084,    4,   1,    0 } },
        { PlayerField::PvpPowerHealing,                        { 9088,    4,   1,    0 } },
        { PlayerField::ExploredZones,                          { 9092,    4, 256,    4 } },
        { PlayerField::RestStateXp,                            { 10116,    4,   1,    0 } },
        { PlayerField::FieldModDamageDonePositive,             { 10120,    4,   7,    4 } },
        { PlayerField::FieldModDamageDoneNegative,             { 10148,    4,   7,    4 } },
        { PlayerField::FieldModDamageDonePct,                  { 10176,    4,   7,    4 } },
        { PlayerField::FieldModHealingDone,                    { 10204,    4,   1,    0 } },
        { PlayerField::FieldModHealingPct,                     { 10208,    4,   1,    0 } },
        { PlayerField::FieldModHealingDonePct,                 { 10212,    4,   1,    0 } },
        { PlayerField::FieldModPeriodicHealingDonePct,         { 10216,    4,   1,    0 } },
        { PlayerField::WeaponDmgMultiplier,                    { 10220,    4,   3,    4 } },
        { PlayerField::ModSpellPowerPct,                       { 10244,    4,   1,    0 } },
        { PlayerField::ModResiliencePct,                       { 10248,    4,   1,    0 } },
        { PlayerField::OverrideSpellPowerByApPct,              { 10252,    4,   1,    0 } },
        { PlayerField::OverrideApBySpellPowerPct,              { 10256,    4,   1,    0 } },
        { PlayerField::FieldModTargetResistance,               { 10260,    4,   1,    0 } },
        { PlayerField::FieldModTargetPhysicalResistance,       { 10264,    4,   1,    0 } },
        { PlayerField::PlayerFieldBytes,                       { 10272,    4,   1,    0 } },
        { PlayerField::PlayerFieldBytesMiscFlags,              { 10272,    1,   1,    0 } },
        { PlayerField::PlayerFieldBytesRafLevel,               { 10273,    1,   1,    0 } },
        { PlayerField::PlayerFieldBytesEnabledActionBars,      { 10274,    1,   1,    0 } },
        { PlayerField::PlayerFieldBytesMaxPvpRank,             { 10275,    1,   1,    0 } },
        { PlayerField::SelfResurrectionSpell,                  { 10276,    4,   1,    0 } },
        { PlayerField::FieldPvpMedals,                         { 10280,    4,   1,    0 } },
        { PlayerField::PlayerFieldBytes2,                      { 10280,    4,   1,    0 } },
        { PlayerField::FieldBuyBackPrice,                      { 10284,    4,  12,    4 } },
        { PlayerField::FieldBuyBackTimestamp,                  { 10332,    4,  12,    4 } },
        { PlayerField::FieldYesterdayKills,                    { 10380,    4,   1,    0 } },
        { PlayerField::FieldLifetimeHonorableKills,            { 10384,    4,   1,    0 } },
        { PlayerField::FieldWatchedFactionIdx,                 { 10388,    4,   1,    0 } },
        { PlayerField::FieldCombatRating,                      { 10392,    4,  32,    4 } },
        { PlayerField::FieldMaxLevel,                          { 10664,    4,   1,    0 } },
        { PlayerField::RuneRegen,                              { 10668,    4,   4,    4 } },
        { PlayerField::NoReagentCost,                          { 10684,    4,   4,    4 } },
        { PlayerField::FieldGlyphSlots,                        { 10700,    4,   6,    4 } },
        { PlayerField::FieldGlyphs,                            { 10724,    4,   6,    4 } },
        { PlayerField::GlyphsEnabled,                          { 10748,    4,   1,    0 } },
        { PlayerField::PetSpellPower,                          { 10752,    4,   1,    0 } },
        { PlayerField::Researching,                            { 10756,    4,  10,    4 } },
        { PlayerField::ProfessionSkillLine,                    { 10796,    4,   2,    4 } },
        { PlayerField::UiHitMod,                               { 10804,    4,   1,    0 } },
        { PlayerField::UiHitSpellMod,                          { 10808,    4,   1,    0 } },
        { PlayerField::UiHomeRealmTimeOffset,                  { 10812,    4,   1,    0 } },
        { PlayerField::ModPetHaste,                            { 10816,    4,   1,    0 } },
        { PlayerField::SummonedBattlePetGuid,                  { 10820,   16,   1,    0 } },
        { PlayerField::OverrideSpellId,                        { 10836,    4,   1,    0 } },
        { PlayerField::LfgBonusFactionId,                      { 10840,    4,   1,    0 } },
        { PlayerField::LootSpecId,                             { 10844,    4,   1,    0 } },
        { PlayerField::OverrideZonePvpType,                    { 10848,    4,   1,    0 } },
        { PlayerField::ItemLevelDelta,                         { 10852,    4,   1,    0 } },
    };

    // WoWItem: 18 fields, 328 bytes
    static const FieldEntry<ItemField> wodItemFields[] =
    {
        { ItemField::OwnerGuid,           {   48,   16,   1,    0 } },
        { ItemField::ContainerGuid,       {   64,   16,   1,    0 } },
        { ItemField::CreatorGuid,         {   80,   16,   1,    0 } },
        { ItemField::GiftCreatorGuid,     {   96,   16,   1,    0 } },
        { ItemField::StackCount,          {  112,    4,   1,    0 } },
        { ItemField::Duration,            {  116,    4,   1,    0 } },
        { ItemField::SpellCharges,        {  120,    4,   5,    4 } },
        { ItemField::Flags,               {  140,    4,   1,    0 } },
        { ItemField::Enchantment,         {  144,   12,  13,   12 } },
        { ItemField::EnchantmentId,       {  144,    4,  13,   12 } },
        { ItemField::EnchantmentDuration, {  148,    4,  13,   12 } },
        { ItemField::EnchantmentCharges,  {  152,    4,  13,   12 } },
        { ItemField::PropertySeed,        {  300,    4,   1,    0 } },
        { ItemField::RandomPropertiesId,  {  304,    4,   1,    0 } },
        { ItemField::Durability,          {  308,    4,   1,    0 } },
        { ItemField::MaxDurability,       {  312,    4,   1,    0 } },
        { ItemField::CreatePlayedTime,    {  316,    4,   1,    0 } },
        { ItemField::ModifierMask,        {  320,    4,   1,    0 } },
    };

    // WoWContainer: 2 fields, 908 bytes
    static const FieldEntry<ContainerField> wodContainerFields[] =
    {
        { ContainerField::ItemSlot,  {  328,   16,  36,   16 } },
        { ContainerField::SlotCount, {  904,    4,   1,    0 } },
    };

    // WoWGameObject: 12 fields, 132 bytes
    static const FieldEntry<GameObjectField> wodGameObjectFields[] =
    {
        { GameObjectField::ObjectFieldCreatedBy, {   48,   16,   1,    0 } },
        { GameObjectField::DisplayId,            {   64,   16,   1,    0 } },
        { GameObjectField::Flags,                {   68,    4,   1,    0 } },
        { GameObjectField::Rotation,             {   72,    4,   4,    4 } },
        { GameObjectField::FactionTemplate,      {   88,    4,   1,    0 } },
        { GameObjectField::Bytes1,               {   96,    4,   1,    0 } },
        { GameObjectField::Bytes1State,          {   96,    1,   1,    0 } },
        { GameObjectField::Bytes1Type,           {   97,    1,   1,    0 } },
        { GameObjectField::Bytes1Unk,            {   98,    1,   1,    0 } },
        { GameObjectField::Bytes1Health,         {   99,    1,   1,    0 } },
        { GameObjectField::Dynamic,              {  112,    4,   1,    0 } },
        { GameObjectField::Level,                {  120,   20,   1,    0 } },
    };

    // WoWDynamicObject: 5 fields, 80 bytes
    static const FieldEntry<DynamicObjectField> wodDynamicObjectFields[] =
    {
        { DynamicObjectField::CasterGuid,         {   48,   16,   1,    0 } },
        { DynamicObjectField::DynamicobjectBytes, {   64,   16,   1,    0 } },
        { DynamicObjectField::SpellId,            {   68,    4,   1,    0 } },
        { DynamicObjectField::Radius,             {   72,    4,   1,    0 } },
        { DynamicObjectField::CastTime,           {   76,    4,   1,    0 } },
    };

    // WoWCorpse: 16 fields, 180 bytes
    static const FieldEntry<CorpseField> wodCorpseFields[] =
    {
        { CorpseField::OwnerGuid,              {   48,   16,   1,    0 } },
        { CorpseField::PartyGuid,              {   64,   16,   1,    0 } },
        { CorpseField::DisplayId,              {   80,   16,   1,    0 } },
        { CorpseField::Item,                   {   84,    4,  19,    4 } },
        { CorpseField::CorpseBytes1,           {  160,    4,   1,    0 } },
        { CorpseField::CorpseBytes1Unk1,       {  160,    1,   1,    0 } },
        { CorpseField::CorpseBytes1Race,       {  161,    1,   1,    0 } },
        { CorpseField::CorpseBytes1Gender,     {  162,    1,   1,    0 } },
        { CorpseField::CorpseBytes1SkinColor,  {  163,    1,   1,    0 } },
        { CorpseField::CorpseBytes2,           {  164,    4,   1,    0 } },
        { CorpseField::CorpseBytes2Face,       {  164,    1,   1,    0 } },
        { CorpseField::CorpseBytes2HairStyle,  {  165,    1,   1,    0 } },
        { CorpseField::CorpseBytes2HairColor,  {  166,    1,   1,    0 } },
        { CorpseField::CorpseBytes2FacialHair, {  167,    1,   1,    0 } },
        { CorpseField::CorpseFlags,            {  168,    4,   1,    0 } },
        { CorpseField::DynamicFlags,           {  172,    4,   1,    0 } },
    };

    // WoWAreaTrigger: 5 fields, 116 bytes
    static const FieldEntry<AreaTriggerField> wodAreaTriggerFields[] =
    {
        { AreaTriggerField::CasterGuid,    {   76,   16,   1,    0 } },
        { AreaTriggerField::PosY,          {   80,   16,   1,    0 } },
        { AreaTriggerField::Duration,      {   92,    4,   1,    0 } },
        { AreaTriggerField::SpellId,       {  100,    4,   1,    0 } },
        { AreaTriggerField::SpellVisualId, {  104,    4,   1,    0 } },
    };

    const ExpansionLayoutSources wodLayouts
    {
        { wodObjectFields, static_cast<uint16_t>(std::size(wodObjectFields)), 48 },  // object
        { wodUnitFields, static_cast<uint16_t>(std::size(wodUnitFields)), 848 },  // unit
        { wodPlayerFields, static_cast<uint16_t>(std::size(wodPlayerFields)), 14404 },  // player
        { wodItemFields, static_cast<uint16_t>(std::size(wodItemFields)), 328 },  // item
        { wodContainerFields, static_cast<uint16_t>(std::size(wodContainerFields)), 908 },  // container
        { wodGameObjectFields, static_cast<uint16_t>(std::size(wodGameObjectFields)), 132 },  // gameObject
        { wodDynamicObjectFields, static_cast<uint16_t>(std::size(wodDynamicObjectFields)), 80 },  // dynamicObject
        { wodCorpseFields, static_cast<uint16_t>(std::size(wodCorpseFields)), 180 },  // corpse
        { wodAreaTriggerFields, static_cast<uint16_t>(std::size(wodAreaTriggerFields)), 116 },  // areaTrigger
    };
}
