/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

// Generated by the version table generator - do not edit by hand, regenerate instead.

#include "Version/ObjectLayout.hpp"

namespace Version::Tables
{
    static const FieldDesc tbcObjectFields[] =
    {
        {    0,   8 },  // Guid
        {    8,   4 },  // Type
        {   12,   4 },  // Entry
        {   16,   4 },  // ScaleX
        {   20,   4 },  // PaddingObject
        { kNoField, 0 },  // Data - not in this version
        { kNoField, 0 },  // FieldType - not in this version
        { kNoField, 0 },  // DynamicField - not in this version
    };

    static const FieldDesc tbcUnitFields[] =
    {
        {   24,   8 },  // CharmGuid
        {   32,   8 },  // SummonGuid
        {   40,   8 },  // CharmedByGuid
        {   48,   8 },  // SummonedByGuid
        {   56,   8 },  // CreatedByGuid
        {   64,   8 },  // TargetGuid
        {   72,   8 },  // PersuadedGuid
        {   80,   8 },  // ChannelObjectGuid
        {   88,   4 },  // Health
        {   92,   4 },  // Power1
        {   96,   4 },  // Power2
        {  100,   4 },  // Power3
        {  104,   4 },  // Power4
        {  108,   4 },  // Power5
        {  112,   4 },  // MaxHealth
        {  116,   4 },  // MaxPower1
        {  120,   4 },  // MaxPower2
        {  124,   4 },  // MaxPower3
        {  128,   4 },  // MaxPower4
        {  132,   4 },  // MaxPower5
        {  136,   4 },  // Level
        {  140,   4 },  // FactionTemplate
        {  144,   4 },  // FieldBytes0
        {  148,  12 },  // VirtualItemSlotDisplay
        {  160,  24 },  // VirtualItemInfo
        {  184,   4 },  // UnitFlags
        {  192, 224 },  // Aura
        {  416,  56 },  // AuraFlags
        {  472,  56 },  // AuraLevels
        {  528,  56 },  // AuraApplications
        {  584,   4 },  // AuraState
        {  588,  12 },  // BaseAttackTime
        {  600,   4 },  // BoundingRadius
        {  604,   4 },  // CombatReach
        {  608,   4 },  // DisplayId
        {  612,   4 },  // NativeDisplayId
        {  616,   4 },  // MountDisplayId
        {  620,   4 },  // MinimumDamage
        {  624,   4 },  // MaximumDamage
        {  628,   4 },  // MinimumOffhandDamage
        {  632,   4 },  // MaximumOffhandDamage
        {  636,   4 },  // FieldBytes1
        {  640,   4 },  // PetNumber
        {  644,   4 },  // PetNameTimestamp
        {  648,   4 },  // PetExperience
        {  652,   4 },  // PetNextLevelExperience
        {  656,   4 },  // DynamicFlags
        {  660,   4 },  // ChannelSpell
        {  664,   4 },  // ModCastSpeed
        {  668,   4 },  // CreatedBySpellId
        {  672,   4 },  // NpcFlags
        {  676,   4 },  // NpcEmoteState
        {  680,   4 },  // TrainingPoints
        {  684,  20 },  // Stat
        {  744,  28 },  // Resistance
        {  828,   4 },  // BaseMana
        {  832,   4 },  // BaseHealth
        {  836,   4 },  // FieldBytes2
        {  840,   4 },  // AttackPower
        {  844,   4 },  // AttackPowerMods
        {  848,   4 },  // AttackPowerMultiplier
        {  852,   4 },  // RangedAttackPower
        {  856,   4 },  // RangedAttackPowerMods
        {  860,   4 },  // RangedAttackPowerMultiplier
        {  864,   4 },  // MinimumRangedDamage
        {  868,   4 },  // MaximumRangedDamage
        {  872,  28 },  // PowerCostModifier
        {  900,  28 },  // PowerCostMultiplier
        {  932,   4 },  // UnitPadding
        {  188,   4 },  // UnitFlags2
        {  704,  20 },  // PositiveStat
        {  724,  20 },  // NegativeStat
        {  772,  28 },  // ResistanceBuffModPositive
        {  800,  28 },  // ResistanceBuffModNegative
        {  928,   4 },  // MaxHealthModifier
        { kNoField, 0 },  // CritterGuid - not in this version
        { kNoField, 0 },  // Power6 - not in this version
        { kNoField, 0 },  // Power7 - not in this version
        { kNoField, 0 },  // MaxPower6 - not in this version
        { kNoField, 0 },  // MaxPower7 - not in this version
        { kNoField, 0 },  // PowerRegenFlatModifier - not in this version
        { kNoField, 0 },  // PowerRegenInterruptedFlatModifier - not in this version
        { kNoField, 0 },  // HoverHeight - not in this version
        { kNoField, 0 },  // ModCastHaste - not in this version
        { kNoField, 0 },  // AttackPowerModPos - not in this version
        { kNoField, 0 },  // AttackPowerModNeg - not in this version
        { kNoField, 0 },  // RangedAttackPowerModsPos - not in this version
        { kNoField, 0 },  // RangedAttackPowerModsNeg - not in this version
        { kNoField, 0 },  // MaxItemLevel - not in this version
        { kNoField, 0 },  // DemonCreatorGuid - not in this version
        { kNoField, 0 },  // BattlePetCompanionGuid - not in this version
        { kNoField, 0 },  // SummonedByHomeRealm - not in this version
        { kNoField, 0 },  // DisplayPower - not in this version
        { kNoField, 0 },  // OverrideDisplayPowerId - not in this version
        { kNoField, 0 },  // EffectiveLevel - not in this version
        { kNoField, 0 },  // ModHaste - not in this version
        { kNoField, 0 },  // ModRangedHaste - not in this version
        { kNoField, 0 },  // ModHasteRegen - not in this version
        { kNoField, 0 },  // MinItemLevel - not in this version
        { kNoField, 0 },  // WildBattlePetLevel - not in this version
        { kNoField, 0 },  // BattlePetCompanionNameTimestamp - not in this version
        { kNoField, 0 },  // InteractSpellId - not in this version
    };

    static const FieldDesc tbcPlayerFields[] =
    {
        {  936,   8 },  // DuelArbiter
        {  944,   4 },  // PlayerFlags
        {  948,   4 },  // GuildId
        {  952,   4 },  // GuildRank
        {  956,   4 },  // PlayerBytes
        {  960,   4 },  // PlayerBytes2
        {  964,   4 },  // PlayerBytes3
        {  968,   4 },  // DuelTeam
        {  972,   4 },  // GuildTimestamp
        {  976, 400 },  // Quests
        { 1376, 1216 },  // VisibleItems
        { 2600, 184 },  // InventorySlot
        { 2784, 128 },  // PackSlot
        { 2912, 224 },  // BankSlot
        { 3136,  56 },  // BankBagSlot
        { 3192,  96 },  // VendorBuyBackSlot
        { 3288, 256 },  // KeyRingSlot
        { 3688,   8 },  // FarsightGuid
        { kNoField, 0 },  // FieldComboTarget - not in this version
        { 3704,   4 },  // Xp
        { 3708,   4 },  // NextLevelXp
        { 3712, 1536 },  // SkillInfo
        { 5248,   4 },  // CharacterPoints1
        { 5252,   4 },  // CharacterPoints2
        { 5256,   4 },  // TrackCreatures
        { 5260,   4 },  // TrackResources
        { 5264,   4 },  // BlockPct
        { 5268,   4 },  // DodgePct
        { 5272,   4 },  // ParryPct
        { 5284,   4 },  // CritPct
        { 5288,   4 },  // RangedCritPct
        { 5328, 512 },  // ExploredZones
        { 5840,   4 },  // RestStateXp
        { 5844,   4 },  // FieldCoinage
        { kNoField, 0 },  // PosStat - not in this version
        { kNoField, 0 },  // NegStat - not in this version
        { kNoField, 0 },  // ResistanceBuffModPositive - not in this version
        { kNoField, 0 },  // ResistanceBuffModNegative - not in this version
        { 5848,  28 },  // FieldModDamageDonePositive
        { 5876,  28 },  // FieldModDamageDoneNegative
        { 5904,  28 },  // FieldModDamageDonePct
        { 5944,   4 },  // PlayerFieldBytes
        { 5948,   4 },  // AmmoId
        { 5952,   4 },  // SelfResurrectionSpell
        { 5956,   4 },  // FieldPvpMedals
        { 5960,  48 },  // FieldBuyBackPrice
        { 6008,  48 },  // FieldBuyBackTimestamp
        { kNoField, 0 },  // FieldSessionKills - not in this version
        { kNoField, 0 },  // FieldYesterdayKills - not in this version
        { kNoField, 0 },  // FieldLastWeekKills - not in this version
        { kNoField, 0 },  // FieldThisWeekKills - not in this version
        { kNoField, 0 },  // FieldThisWeekContribution - not in this version
        { 6068,   4 },  // FieldLifetimeHonorableKills
        { kNoField, 0 },  // FieldLifetimeDishonorableKills - not in this version
        { kNoField, 0 },  // FieldYersterdayContribution - not in this version
        { kNoField, 0 },  // FieldLastWeekContribution - not in this version
        { kNoField, 0 },  // FieldLastWeekRank - not in this version
        { 6072,   4 },  // PlayerFieldBytes2
        { 6076,   4 },  // FieldWatchedFactionIdx
        { 6080,  96 },  // FieldCombatRating
        { 2592,   4 },  // ChosenTitle
        { 2596,   4 },  // PlayerPadding0
        { 3544, 144 },  // VanityPetSlot
        { 3696,   8 },  // FieldKnownTitles
        { 5276,   4 },  // Expertise
        { 5280,   4 },  // OffhandExpertise
        { 5292,   4 },  // OffhandCritPct
        { 5296,  28 },  // SpellCritPct
        { 5324,   4 },  // ShieldBlock
        { 5932,   4 },  // FieldModHealingDone
        { 5936,   4 },  // FieldModTargetResistance
        { 5940,   4 },  // FieldModTargetPhysicalResistance
        { 6056,   4 },  // FieldKills
        { 6060,   4 },  // FieldContributionToday
        { 6064,   4 },  // FieldContributionYesterday
        { 6176,  72 },  // FieldArenaTeamInfo
        { 6248,   4 },  // FieldHonorCurrency
        { 6252,   4 },  // FieldArenaCurrency
        { 6256,   4 },  // FieldModManaRegen
        { 6260,   4 },  // FieldModManaRegenInterrupt
        { 6264,   4 },  // FieldMaxLevel
        { 6268, 100 },  // FieldDailyQuests
        { kNoField, 0 },  // Inebriation - not in this version
        { kNoField, 0 },  // CurrencytokenSlot - not in this version
        { kNoField, 0 },  // FieldKnownCurrencies - not in this version
        { kNoField, 0 },  // ShieldBlockCritPct - not in this version
        { kNoField, 0 },  // FieldModHealingPct - not in this version
        { kNoField, 0 },  // FieldModHealingDonePct - not in this version
        { kNoField, 0 },  // RuneRegen - not in this version
        { kNoField, 0 },  // NoReagentCost - not in this version
        { kNoField, 0 },  // FieldGlyphSlots - not in this version
        { kNoField, 0 },  // FieldGlyphs - not in this version
        { kNoField, 0 },  // GlyphsEnabled - not in this version
        { kNoField, 0 },  // PetSpellPower - not in this version
        { kNoField, 0 },  // GuildDeleteDate - not in this version
        { kNoField, 0 },  // GuildLevel - not in this version
        { kNoField, 0 },  // FieldSkillInfo - not in this version
        { kNoField, 0 },  // Mastery - not in this version
        { kNoField, 0 },  // WeaponDmgMultiplier - not in this version
        { kNoField, 0 },  // ModSpellPowerPct - not in this version
        { kNoField, 0 },  // OverrideSpellPowerByApPct - not in this version
        { kNoField, 0 },  // BattlegroundRating - not in this version
        { kNoField, 0 },  // Researching - not in this version
        { kNoField, 0 },  // ResearchSite - not in this version
        { kNoField, 0 },  // ProfessionSkillLine - not in this version
        { kNoField, 0 },  // UiHitMod - not in this version
        { kNoField, 0 },  // UiHitSpellMod - not in this version
        { kNoField, 0 },  // UiHomeRealmTimeOffset - not in this version
        { kNoField, 0 },  // ModHaste - not in this version
        { kNoField, 0 },  // ModRangedHaste - not in this version
        { kNoField, 0 },  // ModPetHaste - not in this version
        { kNoField, 0 },  // ModHasteRegen - not in this version
        { kNoField, 0 },  // VirtualPlayerRealm - not in this version
        { kNoField, 0 },  // CurrentSpecId - not in this version
        { kNoField, 0 },  // TaxiMountAnimKitId - not in this version
        { kNoField, 0 },  // CurrentBattlePetBreedQuality - not in this version
        { kNoField, 0 },  // MaxTalentTiers - not in this version
        { kNoField, 0 },  // RangedExpertise - not in this version
        { kNoField, 0 },  // CombatRatingExpertise - not in this version
        { kNoField, 0 },  // PvpPowerDamage - not in this version
        { kNoField, 0 },  // PvpPowerHealing - not in this version
        { kNoField, 0 },  // FieldModPeriodicHealingDonePct - not in this version
        { kNoField, 0 },  // ModResiliencePct - not in this version
        { kNoField, 0 },  // OverrideApBySpellPowerPct - not in this version
        { kNoField, 0 },  // SummonedBattlePetGuid - not in this version
        { kNoField, 0 },  // OverrideSpellId - not in this version
        { kNoField, 0 },  // LfgBonusFactionId - not in this version
        { kNoField, 0 },  // LootSpecId - not in this version
        { kNoField, 0 },  // OverrideZonePvpType - not in this version
        { kNoField, 0 },  // ItemLevelDelta - not in this version
    };

    static const FieldDesc tbcItemFields[] =
    {
        {   24,   8 },  // OwnerGuid
        {   32,   8 },  // ContainerGuid
        {   40,   8 },  // CreatorGuid
        {   48,   8 },  // GiftCreatorGuid
        {   56,   4 },  // StackCount
        {   60,   4 },  // Duration
        {   64,  20 },  // SpellCharges
        {   84,   4 },  // Flags
        {   88, 132 },  // Enchantment
        {  220,   4 },  // PropertySeed
        {  224,   4 },  // RandomPropertiesId
        {  228,   4 },  // ItemTextId
        {  232,   4 },  // Durability
        {  236,   4 },  // MaxDurability
        { kNoField, 0 },  // CreatePlayedTime - not in this version
        { kNoField, 0 },  // ItemPadding0 - not in this version
        { kNoField, 0 },  // ModifierMask - not in this version
    };

    static const FieldDesc tbcContainerFields[] =
    {
        {  240,   4 },  // SlotCount
        {  244,   4 },  // PaddingContainer
        {  248, 288 },  // ItemSlot
        { kNoField, 0 },  // ContainerPadding0 - not in this version
    };

    static const FieldDesc tbcGameObjectFields[] =
    {
        {   24,   8 },  // ObjectFieldCreatedBy
        {   32,   4 },  // DisplayId
        {   36,   4 },  // Flags
        {   40,  16 },  // Rotation
        {   56,   4 },  // State
        {   60,   4 },  // X
        {   64,   4 },  // Y
        {   68,   4 },  // Z
        {   72,   4 },  // O
        {   76,   4 },  // Dynamic
        {   80,   4 },  // FactionTemplate
        {   84,   4 },  // Type
        {   88,   4 },  // Level
        {   92,   4 },  // ArtKit
        {   96,   4 },  // AnimationProgress
        {  100,   4 },  // GameobjectPadding
        { kNoField, 0 },  // Bytes1 - not in this version
        { kNoField, 0 },  // Bytes2 - not in this version
    };

    static const FieldDesc tbcDynamicObjectFields[] =
    {
        {   24,   8 },  // CasterGuid
        {   32,   4 },  // DynamicobjectBytes
        {   36,   4 },  // SpellId
        {   40,   4 },  // Radius
        {   44,   4 },  // X
        {   48,   4 },  // Y
        {   52,   4 },  // Z
        {   56,   4 },  // O
        { kNoField, 0 },  // Padding - not in this version
        {   60,   4 },  // CastTime
    };

    static const FieldDesc tbcCorpseFields[] =
    {
        {   24,   8 },  // OwnerGuid
        {   32,   8 },  // PartyGuid
        {   40,   4 },  // O
        {   44,   4 },  // X
        {   48,   4 },  // Y
        {   52,   4 },  // Z
        {   56,   4 },  // DisplayId
        {   60,  76 },  // Item
        {  136,   4 },  // CorpseBytes1
        {  140,   4 },  // CorpseBytes2
        {  144,   4 },  // Guild
        {  148,   4 },  // CorpseFlags
        {  152,   4 },  // DynamicFlags
        {  156,   4 },  // CorpsePadding
    };

    // WoWAreaTrigger does not exist in this client version
    static const FieldDesc tbcAreaTriggerFields[] =
    {
        { kNoField, 0 },  // SpellId - not in this version
        { kNoField, 0 },  // SpellVisualId - not in this version
        { kNoField, 0 },  // Duration - not in this version
        { kNoField, 0 },  // PosX - not in this version
        { kNoField, 0 },  // PosY - not in this version
        { kNoField, 0 },  // PosZ - not in this version
        { kNoField, 0 },  // CasterGuid - not in this version
        { kNoField, 0 },  // Scale - not in this version
    };

    const ExpansionLayouts tbcLayouts
    {
        { tbcObjectFields, static_cast<uint16_t>(std::size(tbcObjectFields)), 24 },  // object
        { tbcUnitFields, static_cast<uint16_t>(std::size(tbcUnitFields)), 936 },  // unit
        { tbcPlayerFields, static_cast<uint16_t>(std::size(tbcPlayerFields)), 6368 },  // player
        { tbcItemFields, static_cast<uint16_t>(std::size(tbcItemFields)), 240 },  // item
        { tbcContainerFields, static_cast<uint16_t>(std::size(tbcContainerFields)), 536 },  // container
        { tbcGameObjectFields, static_cast<uint16_t>(std::size(tbcGameObjectFields)), 104 },  // gameObject
        { tbcDynamicObjectFields, static_cast<uint16_t>(std::size(tbcDynamicObjectFields)), 64 },  // dynamicObject
        { tbcCorpseFields, static_cast<uint16_t>(std::size(tbcCorpseFields)), 160 },  // corpse
        { tbcAreaTriggerFields, static_cast<uint16_t>(std::size(tbcAreaTriggerFields)), 0 },  // areaTrigger
    };
}
