/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

// Layout of the object values for Legion clients: byte offset, size, element count and element stride of every field.

#include "Version/ObjectLayout.hpp"

#include <iterator>

namespace Version::Tables
{
    // WoWObject: 11 fields, 48 bytes
    static const FieldEntry<ObjectField> legionObjectFields[] =
    {
        { ObjectField::Guid,                     {    0,   16,   1,    0 } },
        { ObjectField::Data,                     {   16,   16,   1,    0 } },
        { ObjectField::FieldType,                {   32,    4,   1,    0 } },
        { ObjectField::Type,                     {   32,    4,   1,    0 } },
        { ObjectField::FieldTypeType,            {   32,    2,   1,    0 } },
        { ObjectField::FieldTypeGuildId,         {   34,    2,   1,    0 } },
        { ObjectField::Entry,                    {   36,    4,   1,    0 } },
        { ObjectField::DynamicField,             {   40,    4,   1,    0 } },
        { ObjectField::DynamicFieldDynamicFlags, {   40,    2,   1,    0 } },
        { ObjectField::DynamicFieldPathProgress, {   42,    2,   1,    0 } },
        { ObjectField::ScaleX,                   {   44,    4,   1,    0 } },
    };

    // WoWUnit: 101 fields, 852 bytes
    static const FieldEntry<UnitField> legionUnitFields[] =
    {
        { UnitField::CharmGuid,                         {   48,   16,   1,    0 } },
        { UnitField::SummonGuid,                        {   64,   16,   1,    0 } },
        { UnitField::CritterGuid,                       {   80,   16,   1,    0 } },
        { UnitField::CharmedByGuid,                     {   96,   16,   1,    0 } },
        { UnitField::SummonedByGuid,                    {  112,   16,   1,    0 } },
        { UnitField::CreatedByGuid,                     {  128,   16,   1,    0 } },
        { UnitField::DemonCreatorGuid,                  {  144,   16,   1,    0 } },
        { UnitField::TargetGuid,                        {  160,   16,   1,    0 } },
        { UnitField::MaxHealth,                         {  160,    4,   1,    0 } },
        { UnitField::MaxPower1,                         {  164,    4,   1,    0 } },
        { UnitField::MaxPower2,                         {  168,    4,   1,    0 } },
        { UnitField::BattlePetCompanionGuid,            {  176,   16,   1,    0 } },
        { UnitField::ChannelSpell,                      {  200,    4,   1,    0 } },
        { UnitField::SummonedByHomeRealm,               {  208,    4,   1,    0 } },
        { UnitField::FieldBytes0,                       {  212,    4,   1,    0 } },
        { UnitField::FieldBytes0Race,                   {  212,    1,   1,    0 } },
        { UnitField::FieldBytes0UnitClass,              {  213,    1,   1,    0 } },
        { UnitField::FieldBytes0ClassSpec,              {  214,    1,   1,    0 } },
        { UnitField::FieldBytes0Gender,                 {  215,    1,   1,    0 } },
        { UnitField::DisplayPower,                      {  216,    4,   1,    0 } },
        { UnitField::OverrideDisplayPowerId,            {  220,    4,   1,    0 } },
        { UnitField::Health,                            {  224,    8,   1,    0 } },
        { UnitField::Power1,                            {  232,    4,   1,    0 } },
        { UnitField::Power2,                            {  236,    4,   1,    0 } },
        { UnitField::Power3,                            {  240,    4,   1,    0 } },
        { UnitField::Power4,                            {  244,    4,   1,    0 } },
        { UnitField::Power5,                            {  248,    4,   1,    0 } },
        { UnitField::Power6,                            {  252,    4,   1,    0 } },
        { UnitField::MaxPower3,                         {  272,    4,   1,    0 } },
        { UnitField::MaxPower4,                         {  276,    4,   1,    0 } },
        { UnitField::MaxPower5,                         {  280,    4,   1,    0 } },
        { UnitField::MaxPower6,                         {  284,    4,   1,    0 } },
        { UnitField::PowerRegenFlatModifier,            {  288,    4,   6,    4 } },
        { UnitField::PetNumber,                         {  300,    4,   1,    0 } },
        { UnitField::PetNameTimestamp,                  {  304,    4,   1,    0 } },
        { UnitField::PetExperience,                     {  308,    4,   1,    0 } },
        { UnitField::PowerRegenInterruptedFlatModifier, {  312,    4,   6,    4 } },
        { UnitField::DynamicFlags,                      {  316,    4,   1,    0 } },
        { UnitField::Level,                             {  336,    4,   1,    0 } },
        { UnitField::EffectiveLevel,                    {  340,    4,   1,    0 } },
        { UnitField::FactionTemplate,                   {  360,    4,   1,    0 } },
        { UnitField::VirtualItemSlotDisplay,            {  364,    4,   6,    4 } },
        { UnitField::UnitFlags,                         {  388,    4,   1,    0 } },
        { UnitField::UnitFlags2,                        {  392,    4,   1,    0 } },
        { UnitField::AuraState,                         {  400,    4,   1,    0 } },
        { UnitField::BaseAttackTime,                    {  404,    4,   2,    4 } },
        { UnitField::BoundingRadius,                    {  416,    4,   1,    0 } },
        { UnitField::CombatReach,                       {  420,    4,   1,    0 } },
        { UnitField::DisplayId,                         {  424,    4,   1,    0 } },
        { UnitField::NativeDisplayId,                   {  428,    4,   1,    0 } },
        { UnitField::MountDisplayId,                    {  432,    4,   1,    0 } },
        { UnitField::MinimumDamage,                     {  436,    4,   1,    0 } },
        { UnitField::MaximumDamage,                     {  440,    4,   1,    0 } },
        { UnitField::MinimumOffhandDamage,              {  444,    4,   1,    0 } },
        { UnitField::MaximumOffhandDamage,              {  448,    4,   1,    0 } },
        { UnitField::FieldBytes1,                       {  452,    4,   1,    0 } },
        { UnitField::FieldBytes1StandState,             {  452,    1,   1,    0 } },
        { UnitField::FieldBytes1Unk1,                   {  453,    1,   1,    0 } },
        { UnitField::FieldBytes1StandStateFlag,         {  454,    1,   1,    0 } },
        { UnitField::FieldBytes1AnimationFlag,          {  455,    1,   1,    0 } },
        { UnitField::PetNextLevelExperience,            {  468,    4,   1,    0 } },
        { UnitField::ModCastSpeed,                      {  472,    4,   1,    0 } },
        { UnitField::ModCastHaste,                      {  476,    4,   1,    0 } },
        { UnitField::ModHaste,                          {  480,    4,   1,    0 } },
        { UnitField::ModRangedHaste,                    {  484,    4,   1,    0 } },
        { UnitField::ModHasteRegen,                     {  488,    4,   1,    0 } },
        { UnitField::CreatedBySpellId,                  {  496,    4,   1,    0 } },
        { UnitField::NpcFlags,                          {  500,    8,   1,    0 } },
        { UnitField::NpcEmoteState,                     {  508,    4,   1,    0 } },
        { UnitField::Stat,                              {  512,    4,   4,    4 } },
        { UnitField::PositiveStat,                      {  528,    4,   4,    4 } },
        { UnitField::NegativeStat,                      {  544,    4,   4,    4 } },
        { UnitField::Resistance,                        {  560,    4,   7,    4 } },
        { UnitField::ResistanceBuffModPositive,         {  588,    4,   7,    4 } },
        { UnitField::ResistanceBuffModNegative,         {  616,    4,   7,    4 } },
        { UnitField::BaseMana,                          {  648,    4,   1,    0 } },
        { UnitField::BaseHealth,                        {  652,    4,   1,    0 } },
        { UnitField::FieldBytes2,                       {  656,    4,   1,    0 } },
        { UnitField::FieldBytes2SheathType,             {  656,    1,   1,    0 } },
        { UnitField::FieldBytes2PvpFlag,                {  657,    1,   1,    0 } },
        { UnitField::FieldBytes2PetFlag,                {  658,    1,   1,    0 } },
        { UnitField::FieldBytes2ShapeShiftForm,         {  659,    1,   1,    0 } },
        { UnitField::AttackPower,                       {  660,    4,   1,    0 } },
        { UnitField::AttackPowerModPos,                 {  664,    4,   1,    0 } },
        { UnitField::AttackPowerModNeg,                 {  668,    4,   1,    0 } },
        { UnitField::AttackPowerMultiplier,             {  672,    4,   1,    0 } },
        { UnitField::RangedAttackPower,                 {  676,    4,   1,    0 } },
        { UnitField::RangedAttackPowerModsPos,          {  680,    4,   1,    0 } },
        { UnitField::RangedAttackPowerModsNeg,          {  684,    4,   1,    0 } },
        { UnitField::RangedAttackPowerMultiplier,       {  688,    4,   1,    0 } },
        { UnitField::MinimumRangedDamage,               {  696,    4,   1,    0 } },
        { UnitField::MaximumRangedDamage,               {  700,    4,   1,    0 } },
        { UnitField::PowerCostModifier,                 {  704,    4,   7,    4 } },
        { UnitField::PowerCostMultiplier,               {  732,    4,   7,    4 } },
        { UnitField::MaxHealthModifier,                 {  760,    4,   1,    0 } },
        { UnitField::HoverHeight,                       {  764,    4,   1,    0 } },
        { UnitField::MinItemLevel,                      {  772,    4,   1,    0 } },
        { UnitField::MaxItemLevel,                      {  776,    4,   1,    0 } },
        { UnitField::WildBattlePetLevel,                {  780,    4,   1,    0 } },
        { UnitField::BattlePetCompanionNameTimestamp,   {  784,    4,   1,    0 } },
        { UnitField::InteractSpellId,                   {  788,    4,   1,    0 } },
    };

    // WoWPlayer: 125 fields, 18500 bytes
    static const FieldEntry<PlayerField> legionPlayerFields[] =
    {
        { PlayerField::DuelArbiter,                            {  852,   16,   1,    0 } },
        { PlayerField::PlayerFlags,                            {  900,    4,   1,    0 } },
        { PlayerField::GuildRank,                              {  908,    4,   1,    0 } },
        { PlayerField::GuildDeleteDate,                        {  912,    4,   1,    0 } },
        { PlayerField::GuildLevel,                             {  916,    4,   1,    0 } },
        { PlayerField::PlayerBytes,                            {  920,    4,   1,    0 } },
        { PlayerField::PlayerBytesSkinColor,                   {  920,    1,   1,    0 } },
        { PlayerField::PlayerBytesFace,                        {  921,    1,   1,    0 } },
        { PlayerField::PlayerBytesHairStyle,                   {  922,    1,   1,    0 } },
        { PlayerField::PlayerBytesHornStyle,                   {  922,    1,   1,    0 } },
        { PlayerField::PlayerBytesHairColor,                   {  923,    1,   1,    0 } },
        { PlayerField::PlayerBytesHornColor,                   {  923,    1,   1,    0 } },
        { PlayerField::PlayerBytes2,                           {  924,    4,   1,    0 } },
        { PlayerField::PlayerBytes2Earrings,                   {  924,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Ears,                       {  924,    1,   1,    0 } },
        { PlayerField::PlayerBytes2FacialHair,                 {  924,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Features,                   {  924,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Hair,                       {  924,    1,   1,    0 } },
        { PlayerField::PlayerBytes2HornStyle,                  {  924,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Markings,                   {  924,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Piercings,                  {  924,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Tusks,                      {  924,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Unk1,                       {  925,    1,   1,    0 } },
        { PlayerField::PlayerBytes2BankSlots,                  {  926,    1,   1,    0 } },
        { PlayerField::PlayerBytes2RestState,                  {  927,    1,   1,    0 } },
        { PlayerField::PlayerBytes3,                           {  932,    4,   1,    0 } },
        { PlayerField::PlayerBytes3Gender,                     {  932,    1,   1,    0 } },
        { PlayerField::PlayerBytes3DrunkValue,                 {  933,    1,   1,    0 } },
        { PlayerField::PlayerBytes3PvpRank,                    {  934,    1,   1,    0 } },
        { PlayerField::PlayerBytes3ArenaFaction,               {  935,    1,   1,    0 } },
        { PlayerField::DuelTeam,                               {  936,    4,   1,    0 } },
        { PlayerField::GuildTimestamp,                         {  940,    4,   1,    0 } },
        { PlayerField::VisibleItems,                           { 4144,    8,  19,    8 } },
        { PlayerField::VisibleItemsEntry,                      { 4144,    4,  19,    8 } },
        { PlayerField::VisibleItemsEnchantment,                { 4148,    4,  19,    8 } },
        { PlayerField::VisibleItemsEnchantmentPermEnchantment, { 4148,    2,  19,    8 } },
        { PlayerField::VisibleItemsEnchantmentTempEnchantment, { 4150,    2,  19,    8 } },
        { PlayerField::ChosenTitle,                            { 4296,    4,   1,    0 } },
        { PlayerField::Inebriation,                            { 4300,    4,   1,    0 } },
        { PlayerField::VirtualPlayerRealm,                     { 4304,    4,   1,    0 } },
        { PlayerField::CurrentSpecId,                          { 4308,    4,   1,    0 } },
        { PlayerField::TaxiMountAnimKitId,                     { 4312,    4,   1,    0 } },
        { PlayerField::CurrentBattlePetBreedQuality,           { 4332,    4,   1,    0 } },
        { PlayerField::InventorySlot,                          { 4344,   16,  23,   16 } },
        { PlayerField::PackSlot,                               { 4712,   16,  16,   16 } },
        { PlayerField::BankSlot,                               { 4968,   16,  28,   16 } },
        { PlayerField::BankBagSlot,                            { 5416,   16,   7,   16 } },
        { PlayerField::VendorBuyBackSlot,                      { 5528,   16,  12,   16 } },
        { PlayerField::FarsightGuid,                           { 7464,   16,   1,    0 } },
        { PlayerField::SummonedBattlePetGuid,                  { 7480,   16,   1,    0 } },
        { PlayerField::FieldKnownTitles,                       { 7496,    8,   6,    8 } },
        { PlayerField::FieldCoinage,                           { 7544,    8,   1,    0 } },
        { PlayerField::Xp,                                     { 7552,    4,   1,    0 } },
        { PlayerField::NextLevelXp,                            { 7556,    4,   1,    0 } },
        { PlayerField::FieldSkillInfo,                         { 7564, 1792,   1,    0 } },
        { PlayerField::FieldSkillInfoSkillId,                  { 7564,    4, 448,    4 } },
        { PlayerField::FieldSkillInfoSkillLine,                { 7564,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillStep,                { 7820,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillRank,                { 8076,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillStartingRank,        { 8332,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillMaxRank,             { 8588,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillMod,                 { 8844,    4,  64,    4 } },
        { PlayerField::FieldSkillInfoSkillTalent,              { 9100,    4,  64,    4 } },
        { PlayerField::CharacterPoints1,                       { 9356,    4,   1,    0 } },
        { PlayerField::MaxTalentTiers,                         { 9360,    4,   1,    0 } },
        { PlayerField::TrackCreatures,                         { 9364,    4,   1,    0 } },
        { PlayerField::TrackResources,                         { 9368,    4,   1,    0 } },
        { PlayerField::Expertise,                              { 9372,    4,   1,    0 } },
        { PlayerField::OffhandExpertise,                       { 9376,    4,   1,    0 } },
        { PlayerField::RangedExpertise,                        { 9380,    4,   1,    0 } },
        { PlayerField::CombatRatingExpertise,                  { 9384,    4,   1,    0 } },
        { PlayerField::BlockPct,                               { 9388,    4,   1,    0 } },
        { PlayerField::DodgePct,                               { 9392,    4,   1,    0 } },
        { PlayerField::ParryPct,                               { 9400,    4,   1,    0 } },
        { PlayerField::CritPct,                                { 9408,    4,   1,    0 } },
        { PlayerField::RangedCritPct,                          { 9412,    4,   1,    0 } },
        { PlayerField::OffhandCritPct,                         { 9416,    4,   1,    0 } },
        { PlayerField::SpellCritPct,                           { 9420,    4,   1,    4 } },
        { PlayerField::ShieldBlock,                            { 9424,    4,   1,    0 } },
        { PlayerField::ShieldBlockCritPct,                     { 9428,    4,   1,    0 } },
        { PlayerField::Mastery,                                { 9432,    4,   1,    0 } },
        { PlayerField::PvpPowerDamage,                         { 9460,    4,   1,    0 } },
        { PlayerField::PvpPowerHealing,                        { 9464,    4,   1,    0 } },
        { PlayerField::ExploredZones,                          { 9468,    4, 320,    4 } },
        { PlayerField::RestStateXp,                            { 10748,   16,   1,    0 } },
        { PlayerField::FieldModDamageDonePositive,             { 10764,    4,   7,    4 } },
        { PlayerField::FieldModDamageDoneNegative,             { 10792,    4,   7,    4 } },
        { PlayerField::FieldModDamageDonePct,                  { 10820,    4,   7,    4 } },
        { PlayerField::FieldModHealingDone,                    { 10848,    4,   1,    0 } },
        { PlayerField::FieldModHealingPct,                     { 10852,    4,   1,    0 } },
        { PlayerField::FieldModHealingDonePct,                 { 10856,    4,   1,    0 } },
        { PlayerField::FieldModPeriodicHealingDonePct,         { 10860,    4,   1,    0 } },
        { PlayerField::WeaponDmgMultiplier,                    { 10864,    4,   3,    4 } },
        { PlayerField::ModSpellPowerPct,                       { 10888,    4,   1,    0 } },
        { PlayerField::ModResiliencePct,                       { 10892,    4,   1,    0 } },
        { PlayerField::OverrideSpellPowerByApPct,              { 10896,    4,   1,    0 } },
        { PlayerField::OverrideApBySpellPowerPct,              { 10900,    4,   1,    0 } },
        { PlayerField::FieldModTargetResistance,               { 10904,    4,   1,    0 } },
        { PlayerField::FieldModTargetPhysicalResistance,       { 10908,    4,   1,    0 } },
        { PlayerField::PlayerFieldBytes,                       { 10916,    4,   1,    0 } },
        { PlayerField::PlayerFieldBytesMiscFlags,              { 10916,    1,   1,    0 } },
        { PlayerField::PlayerFieldBytesRafLevel,               { 10917,    1,   1,    0 } },
        { PlayerField::PlayerFieldBytesEnabledActionBars,      { 10918,    1,   1,    0 } },
        { PlayerField::PlayerFieldBytesMaxPvpRank,             { 10919,    1,   1,    0 } },
        { PlayerField::FieldPvpMedals,                         { 10920,    4,   1,    0 } },
        { PlayerField::PlayerFieldBytes2,                      { 10920,    4,   1,    0 } },
        { PlayerField::FieldBuyBackPrice,                      { 10924,    4,  12,    4 } },
        { PlayerField::FieldBuyBackTimestamp,                  { 10972,    4,  12,    4 } },
        { PlayerField::FieldYesterdayKills,                    { 11020,    4,   1,    0 } },
        { PlayerField::FieldLifetimeHonorableKills,            { 11024,    4,   1,    0 } },
        { PlayerField::FieldWatchedFactionIdx,                 { 11028,    4,   1,    0 } },
        { PlayerField::FieldCombatRating,                      { 11032,    4,  32,    4 } },
        { PlayerField::FieldMaxLevel,                          { 11328,    4,   1,    0 } },
        { PlayerField::NoReagentCost,                          { 11340,    4,   4,    4 } },
        { PlayerField::PetSpellPower,                          { 11356,    4,   1,    0 } },
        { PlayerField::Researching,                            { 11360,    4,  10,    4 } },
        { PlayerField::ProfessionSkillLine,                    { 11400,    4,   2,    4 } },
        { PlayerField::UiHitMod,                               { 11408,    4,   1,    0 } },
        { PlayerField::UiHitSpellMod,                          { 11412,    4,   1,    0 } },
        { PlayerField::UiHomeRealmTimeOffset,                  { 11416,    4,   1,    0 } },
        { PlayerField::ModPetHaste,                            { 11420,    4,   1,    0 } },
        { PlayerField::OverrideSpellId,                        { 11428,    4,   1,    0 } },
        { PlayerField::LfgBonusFactionId,                      { 11432,    4,   1,    0 } },
        { PlayerField::LootSpecId,                             { 11436,    4,   1,    0 } },
        { PlayerField::OverrideZonePvpType,                    { 11440,    4,   1,    0 } },
    };

    // WoWItem: 18 fields, 340 bytes
    static const FieldEntry<ItemField> legionItemFields[] =
    {
        { ItemField::OwnerGuid,           {   48,   16,   1,    0 } },
        { ItemField::ContainerGuid,       {   64,   16,   1,    0 } },
        { ItemField::CreatorGuid,         {   80,   16,   1,    0 } },
        { ItemField::GiftCreatorGuid,     {   96,   16,   1,    0 } },
        { ItemField::StackCount,          {  112,    4,   1,    0 } },
        { ItemField::Duration,            {  116,    4,   1,    0 } },
        { ItemField::SpellCharges,        {  120,    4,   5,    4 } },
        { ItemField::Flags,               {  140,    4,   1,    0 } },
        { ItemField::Enchantment,         {  144,   12,  13,   12 } },
        { ItemField::EnchantmentId,       {  144,    4,  13,   12 } },
        { ItemField::EnchantmentDuration, {  148,    4,  13,   12 } },
        { ItemField::EnchantmentCharges,  {  152,    4,  13,   12 } },
        { ItemField::PropertySeed,        {  300,    4,   1,    0 } },
        { ItemField::RandomPropertiesId,  {  304,    4,   1,    0 } },
        { ItemField::Durability,          {  308,    4,   1,    0 } },
        { ItemField::MaxDurability,       {  312,    4,   1,    0 } },
        { ItemField::CreatePlayedTime,    {  316,    4,   1,    0 } },
        { ItemField::ModifierMask,        {  320,    4,   1,    0 } },
    };

    // WoWContainer: 2 fields, 920 bytes
    static const FieldEntry<ContainerField> legionContainerFields[] =
    {
        { ContainerField::ItemSlot,  {  340,   16,  36,   16 } },
        { ContainerField::SlotCount, {  916,    4,   1,    0 } },
    };

    // WoWGameObject: 12 fields, 132 bytes
    static const FieldEntry<GameObjectField> legionGameObjectFields[] =
    {
        { GameObjectField::ObjectFieldCreatedBy, {   48,   16,   1,    0 } },
        { GameObjectField::DisplayId,            {   64,   16,   1,    0 } },
        { GameObjectField::Flags,                {   68,    4,   1,    0 } },
        { GameObjectField::Rotation,             {   72,    4,   4,    4 } },
        { GameObjectField::FactionTemplate,      {   88,    4,   1,    0 } },
        { GameObjectField::Bytes1,               {   96,    4,   1,    0 } },
        { GameObjectField::Bytes1State,          {   96,    1,   1,    0 } },
        { GameObjectField::Bytes1Type,           {   97,    1,   1,    0 } },
        { GameObjectField::Bytes1Unk,            {   98,    1,   1,    0 } },
        { GameObjectField::Bytes1Health,         {   99,    1,   1,    0 } },
        { GameObjectField::Dynamic,              {  112,    4,   1,    0 } },
        { GameObjectField::Level,                {  120,   20,   1,    0 } },
    };

    // WoWDynamicObject: 6 fields, 84 bytes
    static const FieldEntry<DynamicObjectField> legionDynamicObjectFields[] =
    {
        { DynamicObjectField::CasterGuid,            {   48,   16,   1,    0 } },
        { DynamicObjectField::DynamicobjectBytes,    {   64,    4,   1,    0 } },
        { DynamicObjectField::DynamicobjectBytesRaw, {   64,    4,   1,    0 } },
        { DynamicObjectField::SpellId,               {   72,    4,   1,    0 } },
        { DynamicObjectField::Radius,                {   76,    4,   1,    0 } },
        { DynamicObjectField::CastTime,              {   80,    4,   1,    0 } },
    };

    // WoWCorpse: 16 fields, 184 bytes
    static const FieldEntry<CorpseField> legionCorpseFields[] =
    {
        { CorpseField::OwnerGuid,              {   48,   16,   1,    0 } },
        { CorpseField::PartyGuid,              {   64,   16,   1,    0 } },
        { CorpseField::DisplayId,              {   80,   16,   1,    0 } },
        { CorpseField::Item,                   {   84,    4,  19,    4 } },
        { CorpseField::CorpseBytes1,           {  160,    4,   1,    0 } },
        { CorpseField::CorpseBytes1Unk1,       {  160,    1,   1,    0 } },
        { CorpseField::CorpseBytes1Race,       {  161,    1,   1,    0 } },
        { CorpseField::CorpseBytes1Gender,     {  162,    1,   1,    0 } },
        { CorpseField::CorpseBytes1SkinColor,  {  163,    1,   1,    0 } },
        { CorpseField::CorpseBytes2,           {  164,    4,   1,    0 } },
        { CorpseField::CorpseBytes2Face,       {  164,    1,   1,    0 } },
        { CorpseField::CorpseBytes2HairStyle,  {  165,    1,   1,    0 } },
        { CorpseField::CorpseBytes2HairColor,  {  166,    1,   1,    0 } },
        { CorpseField::CorpseBytes2FacialHair, {  167,    1,   1,    0 } },
        { CorpseField::CorpseFlags,            {  168,    4,   1,    0 } },
        { CorpseField::DynamicFlags,           {  172,    4,   1,    0 } },
    };

    // WoWAreaTrigger: 4 fields, 172 bytes
    static const FieldEntry<AreaTriggerField> legionAreaTriggerFields[] =
    {
        { AreaTriggerField::PosY,       {   80,   16,   1,    0 } },
        { AreaTriggerField::CasterGuid, {  104,   16,   1,    0 } },
        { AreaTriggerField::Duration,   {  120,    4,   1,    0 } },
        { AreaTriggerField::SpellId,    {  136,    4,   1,    0 } },
    };

    const ExpansionLayoutSources legionLayouts
    {
        { legionObjectFields, static_cast<uint16_t>(std::size(legionObjectFields)), 48 },  // object
        { legionUnitFields, static_cast<uint16_t>(std::size(legionUnitFields)), 852 },  // unit
        { legionPlayerFields, static_cast<uint16_t>(std::size(legionPlayerFields)), 18500 },  // player
        { legionItemFields, static_cast<uint16_t>(std::size(legionItemFields)), 340 },  // item
        { legionContainerFields, static_cast<uint16_t>(std::size(legionContainerFields)), 920 },  // container
        { legionGameObjectFields, static_cast<uint16_t>(std::size(legionGameObjectFields)), 132 },  // gameObject
        { legionDynamicObjectFields, static_cast<uint16_t>(std::size(legionDynamicObjectFields)), 84 },  // dynamicObject
        { legionCorpseFields, static_cast<uint16_t>(std::size(legionCorpseFields)), 184 },  // corpse
        { legionAreaTriggerFields, static_cast<uint16_t>(std::size(legionAreaTriggerFields)), 172 },  // areaTrigger
    };
}
