/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

// Layout of the object values for WotLK clients: byte offset, size, element count and element stride of every field.

#include "Version/ObjectLayout.hpp"

#include <iterator>

namespace Version::Tables
{
    // WoWObject: 7 fields, 24 bytes
    static const FieldEntry<ObjectField> wotlkObjectFields[] =
    {
        { ObjectField::Guid,          {    0,    8,   1,    0 } },
        { ObjectField::GuidLow,       {    0,    4,   1,    0 } },
        { ObjectField::GuidHigh,      {    4,    4,   1,    0 } },
        { ObjectField::Type,          {    8,    4,   1,    0 } },
        { ObjectField::Entry,         {   12,    4,   1,    0 } },
        { ObjectField::ScaleX,        {   16,    4,   1,    0 } },
        { ObjectField::PaddingObject, {   20,    4,   1,    0 } },
    };

    // WoWUnit: 104 fields, 592 bytes
    static const FieldEntry<UnitField> wotlkUnitFields[] =
    {
        { UnitField::CharmGuid,                         {   24,    8,   1,    0 } },
        { UnitField::CharmGuidLow,                      {   24,    4,   1,    0 } },
        { UnitField::CharmGuidHigh,                     {   28,    4,   1,    0 } },
        { UnitField::SummonGuid,                        {   32,    8,   1,    0 } },
        { UnitField::SummonGuidLow,                     {   32,    4,   1,    0 } },
        { UnitField::SummonGuidHigh,                    {   36,    4,   1,    0 } },
        { UnitField::CritterGuid,                       {   40,    8,   1,    0 } },
        { UnitField::CritterGuidLow,                    {   40,    4,   1,    0 } },
        { UnitField::CritterGuidHigh,                   {   44,    4,   1,    0 } },
        { UnitField::CharmedByGuid,                     {   48,    8,   1,    0 } },
        { UnitField::CharmedByGuidLow,                  {   48,    4,   1,    0 } },
        { UnitField::CharmedByGuidHigh,                 {   52,    4,   1,    0 } },
        { UnitField::SummonedByGuid,                    {   56,    8,   1,    0 } },
        { UnitField::SummonedByGuidLow,                 {   56,    4,   1,    0 } },
        { UnitField::SummonedByGuidHigh,                {   60,    4,   1,    0 } },
        { UnitField::CreatedByGuid,                     {   64,    8,   1,    0 } },
        { UnitField::CreatedByGuidLow,                  {   64,    4,   1,    0 } },
        { UnitField::CreatedByGuidHigh,                 {   68,    4,   1,    0 } },
        { UnitField::TargetGuid,                        {   72,    8,   1,    0 } },
        { UnitField::TargetGuidLow,                     {   72,    4,   1,    0 } },
        { UnitField::TargetGuidHigh,                    {   76,    4,   1,    0 } },
        { UnitField::ChannelObjectGuid,                 {   80,    8,   1,    0 } },
        { UnitField::ChannelObjectGuidLow,              {   80,    4,   1,    0 } },
        { UnitField::ChannelObjectGuidHigh,             {   84,    4,   1,    0 } },
        { UnitField::ChannelSpell,                      {   88,    4,   1,    0 } },
        { UnitField::FieldBytes0,                       {   92,    4,   1,    0 } },
        { UnitField::FieldBytes0Race,                   {   92,    1,   1,    0 } },
        { UnitField::FieldBytes0UnitClass,              {   93,    1,   1,    0 } },
        { UnitField::FieldBytes0Gender,                 {   94,    1,   1,    0 } },
        { UnitField::FieldBytes0PowerType,              {   95,    1,   1,    0 } },
        { UnitField::Health,                            {   96,    4,   1,    0 } },
        { UnitField::Power1,                            {  100,    4,   1,    0 } },
        { UnitField::Power2,                            {  104,    4,   1,    0 } },
        { UnitField::Power3,                            {  108,    4,   1,    0 } },
        { UnitField::Power4,                            {  112,    4,   1,    0 } },
        { UnitField::Power5,                            {  116,    4,   1,    0 } },
        { UnitField::Power6,                            {  120,    4,   1,    0 } },
        { UnitField::Power7,                            {  124,    4,   1,    0 } },
        { UnitField::MaxHealth,                         {  128,    4,   1,    0 } },
        { UnitField::MaxPower1,                         {  132,    4,   1,    0 } },
        { UnitField::MaxPower2,                         {  136,    4,   1,    0 } },
        { UnitField::MaxPower3,                         {  140,    4,   1,    0 } },
        { UnitField::MaxPower4,                         {  144,    4,   1,    0 } },
        { UnitField::MaxPower5,                         {  148,    4,   1,    0 } },
        { UnitField::MaxPower6,                         {  152,    4,   1,    0 } },
        { UnitField::MaxPower7,                         {  156,    4,   1,    0 } },
        { UnitField::PowerRegenFlatModifier,            {  160,    4,   7,    4 } },
        { UnitField::PowerRegenInterruptedFlatModifier, {  188,    4,   7,    4 } },
        { UnitField::Level,                             {  216,    4,   1,    0 } },
        { UnitField::FactionTemplate,                   {  220,    4,   1,    0 } },
        { UnitField::VirtualItemSlotDisplay,            {  224,    4,   3,    4 } },
        { UnitField::UnitFlags,                         {  236,    4,   1,    0 } },
        { UnitField::UnitFlags2,                        {  240,    4,   1,    0 } },
        { UnitField::AuraState,                         {  244,    4,   1,    0 } },
        { UnitField::BaseAttackTime,                    {  248,    4,   3,    4 } },
        { UnitField::BoundingRadius,                    {  260,    4,   1,    0 } },
        { UnitField::CombatReach,                       {  264,    4,   1,    0 } },
        { UnitField::DisplayId,                         {  268,    4,   1,    0 } },
        { UnitField::NativeDisplayId,                   {  272,    4,   1,    0 } },
        { UnitField::MountDisplayId,                    {  276,    4,   1,    0 } },
        { UnitField::MinimumDamage,                     {  280,    4,   1,    0 } },
        { UnitField::MaximumDamage,                     {  284,    4,   1,    0 } },
        { UnitField::MinimumOffhandDamage,              {  288,    4,   1,    0 } },
        { UnitField::MaximumOffhandDamage,              {  292,    4,   1,    0 } },
        { UnitField::FieldBytes1,                       {  296,    4,   1,    0 } },
        { UnitField::FieldBytes1StandState,             {  296,    1,   1,    0 } },
        { UnitField::FieldBytes1PetTalentPoints,        {  297,    1,   1,    0 } },
        { UnitField::FieldBytes1StandStateFlag,         {  298,    1,   1,    0 } },
        { UnitField::FieldBytes1AnimationFlag,          {  299,    1,   1,    0 } },
        { UnitField::PetNumber,                         {  300,    4,   1,    0 } },
        { UnitField::PetNameTimestamp,                  {  304,    4,   1,    0 } },
        { UnitField::PetExperience,                     {  308,    4,   1,    0 } },
        { UnitField::PetNextLevelExperience,            {  312,    4,   1,    0 } },
        { UnitField::DynamicFlags,                      {  316,    4,   1,    0 } },
        { UnitField::ModCastSpeed,                      {  320,    4,   1,    0 } },
        { UnitField::CreatedBySpellId,                  {  324,    4,   1,    0 } },
        { UnitField::NpcFlags,                          {  328,    4,   1,    0 } },
        { UnitField::NpcEmoteState,                     {  332,    4,   1,    0 } },
        { UnitField::Stat,                              {  336,    4,   5,    4 } },
        { UnitField::PositiveStat,                      {  356,    4,   5,    4 } },
        { UnitField::NegativeStat,                      {  376,    4,   5,    4 } },
        { UnitField::Resistance,                        {  396,    4,   7,    4 } },
        { UnitField::ResistanceBuffModPositive,         {  424,    4,   7,    4 } },
        { UnitField::ResistanceBuffModNegative,         {  452,    4,   7,    4 } },
        { UnitField::BaseMana,                          {  480,    4,   1,    0 } },
        { UnitField::BaseHealth,                        {  484,    4,   1,    0 } },
        { UnitField::FieldBytes2,                       {  488,    4,   1,    0 } },
        { UnitField::FieldBytes2SheathType,             {  488,    1,   1,    0 } },
        { UnitField::FieldBytes2PvpFlag,                {  489,    1,   1,    0 } },
        { UnitField::FieldBytes2PetFlag,                {  490,    1,   1,    0 } },
        { UnitField::FieldBytes2ShapeShiftForm,         {  491,    1,   1,    0 } },
        { UnitField::AttackPower,                       {  492,    4,   1,    0 } },
        { UnitField::AttackPowerMods,                   {  496,    4,   1,    0 } },
        { UnitField::AttackPowerMultiplier,             {  500,    4,   1,    0 } },
        { UnitField::RangedAttackPower,                 {  504,    4,   1,    0 } },
        { UnitField::RangedAttackPowerMods,             {  508,    4,   1,    0 } },
        { UnitField::RangedAttackPowerMultiplier,       {  512,    4,   1,    0 } },
        { UnitField::MinimumRangedDamage,               {  516,    4,   1,    0 } },
        { UnitField::MaximumRangedDamage,               {  520,    4,   1,    0 } },
        { UnitField::PowerCostModifier,                 {  524,    4,   7,    4 } },
        { UnitField::PowerCostMultiplier,               {  552,    4,   7,    4 } },
        { UnitField::MaxHealthModifier,                 {  580,    4,   1,    0 } },
        { UnitField::HoverHeight,                       {  584,    4,   1,    0 } },
        { UnitField::UnitPadding,                       {  588,    4,   1,    0 } },
    };

    // WoWPlayer: 129 fields, 5304 bytes
    static const FieldEntry<PlayerField> wotlkPlayerFields[] =
    {
        { PlayerField::DuelArbiter,                                     {  592,    8,   1,    0 } },
        { PlayerField::PlayerFlags,                                     {  600,    4,   1,    0 } },
        { PlayerField::GuildId,                                         {  604,    4,   1,    0 } },
        { PlayerField::GuildRank,                                       {  608,    4,   1,    0 } },
        { PlayerField::PlayerBytes,                                     {  612,    4,   1,    0 } },
        { PlayerField::PlayerBytesSkinColor,                            {  612,    1,   1,    0 } },
        { PlayerField::PlayerBytesFace,                                 {  613,    1,   1,    0 } },
        { PlayerField::PlayerBytesHairStyle,                            {  614,    1,   1,    0 } },
        { PlayerField::PlayerBytesHornStyle,                            {  614,    1,   1,    0 } },
        { PlayerField::PlayerBytesHairColor,                            {  615,    1,   1,    0 } },
        { PlayerField::PlayerBytesHornColor,                            {  615,    1,   1,    0 } },
        { PlayerField::PlayerBytes2,                                    {  616,    4,   1,    0 } },
        { PlayerField::PlayerBytes2FacialHair,                          {  616,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Piercings,                           {  616,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Features,                            {  616,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Markings,                            {  616,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Hair,                                {  616,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Earrings,                            {  616,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Tusks,                               {  616,    1,   1,    0 } },
        { PlayerField::PlayerBytes2HornStyle,                           {  616,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Ears,                                {  616,    1,   1,    0 } },
        { PlayerField::PlayerBytes2Unk1,                                {  617,    1,   1,    0 } },
        { PlayerField::PlayerBytes2BankSlots,                           {  618,    1,   1,    0 } },
        { PlayerField::PlayerBytes2RestState,                           {  619,    1,   1,    0 } },
        { PlayerField::PlayerBytes3,                                    {  620,    4,   1,    0 } },
        { PlayerField::PlayerBytes3Gender,                              {  620,    1,   1,    0 } },
        { PlayerField::PlayerBytes3DrunkValue,                          {  621,    1,   1,    0 } },
        { PlayerField::PlayerBytes3PvpRank,                             {  622,    1,   1,    0 } },
        { PlayerField::PlayerBytes3ArenaFaction,                        {  623,    1,   1,    0 } },
        { PlayerField::DuelTeam,                                        {  624,    4,   1,    0 } },
        { PlayerField::GuildTimestamp,                                  {  628,    4,   1,    0 } },
        { PlayerField::Quests,                                          {  632,   20,  25,   20 } },
        { PlayerField::QuestsQuestId,                                   {  632,    4,  25,   20 } },
        { PlayerField::QuestsState,                                     {  636,    4,  25,   20 } },
        { PlayerField::QuestsRequiredMobOrGo,                           {  640,    8,  25,   20 } },
        { PlayerField::QuestsExpireTime,                                {  648,    4,  25,   20 } },
        { PlayerField::VisibleItems,                                    { 1132,    8,  19,    8 } },
        { PlayerField::VisibleItemsEntry,                               { 1132,    4,  19,    8 } },
        { PlayerField::VisibleItemsEnchantment,                         { 1136,    4,  19,    8 } },
        { PlayerField::VisibleItemsEnchantmentPermEnchantment,          { 1136,    2,  19,    8 } },
        { PlayerField::VisibleItemsEnchantmentTempEnchantment,          { 1138,    2,  19,    8 } },
        { PlayerField::ChosenTitle,                                     { 1284,    4,   1,    0 } },
        { PlayerField::Inebriation,                                     { 1288,    4,   1,    0 } },
        { PlayerField::PlayerPadding0,                                  { 1292,    4,   1,    0 } },
        { PlayerField::InventorySlot,                                   { 1296,    8,  23,    8 } },
        { PlayerField::PackSlot,                                        { 1480,    8,  16,    8 } },
        { PlayerField::BankSlot,                                        { 1608,    8,  28,    8 } },
        { PlayerField::BankBagSlot,                                     { 1832,    8,   7,    8 } },
        { PlayerField::VendorBuyBackSlot,                               { 1888,    8,  12,    8 } },
        { PlayerField::KeyRingSlot,                                     { 1984,    8,  32,    8 } },
        { PlayerField::CurrencytokenSlot,                               { 2240,    8,  32,    8 } },
        { PlayerField::FarsightGuid,                                    { 2496,    8,   1,    0 } },
        { PlayerField::FieldKnownTitles,                                { 2504,    8,   3,    8 } },
        { PlayerField::FieldKnownCurrencies,                            { 2528,    8,   1,    0 } },
        { PlayerField::Xp,                                              { 2536,    4,   1,    0 } },
        { PlayerField::NextLevelXp,                                     { 2540,    4,   1,    0 } },
        { PlayerField::SkillInfo,                                       { 2544,   12, 128,   12 } },
        { PlayerField::SkillInfoId,                                     { 2544,    2, 128,   12 } },
        { PlayerField::SkillInfoStep,                                   { 2546,    2, 128,   12 } },
        { PlayerField::SkillInfoCurrentValue,                           { 2548,    2, 128,   12 } },
        { PlayerField::SkillInfoMaxValue,                               { 2550,    2, 128,   12 } },
        { PlayerField::SkillInfoBonusTemporary,                         { 2552,    2, 128,   12 } },
        { PlayerField::SkillInfoBonusPermanent,                         { 2554,    2, 128,   12 } },
        { PlayerField::CharacterPoints1,                                { 4080,    4,   1,    0 } },
        { PlayerField::CharacterPoints2,                                { 4084,    4,   1,    0 } },
        { PlayerField::TrackCreatures,                                  { 4088,    4,   1,    0 } },
        { PlayerField::TrackResources,                                  { 4092,    4,   1,    0 } },
        { PlayerField::BlockPct,                                        { 4096,    4,   1,    0 } },
        { PlayerField::DodgePct,                                        { 4100,    4,   1,    0 } },
        { PlayerField::ParryPct,                                        { 4104,    4,   1,    0 } },
        { PlayerField::Expertise,                                       { 4108,    4,   1,    0 } },
        { PlayerField::OffhandExpertise,                                { 4112,    4,   1,    0 } },
        { PlayerField::CritPct,                                         { 4116,    4,   1,    0 } },
        { PlayerField::RangedCritPct,                                   { 4120,    4,   1,    0 } },
        { PlayerField::OffhandCritPct,                                  { 4124,    4,   1,    0 } },
        { PlayerField::SpellCritPct,                                    { 4128,    4,   7,    4 } },
        { PlayerField::ShieldBlock,                                     { 4156,    4,   1,    0 } },
        { PlayerField::ShieldBlockCritPct,                              { 4160,    4,   1,    0 } },
        { PlayerField::ExploredZones,                                   { 4164,    4, 128,    4 } },
        { PlayerField::RestStateXp,                                     { 4676,    4,   1,    0 } },
        { PlayerField::FieldCoinage,                                    { 4680,    4,   1,    0 } },
        { PlayerField::FieldModDamageDonePositive,                      { 4684,    4,   7,    4 } },
        { PlayerField::FieldModDamageDoneNegative,                      { 4712,    4,   7,    4 } },
        { PlayerField::FieldModDamageDonePct,                           { 4740,    4,   7,    4 } },
        { PlayerField::FieldModHealingDone,                             { 4768,    4,   1,    0 } },
        { PlayerField::FieldModHealingPct,                              { 4772,    4,   1,    0 } },
        { PlayerField::FieldModHealingDonePct,                          { 4776,    4,   1,    0 } },
        { PlayerField::FieldModTargetResistance,                        { 4780,    4,   1,    0 } },
        { PlayerField::FieldModTargetPhysicalResistance,                { 4784,    4,   1,    0 } },
        { PlayerField::PlayerFieldBytes,                                { 4788,    4,   1,    0 } },
        { PlayerField::PlayerFieldBytesMiscFlags,                       { 4788,    1,   1,    0 } },
        { PlayerField::PlayerFieldBytesRafLevel,                        { 4789,    1,   1,    0 } },
        { PlayerField::PlayerFieldBytesEnabledActionBars,               { 4790,    1,   1,    0 } },
        { PlayerField::PlayerFieldBytesMaxPvpRank,                      { 4791,    1,   1,    0 } },
        { PlayerField::AmmoId,                                          { 4792,    4,   1,    0 } },
        { PlayerField::SelfResurrectionSpell,                           { 4796,    4,   1,    0 } },
        { PlayerField::FieldPvpMedals,                                  { 4800,    4,   1,    0 } },
        { PlayerField::FieldBuyBackPrice,                               { 4804,    4,  12,    4 } },
        { PlayerField::FieldBuyBackTimestamp,                           { 4852,    4,  12,    4 } },
        { PlayerField::FieldKills,                                      { 4900,    4,   1,    0 } },
        { PlayerField::FieldKillsKillsToday,                            { 4900,    2,   1,    0 } },
        { PlayerField::FieldKillsKillsYesterday,                        { 4902,    2,   1,    0 } },
        { PlayerField::FieldContributionToday,                          { 4904,    4,   1,    0 } },
        { PlayerField::FieldContributionYesterday,                      { 4908,    4,   1,    0 } },
        { PlayerField::FieldLifetimeHonorableKills,                     { 4912,    4,   1,    0 } },
        { PlayerField::PlayerFieldBytes2,                               { 4916,    4,   1,    0 } },
        { PlayerField::PlayerFieldBytes2OverrideSpellId,                { 4916,    2,   1,    0 } },
        { PlayerField::PlayerFieldBytes2IgnorePowerRegenPredictionMask, { 4918,    1,   1,    0 } },
        { PlayerField::PlayerFieldBytes2AuraVision,                     { 4919,    1,   1,    0 } },
        { PlayerField::FieldWatchedFactionIdx,                          { 4920,    4,   1,    0 } },
        { PlayerField::FieldCombatRating,                               { 4924,    4,  25,    4 } },
        { PlayerField::FieldArenaTeamInfo,                              { 5024,   28,   3,   28 } },
        { PlayerField::FieldArenaTeamInfoTeamId,                        { 5024,    4,   3,   28 } },
        { PlayerField::FieldArenaTeamInfoType,                          { 5028,    4,   3,   28 } },
        { PlayerField::FieldArenaTeamInfoMemberRank,                    { 5032,    4,   3,   28 } },
        { PlayerField::FieldArenaTeamInfoGamesWeek,                     { 5036,    4,   3,   28 } },
        { PlayerField::FieldArenaTeamInfoGamesSeason,                   { 5040,    4,   3,   28 } },
        { PlayerField::FieldArenaTeamInfoWinsSeason,                    { 5044,    4,   3,   28 } },
        { PlayerField::FieldArenaTeamInfoPersonalRating,                { 5048,    4,   3,   28 } },
        { PlayerField::FieldHonorCurrency,                              { 5108,    4,   1,    0 } },
        { PlayerField::FieldArenaCurrency,                              { 5112,    4,   1,    0 } },
        { PlayerField::FieldMaxLevel,                                   { 5116,    4,   1,    0 } },
        { PlayerField::FieldDailyQuests,                                { 5120,    4,  25,    4 } },
        { PlayerField::RuneRegen,                                       { 5220,    4,   4,    4 } },
        { PlayerField::NoReagentCost,                                   { 5236,    4,   3,    4 } },
        { PlayerField::FieldGlyphSlots,                                 { 5248,    4,   6,    4 } },
        { PlayerField::FieldGlyphs,                                     { 5272,    4,   6,    4 } },
        { PlayerField::GlyphsEnabled,                                   { 5296,    4,   1,    0 } },
        { PlayerField::PetSpellPower,                                   { 5300,    4,   1,    0 } },
    };

    // WoWItem: 26 fields, 256 bytes
    static const FieldEntry<ItemField> wotlkItemFields[] =
    {
        { ItemField::OwnerGuid,           {   24,    8,   1,    0 } },
        { ItemField::OwnerGuidLow,        {   24,    4,   1,    0 } },
        { ItemField::OwnerGuidHigh,       {   28,    4,   1,    0 } },
        { ItemField::ContainerGuid,       {   32,    8,   1,    0 } },
        { ItemField::ContainerGuidLow,    {   32,    4,   1,    0 } },
        { ItemField::ContainerGuidHigh,   {   36,    4,   1,    0 } },
        { ItemField::CreatorGuid,         {   40,    8,   1,    0 } },
        { ItemField::CreatorGuidLow,      {   40,    4,   1,    0 } },
        { ItemField::CreatorGuidHigh,     {   44,    4,   1,    0 } },
        { ItemField::GiftCreatorGuid,     {   48,    8,   1,    0 } },
        { ItemField::GiftCreatorGuidLow,  {   48,    4,   1,    0 } },
        { ItemField::GiftCreatorGuidHigh, {   52,    4,   1,    0 } },
        { ItemField::StackCount,          {   56,    4,   1,    0 } },
        { ItemField::Duration,            {   60,    4,   1,    0 } },
        { ItemField::SpellCharges,        {   64,    4,   5,    4 } },
        { ItemField::Flags,               {   84,    4,   1,    0 } },
        { ItemField::Enchantment,         {   88,   12,  12,   12 } },
        { ItemField::EnchantmentId,       {   88,    4,  12,   12 } },
        { ItemField::EnchantmentDuration, {   92,    4,  12,   12 } },
        { ItemField::EnchantmentCharges,  {   96,    4,  12,   12 } },
        { ItemField::PropertySeed,        {  232,    4,   1,    0 } },
        { ItemField::RandomPropertiesId,  {  236,    4,   1,    0 } },
        { ItemField::Durability,          {  240,    4,   1,    0 } },
        { ItemField::MaxDurability,       {  244,    4,   1,    0 } },
        { ItemField::CreatePlayedTime,    {  248,    4,   1,    0 } },
        { ItemField::ItemPadding0,        {  252,    4,   1,    0 } },
    };

    // WoWContainer: 5 fields, 552 bytes
    static const FieldEntry<ContainerField> wotlkContainerFields[] =
    {
        { ContainerField::SlotCount,        {  256,    4,   1,    0 } },
        { ContainerField::PaddingContainer, {  260,    4,   1,    0 } },
        { ContainerField::ItemSlot,         {  264,    8,  36,    8 } },
        { ContainerField::ItemSlotLow,      {  264,    4,  36,    8 } },
        { ContainerField::ItemSlotHigh,     {  268,    4,  36,    8 } },
    };

    // WoWGameObject: 16 fields, 72 bytes
    static const FieldEntry<GameObjectField> wotlkGameObjectFields[] =
    {
        { GameObjectField::ObjectFieldCreatedBy,     {   24,    8,   1,    0 } },
        { GameObjectField::ObjectFieldCreatedByLow,  {   24,    4,   1,    0 } },
        { GameObjectField::ObjectFieldCreatedByHigh, {   28,    4,   1,    0 } },
        { GameObjectField::DisplayId,                {   32,    4,   1,    0 } },
        { GameObjectField::Flags,                    {   36,    4,   1,    0 } },
        { GameObjectField::Rotation,                 {   40,    4,   4,    4 } },
        { GameObjectField::Dynamic,                  {   56,    4,   1,    0 } },
        { GameObjectField::DynamicDynFlag,           {   56,    2,   1,    0 } },
        { GameObjectField::DynamicPathProgress,      {   58,    2,   1,    0 } },
        { GameObjectField::FactionTemplate,          {   60,    4,   1,    0 } },
        { GameObjectField::Level,                    {   64,    4,   1,    0 } },
        { GameObjectField::Bytes1,                   {   68,    4,   1,    0 } },
        { GameObjectField::Bytes1State,              {   68,    1,   1,    0 } },
        { GameObjectField::Bytes1Type,               {   69,    1,   1,    0 } },
        { GameObjectField::Bytes1ArtKit,             {   70,    1,   1,    0 } },
        { GameObjectField::Bytes1AnimationProgress,  {   71,    1,   1,    0 } },
    };

    // WoWDynamicObject: 9 fields, 48 bytes
    static const FieldEntry<DynamicObjectField> wotlkDynamicObjectFields[] =
    {
        { DynamicObjectField::CasterGuid,             {   24,    8,   1,    0 } },
        { DynamicObjectField::DynamicobjectBytes,     {   32,    4,   1,    0 } },
        { DynamicObjectField::DynamicobjectBytesType, {   32,    1,   1,    0 } },
        { DynamicObjectField::DynamicobjectBytesUnk1, {   33,    1,   1,    0 } },
        { DynamicObjectField::DynamicobjectBytesUnk2, {   34,    1,   1,    0 } },
        { DynamicObjectField::DynamicobjectBytesUnk3, {   35,    1,   1,    0 } },
        { DynamicObjectField::SpellId,                {   36,    4,   1,    0 } },
        { DynamicObjectField::Radius,                 {   40,    4,   1,    0 } },
        { DynamicObjectField::CastTime,               {   44,    4,   1,    0 } },
    };

    // WoWCorpse: 18 fields, 144 bytes
    static const FieldEntry<CorpseField> wotlkCorpseFields[] =
    {
        { CorpseField::OwnerGuid,              {   24,    8,   1,    0 } },
        { CorpseField::PartyGuid,              {   32,    8,   1,    0 } },
        { CorpseField::DisplayId,              {   40,    4,   1,    0 } },
        { CorpseField::Item,                   {   44,    4,  19,    4 } },
        { CorpseField::CorpseBytes1,           {  120,    4,   1,    0 } },
        { CorpseField::CorpseBytes1Unk1,       {  120,    1,   1,    0 } },
        { CorpseField::CorpseBytes1Race,       {  121,    1,   1,    0 } },
        { CorpseField::CorpseBytes1Gender,     {  122,    1,   1,    0 } },
        { CorpseField::CorpseBytes1SkinColor,  {  123,    1,   1,    0 } },
        { CorpseField::CorpseBytes2,           {  124,    4,   1,    0 } },
        { CorpseField::CorpseBytes2Face,       {  124,    1,   1,    0 } },
        { CorpseField::CorpseBytes2HairStyle,  {  125,    1,   1,    0 } },
        { CorpseField::CorpseBytes2HairColor,  {  126,    1,   1,    0 } },
        { CorpseField::CorpseBytes2FacialHair, {  127,    1,   1,    0 } },
        { CorpseField::Guild,                  {  128,    4,   1,    0 } },
        { CorpseField::CorpseFlags,            {  132,    4,   1,    0 } },
        { CorpseField::DynamicFlags,           {  136,    4,   1,    0 } },
        { CorpseField::CorpsePadding,          {  140,    4,   1,    0 } },
    };

    // WoWAreaTrigger does not exist in this client version

    const ExpansionLayoutSources wotlkLayouts
    {
        { wotlkObjectFields, static_cast<uint16_t>(std::size(wotlkObjectFields)), 24 },  // object
        { wotlkUnitFields, static_cast<uint16_t>(std::size(wotlkUnitFields)), 592 },  // unit
        { wotlkPlayerFields, static_cast<uint16_t>(std::size(wotlkPlayerFields)), 5304 },  // player
        { wotlkItemFields, static_cast<uint16_t>(std::size(wotlkItemFields)), 256 },  // item
        { wotlkContainerFields, static_cast<uint16_t>(std::size(wotlkContainerFields)), 552 },  // container
        { wotlkGameObjectFields, static_cast<uint16_t>(std::size(wotlkGameObjectFields)), 72 },  // gameObject
        { wotlkDynamicObjectFields, static_cast<uint16_t>(std::size(wotlkDynamicObjectFields)), 48 },  // dynamicObject
        { wotlkCorpseFields, static_cast<uint16_t>(std::size(wotlkCorpseFields)), 144 },  // corpse
        { nullptr, 0, 0 },  // areaTrigger
    };
}
