/*
Copyright (c) 2014-2026 AscEmu Team <http://www.ascemu.org>
This file is released under the MIT license. See README-MIT for more information.
*/

// Generated by the version table generator - do not edit by hand, regenerate instead.

#include "Version/ObjectLayout.hpp"

namespace Version::Tables
{
    static const FieldDesc classicObjectFields[] =
    {
        {    0,   8 },  // Guid
        {    8,   4 },  // Type
        {   12,   4 },  // Entry
        {   16,   4 },  // ScaleX
        {   20,   4 },  // PaddingObject
        { kNoField, 0 },  // Data - not in this version
        { kNoField, 0 },  // FieldType - not in this version
        { kNoField, 0 },  // DynamicField - not in this version
    };

    static const FieldDesc classicUnitFields[] =
    {
        {   24,   8 },  // CharmGuid
        {   32,   8 },  // SummonGuid
        {   40,   8 },  // CharmedByGuid
        {   48,   8 },  // SummonedByGuid
        {   56,   8 },  // CreatedByGuid
        {   64,   8 },  // TargetGuid
        {   72,   8 },  // PersuadedGuid
        {   80,   8 },  // ChannelObjectGuid
        {   88,   4 },  // Health
        {   92,   4 },  // Power1
        {   96,   4 },  // Power2
        {  100,   4 },  // Power3
        {  104,   4 },  // Power4
        {  108,   4 },  // Power5
        {  112,   4 },  // MaxHealth
        {  116,   4 },  // MaxPower1
        {  120,   4 },  // MaxPower2
        {  124,   4 },  // MaxPower3
        {  128,   4 },  // MaxPower4
        {  132,   4 },  // MaxPower5
        {  136,   4 },  // Level
        {  140,   4 },  // FactionTemplate
        {  144,   4 },  // FieldBytes0
        {  148,  12 },  // VirtualItemSlotDisplay
        {  160,  24 },  // VirtualItemInfo
        {  184,   4 },  // UnitFlags
        {  188, 192 },  // Aura
        {  380,  24 },  // AuraFlags
        {  404,  48 },  // AuraLevels
        {  452,  48 },  // AuraApplications
        {  500,   4 },  // AuraState
        {  504,  12 },  // BaseAttackTime
        {  516,   4 },  // BoundingRadius
        {  520,   4 },  // CombatReach
        {  524,   4 },  // DisplayId
        {  528,   4 },  // NativeDisplayId
        {  532,   4 },  // MountDisplayId
        {  536,   4 },  // MinimumDamage
        {  540,   4 },  // MaximumDamage
        {  544,   4 },  // MinimumOffhandDamage
        {  548,   4 },  // MaximumOffhandDamage
        {  552,   4 },  // FieldBytes1
        {  556,   4 },  // PetNumber
        {  560,   4 },  // PetNameTimestamp
        {  564,   4 },  // PetExperience
        {  568,   4 },  // PetNextLevelExperience
        {  572,   4 },  // DynamicFlags
        {  576,   4 },  // ChannelSpell
        {  580,   4 },  // ModCastSpeed
        {  584,   4 },  // CreatedBySpellId
        {  588,   4 },  // NpcFlags
        {  592,   4 },  // NpcEmoteState
        {  596,   4 },  // TrainingPoints
        {  600,  20 },  // Stat
        {  620,  28 },  // Resistance
        {  648,   4 },  // BaseMana
        {  652,   4 },  // BaseHealth
        {  656,   4 },  // FieldBytes2
        {  660,   4 },  // AttackPower
        {  664,   4 },  // AttackPowerMods
        {  668,   4 },  // AttackPowerMultiplier
        {  672,   4 },  // RangedAttackPower
        {  676,   4 },  // RangedAttackPowerMods
        {  680,   4 },  // RangedAttackPowerMultiplier
        {  684,   4 },  // MinimumRangedDamage
        {  688,   4 },  // MaximumRangedDamage
        {  692,  28 },  // PowerCostModifier
        {  720,  28 },  // PowerCostMultiplier
        {  748,   4 },  // UnitPadding
        { kNoField, 0 },  // UnitFlags2 - not in this version
        { kNoField, 0 },  // PositiveStat - not in this version
        { kNoField, 0 },  // NegativeStat - not in this version
        { kNoField, 0 },  // ResistanceBuffModPositive - not in this version
        { kNoField, 0 },  // ResistanceBuffModNegative - not in this version
        { kNoField, 0 },  // MaxHealthModifier - not in this version
        { kNoField, 0 },  // CritterGuid - not in this version
        { kNoField, 0 },  // Power6 - not in this version
        { kNoField, 0 },  // Power7 - not in this version
        { kNoField, 0 },  // MaxPower6 - not in this version
        { kNoField, 0 },  // MaxPower7 - not in this version
        { kNoField, 0 },  // PowerRegenFlatModifier - not in this version
        { kNoField, 0 },  // PowerRegenInterruptedFlatModifier - not in this version
        { kNoField, 0 },  // HoverHeight - not in this version
        { kNoField, 0 },  // ModCastHaste - not in this version
        { kNoField, 0 },  // AttackPowerModPos - not in this version
        { kNoField, 0 },  // AttackPowerModNeg - not in this version
        { kNoField, 0 },  // RangedAttackPowerModsPos - not in this version
        { kNoField, 0 },  // RangedAttackPowerModsNeg - not in this version
        { kNoField, 0 },  // MaxItemLevel - not in this version
        { kNoField, 0 },  // DemonCreatorGuid - not in this version
        { kNoField, 0 },  // BattlePetCompanionGuid - not in this version
        { kNoField, 0 },  // SummonedByHomeRealm - not in this version
        { kNoField, 0 },  // DisplayPower - not in this version
        { kNoField, 0 },  // OverrideDisplayPowerId - not in this version
        { kNoField, 0 },  // EffectiveLevel - not in this version
        { kNoField, 0 },  // ModHaste - not in this version
        { kNoField, 0 },  // ModRangedHaste - not in this version
        { kNoField, 0 },  // ModHasteRegen - not in this version
        { kNoField, 0 },  // MinItemLevel - not in this version
        { kNoField, 0 },  // WildBattlePetLevel - not in this version
        { kNoField, 0 },  // BattlePetCompanionNameTimestamp - not in this version
        { kNoField, 0 },  // InteractSpellId - not in this version
    };

    static const FieldDesc classicPlayerFields[] =
    {
        {  752,   8 },  // DuelArbiter
        {  760,   4 },  // PlayerFlags
        {  764,   4 },  // GuildId
        {  768,   4 },  // GuildRank
        {  772,   4 },  // PlayerBytes
        {  776,   4 },  // PlayerBytes2
        {  780,   4 },  // PlayerBytes3
        {  784,   4 },  // DuelTeam
        {  788,   4 },  // GuildTimestamp
        {  792, 240 },  // Quests
        { 1032, 912 },  // VisibleItems
        { 1944, 184 },  // InventorySlot
        { 2128, 128 },  // PackSlot
        { 2256, 192 },  // BankSlot
        { 2448,  48 },  // BankBagSlot
        { 2496,  96 },  // VendorBuyBackSlot
        { 2592, 160 },  // KeyRingSlot
        { 2752,   8 },  // FarsightGuid
        { 2760,   8 },  // FieldComboTarget
        { 2768,   4 },  // Xp
        { 2772,   4 },  // NextLevelXp
        { 2776, 1536 },  // SkillInfo
        { 4312,   4 },  // CharacterPoints1
        { 4316,   4 },  // CharacterPoints2
        { 4320,   4 },  // TrackCreatures
        { 4324,   4 },  // TrackResources
        { 4328,   4 },  // BlockPct
        { 4332,   4 },  // DodgePct
        { 4336,   4 },  // ParryPct
        { 4340,   4 },  // CritPct
        { 4344,   4 },  // RangedCritPct
        { 4348, 256 },  // ExploredZones
        { 4604,   4 },  // RestStateXp
        { 4608,   4 },  // FieldCoinage
        { 4612,  20 },  // PosStat
        { 4632,  20 },  // NegStat
        { 4652,  28 },  // ResistanceBuffModPositive
        { 4680,  28 },  // ResistanceBuffModNegative
        { 4708,  28 },  // FieldModDamageDonePositive
        { 4736,  28 },  // FieldModDamageDoneNegative
        { 4764,  28 },  // FieldModDamageDonePct
        { 4792,   4 },  // PlayerFieldBytes
        { 4796,   4 },  // AmmoId
        { 4800,   4 },  // SelfResurrectionSpell
        { 4804,   4 },  // FieldPvpMedals
        { 4808,  48 },  // FieldBuyBackPrice
        { 4856,  48 },  // FieldBuyBackTimestamp
        { 4904,   4 },  // FieldSessionKills
        { 4908,   4 },  // FieldYesterdayKills
        { 4912,   4 },  // FieldLastWeekKills
        { 4916,   4 },  // FieldThisWeekKills
        { 4920,   4 },  // FieldThisWeekContribution
        { 4924,   4 },  // FieldLifetimeHonorableKills
        { 4928,   4 },  // FieldLifetimeDishonorableKills
        { 4932,   4 },  // FieldYersterdayContribution
        { 4936,   4 },  // FieldLastWeekContribution
        { 4940,   4 },  // FieldLastWeekRank
        { 4944,   4 },  // PlayerFieldBytes2
        { 4948,   4 },  // FieldWatchedFactionIdx
        { 4952,  80 },  // FieldCombatRating
        { kNoField, 0 },  // ChosenTitle - not in this version
        { kNoField, 0 },  // PlayerPadding0 - not in this version
        { kNoField, 0 },  // VanityPetSlot - not in this version
        { kNoField, 0 },  // FieldKnownTitles - not in this version
        { kNoField, 0 },  // Expertise - not in this version
        { kNoField, 0 },  // OffhandExpertise - not in this version
        { kNoField, 0 },  // OffhandCritPct - not in this version
        { kNoField, 0 },  // SpellCritPct - not in this version
        { kNoField, 0 },  // ShieldBlock - not in this version
        { kNoField, 0 },  // FieldModHealingDone - not in this version
        { kNoField, 0 },  // FieldModTargetResistance - not in this version
        { kNoField, 0 },  // FieldModTargetPhysicalResistance - not in this version
        { kNoField, 0 },  // FieldKills - not in this version
        { kNoField, 0 },  // FieldContributionToday - not in this version
        { kNoField, 0 },  // FieldContributionYesterday - not in this version
        { kNoField, 0 },  // FieldArenaTeamInfo - not in this version
        { kNoField, 0 },  // FieldHonorCurrency - not in this version
        { kNoField, 0 },  // FieldArenaCurrency - not in this version
        { kNoField, 0 },  // FieldModManaRegen - not in this version
        { kNoField, 0 },  // FieldModManaRegenInterrupt - not in this version
        { kNoField, 0 },  // FieldMaxLevel - not in this version
        { kNoField, 0 },  // FieldDailyQuests - not in this version
        { kNoField, 0 },  // Inebriation - not in this version
        { kNoField, 0 },  // CurrencytokenSlot - not in this version
        { kNoField, 0 },  // FieldKnownCurrencies - not in this version
        { kNoField, 0 },  // ShieldBlockCritPct - not in this version
        { kNoField, 0 },  // FieldModHealingPct - not in this version
        { kNoField, 0 },  // FieldModHealingDonePct - not in this version
        { kNoField, 0 },  // RuneRegen - not in this version
        { kNoField, 0 },  // NoReagentCost - not in this version
        { kNoField, 0 },  // FieldGlyphSlots - not in this version
        { kNoField, 0 },  // FieldGlyphs - not in this version
        { kNoField, 0 },  // GlyphsEnabled - not in this version
        { kNoField, 0 },  // PetSpellPower - not in this version
        { kNoField, 0 },  // GuildDeleteDate - not in this version
        { kNoField, 0 },  // GuildLevel - not in this version
        { kNoField, 0 },  // FieldSkillInfo - not in this version
        { kNoField, 0 },  // Mastery - not in this version
        { kNoField, 0 },  // WeaponDmgMultiplier - not in this version
        { kNoField, 0 },  // ModSpellPowerPct - not in this version
        { kNoField, 0 },  // OverrideSpellPowerByApPct - not in this version
        { kNoField, 0 },  // BattlegroundRating - not in this version
        { kNoField, 0 },  // Researching - not in this version
        { kNoField, 0 },  // ResearchSite - not in this version
        { kNoField, 0 },  // ProfessionSkillLine - not in this version
        { kNoField, 0 },  // UiHitMod - not in this version
        { kNoField, 0 },  // UiHitSpellMod - not in this version
        { kNoField, 0 },  // UiHomeRealmTimeOffset - not in this version
        { kNoField, 0 },  // ModHaste - not in this version
        { kNoField, 0 },  // ModRangedHaste - not in this version
        { kNoField, 0 },  // ModPetHaste - not in this version
        { kNoField, 0 },  // ModHasteRegen - not in this version
        { kNoField, 0 },  // VirtualPlayerRealm - not in this version
        { kNoField, 0 },  // CurrentSpecId - not in this version
        { kNoField, 0 },  // TaxiMountAnimKitId - not in this version
        { kNoField, 0 },  // CurrentBattlePetBreedQuality - not in this version
        { kNoField, 0 },  // MaxTalentTiers - not in this version
        { kNoField, 0 },  // RangedExpertise - not in this version
        { kNoField, 0 },  // CombatRatingExpertise - not in this version
        { kNoField, 0 },  // PvpPowerDamage - not in this version
        { kNoField, 0 },  // PvpPowerHealing - not in this version
        { kNoField, 0 },  // FieldModPeriodicHealingDonePct - not in this version
        { kNoField, 0 },  // ModResiliencePct - not in this version
        { kNoField, 0 },  // OverrideApBySpellPowerPct - not in this version
        { kNoField, 0 },  // SummonedBattlePetGuid - not in this version
        { kNoField, 0 },  // OverrideSpellId - not in this version
        { kNoField, 0 },  // LfgBonusFactionId - not in this version
        { kNoField, 0 },  // LootSpecId - not in this version
        { kNoField, 0 },  // OverrideZonePvpType - not in this version
        { kNoField, 0 },  // ItemLevelDelta - not in this version
    };

    static const FieldDesc classicItemFields[] =
    {
        {   24,   8 },  // OwnerGuid
        {   32,   8 },  // ContainerGuid
        {   40,   8 },  // CreatorGuid
        {   48,   8 },  // GiftCreatorGuid
        {   56,   4 },  // StackCount
        {   60,   4 },  // Duration
        {   64,  20 },  // SpellCharges
        {   84,   4 },  // Flags
        {   88,  84 },  // Enchantment
        {  172,   4 },  // PropertySeed
        {  176,   4 },  // RandomPropertiesId
        {  180,   4 },  // ItemTextId
        {  184,   4 },  // Durability
        {  188,   4 },  // MaxDurability
        { kNoField, 0 },  // CreatePlayedTime - not in this version
        { kNoField, 0 },  // ItemPadding0 - not in this version
        { kNoField, 0 },  // ModifierMask - not in this version
    };

    static const FieldDesc classicContainerFields[] =
    {
        {  192,   4 },  // SlotCount
        {  196,   4 },  // PaddingContainer
        {  200, 232 },  // ItemSlot
        { kNoField, 0 },  // ContainerPadding0 - not in this version
    };

    static const FieldDesc classicGameObjectFields[] =
    {
        {   24,   8 },  // ObjectFieldCreatedBy
        {   32,   4 },  // DisplayId
        {   36,   4 },  // Flags
        {   40,  16 },  // Rotation
        {   56,   4 },  // State
        {   60,   4 },  // X
        {   64,   4 },  // Y
        {   68,   4 },  // Z
        {   72,   4 },  // O
        {   76,   4 },  // Dynamic
        {   80,   4 },  // FactionTemplate
        {   84,   4 },  // Type
        {   88,   4 },  // Level
        {   92,   4 },  // ArtKit
        {   96,   4 },  // AnimationProgress
        {  100,   4 },  // GameobjectPadding
        { kNoField, 0 },  // Bytes1 - not in this version
        { kNoField, 0 },  // Bytes2 - not in this version
    };

    static const FieldDesc classicDynamicObjectFields[] =
    {
        {   24,   8 },  // CasterGuid
        {   32,   4 },  // DynamicobjectBytes
        {   36,   4 },  // SpellId
        {   40,   4 },  // Radius
        {   44,   4 },  // X
        {   48,   4 },  // Y
        {   52,   4 },  // Z
        {   56,   4 },  // O
        {   60,   4 },  // Padding
        { kNoField, 0 },  // CastTime - not in this version
    };

    static const FieldDesc classicCorpseFields[] =
    {
        {   24,   8 },  // OwnerGuid
        {   32,   8 },  // PartyGuid
        {   40,   4 },  // O
        {   44,   4 },  // X
        {   48,   4 },  // Y
        {   52,   4 },  // Z
        {   56,   4 },  // DisplayId
        {   60,  76 },  // Item
        {  136,   4 },  // CorpseBytes1
        {  140,   4 },  // CorpseBytes2
        {  144,   4 },  // Guild
        {  148,   4 },  // CorpseFlags
        {  152,   4 },  // DynamicFlags
        {  156,   4 },  // CorpsePadding
    };

    // WoWAreaTrigger does not exist in this client version
    static const FieldDesc classicAreaTriggerFields[] =
    {
        { kNoField, 0 },  // SpellId - not in this version
        { kNoField, 0 },  // SpellVisualId - not in this version
        { kNoField, 0 },  // Duration - not in this version
        { kNoField, 0 },  // PosX - not in this version
        { kNoField, 0 },  // PosY - not in this version
        { kNoField, 0 },  // PosZ - not in this version
        { kNoField, 0 },  // CasterGuid - not in this version
        { kNoField, 0 },  // Scale - not in this version
    };

    const ExpansionLayouts classicLayouts
    {
        { classicObjectFields, static_cast<uint16_t>(std::size(classicObjectFields)), 24 },  // object
        { classicUnitFields, static_cast<uint16_t>(std::size(classicUnitFields)), 752 },  // unit
        { classicPlayerFields, static_cast<uint16_t>(std::size(classicPlayerFields)), 5032 },  // player
        { classicItemFields, static_cast<uint16_t>(std::size(classicItemFields)), 192 },  // item
        { classicContainerFields, static_cast<uint16_t>(std::size(classicContainerFields)), 432 },  // container
        { classicGameObjectFields, static_cast<uint16_t>(std::size(classicGameObjectFields)), 104 },  // gameObject
        { classicDynamicObjectFields, static_cast<uint16_t>(std::size(classicDynamicObjectFields)), 64 },  // dynamicObject
        { classicCorpseFields, static_cast<uint16_t>(std::size(classicCorpseFields)), 160 },  // corpse
        { classicAreaTriggerFields, static_cast<uint16_t>(std::size(classicAreaTriggerFields)), 0 },  // areaTrigger
    };
}
