/*
 * AscEmu Framework based on ArcEmu MMORPG Server
 * Copyright (C) 2014-2016 AscEmu Team <http://www.ascemu.org>
 * Copyright (C) 2008-2012 ArcEmu Team <http://www.ArcEmu.org/>
 * Copyright (C) 2005-2007 Ascent Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _SPELLFAILURE_H
#define _SPELLFAILURE_H

enum SpellCastResult
{
    SPELL_FAILED_SUCCESS                        = 0,
    SPELL_FAILED_AFFECTING_COMBAT               = 1,
    SPELL_FAILED_ALREADY_AT_FULL_HEALTH         = 2,
    SPELL_FAILED_ALREADY_AT_FULL_MANA           = 3,
    SPELL_FAILED_ALREADY_AT_FULL_POWER          = 4,
    SPELL_FAILED_ALREADY_BEING_TAMED            = 5,
    SPELL_FAILED_ALREADY_HAVE_CHARM             = 6,
    SPELL_FAILED_ALREADY_HAVE_SUMMON            = 7,
    SPELL_FAILED_ALREADY_HAVE_PET               = 8,
    SPELL_FAILED_ALREADY_OPEN                   = 9,
    SPELL_FAILED_AURA_BOUNCED                   = 10,
    SPELL_FAILED_AUTOTRACK_INTERRUPTED          = 11,
    SPELL_FAILED_BAD_IMPLICIT_TARGETS           = 12,
    SPELL_FAILED_BAD_TARGETS                    = 13,
    SPELL_FAILED_CANT_BE_CHARMED                = 14,
    SPELL_FAILED_CANT_BE_DISENCHANTED           = 15,
    SPELL_FAILED_CANT_BE_DISENCHANTED_SKILL     = 16,
    SPELL_FAILED_CANT_BE_MILLED                 = 17,
    SPELL_FAILED_CANT_BE_PROSPECTED             = 18,
    SPELL_FAILED_CANT_CAST_ON_TAPPED            = 19,
    SPELL_FAILED_CANT_DUEL_WHILE_INVISIBLE      = 20,
    SPELL_FAILED_CANT_DUEL_WHILE_STEALTHED      = 21,
    SPELL_FAILED_CANT_STEALTH                   = 22,
    SPELL_FAILED_CASTER_AURASTATE               = 23,
    SPELL_FAILED_CASTER_DEAD                    = 24,
    SPELL_FAILED_CHARMED                        = 25,
    SPELL_FAILED_CHEST_IN_USE                   = 26,
    SPELL_FAILED_CONFUSED                       = 27,
    SPELL_FAILED_DONT_REPORT                    = 28,
    SPELL_FAILED_EQUIPPED_ITEM                  = 29,
    SPELL_FAILED_EQUIPPED_ITEM_CLASS            = 30,
    SPELL_FAILED_EQUIPPED_ITEM_CLASS_MAINHAND   = 31,
    SPELL_FAILED_EQUIPPED_ITEM_CLASS_OFFHAND    = 32,
    SPELL_FAILED_ERROR                          = 33,
    SPELL_FAILED_FALLING                        = 34,
    SPELL_FAILED_FIZZLE                         = 35,
    SPELL_FAILED_FLEEING                        = 36,
    SPELL_FAILED_FOOD_LOWLEVEL                  = 37,
    SPELL_FAILED_HIGHLEVEL                      = 38,
    SPELL_FAILED_HUNGER_SATIATED                = 39,
    SPELL_FAILED_IMMUNE                         = 40,
    SPELL_FAILED_INCORRECT_AREA                 = 41,
    SPELL_FAILED_INTERRUPTED                    = 42,
    SPELL_FAILED_INTERRUPTED_COMBAT             = 43,
    SPELL_FAILED_ITEM_ALREADY_ENCHANTED         = 44,
    SPELL_FAILED_ITEM_GONE                      = 45,
    SPELL_FAILED_ITEM_NOT_FOUND                 = 46,
    SPELL_FAILED_ITEM_NOT_READY                 = 47,
    SPELL_FAILED_LEVEL_REQUIREMENT              = 48,
    SPELL_FAILED_LINE_OF_SIGHT                  = 49,
    SPELL_FAILED_LOWLEVEL                       = 50,
    SPELL_FAILED_LOW_CASTLEVEL                  = 51,
    SPELL_FAILED_MAINHAND_EMPTY                 = 52,
    SPELL_FAILED_MOVING                         = 53,
    SPELL_FAILED_NEED_AMMO                      = 54,
    SPELL_FAILED_NEED_AMMO_POUCH                = 55,
    SPELL_FAILED_NEED_EXOTIC_AMMO               = 56,
    SPELL_FAILED_NEED_MORE_ITEMS                = 57,
    SPELL_FAILED_NOPATH                         = 58,
    SPELL_FAILED_NOT_BEHIND                     = 59,
    SPELL_FAILED_NOT_FISHABLE                   = 60,
    SPELL_FAILED_NOT_FLYING                     = 61,
    SPELL_FAILED_NOT_HERE                       = 62,
    SPELL_FAILED_NOT_INFRONT                    = 63,
    SPELL_FAILED_NOT_IN_CONTROL                 = 64,
    SPELL_FAILED_NOT_KNOWN                      = 65,
    SPELL_FAILED_NOT_MOUNTED                    = 66,
    SPELL_FAILED_NOT_ON_TAXI                    = 67,
    SPELL_FAILED_NOT_ON_TRANSPORT               = 68,
    SPELL_FAILED_NOT_READY                      = 69,
    SPELL_FAILED_NOT_SHAPESHIFT                 = 70,
    SPELL_FAILED_NOT_STANDING                   = 71,
    SPELL_FAILED_NOT_TRADEABLE                  = 72,
    SPELL_FAILED_NOT_TRADING                    = 73,
    SPELL_FAILED_NOT_UNSHEATHED                 = 74,
    SPELL_FAILED_NOT_WHILE_GHOST                = 75,
    SPELL_FAILED_NOT_WHILE_LOOTING              = 76,
    SPELL_FAILED_NO_AMMO                        = 77,
    SPELL_FAILED_NO_CHARGES_REMAIN              = 78,
    SPELL_FAILED_NO_CHAMPION                    = 79,
    SPELL_FAILED_NO_COMBO_POINTS                = 80,
    SPELL_FAILED_NO_DUELING                     = 81,
    SPELL_FAILED_NO_ENDURANCE                   = 82,
    SPELL_FAILED_NO_FISH                        = 83,
    SPELL_FAILED_NO_ITEMS_WHILE_SHAPESHIFTED    = 84,
    SPELL_FAILED_NO_MOUNTS_ALLOWED              = 85,
    SPELL_FAILED_NO_PET                         = 86,
    SPELL_FAILED_NO_POWER                       = 87,
    SPELL_FAILED_NOTHING_TO_DISPEL              = 88,
    SPELL_FAILED_NOTHING_TO_STEAL               = 89,
    SPELL_FAILED_ONLY_ABOVEWATER                = 90,
    SPELL_FAILED_ONLY_DAYTIME                   = 91,
    SPELL_FAILED_ONLY_INDOORS                   = 92,
    SPELL_FAILED_ONLY_MOUNTED                   = 93,
    SPELL_FAILED_ONLY_NIGHTTIME                 = 94,
    SPELL_FAILED_ONLY_OUTDOORS                  = 95,
    SPELL_FAILED_ONLY_SHAPESHIFT                = 96,
    SPELL_FAILED_ONLY_STEALTHED                 = 97,
    SPELL_FAILED_ONLY_UNDERWATER                = 98,
    SPELL_FAILED_OUT_OF_RANGE                   = 99,
    SPELL_FAILED_PACIFIED                       = 100,
    SPELL_FAILED_POSSESSED                      = 101,
    SPELL_FAILED_REAGENTS                       = 102,
    SPELL_FAILED_REQUIRES_AREA                  = 103,
    SPELL_FAILED_REQUIRES_SPELL_FOCUS           = 104,
    SPELL_FAILED_ROOTED                         = 105,
    SPELL_FAILED_SILENCED                       = 106,
    SPELL_FAILED_SPELL_IN_PROGRESS              = 107,
    SPELL_FAILED_SPELL_LEARNED                  = 108,
    SPELL_FAILED_SPELL_UNAVAILABLE              = 109,
    SPELL_FAILED_STUNNED                        = 110,
    SPELL_FAILED_TARGETS_DEAD                   = 111,
    SPELL_FAILED_TARGET_AFFECTING_COMBAT        = 112,
    SPELL_FAILED_TARGET_AURASTATE               = 113,
    SPELL_FAILED_TARGET_DUELING                 = 114,
    SPELL_FAILED_TARGET_ENEMY                   = 115,
    SPELL_FAILED_TARGET_ENRAGED                 = 116,
    SPELL_FAILED_TARGET_FRIENDLY                = 117,
    SPELL_FAILED_TARGET_IN_COMBAT               = 118,
    SPELL_FAILED_TARGET_IS_PLAYER               = 119,
    SPELL_FAILED_TARGET_IS_PLAYER_CONTROLLED    = 120,
    SPELL_FAILED_TARGET_NOT_DEAD                = 121,
    SPELL_FAILED_TARGET_NOT_IN_PARTY            = 122,
    SPELL_FAILED_TARGET_NOT_LOOTED              = 123,
    SPELL_FAILED_TARGET_NOT_PLAYER              = 124,
    SPELL_FAILED_TARGET_NO_POCKETS              = 125,
    SPELL_FAILED_TARGET_NO_WEAPONS              = 126,
    SPELL_FAILED_TARGET_NO_RANGED_WEAPONS       = 127,
    SPELL_FAILED_TARGET_UNSKINNABLE             = 128,
    SPELL_FAILED_THIRST_SATIATED                = 129,
    SPELL_FAILED_TOO_CLOSE                      = 130,
    SPELL_FAILED_TOO_MANY_OF_ITEM               = 131,
    SPELL_FAILED_TOTEM_CATEGORY                 = 132,
    SPELL_FAILED_TOTEMS                         = 133,
    SPELL_FAILED_TRY_AGAIN                      = 134,
    SPELL_FAILED_UNIT_NOT_BEHIND                = 135,
    SPELL_FAILED_UNIT_NOT_INFRONT               = 136,
    SPELL_FAILED_VISION_OBSCURED                = 137,
    SPELL_FAILED_WRONG_PET_FOOD                 = 138,
    SPELL_FAILED_NOT_WHILE_FATIGUED             = 139,
    SPELL_FAILED_TARGET_NOT_IN_INSTANCE         = 140,
    SPELL_FAILED_NOT_WHILE_TRADING              = 141,
    SPELL_FAILED_TARGET_NOT_IN_RAID             = 142,
    SPELL_FAILED_TARGET_FREEFORALL              = 143,
    SPELL_FAILED_NO_EDIBLE_CORPSES              = 144,
    SPELL_FAILED_ONLY_BATTLEGROUNDS             = 145,
    SPELL_FAILED_TARGET_NOT_GHOST               = 146,
    SPELL_FAILED_TRANSFORM_UNUSABLE             = 147,
    SPELL_FAILED_WRONG_WEATHER                  = 148,
    SPELL_FAILED_DAMAGE_IMMUNE                  = 149,
    SPELL_FAILED_PREVENTED_BY_MECHANIC          = 150,
    SPELL_FAILED_PLAY_TIME                      = 151,
    SPELL_FAILED_REPUTATION                     = 152,
    SPELL_FAILED_MIN_SKILL                      = 153,
    SPELL_FAILED_NOT_IN_RATED_BG                = 154,
    SPELL_FAILED_NOT_ON_SHAPESHIFT              = 155,
    SPELL_FAILED_NOT_ON_STEALTHED               = 156,
    SPELL_FAILED_NOT_ON_DAMAGE_IMMUNE           = 157,
    SPELL_FAILED_NOT_ON_MOUNTED                 = 158,
    SPELL_FAILED_TOO_SHALLOW                    = 159,
    SPELL_FAILED_TARGET_NOT_IN_SANCTUARY        = 160,
    SPELL_FAILED_TARGET_IS_TRIVIAL              = 161,
    SPELL_FAILED_BM_OR_INVISGOD                 = 162,
    SPELL_FAILED_EXPERT_RIDING_REQUIREMENT      = 163,
    SPELL_FAILED_ARTISAN_RIDING_REQUIREMENT     = 164,
    SPELL_FAILED_NOT_IDLE                       = 165,
    SPELL_FAILED_NOT_INACTIVE                   = 166,
    SPELL_FAILED_PARTIAL_PLAYTIME               = 167,
    SPELL_FAILED_NO_PLAYTIME                    = 168,
    SPELL_FAILED_NOT_IN_BATTLEGROUND            = 169,
    SPELL_FAILED_NOT_IN_RAID_INSTANCE           = 170,
    SPELL_FAILED_ONLY_IN_ARENA                  = 171,
    SPELL_FAILED_TARGET_LOCKED_TO_RAID_INSTANCE = 172,
    SPELL_FAILED_ON_USE_ENCHANT                 = 173,
    SPELL_FAILED_NOT_ON_GROUND                  = 174,
    SPELL_FAILED_CUSTOM_ERROR                   = 175,
    SPELL_FAILED_CANT_DO_THAT_RIGHT_NOW         = 176,
    SPELL_FAILED_TOO_MANY_SOCKETS               = 177,
    SPELL_FAILED_INVALID_GLYPH                  = 178,
    SPELL_FAILED_UNIQUE_GLYPH                   = 179,
    SPELL_FAILED_GLYPH_SOCKET_LOCKED            = 180,
    SPELL_FAILED_NO_VALID_TARGETS               = 181,
    SPELL_FAILED_ITEM_AT_MAX_CHARGES            = 182,
    SPELL_FAILED_NOT_IN_BARBERSHOP              = 183,
    SPELL_FAILED_FISHING_TOO_LOW                = 184,
    SPELL_FAILED_ITEM_ENCHANT_TRADE_WINDOW      = 185,
    SPELL_FAILED_SUMMON_PENDING                 = 186,
    SPELL_FAILED_MAX_SOCKETS                    = 187,
    SPELL_FAILED_PET_CAN_RENAME                 = 188,
    SPELL_FAILED_TARGET_CANNOT_BE_RESURRECTED   = 189,
    SPELL_FAILED_NO_ACTIONS                     = 190,
    SPELL_FAILED_CURRENCY_WEIGHT_MISMATCH       = 191,
    SPELL_FAILED_CURRENCY_WEIGHT_NOT_ENOUGH     = 192,
    SPELL_FAILED_CURRENCY_WEIGHT_TOO_MUCH       = 193,
    SPELL_FAILED_NO_VACANT_SEAT                 = 194,
    SPELL_FAILED_NO_LIQUID                      = 195,
    SPELL_FAILED_ONLY_NOT_SWIMMING              = 196,
    SPELL_FAILED_BY_NOT_MOVING                  = 197,
    SPELL_FAILED_IN_COMBAT_RES_LIMIT_REACHED    = 198,
    SPELL_FAILED_NOT_IN_ARENA                   = 199,
    SPELL_FAILED_TARGET_NOT_ON_GROUND           = 200,
    SPELL_FAILED_EXCEEDED_WEEKLY_USAGE          = 201,
    SPELL_FAILED_NOT_IN_LFG_DUNGEON             = 202,
    SPELL_FAILED_UNKNOWN                        = 203
};

#define SPELL_CANCAST_OK SPELL_FAILED_SUCCESS

// Extra errormsg... Just to keep it in mind
enum SpellExtraError
{
    SPELL_EXTRA_ERROR_NONE = 0,     // none
    SPELL_EXTRA_ERROR_UNK1 = 1,
    SPELL_EXTRA_ERROR_UNK2 = 2,
    SPELL_EXTRA_ERROR_UNK3 = 3,
    SPELL_EXTRA_ERROR_UNK4 = 4,
    SPELL_EXTRA_ERROR_UNK5 = 5,
    SPELL_EXTRA_ERROR_UNK6 = 6,
    SPELL_EXTRA_ERROR_UNK7 = 7,
    SPELL_EXTRA_ERROR_UNK8 = 8,
    SPELL_EXTRA_ERROR_UNK9 = 9,
    SPELL_EXTRA_ERROR_UNK10 = 10,
    SPELL_EXTRA_ERROR_UNK11 = 11,
    SPELL_EXTRA_ERROR_UNK12 = 12,
    SPELL_EXTRA_ERROR_UNK13 = 13,
    SPELL_EXTRA_ERROR_UNK14 = 14,
    SPELL_EXTRA_ERROR_UNK15 = 15,
    SPELL_EXTRA_ERROR_UNK16 = 16,
    SPELL_EXTRA_ERROR_UNK17 = 17,
    SPELL_EXTRA_ERROR_UNK18 = 18,
    SPELL_EXTRA_ERROR_UNK19 = 19,
    SPELL_EXTRA_ERROR_UNK20 = 20,
    SPELL_EXTRA_ERROR_UNK21 = 21,
    SPELL_EXTRA_ERROR_UNK22 = 22,
    SPELL_EXTRA_ERROR_UNK23 = 23,
    SPELL_EXTRA_ERROR_UNK24 = 24,
    SPELL_EXTRA_ERROR_UNK25 = 25,
    SPELL_EXTRA_ERROR_UNK26 = 26,
    SPELL_EXTRA_ERROR_UNK27 = 27,
    SPELL_EXTRA_ERROR_UNK28 = 28,
    SPELL_EXTRA_ERROR_UNK29 = 29,
    SPELL_EXTRA_ERROR_UNK30 = 30,
    SPELL_EXTRA_ERROR_UNK31 = 31,
    SPELL_EXTRA_ERROR_UNK32 = 32,
    SPELL_EXTRA_ERROR_UNK33 = 33,
    SPELL_EXTRA_ERROR_UNK34 = 34,
    SPELL_EXTRA_ERROR_UNK35 = 35,
    SPELL_EXTRA_ERROR_UNK36 = 36,
    SPELL_EXTRA_ERROR_UNK37 = 37,
    SPELL_EXTRA_ERROR_UNK38 = 38,
    SPELL_EXTRA_ERROR_UNK39 = 39,
    SPELL_EXTRA_ERROR_UNK40 = 40,
    SPELL_EXTRA_ERROR_UNK41 = 41,
    SPELL_EXTRA_ERROR_UNK42 = 42,
    SPELL_EXTRA_ERROR_UNK43 = 43,
    SPELL_EXTRA_ERROR_UNK44 = 44,
    SPELL_EXTRA_ERROR_UNK45 = 45,
    SPELL_EXTRA_ERROR_UNK46 = 46,
    SPELL_EXTRA_ERROR_UNK47 = 47,
    SPELL_EXTRA_ERROR_UNK48 = 48,
    SPELL_EXTRA_ERROR_UNK49 = 49,
    SPELL_EXTRA_ERROR_UNK50 = 50,
    SPELL_EXTRA_ERROR_UNK51 = 51,
    SPELL_EXTRA_ERROR_UNK52 = 52,
    SPELL_EXTRA_ERROR_UNK53 = 53,
    SPELL_EXTRA_ERROR_UNK54 = 54,
    SPELL_EXTRA_ERROR_UNK55 = 55,
    SPELL_EXTRA_ERROR_UNK56 = 56,
    SPELL_EXTRA_ERROR_UNK57 = 57,
    SPELL_EXTRA_ERROR_UNK58 = 58,
    SPELL_EXTRA_ERROR_UNK59 = 59,
    SPELL_EXTRA_ERROR_UNK60 = 60,
    SPELL_EXTRA_ERROR_UNK61 = 61,
    SPELL_EXTRA_ERROR_UNK62 = 62,
    SPELL_EXTRA_ERROR_UNK63 = 63,
    SPELL_EXTRA_ERROR_UNK64 = 64,
    SPELL_EXTRA_ERROR_GM_ONLY = 65,     // Only GMs may use that. Your account has been reported for investigation.
    SPELL_EXTRA_ERROR_UNK66 = 66,
    SPELL_EXTRA_ERROR_UNK67 = 67,
    SPELL_EXTRA_ERROR_UNK68 = 68,
    SPELL_EXTRA_ERROR_UNK69 = 69,
    SPELL_EXTRA_ERROR_UNK70 = 70,
    SPELL_EXTRA_ERROR_UNK71 = 71,
    SPELL_EXTRA_ERROR_UNK72 = 72,
    SPELL_EXTRA_ERROR_UNK73 = 73,
    SPELL_EXTRA_ERROR_UNK74 = 74,
    SPELL_EXTRA_ERROR_UNK75 = 75,
    SPELL_EXTRA_ERROR_UNK76 = 76,
    SPELL_EXTRA_ERROR_UNK77 = 77,
    SPELL_EXTRA_ERROR_UNK78 = 78,
    SPELL_EXTRA_ERROR_UNK79 = 79,
    SPELL_EXTRA_ERROR_UNK80 = 80,
    SPELL_EXTRA_ERROR_UNK81 = 81,
    SPELL_EXTRA_ERROR_UNK82 = 82,
    SPELL_EXTRA_ERROR_MUST_HAVE_FIRE_TOTEM  = 83,       // You must have a Fire Totem active.
    SPELL_EXTRA_ERROR_UNK84 = 84,
    SPELL_EXTRA_ERROR_UNK85 = 85,
    SPELL_EXTRA_ERROR_UNK86 = 86,
    SPELL_EXTRA_ERROR_UNK87 = 87,
    SPELL_EXTRA_ERROR_UNK88 = 88,
    SPELL_EXTRA_ERROR_UNK89 = 89,
    SPELL_EXTRA_ERROR_UNK90 = 90,
    SPELL_EXTRA_ERROR_UNK91 = 91,
    SPELL_EXTRA_ERROR_UNK92 = 92,
    SPELL_EXTRA_ERROR_UNK93 = 93,
    SPELL_EXTRA_ERROR_UNK94 = 94,
    SPELL_EXTRA_ERROR_UNK95 = 95,
    SPELL_EXTRA_ERROR_UNK96 = 96,
    SPELL_EXTRA_ERROR_UNK97 = 97,
    SPELL_EXTRA_ERROR_UNK98 = 98,
    SPELL_EXTRA_ERROR_UNK99 = 99
};

enum PetTameFailure
{
    PETTAME_INVALIDCREATURE                                      = 1,
    PETTAME_TOOMANY                                              = 2,
    PETTAME_CREATUREALREADYOWNED                                 = 3,
    PETTAME_NOTTAMEABLE                                          = 4,
    PETTAME_ANOTHERSUMMONACTIVE                                  = 5,
    PETTAME_UNITSCANTTAME                                        = 6,
    PETTAME_NOPETAVAILABLE                                       = 7,
    PETTAME_INTERNALERROR                                        = 8,
    PETTAME_TOOHIGHLEVEL                                         = 9,
    PETTAME_DEAD                                                 = 10,
    PETTAME_NOTDEAD                                              = 11,
    PETTAME_CANTCONTROLEXOTIC                                    = 12,
    PETTAME_UNKNOWNERROR                                         = 13
};

enum MOUNT_FAILURE
{
    ERR_MOUNT_NOTMOUNTABLE                                       = 0,
    ERR_MOUNT_TOOFARAWAY                                         = 1,
    ERR_MOUNT_ALREADYMOUNTED                                     = 2,
    ERR_MOUNT_INVALIDMOUNTEE                                     = 3,
    ERR_MOUNT_NOTYOURPET                                         = 4,
    ERR_MOUNT_OTHER                                              = 5,
    ERR_MOUNT_LOOTING                                            = 6,
    ERR_MOUNT_RACECANTMOUNT                                      = 7,
    ERR_MOUNT_SHAPESHIFTED                                       = 8,
    ERR_MOUNT_FORCEDDISMOUNT                                     = 9
};

enum DISMOUNT_FAILURE
{
    ERR_DISMOUNT_NOPET                                           = 0,
    ERR_DISMOUNT_NOTMOUNTED                                      = 1,
    ERR_DISMOUNT_NOTYOURPET                                      = 2
};

#endif // _SPELLFAILURE_H
