/*
Copyright (c) 2014-2017 AscEmu Team <http://www.ascemu.org/>
This file is released under the MIT license. See README-MIT for more information.
*/

#pragma once

//\todo These opcodes are for wotlk, update them to cata
enum Opcodes
{
    MSG_NULL_ACTION = 0x1001,                           // new
    CMSG_BOOTME = 0x001,
    CMSG_DBLOOKUP = 0x002,
    SMSG_DBLOOKUP = 0x003,
    CMSG_QUERY_OBJECT_POSITION = 0x004,
    SMSG_QUERY_OBJECT_POSITION = 0x005,
    CMSG_QUERY_OBJECT_ROTATION = 0x006,
    SMSG_QUERY_OBJECT_ROTATION = 0x007,
    CMSG_WORLD_TELEPORT = 0x24B2,                       // new
    CMSG_TELEPORT_TO_UNIT = 0x4206,                     // new
    CMSG_ZONE_MAP = 0x00A,
    SMSG_ZONE_MAP = 0x00B,
    CMSG_DEBUG_CHANGECELLZONE = 0x00C,
    CMSG_MOVE_CHARACTER_CHEAT = 0x00D,
    SMSG_MOVE_CHARACTER_CHEAT = 0x00E,
    CMSG_RECHARGE = 0x00F,
    CMSG_LEARN_SPELL = 0x1011,                          // new
    CMSG_CREATEMONSTER = 0x011,
    CMSG_DESTROYMONSTER = 0x012,
    CMSG_CREATEITEM = 0x013,
    CMSG_CREATEGAMEOBJECT = 0x014,
    SMSG_CHECK_FOR_BOTS = 0x015,
    CMSG_MAKEMONSTERATTACKGUID = 0x016,
    CMSG_BOT_DETECTED2 = 0x017,
    CMSG_FORCEACTION = 0x018,
    CMSG_FORCEACTIONONOTHER = 0x019,
    CMSG_FORCEACTIONSHOW = 0x01A,
    SMSG_FORCEACTIONSHOW = 0x01B,
    CMSG_PETGODMODE = 0x01C,
    SMSG_PETGODMODE = 0x01D,
    SMSG_REFER_A_FRIEND_EXPIRED = 0x01E,
    CMSG_WEATHER_SPEED_CHEAT = 0x01F,
    CMSG_UNDRESSPLAYER = 0x020,
    CMSG_BEASTMASTER = 0x021,
    CMSG_GODMODE = 0x022,
    SMSG_GODMODE = 0x023,
    CMSG_CHEAT_SETMONEY = 0x024,
    CMSG_LEVEL_CHEAT = 0x025,
    CMSG_PET_LEVEL_CHEAT = 0x1027,                  // new
    CMSG_SET_WORLDSTATE = 0x027,
    CMSG_COOLDOWN_CHEAT = 0x028,
    CMSG_USE_SKILL_CHEAT = 0x029,
    CMSG_FLAG_QUEST = 0x02A,
    CMSG_FLAG_QUEST_FINISH = 0x02B,
    CMSG_CLEAR_QUEST = 0x02C,
    CMSG_SEND_EVENT = 0x02D,
    CMSG_DEBUG_AISTATE = 0x02E,
    SMSG_DEBUG_AISTATE = 0x02F,
    CMSG_DISABLE_PVP_CHEAT = 0x030,
    CMSG_ADVANCE_SPAWN_TIME = 0x031,
    SMSG_DESTRUCTIBLE_BUILDING_DAMAGE = 0x032,
    CMSG_AUTH_SRP6_BEGIN = 0x033,
    CMSG_AUTH_SRP6_PROOF = 0x034,
    CMSG_AUTH_SRP6_RECODE = 0x035,
    CMSG_CHAR_CREATE = 0x4A36,                      // new
    CMSG_CHAR_ENUM = 0x0502,                        // new
    CMSG_CHAR_DELETE = 0x6425,                      // new
    SMSG_AUTH_SRP6_RESPONSE = 0x039,
    SMSG_CHAR_CREATE = 0x2D05,                      // new
    SMSG_CHAR_ENUM = 0x10B0,                        // new
    SMSG_CHAR_DELETE = 0x0304,                      // new
    CMSG_PLAYER_LOGIN = 0x05B1,                     // new
    SMSG_NEW_WORLD = 0x79B1,                        // new
    SMSG_TRANSFER_PENDING = 0x18A6,                 // new
    SMSG_TRANSFER_ABORTED = 0x0537,                 // new
    SMSG_CHARACTER_LOGIN_FAILED = 0x4417,           // new
    SMSG_LOGIN_SETTIMESPEED = 0x4D15,               // new
    SMSG_GAMETIME_UPDATE = 0x4127,                  // new
    CMSG_GAMETIME_SET = 0x044,
    SMSG_GAMETIME_SET = 0x045,
    CMSG_GAMESPEED_SET = 0x046,
    SMSG_GAMESPEED_SET = 0x047,
    CMSG_SERVERTIME = 0x048,
    SMSG_SERVERTIME = 0x049,
    CMSG_PLAYER_LOGOUT = 0x04A,
    CMSG_LOGOUT_REQUEST = 0x0A25,                   // new
    SMSG_LOGOUT_RESPONSE = 0x0524,                  // new
    SMSG_LOGOUT_COMPLETE = 0x2137,                  // new
    CMSG_LOGOUT_CANCEL = 0x2324,                    // new
    SMSG_LOGOUT_CANCEL_ACK = 0x6514,                // new
    CMSG_NAME_QUERY = 0x2224,                       // new
    SMSG_NAME_QUERY_RESPONSE = 0x6E04,              // new
    CMSG_PET_NAME_QUERY = 0x6F24,                   // new
    SMSG_PET_NAME_QUERY_RESPONSE = 0x4C37,          // new
    CMSG_GUILD_QUERY = 0x1030,                      // new
    SMSG_GUILD_QUERY_RESPONSE = 0x0E06,             // new
    CMSG_ITEM_QUERY_SINGLE = 0x056,
    CMSG_ITEM_QUERY_MULTIPLE = 0x057,
    SMSG_ITEM_QUERY_SINGLE_RESPONSE = 0x058,
    SMSG_ITEM_QUERY_MULTIPLE_RESPONSE = 0x059,
    CMSG_PAGE_TEXT_QUERY = 0x6614,                  // new
    SMSG_PAGE_TEXT_QUERY_RESPONSE = 0x2B14,         // new
    CMSG_QUEST_QUERY = 0x0D06,                      // new
    SMSG_QUEST_QUERY_RESPONSE = 0x6936,             // new
    CMSG_GAMEOBJECT_QUERY = 0x4017,                 // new
    SMSG_GAMEOBJECT_QUERY_RESPONSE = 0x0915,        // new
    CMSG_CREATURE_QUERY = 0x2706,                   // new
    SMSG_CREATURE_QUERY_RESPONSE = 0x6024,          // new
    CMSG_WHO = 0x6C15,                              // new
    SMSG_WHO = 0x6907,                              // new
    CMSG_WHOIS = 0x6B05,                            // new
    SMSG_WHOIS = 0x6917,                            // new
    CMSG_CONTACT_LIST = 0x4534,                     // new
    SMSG_CONTACT_LIST = 0x6017,                     // new
    SMSG_FRIEND_STATUS = 0x0717,                    // new
    CMSG_ADD_FRIEND = 0x6527,                       // new
    CMSG_DEL_FRIEND = 0x6A15,                       // new
    CMSG_SET_CONTACT_NOTES = 0x6135,                // new
    CMSG_ADD_IGNORE = 0x4726,                       // new
    CMSG_DEL_IGNORE = 0x6D26,                       // new
    CMSG_GROUP_INVITE = 0x0513,                     // new
    SMSG_GROUP_INVITE = 0x31B2,                     // new
    CMSG_GROUP_CANCEL = 0x070,
    SMSG_GROUP_CANCEL = 0x071,
    CMSG_GROUP_ACCEPT = 0x072,
    CMSG_GROUP_DECLINE = 0x073,
    SMSG_GROUP_DECLINE = 0x6835,                    // new
    CMSG_GROUP_UNINVITE = 0x075,
    CMSG_GROUP_UNINVITE_GUID = 0x2E07,              // new
    SMSG_GROUP_UNINVITE = 0x077,
    CMSG_GROUP_SET_LEADER = 0x4C17,                 // new
    SMSG_GROUP_SET_LEADER = 0x0526,                 // new
    CMSG_LOOT_METHOD = 0x2F24,                      // new
    CMSG_GROUP_DISBAND = 0x2804,                    // new
    SMSG_GROUP_DESTROYED = 0x2207,                  // new
    SMSG_GROUP_LIST = 0x4C24,                       // new
    SMSG_PARTY_MEMBER_STATS = 0x07E,
    SMSG_PARTY_COMMAND_RESULT = 0x6E07,             // new
    UMSG_UPDATE_GROUP_MEMBERS = 0x080,
    CMSG_GUILD_CREATE = 0x081,
    CMSG_GUILD_INVITE = 0x082,
    SMSG_GUILD_INVITE = 0x083,
    CMSG_GUILD_ACCEPT = 0x084,
    CMSG_GUILD_DECLINE = 0x085,
    SMSG_GUILD_DECLINE = 0x086,
    CMSG_GUILD_INFO = 0x087,
    SMSG_GUILD_INFO = 0x088,
    CMSG_GUILD_ROSTER = 0x089,
    SMSG_GUILD_ROSTER = 0x08A,
    CMSG_GUILD_PROMOTE = 0x08B,
    CMSG_GUILD_DEMOTE = 0x08C,
    CMSG_GUILD_LEAVE = 0x08D,
    CMSG_GUILD_REMOVE = 0x08E,
    CMSG_GUILD_DISBAND = 0x08F,
    CMSG_GUILD_LEADER = 0x090,
    CMSG_GUILD_MOTD = 0x091,
    SMSG_GUILD_EVENT = 0x0705,                      // new
    SMSG_GUILD_COMMAND_RESULT = 0x093,
    UMSG_UPDATE_GUILD = 0x094,
    CMSG_MESSAGECHAT = 0x095,                       // unused
    SMSG_MESSAGECHAT = 0x2026,                      // new
    CMSG_JOIN_CHANNEL = 0x0156,                     // new
    CMSG_LEAVE_CHANNEL = 0x2D56,                    // new
    SMSG_CHANNEL_NOTIFY = 0x0825,                   // new
    CMSG_CHANNEL_LIST = 0x1556,                     // new
    SMSG_CHANNEL_LIST = 0x2214,                     // new
    CMSG_CHANNEL_PASSWORD = 0x2556,                 // new
    CMSG_CHANNEL_SET_OWNER = 0x3556,                // new
    CMSG_CHANNEL_OWNER = 0x3D44,                    // new
    CMSG_CHANNEL_MODERATOR = 0x0146,                // new
    CMSG_CHANNEL_UNMODERATOR = 0x1954,              // new
    CMSG_CHANNEL_MUTE = 0x2554,                     // new
    CMSG_CHANNEL_UNMUTE = 0x3554,                   // new
    CMSG_CHANNEL_INVITE = 0x0144,                   // new
    CMSG_CHANNEL_KICK = 0x3156,                     // new
    CMSG_CHANNEL_BAN = 0x3D56,                      // new
    CMSG_CHANNEL_UNBAN = 0x2D46,                    // new
    CMSG_CHANNEL_ANNOUNCEMENTS = 0x1146,            // new
    CMSG_CHANNEL_MODERATE = 0x2944,                 // new
    SMSG_UPDATE_OBJECT = 0x4715,                // new
    SMSG_DESTROY_OBJECT = 0x4724,               // new
    CMSG_USE_ITEM = 0x2C06,                     // new
    CMSG_OPEN_ITEM = 0x6A34,                    // new
    CMSG_READ_ITEM = 0x2F16,                    // new
    SMSG_READ_ITEM_OK = 0x2605,                 // new
    SMSG_READ_ITEM_FAILED = 0x0F16,             // new
    SMSG_ITEM_COOLDOWN = 0x4D14,                // new
    CMSG_GAMEOBJ_USE = 0x4E17,                  // new
    CMSG_DESTROY_ITEMS = 0x0B2,
    SMSG_GAMEOBJECT_CUSTOM_ANIM = 0x0B3,
    CMSG_AREATRIGGER = 0x0937,                  // new
    MSG_MOVE_START_FORWARD = 0x7814,            // new
    MSG_MOVE_START_BACKWARD = 0x330A,           // new
    MSG_MOVE_STOP = 0x320A,                     // new
    MSG_MOVE_START_STRAFE_LEFT = 0x3A16,        // new
    MSG_MOVE_START_STRAFE_RIGHT = 0x3A02,       // new
    MSG_MOVE_STOP_STRAFE = 0x3002,              // new
    MSG_MOVE_JUMP = 0x7A06,                     // new
    MSG_MOVE_START_TURN_LEFT = 0x700C,          // new
    MSG_MOVE_START_TURN_RIGHT = 0x7000,         // new
    MSG_MOVE_STOP_TURN = 0x331E,                // new
    MSG_MOVE_START_PITCH_UP = 0x3304,           // new
    MSG_MOVE_START_PITCH_DOWN = 0x3908,         // new
    MSG_MOVE_STOP_PITCH = 0x7216,               // new
    MSG_MOVE_SET_RUN_MODE = 0x791A,             // new
    MSG_MOVE_SET_WALK_MODE = 0x7002,            // new
    MSG_MOVE_TOGGLE_LOGGING = 0x10C5,           // new
    MSG_MOVE_TELEPORT = 0x55A0,                 // new
    MSG_MOVE_TELEPORT_CHEAT = 0x10C7,           // new
    MSG_MOVE_TELEPORT_ACK = 0x390C,             // new
    MSG_MOVE_TOGGLE_FALL_LOGGING = 0x10C9,      // new
    MSG_MOVE_FALL_LAND = 0x380A,                // new
    MSG_MOVE_START_SWIM = 0x3206,               // new
    MSG_MOVE_STOP_SWIM = 0x3802,                // new
    MSG_MOVE_SET_RUN_SPEED_CHEAT = 0x10CD,      // new
    MSG_MOVE_SET_RUN_SPEED = 0x3DB5,            // new
    MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT = 0x10CF, // new
    MSG_MOVE_SET_RUN_BACK_SPEED = 0x71B1,       // new
    MSG_MOVE_SET_WALK_SPEED_CHEAT = 0x10D1,     // new
    MSG_MOVE_SET_WALK_SPEED = 0x1DA4,           // new
    MSG_MOVE_SET_SWIM_SPEED_CHEAT = 0x10D3,     // new
    MSG_MOVE_SET_SWIM_SPEED = 0x15A7,           // new
    MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT = 0x10D5,    // new
    MSG_MOVE_SET_SWIM_BACK_SPEED = 0x5CA6,      // new
    MSG_MOVE_SET_ALL_SPEED_CHEAT = 0x10D7,      // new
    MSG_MOVE_SET_TURN_RATE_CHEAT = 0x10D8,      // new
    MSG_MOVE_SET_TURN_RATE = 0x30A5,            // new
    MSG_MOVE_TOGGLE_COLLISION_CHEAT = 0x10DA,   // new
    MSG_MOVE_SET_FACING = 0x7914,               // new
    MSG_MOVE_SET_PITCH = 0x7312,                // new
    MSG_MOVE_WORLDPORT_ACK = 0x2411,            // new
    SMSG_MONSTER_MOVE = 0x6E17,                 // new
    SMSG_MOVE_WATER_WALK = 0x75B1,              // new
    SMSG_MOVE_LAND_WALK = 0x34B7,               // new
    MSG_MOVE_SET_RAW_POSITION_ACK = 0x0E0,
    CMSG_MOVE_SET_RAW_POSITION = 0x0339,        // new
    SMSG_FORCE_RUN_SPEED_CHANGE = 0x14A6,       // new
    CMSG_FORCE_RUN_SPEED_CHANGE_ACK = 0x7818,   // new
    SMSG_FORCE_RUN_BACK_SPEED_CHANGE = 0x3DA6,  // new
    CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK = 0x3216,  // new
    SMSG_FORCE_SWIM_SPEED_CHANGE = 0x59B5,      // new
    CMSG_FORCE_SWIM_SPEED_CHANGE_ACK = 0x7A10,  // new
    SMSG_FORCE_MOVE_ROOT = 0x7DA0,              // new
    CMSG_FORCE_MOVE_ROOT_ACK = 0x701E,          // new
    SMSG_FORCE_MOVE_UNROOT = 0x7DB4,            // new
    CMSG_FORCE_MOVE_UNROOT_ACK = 0x7808,        // new
    MSG_MOVE_ROOT = 0x10ED,                     // new
    MSG_MOVE_UNROOT = 0x10EE,                   // new
    MSG_MOVE_HEARTBEAT = 0x3914,                // new
    SMSG_MOVE_KNOCK_BACK = 0x5CB4,              // new
    CMSG_MOVE_KNOCK_BACK_ACK = 0x721C,          // new
    MSG_MOVE_KNOCK_BACK = 0x0F1,
    SMSG_MOVE_FEATHER_FALL = 0x79B0,            // new
    SMSG_MOVE_NORMAL_FALL = 0x51B6,             // new
    SMSG_MOVE_SET_HOVER = 0x5CB3,               // new
    SMSG_MOVE_UNSET_HOVER = 0x51B3,             // new
    CMSG_MOVE_HOVER_ACK = 0x10F7,               // new
    MSG_MOVE_HOVER = 0x10F8,                    // new
    CMSG_TRIGGER_CINEMATIC_CHEAT = 0x0F8,
    CMSG_OPENING_CINEMATIC = 0x0F9,
    SMSG_TRIGGER_CINEMATIC = 0x6C27,            // new
    CMSG_NEXT_CINEMATIC_CAMERA = 0x2014,        // new
    CMSG_COMPLETE_CINEMATIC = 0x2116,           // new
    SMSG_TUTORIAL_FLAGS = 0x0B35,               // new
    CMSG_TUTORIAL_FLAG = 0x6C26,                // new
    CMSG_TUTORIAL_CLEAR = 0x6515,               // new
    CMSG_TUTORIAL_RESET = 0x2726,               // new
    CMSG_STANDSTATECHANGE = 0x0535,                         // new
    CMSG_EMOTE = 0x4C26,                                    // new
    SMSG_EMOTE = 0x0A34,                                    // new
    CMSG_TEXT_EMOTE = 0x2E24,                               // new
    SMSG_TEXT_EMOTE = 0x0B05,                               // new
    CMSG_AUTOEQUIP_GROUND_ITEM = 0x1107,                    // new
    CMSG_AUTOSTORE_GROUND_ITEM = 0x1108,                    // new
    CMSG_AUTOSTORE_LOOT_ITEM = 0x0E34,                      // new
    CMSG_STORE_LOOT_IN_SLOT = 0x110A,                       // new
    CMSG_AUTOEQUIP_ITEM = 0x4304,                           // new
    CMSG_AUTOSTORE_BAG_ITEM = 0x0236,                       // new
    CMSG_SWAP_ITEM = 0x6326,                                // new
    CMSG_SWAP_INV_ITEM = 0x2614,                            // new
    CMSG_SPLIT_ITEM = 0x0F17,                               // new
    CMSG_AUTOEQUIP_ITEM_SLOT = 0x4A17,                      // new
    OBSOLETE_DROP_ITEM = 0x110,
    CMSG_DESTROYITEM = 0x4A27,                              // new
    SMSG_INVENTORY_CHANGE_FAILURE = 0x2236,                 // new
    SMSG_OPEN_CONTAINER = 0x113,
    CMSG_INSPECT = 0x0927,                          // new
    SMSG_INSPECT = 0x4014,                          // new
    CMSG_INITIATE_TRADE = 0x7916,                   // new
    CMSG_BEGIN_TRADE = 0x721E,                      // new
    CMSG_BUSY_TRADE = 0x118,
    CMSG_IGNORE_TRADE = 0x119,
    CMSG_ACCEPT_TRADE = 0x7110,                     // new
    CMSG_UNACCEPT_TRADE = 0x391A,                   // new
    CMSG_CANCEL_TRADE = 0x731E,                     // new
    CMSG_SET_TRADE_ITEM = 0x7B0C,                   // new
    CMSG_CLEAR_TRADE_ITEM = 0x7018,                 // new
    CMSG_SET_TRADE_GOLD = 0x3008,                   // new
    SMSG_TRADE_STATUS = 0x5CA3,                     // new
    SMSG_TRADE_STATUS_EXTENDED = 0x70A2,            // new
    SMSG_INITIALIZE_FACTIONS = 0x4634,              // new
    SMSG_SET_FACTION_VISIBLE = 0x123,
    SMSG_SET_FACTION_STANDING = 0x124,
    CMSG_SET_FACTION_ATWAR = 0x125,
    CMSG_SET_FACTION_CHEAT = 0x126,
    SMSG_SET_PROFICIENCY = 0x6207,                  // new
    CMSG_SET_ACTION_BUTTON = 0x6F06,                // new
    SMSG_ACTION_BUTTONS = 0x38B5,                   // new
    SMSG_INITIAL_SPELLS = 0x0104,                   // new
    SMSG_LEARNED_SPELL = 0x58A2,                    // new
    SMSG_SUPERCEDED_SPELL = 0x35B0,                 // new
    CMSG_NEW_SPELL_SLOT = 0x112E,                   // new
    CMSG_CAST_SPELL = 0x4C07,                       // new
    CMSG_CANCEL_CAST = 0x012F,                      // new
    SMSG_CAST_FAILED = 0x130,
    SMSG_SPELL_START = 0x6415,                      // new
    SMSG_SPELL_GO = 0x6E16,                         // new
    SMSG_SPELL_FAILURE = 0x0C34,                    // new
    SMSG_SPELL_COOLDOWN = 0x4B16,                   // new
    SMSG_COOLDOWN_EVENT = 0x4F26,                   // new
    CMSG_CANCEL_AURA = 0x136,
    SMSG_EQUIPMENT_SET_SAVED = 0x2216,              // new
    SMSG_PET_CAST_FAILED = 0x138,
    MSG_CHANNEL_START = 0x0A15,                     // new
    MSG_CHANNEL_UPDATE = 0x2417,                    // new
    CMSG_CANCEL_CHANNELLING = 0x6C25,               // new
    SMSG_AI_REACTION = 0x13C,
    CMSG_SET_SELECTION = 0x0506,                    // new
    CMSG_EQUIPMENT_SET_DELETE = 0x13E,
    CMSG_UNUSED = 0x13F,
    CMSG_UNUSED2 = 0x140,
    CMSG_ATTACKSWING = 0x0926,                      // new
    CMSG_ATTACKSTOP = 0x4106,                       // new
    SMSG_ATTACKSTART = 0x2D15,                      // new
    SMSG_ATTACKSTOP = 0x0934,                       // new
    SMSG_ATTACKSWING_NOTINRANGE = 0x0B36,           // new
    SMSG_ATTACKSWING_BADFACING = 0x6C07,            // new
    SMSG_ATTACKSWING_NOTSTANDING = 0x2B26,          // new
    SMSG_ATTACKSWING_DEADTARGET = 0x148,
    SMSG_ATTACKSWING_CANT_ATTACK = 0x0016,          // new
    SMSG_ATTACKERSTATEUPDATE = 0x0B25,              // new
    SMSG_VICTIMSTATEUPDATE_OBSOLETE = 0x14B,
    SMSG_DAMAGE_DONE_OBSOLETE = 0x14C,
    SMSG_DAMAGE_TAKEN_OBSOLETE = 0x14D,
    SMSG_CANCEL_COMBAT = 0x4F04,                    // new
    SMSG_SPELLBREAKLOG = 0x6B17,                    // new
    SMSG_SPELLHEALLOG = 0x2816,                     // new
    SMSG_SPELLENERGIZELOG = 0x0414,                 // new
    SMSG_BREAK_TARGET = 0x152,
    CMSG_SAVE_PLAYER = 0x153,
    CMSG_SETDEATHBINDPOINT = 0x154,
    SMSG_BINDPOINTUPDATE = 0x0527,                  // new
    CMSG_GETDEATHBINDZONE = 0x156,
    SMSG_BINDZONEREPLY = 0x157,
    SMSG_PLAYERBOUND = 0x2516,                      // new
    SMSG_CLIENT_CONTROL_UPDATE = 0x2837,            // new
    CMSG_REPOP_REQUEST = 0x6235,                    // new
    SMSG_RESURRECT_REQUEST = 0x2905,                // new
    CMSG_RESURRECT_RESPONSE = 0x6827,               // new
    CMSG_LOOT = 0x0127,                             // new
    CMSG_LOOT_MONEY = 0x6227,                       // new
    CMSG_LOOT_RELEASE = 0x2007,                     // new
    SMSG_LOOT_RESPONSE = 0x4C16,                    // new
    SMSG_LOOT_RELEASE_RESPONSE = 0x6D25,            // new
    SMSG_LOOT_REMOVED = 0x6817,                     // new
    SMSG_LOOT_MONEY_NOTIFY = 0x2836,                // new
    SMSG_LOOT_ITEM_NOTIFY = 0x6D15,                 // new
    SMSG_LOOT_CLEAR_MONEY = 0x2B37,                 // new
    SMSG_ITEM_PUSH_RESULT = 0x166,
    SMSG_DUEL_REQUESTED = 0x4504,                   // new
    SMSG_DUEL_OUTOFBOUNDS = 0x0C26,                 // new
    SMSG_DUEL_INBOUNDS = 0x0A27,                    // new
    SMSG_DUEL_COMPLETE = 0x2527,                    // new
    SMSG_DUEL_WINNER = 0x2D36,                      // new
    CMSG_DUEL_ACCEPTED = 0x2136,                    // new
    CMSG_DUEL_CANCELLED = 0x6624,                   // new
    SMSG_MOUNTRESULT = 0x16E,
    SMSG_DISMOUNTRESULT = 0x16F,
    SMSG_PUREMOUNT_CANCELLED_OBSOLETE = 0x170,
    CMSG_MOUNTSPECIAL_ANIM = 0x171,
    SMSG_MOUNTSPECIAL_ANIM = 0x172,
    SMSG_PET_TAME_FAILURE = 0x173,
    CMSG_PET_SET_ACTION = 0x174,
    CMSG_PET_ACTION = 0x175,
    CMSG_PET_ABANDON = 0x176,
    CMSG_PET_RENAME = 0x177,
    SMSG_PET_NAME_INVALID = 0x178,
    SMSG_PET_SPELLS = 0x4114,                       // new
    SMSG_PET_MODE = 0x17A,
    CMSG_GOSSIP_HELLO = 0x4525,                     // new
    CMSG_GOSSIP_SELECT_OPTION = 0x0216,             // new
    SMSG_GOSSIP_MESSAGE = 0x2035,                   // new
    SMSG_GOSSIP_COMPLETE = 0x0806,                  // new
    CMSG_NPC_TEXT_QUERY = 0x4E24,                   // new
    SMSG_NPC_TEXT_UPDATE = 0x4436,                  // new
    SMSG_NPC_WONT_TALK = 0x1182,                    // new
    CMSG_QUESTGIVER_STATUS_QUERY = 0x4407,          // new
    SMSG_QUESTGIVER_STATUS = 0x2115,                // new
    CMSG_QUESTGIVER_HELLO = 0x0D17,                 // new
    SMSG_QUESTGIVER_QUEST_LIST = 0x0134,            // new
    CMSG_QUESTGIVER_QUERY_QUEST = 0x2F14,           // new
    CMSG_QUESTGIVER_QUEST_AUTOLAUNCH = 0x1188,      // new
    SMSG_QUESTGIVER_QUEST_DETAILS = 0x2425,         // new
    CMSG_QUESTGIVER_ACCEPT_QUEST = 0x6B37,          // new
    CMSG_QUESTGIVER_COMPLETE_QUEST = 0x0114,        // new
    SMSG_QUESTGIVER_REQUEST_ITEMS = 0x6236,         // new
    CMSG_QUESTGIVER_REQUEST_REWARD = 0x2534,        // new
    SMSG_QUESTGIVER_OFFER_REWARD = 0x2427,          // new
    CMSG_QUESTGIVER_CHOOSE_REWARD = 0x2125,         // new
    SMSG_QUESTGIVER_QUEST_INVALID = 0x4016,         // new
    CMSG_QUESTGIVER_CANCEL = 0x1191,                // new
    SMSG_QUESTGIVER_QUEST_COMPLETE = 0x55A4,        // new
    SMSG_QUESTGIVER_QUEST_FAILED = 0x4236,          // new
    CMSG_QUESTLOG_SWAP_QUEST = 0x1194,              // new
    CMSG_QUESTLOG_REMOVE_QUEST = 0x0D16,            // new
    SMSG_QUESTLOG_FULL = 0x0E36,                    // new
    SMSG_QUESTUPDATE_FAILED = 0x6324,               // new
    SMSG_QUESTUPDATE_FAILEDTIMER = 0x6427,          // new
    SMSG_QUESTUPDATE_COMPLETE = 0x2937,             // new
    SMSG_QUESTUPDATE_ADD_KILL = 0x0D27,             // new
    SMSG_QUESTUPDATE_ADD_ITEM = 0x119B,             // new
    CMSG_QUEST_CONFIRM_ACCEPT = 0x0D15,             // new
    SMSG_QUEST_CONFIRM_ACCEPT = 0x6F07,             // new
    CMSG_PUSHQUESTTOPARTY = 0x4B14,                 // new
    CMSG_LIST_INVENTORY = 0x2806,               // new
    SMSG_LIST_INVENTORY = 0x7CB0,               // new
    CMSG_SELL_ITEM = 0x4E15,                    // new
    SMSG_SELL_ITEM = 0x6105,                    // new
    CMSG_BUY_ITEM = 0x0736,                     // new
    CMSG_BUY_ITEM_IN_SLOT = 0x1A3,
    SMSG_BUY_ITEM = 0x0F26,                     // new
    SMSG_BUY_FAILED = 0x6435,                   // new
    CMSG_TAXICLEARALLNODES = 0x0000,            // new
    CMSG_TAXIENABLEALLNODES = 0x0000,           // new
    CMSG_TAXISHOWNODES = 0x0000,                // new
    SMSG_SHOWTAXINODES = 0x2A36,                // new
    CMSG_TAXINODE_STATUS_QUERY = 0x2F25,        // new
    SMSG_TAXINODE_STATUS = 0x2936,              // new
    CMSG_TAXIQUERYAVAILABLENODES = 0x6C06,      // new
    CMSG_ACTIVATETAXI = 0x6E06,                 // new
    SMSG_ACTIVATETAXIREPLY = 0x6A37,            // new
    SMSG_NEW_TAXI_PATH = 0x4B35,                // new
    CMSG_TRAINER_LIST = 0x2336,                 // new
    SMSG_TRAINER_LIST = 0x4414,                 // new
    CMSG_TRAINER_BUY_SPELL = 0x4415,            // new
    SMSG_TRAINER_BUY_SUCCEEDED = 0x6A05,        // new
    SMSG_TRAINER_BUY_FAILED = 0x0000,           // new
    CMSG_BINDER_ACTIVATE = 0x4006,              // new
    SMSG_PLAYERBINDERROR = 0x6A24,              // new
    CMSG_BANKER_ACTIVATE = 0x1B7,
    SMSG_SHOW_BANK = 0x1B8,
    CMSG_BUY_BANK_SLOT = 0x1B9,
    SMSG_BUY_BANK_SLOT_RESULT = 0x1BA,
    CMSG_PETITION_SHOWLIST = 0x4617,            // new
    SMSG_PETITION_SHOWLIST = 0x6405,            // new
    CMSG_PETITION_BUY = 0x4E05,                 // new
    CMSG_PETITION_SHOW_SIGNATURES = 0x4F15,     // new
    SMSG_PETITION_SHOW_SIGNATURES = 0x0716,     // new
    CMSG_PETITION_SIGN = 0x0E04,                // new
    SMSG_PETITION_SIGN_RESULTS = 0x6217,        // new
    MSG_PETITION_DECLINE = 0x4905,              // new
    CMSG_OFFER_PETITION = 0x4817,               // new
    CMSG_TURN_IN_PETITION = 0x0B27,             // new
    SMSG_TURN_IN_PETITION_RESULTS = 0x0F07,     // new
    CMSG_PETITION_QUERY = 0x4424,               // new
    SMSG_PETITION_QUERY_RESPONSE = 0x4B37,      // new
    SMSG_FISH_NOT_HOOKED = 0x1C8,
    SMSG_FISH_ESCAPED = 0x1C9,
    CMSG_BUG = 0x1CA,
    SMSG_NOTIFICATION = 0x1CB,
    CMSG_PLAYED_TIME = 0x0804,                      // new
    SMSG_PLAYED_TIME = 0x6037,                      // new
    CMSG_QUERY_TIME = 0x0A36,                       // new
    SMSG_QUERY_TIME_RESPONSE = 0x2124,              // new
    SMSG_LOG_XPGAIN = 0x1D0,
    SMSG_AURACASTLOG_OBSOLETE = 0x1D1,
    CMSG_RECLAIM_CORPSE = 0x4036,                   // new
    CMSG_WRAP_ITEM = 0x1D3,
    SMSG_LEVELUP_INFO = 0x0435,                     // new
    MSG_MINIMAP_PING = 0x1D5,
    SMSG_RESISTLOG = 0x1D6,
    SMSG_ENCHANTMENTLOG = 0x6035,                   // new
    CMSG_SET_SKILL_CHEAT = 0x1D8,
    SMSG_START_MIRROR_TIMER = 0x6824,               // new
    SMSG_PAUSE_MIRROR_TIMER = 0x4015,               // new
    SMSG_STOP_MIRROR_TIMER = 0x0B06,                // new
    CMSG_PING = 0x444D,                             // new
    SMSG_PONG = 0x4D42,                             // new
    SMSG_CLEAR_COOLDOWN = 0x1DE,
    SMSG_GAMEOBJECT_PAGETEXT = 0x1DF,
    CMSG_SETSHEATHED = 0x4326,                      // new
    SMSG_COOLDOWN_CHEAT = 0x1E1,
    SMSG_SPELL_DELAYED = 0x0715,                    // new
    CMSG_QUEST_POI_QUERY = 0x4037,                  // new
    SMSG_QUEST_POI_QUERY_RESPONSE = 0x6304,         // new
    CMSG_GHOST = 0x1E5,
    CMSG_GM_INVIS = 0x0000,                         // new
    SMSG_INVALID_PROMOTION_CODE = 0x1E7,
    MSG_GM_BIND_OTHER = 0x0000,                     // new
    MSG_GM_SUMMON = 0x0000,                         // new
    SMSG_ITEM_TIME_UPDATE = 0x2407,                 // new
    SMSG_ITEM_ENCHANT_TIME_UPDATE = 0x0F27,         // new
    SMSG_AUTH_CHALLENGE = 0x4542,                   // new
    CMSG_AUTH_SESSION = 0x0449,                     // new
    SMSG_AUTH_RESPONSE = 0x5DB6,                    // new
    MSG_GM_SHOWLABEL = 0x0000,                      // new
    CMSG_PET_CAST_SPELL = 0x6337,                   // new
    MSG_SAVE_GUILD_EMBLEM = 0x1F1,
    MSG_TABARDVENDOR_ACTIVATE = 0x6926,             // new
    SMSG_PLAY_SPELL_VISUAL = 0x55A5,                // new
    CMSG_ZONEUPDATE = 0x4F37,                       // new
    SMSG_PARTYKILLLOG = 0x1F5,
    SMSG_COMPRESSED_UPDATE_OBJECT = 0x11F7,         // new
    SMSG_PLAY_SPELL_IMPACT = 0x1F7,
    SMSG_EXPLORATION_EXPERIENCE = 0x6716,           // new
    CMSG_GM_SET_SECURITY_GROUP = 0x0000,            // new
    CMSG_GM_NUKE = 0x0000,                          // new
    MSG_RANDOM_ROLL = 0x0905,                       // new
    SMSG_ENVIRONMENTALDAMAGELOG = 0x6C05,           // new
    CMSG_RWHOIS_OBSOLETE = 0x1FD,
    SMSG_RWHOIS = 0x1FE,
    SMSG_LFG_PLAYER_REWARD = 0x1FF,
    SMSG_LFG_TELEPORT_DENIED = 0x200,
    CMSG_UNLEARN_SPELL = 0x1202,                    // new
    CMSG_UNLEARN_SKILL = 0x6106,                    // new
    SMSG_REMOVED_SPELL = 0x4804,                    // new
    CMSG_DECHARGE = 0x204,
    CMSG_GMTICKET_CREATE = 0x0137,                  // new
    SMSG_GMTICKET_CREATE = 0x2107,                  // new
    CMSG_GMTICKET_UPDATETEXT = 0x0636,              // new
    SMSG_GMTICKET_UPDATETEXT = 0x6535,              // new
    SMSG_ACCOUNT_DATA_TIMES = 0x4B05,               // new
    CMSG_REQUEST_ACCOUNT_DATA = 0x20A,
    CMSG_UPDATE_ACCOUNT_DATA = 0x4736,              // new
    SMSG_UPDATE_ACCOUNT_DATA = 0x6837,              // new
    SMSG_CLEAR_FAR_SIGHT_IMMEDIATE = 0x20D,
    SMSG_POWERGAINLOG_OBSOLETE = 0x20E,
    CMSG_GM_TEACH = 0x20F,
    CMSG_GM_CREATE_ITEM_TARGET = 0x210,
    CMSG_GMTICKET_GETTICKET = 0x0326,               // new
    SMSG_GMTICKET_GETTICKET = 0x2C15,               // new
    CMSG_UNLEARN_TALENTS = 0x213,
    SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT = 0x214,
    SMSG_GAMEOBJECT_DESPAWN_ANIM = 0x6735,          // new
    MSG_CORPSE_QUERY = 0x4336,                      // new
    CMSG_GMTICKET_DELETETICKET = 0x6B14,            // new
    SMSG_GMTICKET_DELETETICKET = 0x6D17,            // new
    SMSG_CHAT_WRONG_FACTION = 0x6724,               // new
    CMSG_GMTICKET_SYSTEMSTATUS = 0x4205,            // new
    SMSG_GMTICKET_SYSTEMSTATUS = 0x0D35,            // new
    CMSG_SPIRIT_HEALER_ACTIVATE = 0x2E26,           // new
    CMSG_SET_STAT_CHEAT = 0x21D,
    SMSG_SET_REST_START_OBSOLETE = 0x21E,
    CMSG_SKILL_BUY_STEP = 0x21F,
    CMSG_SKILL_BUY_RANK = 0x220,
    CMSG_XP_CHEAT = 0x221,
    SMSG_SPIRIT_HEALER_CONFIRM = 0x4917,            // new
    CMSG_CHARACTER_POINT_CHEAT = 0x223,
    SMSG_GOSSIP_POI = 0x4316,                       // new
    CMSG_CHAT_IGNORED = 0x225,
    CMSG_GM_VISION = 0x226,
    CMSG_SERVER_COMMAND = 0x227,
    CMSG_GM_SILENCE = 0x228,
    CMSG_GM_REVEALTO = 0x229,
    CMSG_GM_RESURRECT = 0x22A,
    CMSG_GM_SUMMONMOB = 0x0000,                     // new
    CMSG_GM_MOVECORPSE = 0x22C,
    CMSG_GM_FREEZE = 0x22D,
    CMSG_GM_UBERINVIS = 0x22E,
    CMSG_GM_REQUEST_PLAYER_INFO = 0x22F,
    SMSG_GM_PLAYER_INFO = 0x4A15,                   // new
    CMSG_GUILD_RANK = 0x231,
    CMSG_GUILD_ADD_RANK = 0x232,
    CMSG_GUILD_DEL_RANK = 0x233,
    CMSG_GUILD_SET_PUBLIC_NOTE = 0x0000,
    CMSG_GUILD_SET_OFFICER_NOTE = 0x235,
    SMSG_LOGIN_VERIFY_WORLD = 0x2005,               // new
    CMSG_CLEAR_EXPLORATION = 0x237,
    CMSG_SEND_MAIL = 0x0523,                        // new
    SMSG_SEND_MAIL_RESULT = 0x4927,                 // new
    CMSG_GET_MAIL_LIST = 0x4D37,                    // new
    SMSG_MAIL_LIST_RESULT = 0x4217,                 // new
    CMSG_BATTLEFIELD_LIST = 0x3814,                 // new
    SMSG_BATTLEFIELD_LIST = 0x71B5,                 // new
    CMSG_BATTLEFIELD_JOIN = 0x123F,                 // new
    SMSG_BATTLEFIELD_WIN_OBSOLETE = 0x23F,
    SMSG_BATTLEFIELD_LOSE_OBSOLETE = 0x240,
    CMSG_TAXICLEARNODE = 0x241,
    CMSG_TAXIENABLENODE = 0x242,
    CMSG_ITEM_TEXT_QUERY = 0x2406,                  // new
    SMSG_ITEM_TEXT_QUERY_RESPONSE = 0x2725,         // new
    CMSG_MAIL_TAKE_MONEY = 0x4034,                  // new
    CMSG_MAIL_TAKE_ITEM = 0x2B06,                   // new
    CMSG_MAIL_MARK_AS_READ = 0x0C07,                // new
    CMSG_MAIL_RETURN_TO_SENDER = 0x0816,            // new
    CMSG_MAIL_DELETE = 0x6104,                      // new
    CMSG_MAIL_CREATE_TEXT_ITEM = 0x0B14,            // new
    SMSG_SPELLLOGMISS = 0x0625,                     // new
    SMSG_SPELLLOGEXECUTE = 0x0626,                  // new
    SMSG_DEBUGAURAPROC = 0x24D,
    SMSG_PERIODICAURALOG = 0x0416,                  // new
    SMSG_SPELLDAMAGESHIELD = 0x2927,                // new
    SMSG_SPELLNONMELEEDAMAGELOG = 0x4315,           // new
    CMSG_LEARN_TALENT = 0x6E24,                     // new
    SMSG_RESURRECT_FAILED = 0x252,
    CMSG_TOGGLE_PVP = 0x6815,                       // new
    SMSG_ZONE_UNDER_ATTACK = 0x254,
    MSG_AUCTION_HELLO = 0x2307,                     // new
    CMSG_AUCTION_SELL_ITEM = 0x4A06,                // new
    CMSG_AUCTION_REMOVE_ITEM = 0x6426,              // new
    CMSG_AUCTION_LIST_ITEMS = 0x0324,               // new
    CMSG_AUCTION_LIST_OWNER_ITEMS = 0x0206,         // new
    CMSG_AUCTION_PLACE_BID = 0x2306,                // new
    SMSG_AUCTION_COMMAND_RESULT = 0x4C25,           // new
    SMSG_AUCTION_LIST_RESULT = 0x6637,              // new
    SMSG_AUCTION_OWNER_LIST_RESULT = 0x6C34,        // new
    SMSG_AUCTION_BIDDER_NOTIFICATION = 0x4E27,      // new
    SMSG_AUCTION_OWNER_NOTIFICATION = 0x4116,       // new
    SMSG_PROCRESIST = 0x260,
    SMSG_STANDSTATE_CHANGE_FAILURE_OBSOLETE = 0x261,
    SMSG_DISPEL_FAILED = 0x262,
    SMSG_SPELLORDAMAGE_IMMUNE = 0x263,
    CMSG_AUCTION_LIST_BIDDER_ITEMS = 0x6937,            // new
    SMSG_AUCTION_BIDDER_LIST_RESULT = 0x0027,           // new
    SMSG_SET_FLAT_SPELL_MODIFIER = 0x2834,              // new
    SMSG_SET_PCT_SPELL_MODIFIER = 0x0224,               // new
    CMSG_SET_AMMO = 0x268,
    SMSG_CORPSE_RECLAIM_DELAY = 0x0D34,                 // new
    CMSG_SET_ACTIVE_MOVER = 0x3314,                     // new
    CMSG_PET_CANCEL_AURA = 0x26B,
    CMSG_PLAYER_AI_CHEAT = 0x26C,
    CMSG_CANCEL_AUTO_REPEAT_SPELL = 0x6C35,             // new
    MSG_GM_ACCOUNT_ONLINE = 0x26E,
    MSG_LIST_STABLED_PETS = 0x26F,
    CMSG_STABLE_PET = 0x270,
    CMSG_UNSTABLE_PET = 0x271,
    CMSG_BUY_STABLE_SLOT = 0x272,
    SMSG_STABLE_RESULT = 0x273,
    CMSG_STABLE_REVIVE_PET = 0x274,
    CMSG_STABLE_SWAP_PET = 0x275,
    MSG_QUEST_PUSH_RESULT = 0x276,
    SMSG_PLAY_MUSIC = 0x277,
    SMSG_PLAY_OBJECT_SOUND = 0x278,
    CMSG_REQUEST_PET_INFO = 0x279,
    CMSG_FAR_SIGHT = 0x27A,
    SMSG_SPELLDISPELLOG = 0x4516,                       // new
    SMSG_DAMAGE_CALC_LOG = 0x27C,
    CMSG_ENABLE_DAMAGE_LOG = 0x27D,
    CMSG_GROUP_CHANGE_SUB_GROUP = 0x27E,
    CMSG_REQUEST_PARTY_MEMBER_STATS = 0x27F,
    CMSG_GROUP_SWAP_SUB_GROUP = 0x280,
    CMSG_RESET_FACTION_CHEAT = 0x281,
    CMSG_AUTOSTORE_BANK_ITEM = 0x282,
    CMSG_AUTOBANK_ITEM = 0x283,
    MSG_QUERY_NEXT_MAIL_TIME = 0x0F04,                  // new
    SMSG_RECEIVED_MAIL = 0x2924,                        // new
    SMSG_RAID_GROUP_ONLY = 0x286,
    CMSG_SET_DURABILITY_CHEAT = 0x287,
    CMSG_SET_PVP_RANK_CHEAT = 0x288,
    CMSG_ADD_PVP_MEDAL_CHEAT = 0x289,
    CMSG_DEL_PVP_MEDAL_CHEAT = 0x28A,
    CMSG_SET_PVP_TITLE = 0x28B,
    SMSG_PVP_CREDIT = 0x28C,
    SMSG_AUCTION_REMOVED_NOTIFICATION = 0x2334,         // new
    CMSG_GROUP_RAID_CONVERT = 0x6E27,
    CMSG_GROUP_ASSISTANT_LEADER = 0x28F,
    CMSG_BUYBACK_ITEM = 0x6C17,                         // new
    SMSG_SERVER_MESSAGE = 0x291,
    CMSG_MEETINGSTONE_JOIN = 0x292,
    SMSG_LFG_OFFER_CONTINUE = 0x293,
    CMSG_MEETINGSTONE_CHEAT = 0x294,
    SMSG_MEETINGSTONE_SETQUEUE = 0x295,
    CMSG_LFG_GET_STATUS = 0x2581,                   // new
    SMSG_MEETINGSTONE_COMPLETE = 0x297,
    SMSG_MEETINGSTONE_IN_PROGRESS = 0x298,
    SMSG_MEETINGSTONE_MEMBER_ADDED = 0x299,
    CMSG_GMTICKETSYSTEM_TOGGLE = 0x29A,
    CMSG_CANCEL_GROWTH_AURA = 0x29B,
    SMSG_CANCEL_AUTO_REPEAT = 0x29C,
    SMSG_STANDSTATE_UPDATE = 0x6F04,                // new
    SMSG_LOOT_ALL_PASSED = 0x6237,                  // new
    SMSG_LOOT_ROLL_WON = 0x6617,                    // new
    CMSG_LOOT_ROLL = 0x6934,                        // new
    SMSG_LOOT_START_ROLL = 0x2227,                  // new
    SMSG_LOOT_ROLL = 0x6507,                        // new
    CMSG_LOOT_MASTER_GIVE = 0x4F35,                 // new
    SMSG_LOOT_MASTER_LIST = 0x0325,                 // new
    SMSG_SET_FORCED_REACTIONS = 0x2A5,
    SMSG_SPELL_FAILED_OTHER = 0x4535,               // new
    SMSG_GAMEOBJECT_RESET_STATE = 0x2A7,
    CMSG_REPAIR_ITEM = 0x2917,                      // new
    SMSG_CHAT_PLAYER_NOT_FOUND = 0x2526,            // new
    MSG_TALENT_WIPE_CONFIRM = 0x0107,               // new
    SMSG_SUMMON_REQUEST = 0x2AB,
    CMSG_SUMMON_RESPONSE = 0x2AC,
    MSG_MOVE_TOGGLE_GRAVITY_CHEAT = 0x2AD,
    SMSG_MONSTER_MOVE_TRANSPORT = 0x2004,           // new
    SMSG_PET_BROKEN = 0x2AF,
    MSG_MOVE_FEATHER_FALL = 0x2B0,
    MSG_MOVE_WATER_WALK = 0x2B1,
    CMSG_SERVER_BROADCAST = 0x2B2,
    CMSG_SELF_RES = 0x2B3,
    SMSG_FEIGN_DEATH_RESISTED = 0x2B4,
    CMSG_RUN_SCRIPT = 0x2B5,
    SMSG_SCRIPT_MESSAGE = 0x2B6,
    SMSG_DUEL_COUNTDOWN = 0x4836,                   // new
    SMSG_AREA_TRIGGER_MESSAGE = 0x4505,             // new
    CMSG_TOGGLE_HELM = 0x2B9,
    CMSG_TOGGLE_CLOAK = 0x2BA,
    SMSG_LFG_ROLE_CHOSEN = 0x2BB,
    SMSG_PLAYER_SKINNED = 0x2BC,
    SMSG_DURABILITY_DAMAGE_DEATH = 0x4C27,          // new
    CMSG_SET_EXPLORATION = 0x2BE,
    CMSG_SET_ACTIONBAR_TOGGLES = 0x2506,            // new
    UMSG_DELETE_GUILD_CHARTER = 0x2C0,
    MSG_PETITION_RENAME = 0x4005,                   // new
    SMSG_INIT_WORLD_STATES = 0x2C2,
    SMSG_UPDATE_WORLD_STATE = 0x2C3,
    CMSG_ITEM_NAME_QUERY = 0x2C4,
    SMSG_ITEM_NAME_QUERY_RESPONSE = 0x2C5,
    SMSG_PET_ACTION_FEEDBACK = 0x2C6,
    CMSG_CHAR_RENAME = 0x2327,                      // new
    SMSG_CHAR_RENAME = 0x2024,                      // new
    CMSG_MOVE_SPLINE_DONE = 0x790E,                 // new
    CMSG_MOVE_FALL_RESET = 0x310A,                  // new
    SMSG_UPDATE_LAST_INSTANCE_CREATED = 0x2CB,
    SMSG_RAID_INSTANCE_INFO = 0x2CC,
    CMSG_REQUEST_RAID_INFO = 0x2F26,                // new
    CMSG_MOVE_TIME_SKIPPED = 0x7A0A,                // new
    CMSG_MOVE_FEATHER_FALL_ACK = 0x2CF,
    CMSG_MOVE_WATER_WALK_ACK = 0x3B00,              // new
    CMSG_MOVE_NOT_ACTIVE_MOVER = 0x2D1,
    SMSG_PLAY_SOUND = 0x2D2,
    CMSG_BATTLEFIELD_STATUS = 0x2500,               // new
    SMSG_BATTLEFIELD_STATUS = 0x7DA1,               // new
    CMSG_BATTLEFIELD_PORT = 0x2D5,
    MSG_INSPECT_HONOR_STATS = 0x2D6,
    CMSG_BATTLEMASTER_HELLO = 0x0234,               // new
    CMSG_MOVE_START_SWIM_CHEAT = 0x12D9,            // new
    CMSG_MOVE_STOP_SWIM_CHEAT = 0x12DA,             // new
    SMSG_FORCE_WALK_SPEED_CHANGE = 0x54A2,          // new
    CMSG_FORCE_WALK_SPEED_CHANGE_ACK = 0x7210,      // new
    SMSG_FORCE_SWIM_BACK_SPEED_CHANGE = 0x30B5,     // new
    CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK = 0x7A16, // new
    SMSG_FORCE_TURN_RATE_CHANGE = 0x5DA1,           // new
    CMSG_FORCE_TURN_RATE_CHANGE_ACK = 0x7316,       // new
    MSG_PVP_LOG_DATA = 0x2E0,
    CMSG_LEAVE_BATTLEFIELD = 0x2E1,
    CMSG_AREA_SPIRIT_HEALER_QUERY = 0x4907,         // new
    CMSG_AREA_SPIRIT_HEALER_QUEUE = 0x4815,         // new
    SMSG_AREA_SPIRIT_HEALER_TIME = 0x0734,          // new
    CMSG_GM_UNTEACH = 0x2E5,
    SMSG_WARDEN_DATA = 0x2E6,
    CMSG_WARDEN_DATA = 0x2E7,
    SMSG_GROUP_JOINED_BATTLEGROUND = 0x2E8,
    MSG_BATTLEGROUND_PLAYER_POSITIONS = 0x2E9,
    CMSG_PET_STOP_ATTACK = 0x2EA,
    SMSG_BINDER_CONFIRM = 0x2835,                   // new
    SMSG_BATTLEGROUND_PLAYER_JOINED = 0x2EC,
    SMSG_BATTLEGROUND_PLAYER_LEFT = 0x2ED,
    CMSG_BATTLEMASTER_JOIN = 0x7902,                    // new
    SMSG_ADDON_INFO = 0x2C14,                           // new
    CMSG_PET_UNLEARN = 0x2F0,
    SMSG_PET_UNLEARN_CONFIRM = 0x2F1,
    SMSG_PARTY_MEMBER_STATS_FULL = 0x2F2,
    CMSG_PET_SPELL_AUTOCAST = 0x2514,                   // new
    SMSG_WEATHER = 0x2904,                              // new
    SMSG_PLAY_TIME_WARNING = 0x2F5,
    SMSG_MINIGAME_SETUP = 0x2F6,
    SMSG_MINIGAME_STATE = 0x2F7,
    CMSG_MINIGAME_MOVE = 0x2F8,
    SMSG_MINIGAME_MOVE_FAILED = 0x2F9,
    SMSG_RAID_INSTANCE_MESSAGE = 0x2FA,
    SMSG_COMPRESSED_MOVES = 0x2FB,
    CMSG_GUILD_INFO_TEXT = 0x2FC,
    SMSG_CHAT_RESTRICTED = 0x6536,                      // new
    SMSG_SPLINE_SET_RUN_SPEED = 0x51B7,                 // new
    SMSG_SPLINE_SET_RUN_BACK_SPEED = 0x3DB3,            // new
    SMSG_SPLINE_SET_SWIM_SPEED = 0x39A4,                // new
    SMSG_SPLINE_SET_WALK_SPEED = 0x34A5,                // new
    SMSG_SPLINE_SET_SWIM_BACK_SPEED = 0x59A1,           // new
    SMSG_SPLINE_SET_TURN_RATE = 0x78B5,                 // new
    SMSG_SPLINE_MOVE_UNROOT = 0x75B6,                   // new
    SMSG_SPLINE_MOVE_FEATHER_FALL = 0x3DA5,             // new
    SMSG_SPLINE_MOVE_NORMAL_FALL = 0x38B2,              // new
    SMSG_SPLINE_MOVE_SET_HOVER = 0x14B6,                // new
    SMSG_SPLINE_MOVE_UNSET_HOVER = 0x7DA5,              // new
    SMSG_SPLINE_MOVE_WATER_WALK = 0x50A2,               // new
    SMSG_SPLINE_MOVE_LAND_WALK = 0x3DA7,                // new
    SMSG_SPLINE_MOVE_START_SWIM = 0x31A5,               // new
    SMSG_SPLINE_MOVE_STOP_SWIM = 0x1DA2,                // new
    SMSG_SPLINE_MOVE_SET_RUN_MODE = 0x75A7,             // new
    SMSG_SPLINE_MOVE_SET_WALK_MODE = 0x54B6,            // new
    CMSG_GM_NUKE_ACCOUNT = 0x30F,
    MSG_GM_DESTROY_CORPSE = 0x310,
    CMSG_GM_DESTROY_ONLINE_CORPSE = 0x311,
    CMSG_ACTIVATETAXIEXPRESS = 0x0515,                  // new
    SMSG_SET_FACTION_ATWAR = 0x313,
    SMSG_GAMETIMEBIAS_SET = 0x314,
    CMSG_DEBUG_ACTIONS_START = 0x315,
    CMSG_DEBUG_ACTIONS_STOP = 0x316,
    CMSG_SET_FACTION_INACTIVE = 0x317,
    CMSG_SET_WATCHED_FACTION = 0x318,
    MSG_MOVE_TIME_SKIPPED = 0x319,
    SMSG_SPLINE_MOVE_ROOT = 0x51B4,                     // new
    CMSG_SET_EXPLORATION_ALL = 0x31B,
    SMSG_INVALIDATE_PLAYER = 0x31C,
    CMSG_RESET_INSTANCES = 0x6E14,                      // new
    SMSG_INSTANCE_RESET = 0x6F05,                       // new
    SMSG_INSTANCE_RESET_FAILED = 0x4725,                // new
    SMSG_UPDATE_LAST_INSTANCE = 0x0437,                 // new
    MSG_RAID_TARGET_UPDATE = 0x321,
    MSG_RAID_READY_CHECK = 0x2304,                      // new
    CMSG_LUA_USAGE = 0x323,
    SMSG_PET_ACTION_SOUND = 0x324,
    SMSG_PET_DISMISS_SOUND = 0x325,
    SMSG_GHOSTEE_GONE = 0x326,
    CMSG_GM_UPDATE_TICKET_STATUS = 0x327,
    SMSG_GM_TICKET_STATUS_UPDATE = 0x2C25,              // new
    MSG_SET_DUNGEON_DIFFICULTY = 0x4925,                // new
    CMSG_GMSURVEY_SUBMIT = 0x2724,                      // new
    SMSG_UPDATE_INSTANCE_OWNERSHIP = 0x4915,            // new
    CMSG_IGNORE_KNOCKBACK_CHEAT = 0x32C,
    SMSG_CHAT_PLAYER_AMBIGUOUS = 0x2F34,                // new
    MSG_DELAY_GHOST_TELEPORT = 0x32E,
    SMSG_SPELLINSTAKILLLOG = 0x6216,                    // new
    SMSG_SPELL_UPDATE_CHAIN_TARGETS = 0x1331,           // new
    CMSG_CHAT_FILTERED = 0x1332,                        // new
    SMSG_EXPECTED_SPAM_RECORDS = 0x332,
    SMSG_SPELLSTEALLOG = 0x4E26,                        // new
    CMSG_LOTTERY_QUERY_OBSOLETE = 0x334,
    SMSG_LOTTERY_QUERY_RESULT_OBSOLETE = 0x335,
    CMSG_BUY_LOTTERY_TICKET_OBSOLETE = 0x336,
    SMSG_LOTTERY_RESULT_OBSOLETE = 0x337,
    SMSG_CHARACTER_PROFILE = 0x338,
    SMSG_CHARACTER_PROFILE_REALM_CONNECTED = 0x339,
    SMSG_DEFENSE_MESSAGE = 0x33A,
    SMSG_INSTANCE_DIFFICULTY = 0x33B,
    MSG_GM_RESETINSTANCELIMIT = 0x33C,
    SMSG_MOTD = 0x0A35,                                 // new
    SMSG_MOVE_SET_FLIGHT_OBSOLETE = 0x33E,
    SMSG_MOVE_UNSET_FLIGHT_OBSOLETE = 0x33F,
    CMSG_MOVE_FLIGHT_ACK_OBSOLETE = 0x340,
    MSG_MOVE_START_SWIM_CHEAT = 0x1342,                 // new
    MSG_MOVE_STOP_SWIM_CHEAT = 0x1343,                  // new
    SMSG_MOVE_SET_CAN_FLY = 0x3DA1,                     // new
    SMSG_MOVE_UNSET_CAN_FLY = 0x15A2,                   // new
    CMSG_MOVE_SET_CAN_FLY_ACK = 0x790C,                 // new
    CMSG_MOVE_SET_CAN_FLY = 0x720E,                     // new
    CMSG_SOCKET_GEMS = 0x2F04,                          // new
    CMSG_ARENA_TEAM_CREATE = 0x348,
    SMSG_ARENA_TEAM_COMMAND_RESULT = 0x349,
    UMSG_UPDATE_ARENA_TEAM_OBSOLETE = 0x34A,
    CMSG_ARENA_TEAM_QUERY = 0x34B,
    SMSG_ARENA_TEAM_QUERY_RESPONSE = 0x34C,
    CMSG_ARENA_TEAM_ROSTER = 0x34D,
    SMSG_ARENA_TEAM_ROSTER = 0x34E,
    CMSG_ARENA_TEAM_INVITE = 0x34F,
    SMSG_ARENA_TEAM_INVITE = 0x350,
    CMSG_ARENA_TEAM_ACCEPT = 0x351,
    CMSG_ARENA_TEAM_DECLINE = 0x352,
    CMSG_ARENA_TEAM_LEAVE = 0x353,
    CMSG_ARENA_TEAM_REMOVE = 0x354,
    CMSG_ARENA_TEAM_DISBAND = 0x355,
    CMSG_ARENA_TEAM_LEADER = 0x356,
    SMSG_ARENA_TEAM_EVENT = 0x357,
    CMSG_BATTLEMASTER_JOIN_ARENA = 0x710C,      // new
    MSG_MOVE_START_ASCEND = 0x390A,             // new
    MSG_MOVE_STOP_ASCEND = 0x7B00,              // new
    SMSG_ARENA_TEAM_STATS = 0x35B,
    CMSG_LFG_JOIN = 0x2430,                     // new
    CMSG_LFG_LEAVE = 0x2433,                    // new
    CMSG_SEARCH_LFG_JOIN = 0x35E,
    CMSG_SEARCH_LFG_LEAVE = 0x35F,
    SMSG_UPDATE_LFG_LIST = 0x360,
    SMSG_LFG_PROPOSAL_UPDATE = 0x361,
    CMSG_LFG_PROPOSAL_RESULT = 0x362,
    SMSG_LFG_ROLE_CHECK_UPDATE = 0x1364,            // new
    SMSG_LFG_JOIN_RESULT = 0x1365,                  // new
    SMSG_LFG_QUEUE_STATUS = 0x365,
    CMSG_SET_LFG_COMMENT = 0x366,
    SMSG_LFG_UPDATE_PLAYER = 0x1368,                // new
    SMSG_LFG_UPDATE_PARTY = 0x1369,                 // new
    SMSG_LFG_UPDATE_SEARCH = 0x136A,                // new
    CMSG_LFG_SET_ROLES = 0x36A,
    CMSG_LFG_SET_NEEDS = 0x36B,
    CMSG_LFG_SET_BOOT_VOTE = 0x36C,
    SMSG_LFG_BOOT_PROPOSAL_UPDATE = 0x36D,
    CMSG_LFD_PLAYER_LOCK_INFO_REQUEST = 0x36E,
    SMSG_LFG_PLAYER_INFO = 0x1370,                  // new
    CMSG_LFG_TELEPORT = 0x370,
    CMSG_LFD_PARTY_LOCK_INFO_REQUEST = 0x371,
    SMSG_LFG_PARTY_INFO = 0x1373,                   // new
    SMSG_TITLE_EARNED = 0x373,
    CMSG_SET_TITLE = 0x2117,                        // new
    CMSG_CANCEL_MOUNT_AURA = 0x375,
    SMSG_ARENA_ERROR = 0x376,
    MSG_INSPECT_ARENA_TEAMS = 0x377,
    SMSG_DEATH_RELEASE_LOC = 0x2F07,                // new
    CMSG_CANCEL_TEMP_ENCHANTMENT = 0x6C37,          // new
    SMSG_FORCED_DEATH_UPDATE = 0x37A,
    CMSG_CHEAT_SET_HONOR_CURRENCY = 0x37B,
    CMSG_CHEAT_SET_ARENA_CURRENCY = 0x37C,
    MSG_MOVE_SET_FLIGHT_SPEED_CHEAT = 0x71A6,       // new
    MSG_MOVE_SET_FLIGHT_SPEED = 0x71A6,             // new
    MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT = 0x1380,  // new
    MSG_MOVE_SET_FLIGHT_BACK_SPEED = 0x30A2,        // new
    SMSG_FORCE_FLIGHT_SPEED_CHANGE = 0x30B1,        // new
    CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK = 0x7314,    // new
    SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE = 0x74A0,   // new
    CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK = 0x0333,   // new
    SMSG_SPLINE_SET_FLIGHT_SPEED = 0x39A0,          // new
    SMSG_SPLINE_SET_FLIGHT_BACK_SPEED = 0x38B3,     // new
    CMSG_MAELSTROM_INVALIDATE_CACHE = 0x387,
    SMSG_FLIGHT_SPLINE_SYNC = 0x388,
    CMSG_SET_TAXI_BENCHMARK_MODE = 0x4314,          // new
    SMSG_JOINED_BATTLEGROUND_QUEUE = 0x38A,
    SMSG_REALM_SPLIT = 0x2714,                      // new
    CMSG_REALM_SPLIT = 0x2906,                      // new
    CMSG_MOVE_CHNG_TRANSPORT = 0x3102,              // new
    MSG_PARTY_ASSIGNMENT = 0x38E,
    SMSG_OFFER_PETITION_ERROR = 0x38F,
    SMSG_TIME_SYNC_REQ = 0x3CA4,                    // new
    CMSG_TIME_SYNC_RESP = 0x3B0C,                   // new
    CMSG_SEND_LOCAL_EVENT = 0x392,
    CMSG_SEND_GENERAL_TRIGGER = 0x393,
    CMSG_SEND_COMBAT_TRIGGER = 0x394,
    CMSG_MAELSTROM_GM_SENT_MAIL = 0x395,
    SMSG_RESET_FAILED_NOTIFY = 0x396,
    SMSG_REAL_GROUP_UPDATE = 0x397,
    SMSG_LFG_DISABLED = 0x398,
    CMSG_ACTIVE_PVP_CHEAT = 0x399,
    CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY = 0x39A,
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE = 0x39B,
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE = 0x39C,
    SMSG_UPDATE_COMBO_POINTS = 0x39D,
    SMSG_VOICE_SESSION_ROSTER_UPDATE = 0x39E,
    SMSG_VOICE_SESSION_LEAVE = 0x39F,
    SMSG_VOICE_SESSION_ADJUST_PRIORITY = 0x3A0,
    CMSG_VOICE_SET_TALKER_MUTED_REQUEST = 0x3A1,
    SMSG_VOICE_SET_TALKER_MUTED = 0x3A2,
    SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE = 0x3A3,
    SMSG_SET_EXTRA_AURA_INFO_OBSOLETE = 0x3A4,
    SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE = 0x3A5,
    SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE = 0x3A6,
    MSG_MOVE_START_DESCEND = 0x3800,                // new
    CMSG_IGNORE_REQUIREMENTS_CHEAT = 0x3A8,
    SMSG_IGNORE_REQUIREMENTS_CHEAT = 0x3A9,
    SMSG_SPELL_CHANCE_PROC_LOG = 0x13AB,            // new
    CMSG_MOVE_SET_RUN_SPEED = 0x3AB,
    SMSG_DISMOUNT = 0x3AC,
    MSG_MOVE_UPDATE_CAN_FLY = 0x3AD,
    MSG_RAID_READY_CHECK_CONFIRM = 0x4F05,          // new
    CMSG_VOICE_SESSION_ENABLE = 0x2314,             // new
    SMSG_VOICE_SESSION_ENABLE = 0x3B0,
    SMSG_VOICE_PARENTAL_CONTROLS = 0x3B1,
    CMSG_GM_WHISPER = 0x3B2,
    SMSG_GM_MESSAGECHAT = 0x6434,                   // new
    MSG_GM_GEARRATING = 0x3B4,
    CMSG_COMMENTATOR_ENABLE = 0x3B5,
    SMSG_COMMENTATOR_STATE_CHANGED = 0x3B6,
    CMSG_COMMENTATOR_GET_MAP_INFO = 0x3B7,
    SMSG_COMMENTATOR_MAP_INFO = 0x3B8,
    CMSG_COMMENTATOR_GET_PLAYER_INFO = 0x3B9,
    SMSG_COMMENTATOR_GET_PLAYER_INFO = 0x3BA,
    SMSG_COMMENTATOR_PLAYER_INFO = 0x3BB,
    CMSG_COMMENTATOR_ENTER_INSTANCE = 0x3BC,
    CMSG_COMMENTATOR_EXIT_INSTANCE = 0x3BD,
    CMSG_COMMENTATOR_INSTANCE_COMMAND = 0x3BE,
    SMSG_CLEAR_TARGET = 0x3BF,
    CMSG_BOT_DETECTED = 0x3C0,
    SMSG_CROSSED_INEBRIATION_THRESHOLD = 0x3C1,
    CMSG_CHEAT_PLAYER_LOGIN = 0x3C2,
    CMSG_CHEAT_PLAYER_LOOKUP = 0x3C3,
    SMSG_CHEAT_PLAYER_LOOKUP = 0x3C4,
    SMSG_KICK_REASON = 0x3C5,
    MSG_RAID_READY_CHECK_FINISHED = 0x2E15,         // new
    CMSG_COMPLAIN = 0x3C7,
    SMSG_COMPLAIN_RESULT = 0x3C8,
    SMSG_FEATURE_SYSTEM_STATUS = 0x3DB7,            // new
    CMSG_GM_SHOW_COMPLAINTS = 0x3CA,
    CMSG_GM_UNSQUELCH = 0x3CB,
    CMSG_CHANNEL_SILENCE_VOICE = 0x13CD,            // new
    CMSG_CHANNEL_SILENCE_ALL = 0x13CE,              // new
    CMSG_CHANNEL_UNSILENCE_VOICE = 0x13CF,          // new
    CMSG_CHANNEL_UNSILENCE_ALL = 0x13D0,            // new
    CMSG_TARGET_CAST = 0x3D0,
    CMSG_TARGET_SCRIPT_CAST = 0x3D1,
    CMSG_CHANNEL_DISPLAY_LIST = 0x2144,             // new
    CMSG_SET_ACTIVE_VOICE_CHANNEL = 0x4305,         // new
    CMSG_GET_CHANNEL_MEMBER_COUNT = 0x13D5,         // new
    SMSG_CHANNEL_MEMBER_COUNT = 0x6414,             // new
    CMSG_CHANNEL_VOICE_ON = 0x1144,                 // new
    CMSG_CHANNEL_VOICE_OFF = 0x13D8,                // new
    CMSG_DEBUG_LIST_TARGETS = 0x3D8,
    SMSG_DEBUG_LIST_TARGETS = 0x3D9,
    SMSG_AVAILABLE_VOICE_CHANNEL = 0x13DB,          // new
    CMSG_ADD_VOICE_IGNORE = 0x3DB,
    CMSG_DEL_VOICE_IGNORE = 0x3DC,
    CMSG_PARTY_SILENCE = 0x3DD,
    CMSG_PARTY_UNSILENCE = 0x3DE,
    MSG_NOTIFY_PARTY_SQUELCH = 0x3DF,
    SMSG_COMSAT_RECONNECT_TRY = 0x3E0,
    SMSG_COMSAT_DISCONNECT = 0x3E1,
    SMSG_COMSAT_CONNECT_FAIL = 0x3E2,
    SMSG_VOICE_CHAT_STATUS = 0x3E3,
    CMSG_REPORT_PVP_AFK = 0x3E4,
    CMSG_REPORT_PVP_AFK_RESULT = 0x3E5,
    CMSG_GUILD_BANKER_ACTIVATE = 0x2E37,        // new
    CMSG_GUILD_BANK_QUERY_TAB = 0x3E7,
    SMSG_GUILD_BANK_LIST = 0x3E8,
    CMSG_GUILD_BANK_SWAP_ITEMS = 0x3E9,
    CMSG_GUILD_BANK_BUY_TAB = 0x3EA,
    CMSG_GUILD_BANK_UPDATE_TAB = 0x3EB,
    CMSG_GUILD_BANK_DEPOSIT_MONEY = 0x3EC,
    CMSG_GUILD_BANK_WITHDRAW_MONEY = 0x3ED,
    MSG_GUILD_BANK_LOG_QUERY = 0x3EE,
    CMSG_SET_CHANNEL_WATCH = 0x4517,            // new
    SMSG_USERLIST_ADD = 0x3F0,
    SMSG_USERLIST_REMOVE = 0x3F1,
    SMSG_USERLIST_UPDATE = 0x3F2,
    CMSG_CLEAR_CHANNEL_WATCH = 0x13F4,          // new
    SMSG_INSPECT_TALENT = 0x4014,               // new
    SMSG_GOGOGO_OBSOLETE = 0x3F5,
    SMSG_ECHO_PARTY_SQUELCH = 0x3F6,
    CMSG_SET_TITLE_SUFFIX = 0x3F7,
    CMSG_SPELLCLICK = 0x0805,                   // new
    SMSG_LOOT_LIST = 0x6807,                    // new
    CMSG_GM_CHARACTER_RESTORE = 0x3FA,
    CMSG_GM_CHARACTER_SAVE = 0x3FB,
    SMSG_VOICESESSION_FULL = 0x3FC,
    MSG_GUILD_PERMISSIONS = 0x3FD,
    MSG_GUILD_BANK_MONEY_WITHDRAWN = 0x3FE,
    MSG_GUILD_EVENT_LOG_QUERY = 0x3FF,
    CMSG_MAELSTROM_RENAME_GUILD = 0x400,
    CMSG_GET_MIRRORIMAGE_DATA = 0x401,
    SMSG_MIRRORIMAGE_DATA = 0x402,
    SMSG_FORCE_DISPLAY_UPDATE = 0x403,
    SMSG_SPELL_CHANCE_RESIST_PUSHBACK = 0x1405,         // new
    CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT = 0x405,
    SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT = 0x406,
    CMSG_KEEP_ALIVE = 0x0015,                           // new
    SMSG_RAID_READY_CHECK_ERROR = 0x408,
    CMSG_OPT_OUT_OF_LOOT = 0x6B16,                          // new
    MSG_QUERY_GUILD_BANK_TEXT = 0x40A,
    CMSG_SET_GUILD_BANK_TEXT = 0x40B,
    CMSG_SET_GRANTABLE_LEVELS = 0x40C,
    CMSG_GRANT_LEVEL = 0x0000,                                  // new
    CMSG_REFER_A_FRIEND = 0x40E,
    MSG_GM_CHANGE_ARENA_RATING = 0x40F,
    CMSG_DECLINE_CHANNEL_INVITE = 0x1411,                       // new
    CMSG_GROUPACTION_THROTTLED = 0x411,
    SMSG_OVERRIDE_LIGHT = 0x0000,
    SMSG_TOTEM_CREATED = 0x413,
    CMSG_TOTEM_DESTROYED = 0x414,
    CMSG_EXPIRE_RAID_INSTANCE = 0x415,
    CMSG_NO_SPELL_VARIANCE = 0x1417,                            // new
    CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY = 0x6305,             // new
    SMSG_QUESTGIVER_STATUS_MULTIPLE = 0x4F25,                   // new
    CMSG_SET_PLAYER_DECLINED_NAMES = 0x419,
    SMSG_SET_PLAYER_DECLINED_NAMES_RESULT = 0x41A,
    CMSG_QUERY_SERVER_BUCK_DATA = 0x41B,
    CMSG_CLEAR_SERVER_BUCK_DATA = 0x41C,
    SMSG_SERVER_BUCK_DATA = 0x141E,                             // new
    SMSG_SEND_UNLEARN_SPELLS = 0x4E25,                          // new
    SMSG_PROPOSE_LEVEL_GRANT = 0x6114,                          // new
    CMSG_ACCEPT_LEVEL_GRANT = 0x0205,                           // new
    SMSG_REFER_A_FRIEND_FAILURE = 0x421,
    SMSG_SPLINE_MOVE_SET_FLYING = 0x422,
    SMSG_SPLINE_MOVE_UNSET_FLYING = 0x423,
    SMSG_SUMMON_CANCEL = 0x424,
    CMSG_CHANGE_PERSONAL_ARENA_RATING = 0x425,
    CMSG_ALTER_APPEARANCE = 0x0914,                             // new
    SMSG_ENABLE_BARBER_SHOP = 0x2D16,                           // new
    SMSG_BARBER_SHOP_RESULT = 0x6125,                           // new
    CMSG_CALENDAR_GET_CALENDAR = 0x2814,                        // new
    CMSG_CALENDAR_GET_EVENT = 0x42A,
    CMSG_CALENDAR_GUILD_FILTER = 0x42B,
    CMSG_CALENDAR_ARENA_TEAM = 0x42C,
    CMSG_CALENDAR_ADD_EVENT = 0x42D,
    CMSG_CALENDAR_UPDATE_EVENT = 0x42E,
    CMSG_CALENDAR_REMOVE_EVENT = 0x42F,
    CMSG_CALENDAR_COPY_EVENT = 0x0000,
    CMSG_CALENDAR_EVENT_INVITE = 0x431,
    CMSG_CALENDAR_EVENT_RSVP = 0x432,
    CMSG_CALENDAR_EVENT_REMOVE_INVITE = 0x433,
    CMSG_CALENDAR_EVENT_STATUS = 0x434,
    CMSG_CALENDAR_EVENT_MODERATOR_STATUS = 0x435,
    SMSG_CALENDAR_SEND_CALENDAR = 0x436,
    SMSG_CALENDAR_SEND_EVENT = 0x437,
    SMSG_CALENDAR_FILTER_GUILD = 0x438,
    SMSG_CALENDAR_ARENA_TEAM = 0x439,
    SMSG_CALENDAR_EVENT_INVITE = 0x43A,
    SMSG_CALENDAR_EVENT_INVITE_REMOVED = 0x43B,
    SMSG_CALENDAR_EVENT_STATUS = 0x43C,
    SMSG_CALENDAR_COMMAND_RESULT = 0x43D,
    SMSG_CALENDAR_RAID_LOCKOUT_ADDED = 0x43E,
    SMSG_CALENDAR_RAID_LOCKOUT_REMOVED = 0x43F,
    SMSG_CALENDAR_EVENT_INVITE_ALERT = 0x440,
    SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT = 0x441,
    SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT = 0x442,
    SMSG_CALENDAR_EVENT_REMOVED_ALERT = 0x443,
    SMSG_CALENDAR_EVENT_UPDATED_ALERT = 0x444,
    SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT = 0x445,
    CMSG_CALENDAR_COMPLAIN = 0x446,
    CMSG_CALENDAR_GET_NUM_PENDING = 0x4D05,                 // new
    SMSG_CALENDAR_SEND_NUM_PENDING = 0x448,
    CMSG_SAVE_DANCE = 0x449,
    SMSG_NOTIFY_DANCE = 0x44A,
    CMSG_PLAY_DANCE = 0x44B,
    SMSG_PLAY_DANCE = 0x44C,
    CMSG_LOAD_DANCES = 0x44D,
    CMSG_STOP_DANCE = 0x44E,
    SMSG_STOP_DANCE = 0x44F,
    CMSG_SYNC_DANCE = 0x450,
    CMSG_DANCE_QUERY = 0x451,
    SMSG_DANCE_QUERY_RESPONSE = 0x452,
    SMSG_INVALIDATE_DANCE = 0x453,
    CMSG_DELETE_DANCE = 0x454,
    SMSG_LEARNED_DANCE_MOVES = 0x0E05,                      // new
    CMSG_LEARN_DANCE_MOVE = 0x456,
    CMSG_UNLEARN_DANCE_MOVE = 0x457,
    CMSG_SET_RUNE_COUNT = 0x458,
    CMSG_SET_RUNE_COOLDOWN = 0x459,
    MSG_MOVE_SET_PITCH_RATE_CHEAT = 0x45A,
    MSG_MOVE_SET_PITCH_RATE = 0x75B0,                   // new
    SMSG_FORCE_PITCH_RATE_CHANGE = 0x1DB5,              // new
    CMSG_FORCE_PITCH_RATE_CHANGE_ACK = 0x0334,          // new
    SMSG_SPLINE_SET_PITCH_RATE = 0x14B0,                // new
    SMSG_MOVE_ABANDON_TRANSPORT = 0x45F,
    MSG_MOVE_ABANDON_TRANSPORT = 0x460,
    CMSG_MOVE_ABANDON_TRANSPORT_ACK = 0x461,
    CMSG_UPDATE_MISSILE_TRAJECTORY = 0x462,
    SMSG_UPDATE_ACCOUNT_DATA_COMPLETE = 0x2015,         // new
    SMSG_TRIGGER_MOVIE = 0x4625,                        // new
    CMSG_COMPLETE_MOVIE = 0x4136,                       // new
    CMSG_SET_GLYPH_SLOT = 0x466,
    CMSG_SET_GLYPH = 0x467,
    SMSG_ACHIEVEMENT_EARNED = 0x4405,                   // new
    SMSG_DYNAMIC_DROP_ROLL_RESULT = 0x469,
    SMSG_CRITERIA_UPDATE = 0x46A,
    CMSG_QUERY_INSPECT_ACHIEVEMENTS = 0x46B,
    SMSG_RESPOND_INSPECT_ACHIEVEMENTS = 0x15B0,         // new
    CMSG_DISMISS_CONTROLLED_VEHICLE = 0x46D,
    CMSG_COMPLETE_ACHIEVEMENT_CHEAT = 0x46E,
    SMSG_QUESTUPDATE_ADD_PVP_KILL = 0x46F,
    CMSG_SET_CRITERIA_CHEAT = 0x470,
    SMSG_GROUP_SWAP_FAILED = 0x471,
    CMSG_UNITANIMTIER_CHEAT = 0x472,
    CMSG_CHAR_CUSTOMIZE = 0x2C34,                   // new
    SMSG_CHAR_CUSTOMIZE = 0x4F16,                   // new
    SMSG_PET_RENAMEABLE = 0x475,
    CMSG_REQUEST_VEHICLE_EXIT = 0x476,
    CMSG_REQUEST_VEHICLE_PREV_SEAT = 0x477,
    CMSG_REQUEST_VEHICLE_NEXT_SEAT = 0x478,
    CMSG_REQUEST_VEHICLE_SWITCH_SEAT = 0x479,
    CMSG_PET_LEARN_TALENT = 0x6725,                 // new
    CMSG_PET_UNLEARN_TALENTS = 0x47B,
    SMSG_SET_PHASE_SHIFT = 0x70A0,                  // new
    SMSG_ALL_ACHIEVEMENT_DATA = 0x58B1,             // new
    CMSG_FORCE_SAY_CHEAT = 0x47E,
    SMSG_HEALTH_UPDATE = 0x47F,
    SMSG_POWER_UPDATE = 0x4A07,                     // new
    CMSG_GAMEOBJ_REPORT_USE = 0x4827,               // new
    SMSG_HIGHEST_THREAT_UPDATE = 0x482,
    SMSG_THREAT_UPDATE = 0x483,
    SMSG_THREAT_REMOVE = 0x484,
    SMSG_THREAT_CLEAR = 0x485,
    SMSG_CONVERT_RUNE = 0x486,
    SMSG_RESYNC_RUNES = 0x487,
    SMSG_ADD_RUNE_POWER = 0x6915,                   // new
    CMSG_START_QUEST = 0x489,
    CMSG_REMOVE_GLYPH = 0x48A,
    CMSG_DUMP_OBJECTS = 0x48B,
    SMSG_DUMP_OBJECTS_DATA = 0x48C,
    CMSG_DISMISS_CRITTER = 0x48D,
    SMSG_NOTIFY_DEST_LOC_SPELL_CAST = 0x148F,           // new
    CMSG_AUCTION_LIST_PENDING_SALES = 0x2C17,           // new
    SMSG_AUCTION_LIST_PENDING_SALES = 0x6A27,           // new
    SMSG_MODIFY_COOLDOWN = 0x491,
    SMSG_PET_UPDATE_COMBO_POINTS = 0x492,
    CMSG_ENABLETAXI = 0x493,
    SMSG_PRE_RESURRECT = 0x6C36,                        // new
    SMSG_AURA_UPDATE_ALL = 0x6916,                      // new
    SMSG_AURA_UPDATE = 0x4707,                          // new
    CMSG_FLOOD_GRACE_CHEAT = 0x497,
    SMSG_SERVER_FIRST_ACHIEVEMENT = 0x6424,             // new
    SMSG_PET_LEARNED_SPELL = 0x0507,                    // new
    SMSG_PET_UNLEARNED_SPELL = 0x6A04,                  // new
    CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE = 0x49B,
    CMSG_HEARTH_AND_RESURRECT = 0x49C,
    SMSG_CONTROL_VEHICLE = 0x49D,
    SMSG_CRITERIA_DELETED = 0x49E,
    SMSG_ACHIEVEMENT_DELETED = 0x6A16,                  // new
    CMSG_SERVER_INFO_QUERY = 0x4A0,
    SMSG_SERVER_INFO_RESPONSE = 0x4A1,
    CMSG_CHECK_LOGIN_CRITERIA = 0x4A2,
    SMSG_SERVER_BUCK_DATA_START = 0x4A3,
    CMSG_QUERY_VEHICLE_STATUS = 0x4A4,
    UMSG_UNKNOWN_1189 = 0x4A5,
    SMSG_UNKNOWN_1190 = 0x4A6,
    SMSG_PLAYER_VEHICLE_DATA = 0x4A7,
    CMSG_PLAYER_VEHICLE_ENTER = 0x4A8,
    CMSG_EJECT_PASSENGER = 0x4A9,
    SMSG_PET_GUIDS = 0x4AA,
    SMSG_CLIENTCACHE_VERSION = 0x2734,                  // new
    UMSG_UNKNOWN_1196 = 0x4AC,
    UMSG_UNKNOWN_1197 = 0x4AD,
    UMSG_UNKNOWN_1198 = 0x4AE,
    UMSG_UNKNOWN_1199 = 0x4AF,
    UMSG_UNKNOWN_1200 = 0x4B0,
    UMSG_UNKNOWN_1201 = 0x4B1,
    SMSG_ITEMREFUNDINFO = 0x15A3,                   // new
    CMSG_ITEMREFUNDINFO = 0x2206,                   // new
    CMSG_ITEMREFUNDREQUEST = 0x4B4,
    SMSG_ITEMREFUNDREQUEST = 0x4B5,
    CMSG_UNKNOWN_1206 = 0x4B6,
    SMSG_UNKNOWN_1207 = 0x4B7,
    SMSG_UNKNOWN_1208 = 0x4B8,
    UMSG_UNKNOWN_1209 = 0x4B9,
    CMSG_UNKNOWN_1210 = 0x4BA,
    SMSG_UNKNOWN_1211 = 0x4BB,
    SMSG_EQUIPMENT_SET_LIST = 0x2E04,               // new
    CMSG_EQUIPMENT_SET_SAVE = 0x4BD,
    CMSG_UPDATE_PROJECTILE_POSITION = 0x4BE,
    SMSG_SET_PROJECTILE_POSITION = 0x4BF,
    SMSG_TALENTS_INFO = 0x6F26,                     // new
    CMSG_LEARN_TALENTS_MULTIPLE = 0x4C1,
    CMSG_LEARN_PREVIEW_TALENTS_PET = 0x6E24,        // new
    UMSG_UNKNOWN_1219 = 0x4C3,
    UMSG_UNKNOWN_1220 = 0x4C4,
    UMSG_UNKNOWN_1221 = 0x4C5,
    UMSG_UNKNOWN_1222 = 0x4C6,
    SMSG_UNKNOWN_1223 = 0x4C7,
    SMSG_UNKNOWN_1224 = 0x4C8,
    UMSG_UNKNOWN_1225 = 0x4C9,
    UMSG_UNKNOWN_1226 = 0x4CA,
    CMSG_UNKNOWN_1227 = 0x4CB,
    SMSG_UNKNOWN_1228 = 0x4CC,
    SMSG_MULTIPLE_PACKETS = 0x4CD,
    SMSG_MOVE_GRAVITY_DISABLE = 0x75B2,             // new
    CMSG_MOVE_GRAVITY_DISABLE_ACK = 0x3118,         // new
    SMSG_MOVE_GRAVITY_ENABLE = 0x30B3,              // new
    CMSG_MOVE_GRAVITY_ENABLE_ACK = 0x700A,          // new
    MSG_MOVE_GRAVITY_CHNG = 0x4D2,
    SMSG_SPLINE_MOVE_GRAVITY_DISABLE = 0x5DB5,                  // new
    SMSG_SPLINE_MOVE_GRAVITY_ENABLE = 0x3CA6,                   // new
    CMSG_EQUIPMENT_SET_USE = 0x4D5,
    SMSG_EQUIPMENT_SET_USE_RESULT = 0x2424,                     // new
    CMSG_FORCE_ANIM = 0x4D7,
    SMSG_FORCE_ANIM = 0x4D8,
    CMSG_CHAR_FACTION_CHANGE = 0x4D9,
    SMSG_CHAR_FACTION_CHANGE = 0x4DA,
    CMSG_PVP_QUEUE_STATS_REQUEST = 0x4DB,
    SMSG_PVP_QUEUE_STATS = 0x4DC,
    CMSG_SET_PAID_SERVICE_CHEAT = 0x4DD,
    SMSG_BATTLEFIELD_MGR_ENTRY_INVITE = 0x4DE,
    CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE = 0x4DF,
    SMSG_BATTLEFIELD_MGR_ENTERED = 0x4E0,
    SMSG_BATTLEFIELD_MGR_QUEUE_INVITE = 0x4E1,
    CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE = 0x4E2,
    CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST = 0x710C,                // new
    SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE = 0x4E4,
    SMSG_BATTLEFIELD_MGR_EJECT_PENDING = 0x4E5,
    SMSG_BATTLEFIELD_MGR_EJECTED = 0x4E6,
    CMSG_BATTLEFIELD_MGR_EXIT_REQUEST = 0x4E7,
    SMSG_BATTLEFIELD_MGR_STATE_CHANGE = 0x4E8,
    CMSG_BATTLEFIELD_MANAGER_ADVANCE_STATE = 0x4E9,
    CMSG_BATTLEFIELD_MANAGER_SET_NEXT_TRANS_TIME = 0x4EA,
    MSG_SET_RAID_DIFFICULTY = 0x0614,                           // new
    CMSG_TOGGLE_XP_GAIN = 0x4EC,
    SMSG_TOGGLE_XP_GAIN = 0x4ED,
    SMSG_GMRESPONSE_DB_ERROR = 0x4EE,
    SMSG_GMRESPONSE_RECEIVED = 0x2E34,                      // new
    CMSG_GMRESPONSE_RESOLVE = 0x6506,                       // new
    SMSG_GMRESPONSE_STATUS_UPDATE = 0x0A04,                 // new
    SMSG_GMRESPONSE_CREATE_TICKET = 0x4F2,
    CMSG_GMRESPONSE_CREATE_TICKET = 0x4F3,
    CMSG_SERVERINFO = 0x4F4,
    SMSG_SERVERINFO = 0x4F5,
    CMSG_WORLD_STATE_UI_TIMER_UPDATE = 0x4605,              // new
    SMSG_WORLD_STATE_UI_TIMER_UPDATE = 0x4A14,              // new
    CMSG_CHAR_RACE_CHANGE = 0x4F8,
    MSG_VIEW_PHASE_SHIFT = 0x4F9,
    SMSG_TALENTS_INVOLUNTARILY_RESET = 0x2C27,              // new
    CMSG_DEBUG_SERVER_GEO = 0x4FB,
    SMSG_DEBUG_SERVER_GEO = 0x4FC,
    SMSG_LOOT_SLOT_CHANGED = 0x4FD,
    UMSG_UPDATE_GROUP_INFO = 0x4FE,
    CMSG_READY_FOR_ACCOUNT_DATA_TIMES = 0x2B16,         // new
    CMSG_QUERY_QUESTS_COMPLETED = 0x500,
    SMSG_QUERY_QUESTS_COMPLETED_RESPONSE = 0x501,
    CMSG_GM_REPORT_LAG = 0x6726,                        // new
    CMSG_AFK_MONITOR_INFO_REQUEST = 0x503,
    SMSG_AFK_MONITOR_INFO_RESPONSE = 0x504,
    CMSG_AFK_MONITOR_INFO_CLEAR = 0x505,
    SMSG_CORPSE_NOT_IN_INSTANCE = 0x2A14,               // new
    CMSG_GM_NUKE_CHARACTER = 0x507,
    CMSG_SET_ALLOW_LOW_LEVEL_RAID1 = 0x4435,            // new
    CMSG_SET_ALLOW_LOW_LEVEL_RAID2 = 0x0536,            // new
    SMSG_CAMERA_SHAKE = 0x4214,                         // new
    SMSG_SOCKET_GEMS_RESULT = 0x50B,
    CMSG_SET_CHARACTER_MODEL = 0x50C,
    SMSG_REDIRECT_CLIENT = 0x50D,
    CMSG_REDIRECTION_FAILED = 0x50E,
    SMSG_SUSPEND_COMMS = 0x50F,
    CMSG_SUSPEND_COMMS_ACK = 0x510,
    SMSG_FORCE_SEND_QUEUED_PACKETS = 0x511,
    CMSG_REDIRECTION_AUTH_PROOF = 0x512,
    CMSG_DROP_NEW_CONNECTION = 0x513,
    SMSG_SEND_ALL_COMBAT_LOG = 0x514,
    SMSG_OPEN_LFG_DUNGEON_FINDER = 0x515,
    SMSG_MOVE_SET_COLLISION_HGT = 0x11B0,               // new
    CMSG_MOVE_SET_COLLISION_HGT_ACK = 0x7114,           // new
    MSG_MOVE_SET_COLLISION_HGT = 0x518,
    CMSG_CLEAR_RANDOM_BG_WIN_TIME = 0x519,
    CMSG_CLEAR_HOLIDAY_BG_WIN_TIME = 0x51A,
    CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND = 0x51B,
    SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT1 = 0x51C,
    SMSG_COMMENTATOR_SKIRMISH_QUEUE_RESULT2 = 0x51D,
    SMSG_MULTIPLE_MOVES = 0x51E,
    CMSG_VIOLENCE_LEVEL = 0x7816,                       // new
    CMSG_LOG_DISCONNECT = 0x446D,                       // new
    CMSG_LOAD_SCREEN = 0x2422,                          // new
    CMSG_UI_TIME_REQUEST = 0x4605,                      // new
    SMSG_UI_TIME = 0x4A14,                              // new
    CMSG_MESSAGECHAT_SAY = 0x1154,                      // new
    CMSG_MESSAGECHAT_YELL = 0x3544,                     // new
    CMSG_MESSAGECHAT_CHANNEL = 0x1D44,                  // new
    CMSG_MESSAGECHAT_WHISPER = 0x0D56,                  // new
    CMSG_MESSAGECHAT_GUILD = 0x3956,                    // new
    CMSG_MESSAGECHAT_OFFICER = 0x1946,                  // new
    CMSG_MESSAGECHAT_AFK = 0x0D44,                      // new
    CMSG_MESSAGECHAT_DND = 0x2946,                      // new
    CMSG_MESSAGECHAT_EMOTE = 0x1156,                    // new
    CMSG_MESSAGECHAT_PARTY = 0x1D46,                    // new
    CMSG_MESSAGECHAT_RAID = 0x2D44,                     // new
    CMSG_MESSAGECHAT_RAID_WARNING = 0x0944,             // new
    CMSG_MESSAGECHAT_BATTLEGROUND = 0x2156,             // new
    CMSG_QUERY_BATTLEFIELD_STATE = 0x7202,              // new
    CMSG_GUILD_BANK_MONEY_WITHDRAWN = 0x1225,           // new
    SMSG_GUILD_BANK_MONEY_WITHDRAWN = 0x5DB4,           // new
    CMSG_UNREGISTER_ALL_ADDON_PREFIXES = 0x3D54,        // new
    CMSG_REQUEST_CATEGORY_COOLDOWNS = 0x7102,           // new
    CMSG_REQUEST_HOTFIX = 0x2401,                       // new
    CMSG_REQUEST_CEMETERY_LIST = 0x720A,                // new
    SMSG_REQUEST_CEMETERY_LIST_RESPONSE = 0x30A7,       // new
    CMSG_REORDER_CHARACTERS = 0x0593,                   // new
    SMSG_MOVE_UPDATE_KNOCK_BACK = 0x3DB2,               // new
    SMSG_PLAYER_MOVE = 0x79A2,                          // new
    SMSG_SPELLOGDAMAGE_IMMUNE = 0x4507,                 // new
    SMSG_LOOT_UPDATE = 0x14FE,                          // new
    CMSG_OBJECT_UPDATE_FAILED = 0x3808,                 // new
    CMSG_GROUP_INVITE_RESPONSE = 0x0410,                // new
    CMSG_GROUP_SET_ROLES = 0x25B1,                      // new
    SMSG_GROUP_SET_ROLE= 0x39A6,                        // new
    CMSG_GROUP_REQUEST_JOIN_UPDATES = 0x2583,           // new
    CMSG_LEARN_PREVIEW_TALENTS = 0x2415,                // new
    SMSG_MOVE_UPDATE_TELEPORT = 0x50B2,                 // new
    MSG_WOW_CONNECTION = 0x4F57,                        // new
    CMSG_LFG_LOCK_INFO_REQUEST = 0x0412,                // new
    CMSG_ADDON_REGISTERED_PREFIXES = 0x0954,            // new
    CMSG_ROLE_CHECK_BEGIN = 0x0430,                     // new
    SMSG_ROLE_CHECK_BEGIN = 0x70B0,                     // new
    CMSG_MAKE_EVERYONE_ASSISTANT = 0x2530,              // new
    CMSG_REPORT_PLAYER = 0x2501,                        // new
    CMSG_REPORT = 0x0427,                               // new
        
    NUM_MSG_TYPES = 0xFFFF
};
