name: AscEmu CI (MacOS::clang)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        version: [Classic, TBC, WotLK, Cata, Mop, WoD, Legion]

    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Setup Environment
        run: |
          brew update
          for pkg in mysql openssl mysql-client cmake ninja; do
            brew ls --versions $pkg || brew install $pkg
          done
          brew config

      - name: AscEmu Build ${{ matrix.version }}
        run: |
          clang --version
          cmake --version
          ninja --version
          build_dir="ascemu_build_${{ matrix.version }}"
          mkdir "$build_dir"
          cd "$build_dir"
          cmake .. \
            -GNinja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_WITH_WARNINGS=0 \
            -DBUILD_TOOLS=0 \
            -DMYSQL_INCLUDE_DIR=$(brew --prefix mysql)/include/mysql \
            -DMYSQL_LIBRARY=$(brew --prefix mysql)/lib/libmysqlclient.dylib \
            -DASCEMU_VERSION=${{ matrix.version }}
          ninja -j$(sysctl -n hw.ncpu)
          sudo ninja install
