/*
Copyright (c) 2014-2017 AscEmu Team <http://www.ascemu.org/>
This file is released under the MIT license. See README-MIT for more information.
*/

#include "Spell/SpellTarget.h"
#include "Units/Creatures/Pet.h"
#include "Spell.h"
#include "Spell/Definitions/SpellInFrontStatus.h"
#include "Spell/Definitions/SpellCastTargetFlags.h"
#include "Spell/Definitions/SpellDamageType.h"
#include "Spell/Definitions/ProcFlags.h"
#include "Spell/Definitions/CastInterruptFlags.h"
#include "Spell/Definitions/AuraInterruptFlags.h"
#include "Spell/Definitions/SpellCustomFlags.h"
#include "Spell/Definitions/SpellGoFlags.h"
#include "Spell/Definitions/SpellTargetType.h"
#include "Spell/Definitions/SpellRanged.h"
#include "Spell/Definitions/SpellIsFlags.h"
#include "Spell/Definitions/DiminishingGroup.h"
#include "Spell/Definitions/SpellState.h"
#include "Spell/Definitions/SpellMechanics.h"
#include "Spell/Definitions/SpellEffectTarget.h"
#include "Spell/Definitions/PowerType.h"
#include "Spell/Definitions/SpellDidHitResult.h"
#include "Spell/SpellHelpers.h"
#include "StdAfx.h"
#include "VMapFactory.h"
#include "Management/Item.h"
#include "Objects/DynamicObject.h"
#include "Management/ItemInterface.h"
#include "Units/Stats.h"
#include "Management/Battleground/Battleground.h"
#include "Server/WorldSocket.h"
#include "Storage/MySQLDataStore.hpp"
#include "Units/Players/PlayerClasses.hpp"
#include "Map/MapMgr.h"
#include "Map/MapScriptInterface.h"
#include "Objects/Faction.h"
#include "Spell/SpellMgr.h"
#include "Spell/SpellAuras.h"
#include "Map/WorldCreatorDefines.hpp"